import { coreEnglishDomainPortV2 } from '../domain/english';
import type { CapabilityProjection } from '../domain/learner/LearnerModelV3';
import type { PracticeFamilyV1 } from './practiceProduct';
export type LearnerAbilityStatusV1='VERY_STABLE'|'DOING_WELL'|'NEEDS_WORK'|'MOST_WORTH_PRACTICING'|'NOT_ENOUGH_EVIDENCE';
export interface LearnerAbilityAreaV1{id:string;label:string;family:PracticeFamilyV1;status:LearnerAbilityStatusV1;statusLabel:string;evidenceCount:number;actionLabel:string;detail?:string}
const labels:Record<LearnerAbilityStatusV1,string>={VERY_STABLE:'正在改善',DOING_WELL:'正在改善',NEEDS_WORK:'正在改善',MOST_WORTH_PRACTICING:'目前最值得補',NOT_ENOUGH_EVIDENCE:'還沒有足夠資料'};
const families:readonly {family:PracticeFamilyV1;label:string}[]=Object.freeze([{family:'VOCABULARY_USAGE',label:'詞彙題'},{family:'CLOZE',label:'綜合測驗'},{family:'CONTEXTUAL_FILL',label:'文意選填'},{family:'DISCOURSE',label:'篇章結構'},{family:'READING',label:'閱讀測驗'},{family:'MIXED',label:'混合題'},{family:'TRANSLATION',label:'中譯英'},{family:'WRITING',label:'英文作文'}]);
const familyFor=(p:CapabilityProjection):PracticeFamilyV1=>{const area=coreEnglishDomainPortV2.get(p.targetRef)?.area;if(area==='READING')return p.targetRef==='reading.logic-structure'?'DISCOURSE':'READING';if(area==='TRANSLATION')return'TRANSLATION';if(area==='WRITING')return'WRITING';return'VOCABULARY_USAGE'};
const rank=(p:CapabilityProjection)=>['OBSERVED_FRAGILE','ASSISTED_CONTROL','UNKNOWN','INDEPENDENT_LOCAL_CONTROL','TRANSFER_PENDING','RETENTION_PENDING','TRANSFER_SUPPORTED','RETENTION_SUPPORTED'].indexOf(p.state);
const statusFor=(p?:CapabilityProjection):LearnerAbilityStatusV1=>!p||p.state==='UNKNOWN'?'NOT_ENOUGH_EVIDENCE':p.state==='OBSERVED_FRAGILE'||p.state==='ASSISTED_CONTROL'?'NEEDS_WORK':'DOING_WELL';
export function projectMyEnglishAbilityV1(projections:readonly CapabilityProjection[]):readonly LearnerAbilityAreaV1[]{const rows=families.map(({family,label})=>{const matches=projections.filter(p=>familyFor(p)===family),weakest=[...matches].sort((a,b)=>rank(a)-rank(b))[0],status=statusFor(weakest),recognition=matches.some(p=>p.performanceDimension==='RECOGNITION'&&p.state!=='UNKNOWN'&&p.state!=='OBSERVED_FRAGILE'),production=matches.some(p=>p.performanceDimension==='PRODUCTION'&&p.state!=='UNKNOWN'&&p.state!=='OBSERVED_FRAGILE');return{id:`GSAT:${family}`,label,family,status,statusLabel:labels[status],evidenceCount:new Set(matches.flatMap(x=>x.sourceEvidenceIds)).size,actionLabel:status==='NOT_ENOUGH_EVIDENCE'?'做幾題看看':'練這一項',detail:recognition&&!production?'選項中已有辨認證據；自己拼／用還沒有足夠資料。':undefined}});const firstWeak=rows.findIndex(row=>row.status==='NEEDS_WORK');if(firstWeak>=0)rows[firstWeak]={...rows[firstWeak],status:'MOST_WORTH_PRACTICING',statusLabel:labels.MOST_WORTH_PRACTICING};return Object.freeze(rows)}
