import http from'node:http';import{COACH_SCHEMA,validateCoachAnalysis}from'../shared/coach-contract.mjs';
const port=Number(process.env.COACH_PORT||8787),pending=new Map(),useMock=process.env.COACH_USE_MOCK==='true';
const issue=(tag,category,span,msgZh,msgEn,h1Zh,h1En,h2Zh,h2En,reveal)=>({errorTag:tag,category,learnerSpan:span,messageZhTW:msgZh,messageEn:msgEn,hint1ZhTW:h1Zh,hint1En:h1En,hint2ZhTW:h2Zh,hint2En:h2En,minimalRevealZhTW:reveal,minimalRevealEn:reveal});
function mock(body){
 const a=body.answer.trim(),lower=a.toLowerCase(),scenario=body.mockScenario||'normal',kp=body.challenge.targetKnowledgePointIds[0];
 if(scenario==='timeout')return new Promise((_,reject)=>setTimeout(()=>reject(Error('timeout')),20000));
 if(scenario==='invalid_schema')return{bad:true};
 const success=(span,msg='你已正確保留這個意思。',en='You preserved this meaning correctly.')=>({learnerSpan:span,messageZhTW:msg,messageEn:en,knowledgePointId:kp});
 if(scenario==='correct'||body.challenge.referenceAnswers.some(r=>r.toLowerCase().replace(/[.,]/g,'')===lower.replace(/[.,]/g,'')))return{verdict:'correct',meaningPreserved:true,acceptedAlternative:scenario==='correct',successes:[success(a.slice(0,80),'整句自然且意思完整。','Your sentence is natural and complete.')],nextIssue:null,evidence:body.challenge.targetKnowledgePointIds.map(knowledgePointId=>({knowledgePointId,result:body.hintsUsed?'assisted':'independent',evidenceType:'production'})),conciseExplanationZhTW:'這次能獨立表達主要意思。',conciseExplanationEn:'You expressed the main meaning successfully.'};
 if(body.challenge.id==='coach-1'){
  if((scenario==='alternative'||lower.includes('understood the answer'))&&lower.includes('teacher')&&lower.includes('kept'))return{verdict:'correct',meaningPreserved:true,acceptedAlternative:true,successes:[success('understood the answer','這是自然且語意正確的替代表達。','This is a natural valid alternative.')],nextIssue:null,evidence:[{knowledgePointId:'figure-out',result:'failed',evidenceType:'production'},{knowledgePointId:'past-narration',result:'independent',evidenceType:'production'}],conciseExplanationZhTW:'翻譯正確；本次未使用目標片語 figure out。',conciseExplanationEn:'The translation is valid; figure out was not produced.'};
  if(lower.includes('figure out')&&/\bkeep\b/.test(lower))return{verdict:'partially_correct',meaningPreserved:true,acceptedAlternative:false,successes:[success('figure out','你正確使用了 figure out。','You used figure out correctly.')],nextIssue:issue('past-tense','tense','keep','事件時間需要一致。','Keep the event time consistent.','事情發生在昨天，請檢查動詞時態。','This happened yesterday. Check the verb tense.','keep 的過去式是 kept。','The past form of keep is kept.','keep → kept'),evidence:[{knowledgePointId:'figure-out',result:'independent',evidenceType:'production'},{knowledgePointId:'past-narration',result:'failed',evidenceType:'production'}],conciseExplanationZhTW:'保留 figure out，先修正一個時態問題。',conciseExplanationEn:'Keep figure out and repair one tense issue.'};
 }
 if(body.challenge.id==='coach-5'&&/allow me come/i.test(a))return{verdict:'partially_correct',meaningPreserved:true,acceptedAlternative:false,successes:[success('allow me','你已表達父母允許你的意思。','You expressed permission correctly.')],nextIssue:issue('allow-to','verb_pattern','allow me come','allow 後面的受詞與動詞之間少了結構標記。','The allow pattern needs a marker before the verb.','回想 allow + 人 + ___ + 原形動詞。','Recall: allow + person + ___ + base verb.','使用 allow me to come。','Use allow me to come.','allow me to come'),evidence:[{knowledgePointId:'allow-o-to-v',result:'failed',evidenceType:'production'}],conciseExplanationZhTW:'意思清楚，現在只修正 allow 的動詞結構。',conciseExplanationEn:'The meaning is clear; repair the allow pattern.'};
 return{verdict:'partially_correct',meaningPreserved:true,acceptedAlternative:false,successes:[success(a.split(/\s+/).slice(0,3).join(' ')||'answer')],nextIssue:issue('target-check','target_expression',undefined,'先確認題目的核心表達。','Check the core target expression.','保留正確內容，看看目標片語是否完整。','Keep what works and check the target phrase.','參考題目指定的片語結構。','Use the guided target pattern.','只補上缺少的目標結構。'),evidence:[{knowledgePointId:kp,result:'failed',evidenceType:'production'}],conciseExplanationZhTW:'先處理一個最重要的問題。',conciseExplanationEn:'Focus on one important issue first.'};
}
const system=`You are a concise bilingual Chinese-to-English output coach. Accept all semantically and grammatically valid alternatives. Preserve genuine successes from the learner text. Return one issue only using priority: meaning, required target, missing verb, tense, verb pattern, article/plural, word form, naturalness. Never invent history. Do not reveal a full corrected sentence. User-facing fields must be short. Evidence is independent only with no hints and no reveal; assisted after hints; failed after reveal.`;
async function openai(body){
 const key=process.env.OPENAI_API_KEY,model=process.env.OPENAI_MODEL;if(!key||!model)throw Error('missing_server_config');
 const payload={model,store:false,instructions:system,input:JSON.stringify({challenge:body.challenge,learnerAnswer:body.answer,revisionNumber:body.revisionNumber,hintsUsed:body.hintsUsed,answerRevealed:body.answerRevealed,suppliedWeaknesses:(body.weaknesses||[]).slice(0,10)}),text:{format:{type:'json_schema',name:'coach_analysis',strict:true,schema:COACH_SCHEMA}}};
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${key}`,'content-type':'application/json'},body:JSON.stringify(payload),signal:controller.signal});if(!r.ok)throw Error(`provider_${r.status}`);const raw=await r.json();const text=raw.output_text??raw.output?.flatMap(x=>x.content||[]).find(x=>x.type==='output_text')?.text;return{analysis:JSON.parse(text),usage:raw.usage}}finally{clearTimeout(timer)}}
async function analyze(body){if(useMock||body.mockScenario&&body.mockScenario!=='normal')return mock(body);for(let n=0;n<2;n++){const result=await openai(body);if(validateCoachAnalysis(result.analysis))return result.analysis}throw Error('invalid_schema')}
const server=http.createServer(async(req,res)=>{res.setHeader('access-control-allow-origin','*');res.setHeader('access-control-allow-headers','content-type');if(req.method==='OPTIONS'){res.writeHead(204).end();return}if(req.method!=='POST'||req.url!=='/coach/analyze'){res.writeHead(404).end();return}let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>30000){res.writeHead(413).end();return}}try{const body=JSON.parse(raw);if(!body.answer||body.answer.length>3000||!body.challenge?.id){res.writeHead(400).end();return}const key=`${body.challenge.id}:${body.answer}:${body.revisionNumber}`;if(pending.has(key)){res.writeHead(409).end();return}const started=Date.now();pending.set(key,true);try{const analysis=await analyze(body);if(!validateCoachAnalysis(analysis)){res.writeHead(502,{'content-type':'application/json'}).end(JSON.stringify({error:'invalid_schema'}));return}console.log(JSON.stringify({event:'coach_complete',challengeId:body.challenge.id,latencyMs:Date.now()-started}));res.writeHead(200,{'content-type':'application/json'}).end(JSON.stringify(analysis))}finally{pending.delete(key)}}catch(error){const timeout=error?.name==='AbortError'||error?.message==='timeout';res.writeHead(timeout?408:503,{'content-type':'application/json'}).end(JSON.stringify({error:timeout?'timeout':'unavailable'}))}});
server.listen(port,'0.0.0.0',()=>console.log(`Coach API listening on 0.0.0.0:${port} (${useMock?'mock':'OpenAI'})`));
