import http from 'node:http';
import { callTeacherV4Bounded as callTeacherV4 } from './teacher-agent-v4.mjs';
import { callProductionBlockTeacherWithProgressionV4 as callProductionBlockTeacherV4 } from './block-teacher-v4.mjs';
import { transcribeProductionArtifactV4 } from './vision-v4.mjs';
import {requestIdV1,sendFailureV1,safeServerEventV1} from './reliability-v1.mjs';
import {scoreGsatSemanticV1} from './gsat-semantic-v1.mjs';

const port=Number(process.env.PORT||process.env.TEACHER_PORT||8787);
const apiKey=process.env.OPENAI_API_KEY;
const model=process.env.OPENAI_MODEL||'gpt-5.6-terra';
const rateWindowMs=Number(process.env.RATE_LIMIT_WINDOW_MS||300000),rateMax=Number(process.env.RATE_LIMIT_MAX||60),rateBuckets=new Map();
const evidenceClaim={type:'object',additionalProperties:false,required:['claim','evidenceIds'],properties:{claim:{type:'string'},evidenceIds:{type:'array',items:{type:'string'}}}};
const hypothesis={type:'object',additionalProperties:false,required:['id','explanation','confidence','supportingEvidenceIds','contradictingEvidenceIds','discriminatingEvidenceNeeded','teachingWouldDiffer'],properties:{id:{type:'string'},explanation:{type:'string'},confidence:{enum:['LOW','MEDIUM','HIGH']},supportingEvidenceIds:{type:'array',items:{type:'string'}},contradictingEvidenceIds:{type:'array',items:{type:'string'}},discriminatingEvidenceNeeded:{type:['string','null']},teachingWouldDiffer:{type:'boolean'}}};
const teacherActions=['CONTINUE_TASK','DEFER','ACKNOWLEDGE','VERIFY','SELF_REPAIR_PROMPT','CLARIFY_TRANSCRIPT','CLARIFY_INTENT','DISCRIMINATING_PROBE','GUIDED_NOTICE','ERROR_FLAG','HINT','GUIDED_REVISION','TRY_AGAIN','SEMANTIC_CONTRAST','FORM_CONTRAST','CONTEXT_CONTRAST','EXAMPLE','COUNTEREXAMPLE','EXPLAIN','DECOMPOSE','REPRESENT_DIFFERENTLY','MODEL','DIRECT_CORRECTION','ELICIT','RECONSTRUCT','RETRIEVE','COMPLETE','REFORMULATE','COMBINE','REDUCE_LOAD','INCREASE_SUPPORT','FADE_SUPPORT','CHANGE_STRATEGY','RETURN_TO_SOURCE','TRANSFER_CHECK','DELAYED_CHECK'];
const learnerSignals=['IMMEDIATE_SELF_REPAIR','DELAYED_SELF_REPAIR','PARTIAL_REPAIR','INDEPENDENT_SUCCESS','CUED_SUCCESS','GUIDED_SUCCESS','MODEL_IMITATION','CONFUSION','NO_PROGRESS','NEW_MISCONCEPTION','VALID_ALTERNATIVE','CHALLENGE_TEACHER','INTENT_CLARIFICATION','OTHER'];
const planSchema={type:'object',additionalProperties:false,required:['observations','positiveEvidence','candidateIssues','competingHypotheses','uncertainty','interventionDecision','interventionReason','teachingObjective','teacherAction','supportLevel','rationale','expectedLearnerSignals','replanIf','stopIf','teacherUtterance'],properties:{observations:{type:'array',items:evidenceClaim},positiveEvidence:{type:'array',items:evidenceClaim},candidateIssues:{type:'array',maxItems:3,items:{type:'object',additionalProperties:false,required:['issue','domain','confidence','sourceEvidenceIds'],properties:{issue:{type:'string'},domain:{enum:['VOCABULARY','CHUNK','GRAMMAR','COMPOSITION','OTHER']},confidence:{enum:['LOW','MEDIUM','HIGH']},sourceEvidenceIds:{type:'array',items:{type:'string'}}}}},competingHypotheses:{type:'array',items:hypothesis},uncertainty:{type:['string','null']},interventionDecision:{enum:['CONTINUE','DEFER','INTERVENE']},interventionReason:{type:['string','null']},teachingObjective:{type:['object','null'],additionalProperties:false,required:['domain','targetId','facet','desiredChange'],properties:{domain:{enum:['VOCABULARY','CHUNK','GRAMMAR','COMPOSITION','OTHER']},targetId:{type:['string','null']},facet:{type:'string'},desiredChange:{type:'string'}}},teacherAction:{enum:[...teacherActions,null]},supportLevel:{enum:['NONE','LIGHT','MODERATE','EXPLICIT','MODEL']},rationale:{type:['string','null']},expectedLearnerSignals:{type:'array',items:{type:'object',additionalProperties:false,required:['signal','implication'],properties:{signal:{enum:learnerSignals},implication:{type:'string'}}}},replanIf:{type:'array',items:{type:'string'}},stopIf:{type:'array',items:{type:'string'}},teacherUtterance:{type:'string'}}};
const locationSchema={type:['object','null'],additionalProperties:false,required:['page','x','y','width','height'],properties:{page:{type:['integer','null']},x:{type:['number','null']},y:{type:['number','null']},width:{type:['number','null']},height:{type:['number','null']}}};
const transcriptSchema={type:'object',additionalProperties:false,required:['spans'],properties:{spans:{type:'array',items:{type:'object',additionalProperties:false,required:['id','artifactId','region','text','confidence','alternatives','location'],properties:{id:{type:'string'},artifactId:{type:'string'},region:{enum:['LEARNER_WRITING','TEACHER_ANNOTATION','PRINTED_PROMPT','UNKNOWN']},text:{type:'string'},confidence:{enum:['LOW','MEDIUM','HIGH']},alternatives:{type:'array',items:{type:'string'}},location:locationSchema}}}}};

function outputText(response){return response.output_text??response.output?.flatMap(item=>item.content||[]).find(item=>item.type==='output_text')?.text}
async function responses(payload,timeoutMs){if(!apiKey)throw new Error('missing_server_config');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${apiKey}`,'content-type':'application/json'},body:JSON.stringify(payload),signal:controller.signal});const raw=await response.json();if(!response.ok)throw new Error(`provider_${response.status}:${raw?.error?.code||raw?.error?.type||'request_failed'}:${raw?.error?.message||'OpenAI request failed'}`);const text=outputText(raw);if(!text)throw new Error('provider_empty_output');return text}finally{clearTimeout(timer)}}
async function plan(body){const instructions=`You are EOT Teacher Core. Replan from observable learner evidence after every learner response. Surface errors are observations, never diagnoses. Use supplied PCK only as pedagogical knowledge, never as a fixed script. Preserve competing hypotheses and valid alternative English. You may CONTINUE, DEFER, or INTERVENE. Never call modeled, cued, or guided success independent. Never accept "allow to" as successful allow O to V. Resolve decision-relevant OCR uncertainty before diagnosis. When a learner reports confusion caused by teaching, reconsider the move and change strategy or diagnosis. Return a concise zh-TW learner utterance plus the complete structured plan. Do not reveal internal IDs or reasoning to the learner.`;return JSON.parse(await responses({model,store:false,instructions,input:JSON.stringify(body),text:{format:{type:'json_schema',name:'teacher_turn_plan',strict:true,schema:planSchema}}},90000))}
async function transcribe(body){const isPdf=body.mimeType==='application/pdf';const content=[{type:'input_text',text:'TRANSCRIBE_AND_SEGMENT. Preserve the original exactly. Do not spellcheck, grammar-correct, or normalize. Separate LEARNER_WRITING, TEACHER_ANNOTATION, PRINTED_PROMPT, and UNKNOWN. Report every visible text or writing-like mark; an illegible or unattributable scribble must be an UNKNOWN span with text "[illegible]", not silently omitted. Include confidence, alternatives, and region/page location. Use LOW confidence and alternatives whenever uncertainty could change teaching.'},isPdf?{type:'input_file',filename:'artifact.pdf',file_data:`data:${body.mimeType};base64,${body.base64}`}:{type:'input_image',image_url:`data:${body.mimeType};base64,${body.base64}`,detail:'high'}];const parsed=JSON.parse(await responses({model,store:false,input:[{role:'user',content}],text:{format:{type:'json_schema',name:'artifact_transcript',strict:true,schema:transcriptSchema}}},120000));return{spans:parsed.spans.map((span,index)=>({...span,id:span.id||`span-${index}`,artifactId:body.artifactId}))}}

const server=http.createServer(async(req,res)=>{const requestId=requestIdV1(req);res.setHeader('access-control-allow-origin','*');res.setHeader('access-control-allow-headers','content-type,x-eot-request-id');res.setHeader('access-control-expose-headers','x-eot-request-id');res.setHeader('x-eot-request-id',requestId);if(req.method==='OPTIONS'){res.writeHead(204).end();return}if(req.method==='GET'&&req.url==='/health'){res.writeHead(200,{'content-type':'application/json'}).end(JSON.stringify({ok:true,configured:Boolean(apiKey),model,gsatSemantic:true}));return}if(req.method!=='POST'||!['/teacher/plan','/teacher/transcribe','/teacher/v4/qualify','/teacher/v4/block-select','/assessment/gsat'].includes(req.url)){res.writeHead(404).end();return}const now=Date.now(),client=String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim(),bucket=rateBuckets.get(client);if(!bucket||now-bucket.startedAt>=rateWindowMs)rateBuckets.set(client,{startedAt:now,count:1});else if(++bucket.count>rateMax){res.writeHead(429,{'content-type':'application/json','retry-after':String(Math.ceil((rateWindowMs-(now-bucket.startedAt))/1000))}).end(JSON.stringify({error:'rate_limited',retryable:true,requestId}));return}const maxBody=req.url==='/teacher/transcribe'?20_000_000:1_000_000;let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>maxBody){res.writeHead(413,{'content-type':'application/json'}).end(JSON.stringify({error:'payload_too_large',retryable:false,requestId}));return}}try{const body=JSON.parse(raw);const output=req.url==='/teacher/plan'?await plan(body):req.url==='/teacher/transcribe'?await transcribeProductionArtifactV4({apiKey,...body}):req.url==='/teacher/v4/block-select'?await callProductionBlockTeacherV4({apiKey,context:body.context,reasoningEffort:body.reasoningEffort||'low',runId:body.runId,caseId:body.caseId}):req.url==='/assessment/gsat'?await scoreGsatSemanticV1({apiKey,model,input:body,requestId}):await callTeacherV4({apiKey,model,context:body.context,reasoningEffort:body.reasoningEffort||'low',requestId:body.requestId});res.writeHead(200,{'content-type':'application/json'}).end(JSON.stringify(output))}catch(error){const failure=sendFailureV1(res,error,requestId);console.warn(JSON.stringify(safeServerEventV1({event:'teacher_request_failed',requestId,path:req.url,status:failure.status,code:failure.code,retryable:failure.retryable})))}});
server.listen(port,'0.0.0.0',()=>console.log(`EOT Teacher Core listening on ${port} with ${model}; configured=${Boolean(apiKey)}`));
