const test=require('node:test');
const assert=require('node:assert/strict');
const evals=require('../../.domain-test-build/application/stage2/blockSelectionEvalV4.js');

test('Stage 2 V4 block-selection gate passes every separate critic with zero hard violations',()=>{const r=evals.runBlockSelectionStage2V4();assert.equal(r.passed,true,JSON.stringify(r.failures.slice(0,3),null,2));assert.equal(r.failures.length,0);assert.equal(r.hardFailures.length,0);assert.equal(r.contrastFailures.length,0);assert.equal(r.paidModelCalls,0)});
test('critics calibrate Golden Pass, Golden Fail and semantic Near Miss',()=>{assert.deepEqual(evals.calibrateBlockCriticsV4(),{goldenPass:true,goldenFailDetected:true,nearMissDetected:true,details:['Golden Pass accepts grounded TEACH choice','Golden Fail rejects inappropriate ASSESS substitution','Near Miss rejects correct assessment block with answer leakage']})});
test('all ten genuine Teaching mechanisms have appropriate, inappropriate and history-contrast coverage',()=>{const r=evals.runBlockSelectionStage2V4();assert.equal(Object.keys(r.teachingMechanisms).length,10);for(const value of Object.values(r.teachingMechanisms))assert.deepEqual(value,{appropriate:true,inappropriateRejected:true,historyContrast:true})});
test('allow to never becomes successful allow O to V evidence',()=>{const c=evals.buildBlockSelectionCorpusV4().find(x=>x.id==='REG-allow');assert.ok(c);assert.equal(c.decision.evidenceMode,'EXPOSURE');assert.equal(evals.evaluateBlockCaseV4(c).passed,true)});
test('system-owned progression gates transfer by prerequisites across domains',()=>{const p=require('../../.domain-test-build/application/v4/pedagogicalProgressionV4.js'),derive=(x={})=>p.derivePedagogicalProgressionV4({objectiveState:'LOCAL_VERIFY',teachingCompleted:true,supportedPracticeCompleted:true,learnerReadyForVerification:true,independentVerificationStatus:'NOT_OBSERVED',strongPriorIndependentEvidence:false,transferQualificationStatus:'NOT_ESTABLISHED',...x});for(const domain of ['GRAMMAR','TRANSLATION','WRITING','VOCABULARY_CHUNK']){const afterTeach=derive({supportedPracticeCompleted:false}),afterPractice=derive(),unstable=derive({learnerReadyForVerification:false}),afterSuccess=derive({independentVerificationStatus:'SUCCESS'}),strongHistory=derive({teachingCompleted:false,supportedPracticeCompleted:false,strongPriorIndependentEvidence:true}),alreadyTransfer=derive({independentVerificationStatus:'SUCCESS',transferQualificationStatus:'ESTABLISHED'}),failed=derive({independentVerificationStatus:'FAILED'}),hinted=derive({independentVerificationStatus:'ASSISTED_INVALIDATED'});assert.equal(p.validatePedagogicalIntentEligibilityV4('TRANSFER',afterTeach).length>0,true,domain);assert.equal(p.validatePedagogicalIntentEligibilityV4('TRANSFER',afterPractice).length>0,true,domain);assert.ok(unstable.eligiblePedagogicalIntents.includes('PRACTICE'),domain);assert.ok(afterPractice.eligiblePedagogicalIntents.includes('ASSESS'),domain);assert.ok(afterSuccess.eligiblePedagogicalIntents.includes('TRANSFER'),domain);assert.ok(strongHistory.eligiblePedagogicalIntents.includes('ASSESS')&&strongHistory.eligiblePedagogicalIntents.includes('TRANSFER'),domain);assert.equal(alreadyTransfer.eligiblePedagogicalIntents.includes('TRANSFER'),false,domain);assert.equal(failed.eligiblePedagogicalIntents.includes('TRANSFER'),false,domain);assert.equal(hinted.eligiblePedagogicalIntents.includes('TRANSFER'),false,domain)}});
