import type { LookupAssessmentModeV1 } from './types';
export interface ContextualSenseRecordV1{recordId:string;lemma:string;senseId:string;pos:string;meaningZhTw:string;contextTerms:readonly string[];localUnits:readonly {text:string;meaningZhTw:string;kind:'COLLOCATION'|'PHRASE'|'CHUNK'}[];usageNote?:string;provenanceRefs:readonly string[]}
export interface SingleWordLookupRequestV1{tappedToken:string;sentence:string;paragraph?:string;assessmentMode:LookupAssessmentModeV1;activeTargetTokens:readonly string[];submitted?:boolean}
export interface ContextualLookupResultV1{status:'RESOLVED'|'AMBIGUOUS'|'ABSTAIN'|'LOCKED';tappedToken:string;lemma?:string;senseId?:string;partOfSpeech?:string;meaningZhTw?:string;localUnit?:{text:string;meaningZhTw:string;kind:'COLLOCATION'|'PHRASE'|'CHUNK'};resolvedSpan?:{text:string;start:number;end:number};usageNote?:string;confidence:'HIGH'|'MEDIUM'|'LOW';provenanceRefs:readonly string[];supportEffect:'NONE'|'LOOKUP_ASSISTED';lockReason?:'FORMAL_ASSESSMENT'|'TARGET_ANSWER_LEAK'}
const normalize=(x:string)=>x.normalize('NFKC').toLocaleLowerCase('en').replace(/[’]/g,"'").replace(/[^a-z' ]+/g,' ').replace(/\s+/g,' ').trim();
const irregular:Record<string,string>={carried:'carry',went:'go',gone:'go',did:'do',done:'do',had:'have'};
export function normalizeTappedLemmaV1(token:string){const t=normalize(token);if(irregular[t])return irregular[t];if(t.endsWith('ies')&&t.length>4)return`${t.slice(0,-3)}y`;if(t.endsWith('ed')&&t.length>4)return t.slice(0,-2).replace(/i$/,'y');if(t.endsWith('s')&&t.length>3)return t.slice(0,-1);return t}
export const coreContextualLexiconV1:readonly ContextualSenseRecordV1[]=Object.freeze([
 {recordId:'eot:impact:effect',lemma:'impact',senseId:'sense:impact:effect',pos:'n',meaningZhTw:'影響',contextTerms:['policy','students','significant'],localUnits:[{text:'have a significant impact on',meaningZhTw:'對……產生重大影響',kind:'COLLOCATION'}],usageNote:'impact 在此表示某事造成的影響。',provenanceRefs:['EOT_CURATED_CONTEXT_V1']},
 {recordId:'eot:carry-out:perform',lemma:'carry',senseId:'sense:carry-out:perform',pos:'v',meaningZhTw:'執行／進行',contextTerms:['experiment','carefully'],localUnits:[{text:'carry out',meaningZhTw:'執行／進行',kind:'PHRASE'}],usageNote:'carried 是 carry 的過去式，與 out 組成片語動詞。',provenanceRefs:['EOT_CURATED_CONTEXT_V1']},
 {recordId:'eot:issue:publish',lemma:'issue',senseId:'sense:issue:publish',pos:'v',meaningZhTw:'發布／發出',contextTerms:['school','guidelines','safety','new'],localUnits:[{text:'issue guidelines',meaningZhTw:'發布指引',kind:'COLLOCATION'}],provenanceRefs:['EOT_CURATED_CONTEXT_V1']},
 {recordId:'eot:issue:problem',lemma:'issue',senseId:'sense:issue:problem',pos:'n',meaningZhTw:'問題',contextTerms:['problem','concern','discuss'],localUnits:[],provenanceRefs:['EOT_CURATED_CONTEXT_V1']}
 ,{recordId:'eot:progress',lemma:'progress',senseId:'sense:progress:advance',pos:'n',meaningZhTw:'進步；進展',contextTerms:['make','learning','study'],localUnits:[{text:'make progress',meaningZhTw:'取得進步',kind:'COLLOCATION'}],usageNote:'學測常見搭配：make progress，而不是 do progress。',provenanceRefs:['EOT_GSAT_CURATED_V1']}
 ,{recordId:'eot:rely',lemma:'rely',senseId:'sense:rely:depend',pos:'v',meaningZhTw:'依靠；依賴',contextTerms:['on','people','information'],localUnits:[{text:'rely on',meaningZhTw:'依靠；依賴',kind:'PHRASE'}],usageNote:'rely 後面通常接 on。',provenanceRefs:['EOT_GSAT_CURATED_V1']}
 ,{recordId:'eot:result',lemma:'result',senseId:'sense:result:outcome',pos:'n',meaningZhTw:'結果',contextTerms:['study','show','significant'],localUnits:[{text:'as a result',meaningZhTw:'因此；結果',kind:'CHUNK'}],provenanceRefs:['EOT_GSAT_CURATED_V1']}
 ,{recordId:'eot:consider',lemma:'consider',senseId:'sense:consider:think',pos:'v',meaningZhTw:'考慮；認為',contextTerms:['people','rules','option'],localUnits:[{text:'consider doing',meaningZhTw:'考慮做某事',kind:'COLLOCATION'}],usageNote:'consider 後常接 V-ing。',provenanceRefs:['EOT_GSAT_CURATED_V1']}
 ,{recordId:'eot:student',lemma:'student',senseId:'sense:student:learner',pos:'n',meaningZhTw:'學生',contextTerms:['books','library'],localUnits:[],provenanceRefs:['EOT_GSAT_CURATED_V1']}
 ,{recordId:'eot:can:ability',lemma:'can',senseId:'sense:can:ability',pos:'modal',meaningZhTw:'可以；能夠',contextTerms:['students','books'],localUnits:[],provenanceRefs:['EOT_GSAT_CURATED_V1']}
 ,{recordId:'eot:book:publication',lemma:'book',senseId:'sense:book:publication',pos:'n',meaningZhTw:'書；書籍',contextTerms:['students','library'],localUnits:[],provenanceRefs:['EOT_GSAT_CURATED_V1']}
 ,{recordId:'eot:online',lemma:'online',senseId:'sense:online:internet',pos:'adv',meaningZhTw:'在線上；透過網路',contextTerms:['books','library'],localUnits:[],provenanceRefs:['EOT_GSAT_CURATED_V1']}
 ,{recordId:'eot:before:earlier',lemma:'before',senseId:'sense:before:earlier',pos:'prep',meaningZhTw:'在……之前',contextTerms:['going','library'],localUnits:[],provenanceRefs:['EOT_GSAT_CURATED_V1']}
 ,{recordId:'eot:go:move',lemma:'go',senseId:'sense:go:move',pos:'v',meaningZhTw:'去；前往',contextTerms:['before','library'],localUnits:[{text:'going to the library',meaningZhTw:'去圖書館',kind:'PHRASE'}],provenanceRefs:['EOT_GSAT_CURATED_V1']}
 ,{recordId:'eot:to:direction',lemma:'to',senseId:'sense:to:direction',pos:'prep',meaningZhTw:'向；到',contextTerms:['going','library'],localUnits:[{text:'to the library',meaningZhTw:'到圖書館',kind:'PHRASE'}],provenanceRefs:['EOT_GSAT_CURATED_V1']}
 ,{recordId:'eot:the:definite',lemma:'the',senseId:'sense:the:definite',pos:'det',meaningZhTw:'這個／該（指特定的人或事物）',contextTerms:['library'],localUnits:[],provenanceRefs:['EOT_GSAT_CURATED_V1']}
 ,{recordId:'eot:library',lemma:'library',senseId:'sense:library:place',pos:'n',meaningZhTw:'圖書館',contextTerms:['books','students'],localUnits:[],provenanceRefs:['EOT_GSAT_CURATED_V1']}
]);
const lexicalTokens=(x:string)=>normalize(x).split(' ').filter(Boolean).map(normalizeTappedLemmaV1).filter(x=>!['a','an','the'].includes(x));
const localUnitPresent=(context:string,unit:string)=>{const hay=lexicalTokens(context),needle=lexicalTokens(unit);let at=0;for(const token of hay)if(token===needle[at])at++;return at===needle.length};
export function resolveSingleWordContextV1(request:SingleWordLookupRequestV1,records:readonly ContextualSenseRecordV1[]=coreContextualLexiconV1):ContextualLookupResultV1{const token=normalize(request.tappedToken),lemma=normalizeTappedLemmaV1(token),base={tappedToken:request.tappedToken,lemma,provenanceRefs:Object.freeze([]),supportEffect:'NONE' as const,confidence:'LOW' as const};if(!token||token.includes(' '))return{...base,status:'ABSTAIN'};const target=request.activeTargetTokens.map(normalizeTappedLemmaV1).includes(lemma);if(!request.submitted&&request.assessmentMode==='FORMAL_ASSESSMENT')return{...base,status:'LOCKED',lockReason:'FORMAL_ASSESSMENT'};if(!request.submitted&&request.assessmentMode==='LEARNING_CHECK'&&target)return{...base,status:'LOCKED',lockReason:'TARGET_ANSWER_LEAK'};const context=normalize(`${request.sentence} ${request.paragraph??''}`),ranked=records.filter(r=>normalize(r.lemma)===lemma).map(r=>({r,score:r.contextTerms.filter(term=>context.includes(normalize(term))).length,unit:r.localUnits.filter(u=>localUnitPresent(context,u.text)).sort((a,b)=>b.text.length-a.text.length)[0]})).sort((a,b)=>(Number(!!b.unit)-Number(!!a.unit))||b.score-a.score);if(!ranked.length)return{...base,status:'ABSTAIN'};if(ranked.length>1&&!ranked[0].unit&&ranked[0].score===ranked[1].score)return{...base,status:'AMBIGUOUS'};const top=ranked[0];if(!top.unit&&top.score===0)return{...base,status:'AMBIGUOUS'};return{status:'RESOLVED',tappedToken:request.tappedToken,lemma:top.r.lemma,senseId:top.r.senseId,partOfSpeech:top.r.pos,meaningZhTw:top.r.meaningZhTw,localUnit:top.unit,usageNote:top.r.usageNote,confidence:top.unit||top.score>=2?'HIGH':'MEDIUM',provenanceRefs:top.r.provenanceRefs,supportEffect:'LOOKUP_ASSISTED'}}
export function resolveTapPhraseFirstContextV1(request:SingleWordLookupRequestV1,records:readonly ContextualSenseRecordV1[]=coreContextualLexiconV1):ContextualLookupResultV1{const locked=resolveSingleWordContextV1(request,records);if(locked.status==='LOCKED')return locked;const sentence=normalize(request.sentence),token=normalize(request.tappedToken);const matches=records.flatMap(record=>record.localUnits.map(unit=>({record,unit,start:sentence.indexOf(normalize(unit.text))}))).filter(x=>x.start>=0&&lexicalTokens(x.unit.text).includes(normalizeTappedLemmaV1(token))).sort((a,b)=>b.unit.text.length-a.unit.text.length);if(matches[0]){const x=matches[0],rawStart=request.sentence.toLowerCase().indexOf(x.unit.text.toLowerCase());return{status:'RESOLVED',tappedToken:request.tappedToken,lemma:x.record.lemma,senseId:x.record.senseId,partOfSpeech:x.record.pos,meaningZhTw:x.record.meaningZhTw,localUnit:x.unit,resolvedSpan:{text:x.unit.text,start:rawStart,end:rawStart+x.unit.text.length},usageNote:x.record.usageNote,confidence:'HIGH',provenanceRefs:x.record.provenanceRefs,supportEffect:'LOOKUP_ASSISTED'}}return locked}
