import { resolveTapPhraseFirstContextV1, type ContextualSenseRecordV1 } from './contextualResolution';
import { createLexicalEncounterEventV1, type LexicalEncounterCaptureMethodV1, type LexicalEncounterEventV1, type LexicalEncounterSourceTypeV1 } from '../learner-truth/lexicalEncounter';
import type { CanonicalLexicalEncounterStoreV1 } from '../learner-truth/lexicalEncounter';
import type { LookupDataSourceV1 } from './types';
import { createContextualLookupRuntimeV1 } from './runtime';
export interface ManualLexicalCaptureInputV1{eventId:string;learnerId:string;sessionId?:string;occurredAt:string;captureMethod?:LexicalEncounterCaptureMethodV1;sourceType:LexicalEncounterSourceTypeV1;sourceAnchor?:string;word?:string;phrase?:string;sentence?:string;selectedSpan?:string;plainText?:string;adjacentDiscourse?:string;userMarkedRemember?:boolean;keepContext?:boolean;maxPersistedContextCharacters?:number}
export function prepareManualLexicalCaptureV1(input:ManualLexicalCaptureInputV1,records?:readonly ContextualSenseRecordV1[]):LexicalEncounterEventV1{
 const local=input.sentence??input.plainText??input.phrase??input.word??'',selected=(input.selectedSpan??input.phrase??input.word??input.plainText??'').trim();if(!selected)throw new Error('manual_lexical_capture_span_required');const firstToken=selected.split(/\s+/)[0],resolved=resolveTapPhraseFirstContextV1({tappedToken:firstToken,sentence:local||selected,paragraph:input.adjacentDiscourse,assessmentMode:'NONE',activeTargetTokens:[],submitted:true},records);const phrase=resolved.resolvedSpan?.text??(selected.includes(' ')?selected:undefined);return createLexicalEncounterEventV1({eventId:input.eventId,learnerId:input.learnerId,sessionId:input.sessionId,occurredAt:input.occurredAt,captureMethod:input.captureMethod??'QUICK_MANUAL_ADD',sourceType:input.sourceType,sourceAnchor:input.sourceAnchor,selectedSpan:selected,normalizedTargetCandidate:resolved.lemma??phrase??selected,phraseOrChunkCandidate:phrase,canonicalTargetRef:resolved.status==='RESOLVED'?'lexical.contextual-fit':undefined,canonicalFacet:resolved.localUnit?'COLLOCATION':'SENSE_DISCRIMINATION',resolutionStatus:resolved.status==='RESOLVED'?'RESOLVED':resolved.status==='AMBIGUOUS'?'AMBIGUOUS':'UNRESOLVED',candidateSenseRefs:resolved.senseId?[resolved.senseId]:[],resolvedContextualSense:resolved.senseId,lookupRequested:input.captureMethod==='EOT_IN_APP_LOOKUP',lookupResultExposed:input.captureMethod==='EOT_IN_APP_LOOKUP'&&resolved.status==='RESOLVED',userMarkedRemember:input.userMarkedRemember??false,provenanceRefs:resolved.provenanceRefs,privacyScope:'EXTERNAL_MINIMIZED',context:{selectedSpan:selected,localFragment:local,adjacentDiscourse:input.adjacentDiscourse,keepContext:input.keepContext,maxPersistedContextCharacters:input.maxPersistedContextCharacters}})}
export function preparePlatformShareLexicalCaptureV1(input:Omit<ManualLexicalCaptureInputV1,'captureMethod'>,records?:readonly ContextualSenseRecordV1[]){return prepareManualLexicalCaptureV1({...input,captureMethod:'PLATFORM_SHARE_ADAPTER'},records)}
export function createEncounterRecordingLookupRuntimeV1(input:{source:LookupDataSourceV1;store:CanonicalLexicalEncounterStoreV1;learnerId:string;sessionId:string;sourceType?:LexicalEncounterSourceTypeV1;sourceAnchor?:string;eventId:()=>string;now?:()=>string}){return createContextualLookupRuntimeV1(input.source,{onLearnerLookup:async({request,decision})=>{const candidate=decision.candidate!;await input.store.append(createLexicalEncounterEventV1({eventId:input.eventId(),learnerId:input.learnerId,sessionId:input.sessionId,occurredAt:(input.now??(()=>new Date().toISOString()))(),captureMethod:'EOT_IN_APP_LOOKUP',sourceType:input.sourceType??'EOT_CONTENT',sourceAnchor:input.sourceAnchor,selectedSpan:request.text.slice(request.selectionStart,request.selectionEnd)||candidate.label,normalizedTargetCandidate:candidate.label,phraseOrChunkCandidate:candidate.kind==='WORD'?undefined:candidate.label,canonicalTargetRef:'lexical.contextual-fit',canonicalFacet:candidate.kind==='WORD'?'SENSE_DISCRIMINATION':'COLLOCATION',resolutionStatus:'RESOLVED',candidateSenseRefs:[candidate.id],resolvedContextualSense:candidate.id,lookupRequested:true,lookupResultExposed:true,userMarkedRemember:false,provenanceRefs:candidate.sourceRef?[candidate.sourceRef]:[],privacyScope:'EOT_REFERENCE_ONLY'}))}})}
