import { Confidence } from '../teacher/TeacherRuntime';
export type OutcomeSurface='WRITING'|'TRANSLATION';
export type WritingDimension='TASK_MEANING_FULFILLMENT'|'IDEA_DEVELOPMENT'|'ORGANIZATION_COHERENCE'|'MEANING_TO_CLAUSE'|'SENTENCE_CONSTRUCTION'|'CLAUSE_RELATION'|'LEXICAL_PRECISION'|'GRAMMAR_CONTROL'|'SPELLING_MORPHOLOGY'|'REGISTER_GENRE'|'REFORMULATION_REVISION'|'INDEPENDENT_PRODUCTION'|'TRANSFER'|'RETENTION';
export type TranslationDimension='SOURCE_MEANING_COMPREHENSION'|'MEANING_SEGMENTATION'|'MEANING_PRESERVATION'|'MEANING_TO_ENGLISH'|'LEXICAL_CHUNK_RETRIEVAL'|'GRAMMAR_CONSTRUCTION_SELECTION'|'SENTENCE_FORMATION'|'NATURALNESS_ALTERNATIVES'|'L1_INTERFERENCE'|'REGISTER'|'INDEPENDENT_PRODUCTION'|'TRANSFER'|'RETENTION';
export interface OutcomeObservation{id:string;surface:OutcomeSurface;dimension:WritingDimension|TranslationDimension;artifactId:string;observable:string;confidence:Confidence;candidateOnly:true}
