export type GsatCalibrationFamilyV1='VOCABULARY'|'COMPREHENSIVE'|'CONTEXTUAL_FILL'|'DISCOURSE'|'READING'|'MIXED'|'TRANSLATION';
export interface GsatCalibrationProbeV1{id:string;stage:1|2;family:GsatCalibrationFamilyV1;operation:string;scoreOpportunity:number;prompt:string;choices:readonly{label:string;correct:boolean}[]}
export const GSAT_STAGE1_PROBES_V1:readonly GsatCalibrationProbeV1[]=Object.freeze([
 {id:'CAL-VOC-SENSE',stage:1,family:'VOCABULARY',operation:'CONTEXTUAL_SENSE',scoreOpportunity:2,prompt:'The policy allows students to borrow a tablet. “allows” means…',choices:[{label:'permits',correct:true},{label:'prevents',correct:false}]},
 {id:'CAL-CLOZE',stage:1,family:'COMPREHENSIVE',operation:'LOCAL_COHESION',scoreOpportunity:2,prompt:'Choose the connector: It was raining; ___, the game continued.',choices:[{label:'however',correct:true},{label:'therefore',correct:false}]},
 {id:'CAL-DISC',stage:1,family:'DISCOURSE',operation:'SENTENCE_CONTINUITY',scoreOpportunity:2,prompt:'Which signal introduces a result?',choices:[{label:'As a result',correct:true},{label:'For example',correct:false}]},
 {id:'CAL-READ-DETAIL',stage:1,family:'READING',operation:'DETAIL',scoreOpportunity:2,prompt:'The notice says the library closes at six. When does it close?',choices:[{label:'At six',correct:true},{label:'At seven',correct:false}]},
 {id:'CAL-READ-INFER',stage:1,family:'READING',operation:'INFERENCE',scoreOpportunity:2,prompt:'Mia took an umbrella after seeing dark clouds. What did she expect?',choices:[{label:'Rain',correct:true},{label:'Snow',correct:false}]},
 {id:'CAL-TRANS',stage:1,family:'TRANSLATION',operation:'MEANING_SEGMENTATION',scoreOpportunity:4,prompt:'「規律複習更有效」保留了哪個比較關係？',choices:[{label:'regular review is more effective',correct:true},{label:'review is always easy',correct:false}]},
]);
const FOLLOWUPS:Readonly<Record<string,readonly GsatCalibrationProbeV1[]>>=Object.freeze({CONTEXTUAL_SENSE:[{id:'CAL2-VOC-SENSE',stage:2,family:'VOCABULARY',operation:'CONTEXTUAL_SENSE',scoreOpportunity:2,prompt:'The committee addressed the problem. “addressed” means…',choices:[{label:'dealt with',correct:true},{label:'wrote a location on',correct:false}]}],LOCAL_COHESION:[{id:'CAL2-CLOZE',stage:2,family:'COMPREHENSIVE',operation:'LOCAL_COHESION',scoreOpportunity:2,prompt:'She practiced daily; ___, her timing improved.',choices:[{label:'as a result',correct:true},{label:'in contrast',correct:false}]}],SENTENCE_CONTINUITY:[{id:'CAL2-DISC',stage:2,family:'DISCOURSE',operation:'SENTENCE_CONTINUITY',scoreOpportunity:2,prompt:'Choose the sentence that continues a cause with its effect.',choices:[{label:'Therefore, fewer items were wasted.',correct:true},{label:'For example, the room was blue.',correct:false}]}],DETAIL:[{id:'CAL2-DETAIL',stage:2,family:'READING',operation:'DETAIL',scoreOpportunity:2,prompt:'A café opens at eight except Sunday. When is it closed?',choices:[{label:'Sunday',correct:true},{label:'Monday',correct:false}]}],INFERENCE:[{id:'CAL2-INFER',stage:2,family:'READING',operation:'INFERENCE',scoreOpportunity:2,prompt:'Leo reread the instructions before pressing Start. Why?',choices:[{label:'To avoid a mistake',correct:true},{label:'To waste time',correct:false}]}],MEANING_SEGMENTATION:[{id:'CAL2-TRANS',stage:2,family:'TRANSLATION',operation:'MEANING_SEGMENTATION',scoreOpportunity:4,prompt:'Which version preserves 「不但…也…」?',choices:[{label:'not only … but also …',correct:true},{label:'either … or …',correct:false}]}]});
export function routeGsatCalibrationStage2V1(results:readonly{probeId:string;correct:boolean;confidence?:number}[]){const byId=new Map(GSAT_STAGE1_PROBES_V1.map(x=>[x.id,x])),detail=results.find(x=>x.probeId==='CAL-READ-DETAIL'),inference=results.find(x=>x.probeId==='CAL-READ-INFER');const candidates=results.filter(x=>!x.correct).map(x=>byId.get(x.probeId)).filter((x):x is GsatCalibrationProbeV1=>Boolean(x));if(detail&&!detail.correct&&inference&&!inference.correct){const index=candidates.findIndex(x=>x.operation==='INFERENCE');if(index>=0)candidates.splice(index,1)}const ranked=candidates.map(x=>({...x,value:x.scoreOpportunity*(1-(results.find(r=>r.probeId===x.id)?.confidence??.5))})).sort((a,b)=>b.value-a.value);return Object.freeze(ranked.slice(0,2).flatMap(x=>FOLLOWUPS[x.operation]?.slice(0,1)??[]))}
