export type GsatQuestionFamilyV1='VOCABULARY'|'CLOZE'|'WORD_BANK'|'DISCOURSE_STRUCTURE'|'READING_COMPREHENSION'|'MIXED_FORMAT'|'ZH_EN_TRANSLATION'|'ENGLISH_COMPOSITION';
export interface GsatDemandBlueprintEntryV1{family:GsatQuestionFamilyV1;taskDemands:readonly string[];observableFailures:readonly string[];possibleBottlenecks:readonly string[];capabilityRefs:readonly string[];mechanismFamilies:readonly string[];practiceRequirements:readonly string[];measurementRequirements:readonly string[]}
const e=(family:GsatQuestionFamilyV1,taskDemands:string[],observableFailures:string[],possibleBottlenecks:string[],capabilityRefs:string[],mechanismFamilies:string[],practiceRequirements:string[],measurementRequirements:string[])=>Object.freeze({family,taskDemands:Object.freeze(taskDemands),observableFailures:Object.freeze(observableFailures),possibleBottlenecks:Object.freeze(possibleBottlenecks),capabilityRefs:Object.freeze(capabilityRefs),mechanismFamilies:Object.freeze(mechanismFamilies),practiceRequirements:Object.freeze(practiceRequirements),measurementRequirements:Object.freeze(measurementRequirements)});
export const gsatDemandBlueprintV1:readonly GsatDemandBlueprintEntryV1[]=Object.freeze([
 e('VOCABULARY',['contextual sense','grammatical fit','collocation'],['sense-confusable option','context mismatch'],['sense discrimination','collocation','morphosyntactic fit'],['sense identity','collocation','morphology'],['sense contrast','collocation network','form contrast'],['new sentence context'],['sense-specific evidence; no lemma shortcut']),
 e('CLOZE',['local grammar','lexical cohesion','logical relation'],['locally plausible but discourse-incompatible choice'],['grammatical fit','lexical cohesion','discourse relation'],['grammar construction','collocation','reading.logic-structure'],['form contrast','cohesion relation map'],['retain surrounding discourse'],['option and passage provenance']),
 e('WORD_BANK',['contextual sense','reference continuity','lexical cohesion'],['surface-association selection'],['sense selection','reference continuity','collocation'],['sense discrimination','reading.reference-tracking','collocation'],['sense contrast','reference chain','distractor contrast'],['contrast remaining slots'],['record slot and alternatives']),
 e('DISCOURSE_STRUCTURE',['paragraph function','backward/forward cohesion','insertion evidence'],['topic fit without continuity'],['paragraph function','reference chain','logical relation'],['reading.logic-structure','reading.reference-tracking'],['text structure map','paragraph function map','sentence insertion continuity'],['mark links on both sides'],['explicit insertion evidence']),
 e('READING_COMPREHENSION',['textual evidence','implied relation','conclusion','option contrast'],['unsupported inference','overstated claim','wrong evidence'],['inference bridge','evidence selection','claim strength'],['reading.inference','reading.logic-structure','reading.reference-tracking'],['inference evidence bridge','claim strength contrast','distractor contrast'],['select evidence before conclusion'],['authorized result or diagnostic response']),
 e('MIXED_FORMAT',['cross-representation evidence','text/table/image integration'],['one source ignored'],['representation integration','evidence conflict'],['reading.inference','reading.logic-structure'],['cross-representation evidence integration'],['map claims to each source'],['source-specific evidence refs']),
 e('ZH_EN_TRANSLATION',['source meaning','segmentation','English realization','lexical precision'],['meaning distortion','literal collision'],['source meaning','segmentation','retrieval','verb pattern','restructuring','naturalness'],['translation source meaning','meaning-form mapping','grammar','collocation'],['meaning segmentation','role map','L1 collision','alternative contrast'],['separate source and learner English'],['valid alternatives and meaning fidelity']),
 e('ENGLISH_COMPOSITION',['task fulfillment','purpose/audience','reasoning','organization/cohesion','sentence realization','revision'],['same-root errors','task mismatch','realization breakdown'],['idea/reasoning','organization','cohesion','retrieval','grammar','self-repair'],['writing purpose-audience','writing idea-reasoning','writing organization-cohesion','writing sentence-realization','writing revision'],['feedback budget','sentence anatomy','cohesion map','local repair'],['cluster roots; preserve authorship'],['bounded focus; H cannot write mastery'])
]);
export function validateGsatDemandBlueprintV1(){const errors:string[]=[];if(new Set(gsatDemandBlueprintV1.map(x=>x.family)).size!==8)errors.push('ALL_EIGHT_GSAT_FAMILIES_REQUIRED');for(const row of gsatDemandBlueprintV1)for(const key of ['taskDemands','observableFailures','possibleBottlenecks','capabilityRefs','mechanismFamilies','practiceRequirements','measurementRequirements'] as const)if(!row[key].length)errors.push(`${row.family}_${key}_EMPTY`);return Object.freeze(errors)}
