export type ArtifactKind='DIRECT_TEXT'|'PASTE'|'IMAGE'|'PDF'; export type RegionKind='LEARNER_WRITING'|'TEACHER_ANNOTATION'|'PRINTED_PROMPT'|'UNKNOWN'; export type Confidence='LOW'|'MEDIUM'|'HIGH';
export interface OriginalArtifact{schemaVersion:1;id:string;learnerId:string;kind:ArtifactKind;mimeType:string;uri?:string;rawText?:string;createdAt:string;immutable:true}
export interface ObservedSpan{id:string;artifactId:string;region:RegionKind;text:string;confidence:Confidence;alternatives?:string[];location?:{page?:number;x?:number;y?:number;width?:number;height?:number}}
export interface TranscriptCorrection{id:string;artifactId:string;spanId:string;observedText:string;confirmedText:string;occurredAt:string;kind:'OCR_ERROR_CORRECTED'}
export type TeacherDomain='VOCABULARY'|'CHUNK'|'GRAMMAR'|'COMPOSITION'|'OTHER'; export type InterventionDecision='CONTINUE'|'DEFER'|'INTERVENE'; export type SupportLevel='NONE'|'LIGHT'|'MODERATE'|'EXPLICIT'|'MODEL';
export type LearnerSignal='IMMEDIATE_SELF_REPAIR'|'DELAYED_SELF_REPAIR'|'PARTIAL_REPAIR'|'INDEPENDENT_SUCCESS'|'CUED_SUCCESS'|'GUIDED_SUCCESS'|'MODEL_IMITATION'|'CONFUSION'|'NO_PROGRESS'|'NEW_MISCONCEPTION'|'VALID_ALTERNATIVE'|'CHALLENGE_TEACHER'|'INTENT_CLARIFICATION'|'OTHER';
export interface EvidenceClaim{claim:string;evidenceIds:string[]} export interface TeacherHypothesis{id:string;explanation:string;confidence:Confidence;supportingEvidenceIds:string[];contradictingEvidenceIds:string[];discriminatingEvidenceNeeded?:string;teachingWouldDiffer:boolean}
export interface TeacherTurnPlan{observations:EvidenceClaim[];positiveEvidence:EvidenceClaim[];candidateIssues:Array<{issue:string;domain:TeacherDomain;confidence:Confidence;sourceEvidenceIds:string[]}>;competingHypotheses:TeacherHypothesis[];uncertainty?:string;interventionDecision:InterventionDecision;interventionReason?:string;teachingObjective?:{domain:TeacherDomain;targetId?:string;facet:string;desiredChange:string};teacherAction?:string;supportLevel:SupportLevel;rationale?:string;expectedLearnerSignals:Array<{signal:LearnerSignal;implication:string}>;replanIf:string[];stopIf:string[];teacherUtterance:string}
export interface TeachingTurn{id:string;learnerResponse:string;plan:TeacherTurnPlan;responseSignal?:LearnerSignal;createdAt:string} export interface TeachingEpisode{schemaVersion:1;id:string;learnerId:string;artifactId:string;sourceText:string;workingText:string;turns:TeachingTurn[];status:'ACTIVE'|'CLOSED_FOR_NOW'|'TRANSFER_SUPPORTED'|'RETENTION_SUPPORTED';createdAt:string;updatedAt:string}
export interface PckUnitContext{id:string;domain:TeacherDomain;state:string;entryMoves:string[];doNot:string[];independentSuccess:string;transfer?:string}
export interface TeacherPlanningContext{sourceText:string;learnerResponse:string;visibleModel?:string;ocrUnresolved?:boolean;priorEvidence:Array<{id:string;knowledgePointId:string;result:string;responseText?:string;metadata?:Record<string,unknown>}>;priorTurns:TeachingTurn[];targetProvenance?:string[];pckUnits?:PckUnitContext[];contextNovelty?:'SAME'|'NEW';originalSourceControlled?:boolean}
const claim=(claim:string,evidenceIds:string[]=[]):EvidenceClaim=>({claim,evidenceIds});
const base=(text:string)=>({observations:[claim(`Learner produced: ${text}`)],positiveEvidence:[] as EvidenceClaim[],candidateIssues:[] as TeacherTurnPlan['candidateIssues'],competingHypotheses:[] as TeacherHypothesis[],supportLevel:'NONE' as SupportLevel,expectedLearnerSignals:[] as TeacherTurnPlan['expectedLearnerSignals'],replanIf:['learner supplies contradictory evidence','the current move causes confusion'],stopIf:['independent repair and history support control']});
export function classifyLearnerSignal(response:string,previous?:TeacherTurnPlan):LearnerSignal{const lower=response.toLowerCase();if(/explanation confused|more confused|understood before/.test(lower))return'CONFUSION';if(/but |right\?|isn'?t|teacher.*wrong/.test(lower))return'CHALLENGE_TEACHER';if(/i (?:always )?(?:don'?t know|forget)|still confused/.test(lower))return'CONFUSION';if(/significant|read more/.test(lower)&&previous?.teacherAction==='SELF_REPAIR_PROMPT')return'IMMEDIATE_SELF_REPAIR';return'OTHER'}
export function planTeacherTurn(context:TeacherPlanningContext):TeacherTurnPlan{
 const text=context.learnerResponse.trim(),lower=text.toLowerCase(),last=context.priorTurns.at(-1),signal=classifyLearnerSignal(text,last?.plan),b=base(text);
 if(context.ocrUnresolved)return{...b,observations:[claim('Artifact transcription has decision-relevant uncertainty')],interventionDecision:'DEFER',uncertainty:'OCR alternatives could change the teaching target',teacherAction:'CLARIFY_TRANSCRIPT',teacherUtterance:'這個字我還不能確定原稿寫的是哪一個。請先確認原文，確認前我不會把它當成你的拼字問題。'};
 if(context.visibleModel&&text===context.visibleModel.trim())return{...b,positiveEvidence:[claim('Learner reproduced a visible model; independent control is not established')],interventionDecision:'INTERVENE',teacherAction:'FADE_SUPPORT',supportLevel:'MODEL',teacherUtterance:'這次有參考到可見答案。先把答案遮住，再用同一個意思自己寫一次。'};
 if(/改善\s*[→>-]\s*\??/.test(text)&&!(context.targetProvenance?.length))return{...b,interventionDecision:'DEFER',uncertainty:'No learner-specific target provenance',teacherAction:'DEFER',teacherUtterance:'目前沒有證據顯示你學過某個指定答案，所以不會把這題當成你的單字測驗。'};
 if(/future job/.test(lower)&&!/future jobs|future of work/.test(lower))return{...b,candidateIssues:[{issue:'future job intended meaning is ambiguous',domain:'CHUNK',confidence:'LOW',sourceEvidenceIds:[]}],interventionDecision:'INTERVENE',teacherAction:'CLARIFY_INTENT',supportLevel:'LIGHT',teacherUtterance:'你想說的是「你未來的一份工作」，還是「未來的工作型態」？意思不同，英文也會不同。'};
 if(signal==='CHALLENGE_TEACHER')return{...b,interventionDecision:'INTERVENE',teacherAction:'CLARIFY_INTENT',supportLevel:'LIGHT',teacherUtterance:'你提出的質疑有道理。先確認你原本要表達的意思，我會重新判斷，不先假設原本的修正一定正確。'};
 if(/always forget.*spell|cannot spell|can'?t spell/.test(lower))return{...b,observations:[...b.observations,claim('Learner reports recurring written-form retrieval difficulty')],competingHypotheses:[{id:'orthography',explanation:'Written form is plausibly unstable while meaning remains available',confidence:'HIGH',supportingEvidenceIds:[],contradictingEvidenceIds:[],teachingWouldDiffer:true},{id:'meaning-gap',explanation:'Meaning knowledge is not currently shown to be weak',confidence:'LOW',supportingEvidenceIds:[],contradictingEvidenceIds:[],teachingWouldDiffer:true}],interventionDecision:'INTERVENE',teachingObjective:{domain:'VOCABULARY',facet:'orthography',desiredChange:'reconstruct the written form independently'},teacherAction:'REPRESENT_DIFFERENTLY',supportLevel:'MODERATE',teacherUtterance:'了解，你卡住的是拼寫，不是意思。我們只處理字形：先找出你最常漏掉或排錯的那一段，再把完整字遮住重建。'};
 if(signal==='CONFUSION'&&(last||/explanation confused|more confused|understood before|still confused/.test(lower)))return{...b,observations:[...b.observations,claim('The learner reports that the prior teaching move increased confusion')],competingHypotheses:[{id:'teacher-induced-confusion',explanation:'The previous representation may have failed',confidence:'HIGH',supportingEvidenceIds:[],contradictingEvidenceIds:[],teachingWouldDiffer:true},{id:'prerequisite-missing',explanation:'A prerequisite may be missing',confidence:'LOW',supportingEvidenceIds:[],contradictingEvidenceIds:[],teachingWouldDiffer:true}],interventionDecision:'INTERVENE',teacherAction:'CHANGE_STRATEGY',supportLevel:'MODERATE',teacherUtterance:'剛才的說法讓事情更混亂，先撤回那個解釋。請只告訴我這句話裡「誰做什麼」，我換一種方式處理。'};
 if(last?.plan.teacherAction==='SELF_REPAIR_PROMPT'&&/\bsignificant\b/.test(lower))return{...b,positiveEvidence:[claim('Immediate independent spelling self-repair observed')],interventionDecision:'CONTINUE',teacherAction:'RETURN_TO_SOURCE',teacherUtterance:'你已經自己修正，而且先前紀錄支持你會這個字；不需要繼續做拼字教學。把修正放回原句即可。'};
 if(last?.plan.teacherAction==='SELF_REPAIR_PROMPT'&&/\bread more\b/.test(lower))return{...b,positiveEvidence:[claim('encourage + object + to + verb was preserved'),claim('read more was independently self-repaired')],interventionDecision:'CONTINUE',teacherAction:'RETURN_TO_SOURCE',teacherUtterance:'你自己改成 read more 了；encourage kids to read 這個結構原本就成立，不需要展開整套文法課。請放回原句。'};
 if(/make the environment better|have a major impact on/.test(lower))return{...b,positiveEvidence:[claim('Communicatively valid alternative English is present')],interventionDecision:'CONTINUE',teacherAction:'ACKNOWLEDGE',teacherUtterance:'這個英文表達成立，我不會為了指定字詞把它判錯。若要檢查另一個目標字，會另外處理。'};
 if(/allow\s+to\b/.test(lower))return{...b,candidateIssues:[{issue:'allow O to V requires an expressed object before to',domain:'CHUNK',confidence:'HIGH',sourceEvidenceIds:[]}],competingHypotheses:[{id:'allow-frame-gap',explanation:'The lexical-syntactic frame may be unstable',confidence:'MEDIUM',supportingEvidenceIds:[],contradictingEvidenceIds:[],teachingWouldDiffer:true},{id:'performance-slip',explanation:'The object may have been omitted under load',confidence:'LOW',supportingEvidenceIds:[],contradictingEvidenceIds:[],discriminatingEvidenceNeeded:'new meaning-based attempt',teachingWouldDiffer:true}],interventionDecision:'INTERVENE',teachingObjective:{domain:'CHUNK',targetId:'allow-o-to-v',facet:'lexical-syntactic pattern',desiredChange:'produce allow + person + to + verb'},teacherAction:last?'REPRESENT_DIFFERENTLY':'DECOMPOSE',supportLevel:last?'MODERATE':'LIGHT',teacherUtterance:last?'換個方式：先找出「誰被允許」，再接 to 和動作。請用一個新意思自己造句。':'這裡還沒有出現「誰被允許」。保留你的意思，用 allow + 人 + to + 動作重寫這一小段。',expectedLearnerSignals:[{signal:'INDEPENDENT_SUCCESS',implication:'local target control only'},{signal:'CONFUSION',implication:'change representation or reconsider diagnosis'}]};
 if(/parents encourage kids to more read/.test(lower))return{...b,positiveEvidence:[claim('encourage + object + to + verb is present')],candidateIssues:[{issue:'read more word order',domain:'GRAMMAR',confidence:'HIGH',sourceEvidenceIds:[]}],interventionDecision:'INTERVENE',teacherAction:'SELF_REPAIR_PROMPT',supportLevel:'LIGHT',teacherUtterance:'encourage kids to read 這一段有做對。只看 more 的位置：你可以自己調整 read 和 more 的順序嗎？'};
 if(/signigicant/.test(lower)){const strong=context.priorEvidence.filter(x=>/significant/.test(x.responseText??'')&&x.result==='SUCCESS').length>=3;return strong?{...b,candidateIssues:[{issue:'signigicant may be a performance slip',domain:'VOCABULARY',confidence:'LOW',sourceEvidenceIds:[]}],competingHypotheses:[{id:'slip',explanation:'Strong spelling history supports performance noise',confidence:'HIGH',supportingEvidenceIds:context.priorEvidence.map(x=>x.id),contradictingEvidenceIds:[],teachingWouldDiffer:true},{id:'orthography',explanation:'Written form may still be unstable',confidence:'LOW',supportingEvidenceIds:[],contradictingEvidenceIds:context.priorEvidence.map(x=>x.id),teachingWouldDiffer:true}],interventionDecision:'INTERVENE',teacherAction:'SELF_REPAIR_PROMPT',supportLevel:'LIGHT',teacherUtterance:'這個字看起來可能只是手誤。先不教規則，你能自己再看一次拼字嗎？'}:{...b,candidateIssues:[{issue:'significant written form may be unstable',domain:'VOCABULARY',confidence:'MEDIUM',sourceEvidenceIds:[]}],competingHypotheses:[{id:'orthography',explanation:'Meaning may be known while written form is unstable',confidence:'MEDIUM',supportingEvidenceIds:[],contradictingEvidenceIds:[],teachingWouldDiffer:true},{id:'unknown-word',explanation:'Lexical representation could be weak',confidence:'LOW',supportingEvidenceIds:[],contradictingEvidenceIds:[],discriminatingEvidenceNeeded:'what the learner reports forgetting',teachingWouldDiffer:true}],interventionDecision:'INTERVENE',teacherAction:'DISCRIMINATING_PROBE',supportLevel:'LIGHT',teacherUtterance:'你現在忘的是這個字的意思，還是知道意思但常常拼不出來？'};}
 if(context.originalSourceControlled&&context.contextNovelty==='NEW')return{...b,candidateIssues:[{issue:'new-context performance differs from source control',domain:'OTHER',confidence:'MEDIUM',sourceEvidenceIds:[]}],interventionDecision:'INTERVENE',teacherAction:'TRANSFER_CHECK',supportLevel:'NONE',teacherUtterance:'原句已能獨立完成，但新情境還不穩。兩者會分開記錄；我們只看這次新情境需要什麼。'};
 if(!text)return{...b,interventionDecision:'CONTINUE',teacherAction:'ELICIT',teacherUtterance:'先寫下你現在最想表達的一句英文。'};
 return{...b,positiveEvidence:[claim('Meaningful learner English is present')],candidateIssues:[{issue:'semantic interpretation requires production Teacher provider',domain:'OTHER',confidence:'LOW',sourceEvidenceIds:[]}],interventionDecision:'DEFER',teacherAction:'CONTINUE_TASK',teacherUtterance:'我先保留你的原意。請告訴我你最想先處理哪一小段。'};
}
