import AsyncStorage from '@react-native-async-storage/async-storage';
import { router } from 'expo-router';
import React,{useEffect,useRef,useState} from 'react';
import { ActivityIndicator,Pressable,StyleSheet,Text,TextInput,View } from 'react-native';
import { KeyboardAwareScrollView } from 'react-native-keyboard-controller';
import { SafeAreaView } from 'react-native-safe-area-context';
import { commitEvidenceCandidateV3 } from '../../src/application/evidence/commitEvidenceCandidateV3';
import { beginStage4RuntimeV4,confirmSourceIntentStage4V4,createOriginalArtifactV4,pauseStage4V4 } from '../../src/application/stage4/learnerRuntimeV4';
import { AdaptiveReviewSeedV4,adaptiveReviewSourceV4,allowResponseIsSuccessfulV4,controlledAdaptiveDecisionV4,projectAdaptiveWorkspaceV4,runAdaptiveDecisionPointV4 } from '../../src/application/stage5a/adaptiveOutputWorkspaceRuntime';
import { allowLookupEntries,sourceIntentKeepsAllowTargetV4 } from '../../src/application/stage5a/allowSliceV4';
import { Stage4RuntimeV4 } from '../../src/domain/stage4/LearnerRuntimeV4';
import { TaskContract } from '../../src/domain/task/TaskContract';
import { AsyncStorageCanonicalEvidenceLedgerV3 } from '../../src/repositories/AsyncStorageCanonicalEvidenceLedgerV3';
import { appendOriginalArtifactV4,loadActiveStage4RuntimeV4,saveStage4RuntimeV4 } from '../../src/repositories/Stage4RuntimeStorage';
import { ContextualLookup } from '../learning/ContextualLookup';
import { OutputWorkspace } from './OutputWorkspace';

const STATE_KEY='eot.stage5a.adaptive.output.workspace.v2',ledger=new AsyncStorageCanonicalEvidenceLedgerV3();
const uid=(prefix:string)=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
type Stored={runtimeId:string;draft:string;placed:boolean;targetApplies:boolean;seed:AdaptiveReviewSeedV4};

export function AllowTeachingSlice({learnerId,forceReset=false,seed='ALLOW_ROLE_MAP'}:{learnerId:string;forceReset?:boolean;seed?:AdaptiveReviewSeedV4}){
  const [runtime,setRuntime]=useState<Stage4RuntimeV4|null>(null),[draft,setDraft]=useState(''),[placed,setPlaced]=useState(false),[targetApplies,setTargetApplies]=useState(true),[loading,setLoading]=useState(true),[error,setError]=useState(''),[intentOpen,setIntentOpen]=useState(false),[intent,setIntent]=useState('');
  const lock=useRef(false);
  async function persist(next:Stage4RuntimeV4,ui?:Partial<Stored>){const state:Stored={runtimeId:next.id,draft:ui?.draft??draft,placed:ui?.placed??placed,targetApplies:ui?.targetApplies??targetApplies,seed:ui?.seed??seed};setRuntime(next);setDraft(state.draft);setPlaced(state.placed);setTargetApplies(state.targetApplies);await saveStage4RuntimeV4(next);await AsyncStorage.setItem(STATE_KEY,JSON.stringify(state))}
  async function initialize(reset:boolean){setLoading(true);setError('');try{if(!reset){const raw=await AsyncStorage.getItem(STATE_KEY),stored=raw?JSON.parse(raw) as Stored:null,active=await loadActiveStage4RuntimeV4(learnerId);if(stored&&active&&stored.runtimeId===active.id&&stored.seed===seed){setRuntime(active);setDraft(stored.draft);setPlaced(stored.placed);setTargetApplies(stored.targetApplies);return}}const source=adaptiveReviewSourceV4(seed),artifact=createOriginalArtifactV4({id:uid('review-artifact'),learnerId,source:'PASTE',mode:'WRITING',pages:[{page:1,mimeType:'text/plain',originalText:source}],submittedAt:new Date().toISOString()});await appendOriginalArtifactV4(artifact);const started=beginStage4RuntimeV4(artifact,[{id:uid('span'),artifactId:artifact.id,region:'LEARNER_WRITING',text:source,confidence:'HIGH',alternatives:[]}],true),result=await runAdaptiveDecisionPointV4(started,{kind:'INITIAL'},context=>controlledAdaptiveDecisionV4(seed,context),true);await persist(result.runtime,{draft:'',placed:false,targetApplies:true,seed})}catch(e){setError(e instanceof Error?e.message:'無法開啟這份作品')}finally{setLoading(false)}}
  useEffect(()=>{const timer=setTimeout(()=>{void initialize(forceReset)},0);return()=>clearTimeout(timer);// eslint-disable-next-line react-hooks/exhaustive-deps
  },[forceReset,learnerId,seed]);
  async function saveDraft(value:string){setDraft(value);if(runtime)await AsyncStorage.setItem(STATE_KEY,JSON.stringify({runtimeId:runtime.id,draft:value,placed,targetApplies,seed} satisfies Stored))}
  async function commitCandidate(next:Stage4RuntimeV4,previous:Stage4RuntimeV4){const candidate=next.evidenceCandidates.at(-1);if(!candidate||candidate.evidenceEligibility!=='ELIGIBLE')return next;const targetRef=candidate.targetRef??previous.decision?.targetReference??'allow-object-infinitive',purpose=previous.decision?.pedagogicalIntent==='ASSESS'?'DIAGNOSTIC':previous.decision?.pedagogicalIntent==='TRANSFER'?'TRANSFER':'PRACTICE';const task:TaskContract={id:`workspace-${next.id}`,purpose,taskFamily:'WRITING',targetRefs:[targetRef],contextNovelty:candidate.contextNovelty==='SOURCE'?'SOURCE':candidate.contextNovelty==='CHANGED_CONTEXT'?'CHANGED_CONTEXT':'SAME_CONTEXT',responseOpenness:'OPEN',supportExposed:candidate.supportBeforeResponse==='NONE'?['NONE']:['CUE'],meaningProvenance:'LEARNER_ORIGINATED',eligibleClaims:candidate.capabilityFacet?[{targetRef,facet:candidate.capabilityFacet}]:[],forbiddenClaims:[]},result=await commitEvidenceCandidateV3({candidate,task,learnerId,id:uid('evidence'),occurredAt:new Date().toISOString(),ledger});if(!result.accepted)throw new Error(`evidence_guard_rejected:${result.reasons.join(',')}`);return{...next,trace:[...next.trace,{id:uid('trace'),occurredAt:new Date().toISOString(),kind:'EVIDENCE_COMMITTED' as const,fixture:false,payload:{evidenceId:result.event.id}}]}}
  async function decide(observation:{kind:'OUTPUT_SUBMITTED'|'LANGUAGE_OBJECT_PLACED'|'HELP_REQUESTED'|'CONTINUE_REQUESTED';response?:string;success?:boolean;payload?:Record<string,string|number|boolean>},ui?:Partial<Stored>){if(!runtime)return;const result=await runAdaptiveDecisionPointV4(runtime,observation,context=>controlledAdaptiveDecisionV4(seed,context),true),committed=await commitCandidate(result.runtime,runtime);await persist(committed,ui)}
  async function guarded(action:()=>Promise<void>){if(lock.current)return;lock.current=true;try{setError('');await action()}catch(e){setError(e instanceof Error?e.message:'無法完成這個動作')}finally{lock.current=false}}
  async function primary(){if(!runtime)return;const vm=projectAdaptiveWorkspaceV4({runtime,draft,placed});if(vm.nextAction.kind==='CONTINUE_SOURCE'){router.replace('/(tabs)');return}if(!vm.output.editable){await decide({kind:'CONTINUE_REQUESTED'},{draft:''});return}const success=allowResponseIsSuccessfulV4(draft);await decide({kind:'OUTPUT_SUBMITTED',response:draft,success},{draft:success?'':draft})}
  async function place(){if(!placed)await decide({kind:'LANGUAGE_OBJECT_PLACED',success:false,payload:{item:'students',role:'ALLOWED_PARTICIPANT'}},{placed:true,draft:''})}
  async function help(){await decide({kind:'HELP_REQUESTED',success:false,payload:{learnerRequestedHelp:true}})}
  async function confirmIntent(){if(!runtime||!intent.trim())return;const applies=sourceIntentKeepsAllowTargetV4(intent),next=confirmSourceIntentStage4V4(runtime,intent.trim());await persist(next,{targetApplies:applies});setIntentOpen(false)}
  if(loading)return <SafeAreaView style={s.safe}><ActivityIndicator color="#654D3B"/></SafeAreaView>;
  if(!runtime)return <SafeAreaView style={s.safe}><Text style={s.error}>{error||'無法載入作品'}</Text></SafeAreaView>;
  if(runtime.status==='PAUSED')return <SafeAreaView style={s.safe}><View style={s.pausePage}><Text style={s.title}>已暫停</Text><Text style={s.copy}>你的原作、目前輸出與教學狀態都已保存。</Text><Primary label="繼續" onPress={()=>void persist({...runtime,status:'LEARNING'})}/><Quiet label="回到 Today" onPress={()=>router.replace('/(tabs)')}/></View></SafeAreaView>;
  if(intentOpen)return <SafeAreaView style={s.safe}><KeyboardAwareScrollView contentContainerStyle={s.intentPage} keyboardShouldPersistTaps="handled" bottomOffset={96}><View style={s.canvas}><Text style={s.kicker}>先確認你的意思</Text><Text style={s.title}>你原本想表達什麼？</Text><TextInput accessibilityLabel="原本想表達的意思" multiline value={intent} onChangeText={setIntent} placeholder="可以用中文或英文告訴我" style={s.intentInput}/><Text style={s.copy}>原始作品會保留；這次確認不是學習證據。</Text><Primary label="更新我的意思" onPress={()=>void confirmIntent()}/><Quiet label="取消" onPress={()=>setIntentOpen(false)}/></View></KeyboardAwareScrollView></SafeAreaView>;
  if(!targetApplies)return <Shell><Top onPause={()=>void persist(pauseStage4V4(runtime))}/><View style={s.changed}><Text style={s.title}>已更新你的意思</Text><Text style={s.copy}>目前這個 allow 句型不一定是你要處理的重點，因此不會建立相關學習證據。</Text><Primary label="回到 Today" onPress={()=>router.replace('/(tabs)')}/></View></Shell>;
  const vm=projectAdaptiveWorkspaceV4({runtime,draft,placed}),lookup=['ALLOW_ROLE_MAP','TEACHING_SUCCEEDS','TEACHING_CHANGES_REPRESENTATION'].includes(seed)?<ContextualLookup entries={allowLookupEntries}/>:undefined;return <Shell><Top onPause={()=>void persist(pauseStage4V4(runtime))}/><OutputWorkspace vm={vm} value={draft} onChangeText={value=>void saveDraft(value)} onPrimary={()=>void guarded(primary)} onPlaceLanguageObject={()=>void guarded(place)} onStuck={()=>void guarded(help)} onCorrectIntent={()=>setIntentOpen(true)} feedback={error} lookup={lookup} /></Shell>
}
function Shell({children}:{children:React.ReactNode}){return <SafeAreaView style={s.safe}><KeyboardAwareScrollView style={s.safe} contentContainerStyle={s.page} keyboardShouldPersistTaps="handled" bottomOffset={96}><View style={s.canvas}>{children}</View></KeyboardAwareScrollView></SafeAreaView>}
function Top({onPause}:{onPause:()=>void}){return <View style={s.top}><View style={s.brand}><View style={s.mark}><Text style={s.markText}>E</Text></View><Text style={s.brandText}>EOT</Text></View><Pressable accessibilityRole="button" onPress={onPause}><Text style={s.pause}>先暫停</Text></Pressable></View>}
function Primary({label,onPress}:{label:string;onPress:()=>void}){return <Pressable accessibilityRole="button" onPress={onPress} style={s.primary}><Text style={s.primaryText}>{label}</Text></Pressable>}
function Quiet({label,onPress}:{label:string;onPress:()=>void}){return <Pressable accessibilityRole="button" onPress={onPress} style={s.quiet}><Text style={s.quietText}>{label}</Text></Pressable>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#F1EEE8'},page:{flexGrow:1,width:'100%',paddingBottom:40},canvas:{width:'100%',maxWidth:390,alignSelf:'center',backgroundColor:'#FFFEFC',minHeight:'100%'},top:{height:60,paddingHorizontal:20,borderTopWidth:5,borderTopColor:'#9A785C',borderBottomWidth:1,borderBottomColor:'#E3DED6',flexDirection:'row',alignItems:'center',justifyContent:'space-between'},brand:{flexDirection:'row',alignItems:'center',gap:9},mark:{width:25,height:25,borderRadius:7,borderWidth:1,borderColor:'#DCCBB8',alignItems:'center',justifyContent:'center'},markText:{fontSize:10,fontWeight:'700',color:'#654D3B'},brandText:{fontSize:13,fontWeight:'800',letterSpacing:1.4,color:'#292622'},pause:{minHeight:44,textAlignVertical:'center',fontSize:12,fontWeight:'600',color:'#746E66'},pausePage:{flex:1,width:'100%',maxWidth:390,alignSelf:'center',justifyContent:'center',padding:24,gap:14,backgroundColor:'#FFFEFC'},intentPage:{flexGrow:1,justifyContent:'center',backgroundColor:'#F1EEE8'},kicker:{marginTop:70,paddingHorizontal:20,fontSize:11,fontWeight:'700',color:'#9A785C'},title:{paddingHorizontal:20,fontSize:28,lineHeight:38,fontWeight:'700',color:'#292622'},copy:{marginHorizontal:20,fontSize:13,lineHeight:21,color:'#746E66'},intentInput:{margin:20,minHeight:150,padding:15,borderWidth:1,borderColor:'#E3DED6',borderRadius:14,fontSize:16,textAlignVertical:'top'},changed:{padding:20,gap:14},primary:{minHeight:50,marginHorizontal:20,borderRadius:13,backgroundColor:'#654D3B',alignItems:'center',justifyContent:'center'},primaryText:{fontSize:14,fontWeight:'700',color:'#FFFEFC'},quiet:{minHeight:44,alignItems:'center',justifyContent:'center'},quietText:{fontSize:12,fontWeight:'600',color:'#6E655C'},error:{padding:20,color:'#9A5A52'}});
