const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const read=p=>fs.readFileSync(p,'utf8'),build=process.env.EOT_DOMAIN_TEST_BUILD||'.domain-test-build',req=rel=>require(path.resolve(process.cwd(),build,rel));
const product=req('product/index.js'),tutorial=req('experience/firstDayTutorialState.js');
const seed={learnerId:'first-run',accountId:null,displayName:'Learner',demoMode:true},now='2026-09-14T00:00:00.000Z';
const milestone=(actionId,route)=>({actionId,route,occurredAt:now});

test('fresh value screen commits into the date screen and date can be unknown',()=>{const goals=read('app/onboarding/goals.tsx'),date=read('app/onboarding/date.tsx');assert.match(goals,/setupStage:'DATE'/);assert.match(goals,/router\.push\('\/onboarding\/date'\)/);assert.match(date,/下一次模考或學測，大概什麼時候？/);assert.match(date,/minimumDate=\{tomorrow\(\)\}/);assert.match(date,/還不確定/);assert.match(date,/examTargetUnknown:true/)});
test('new learner time choices are exactly 10, 20 and 30 plus with semantic persistence',()=>{const time=read('app/onboarding/time.tsx'),labels=[...time.matchAll(/label:'([^']+)'/g)].map(x=>x[1]);assert.deepEqual(labels,['10 分鐘','20 分鐘','30+ 分鐘']);assert.match(time,/dailyBudget:choice\.budget/);assert.match(time,/single tap|onPress=\{\(\)=>void select/)});
test('legacy persisted time values remain loadable without destructive migration',()=>{for(const minutes of[5,15,30]){const initial=product.createInitialProductProfileV2(seed,now),legacy={...initial,study:{dailyStudyMinutes:minutes,preferredSessionMinutes:minutes}};const loaded=product.normalizeProductProfileV2(legacy,seed,now);assert.equal(loaded.study.dailyStudyMinutes,minutes);assert.equal(loaded.study.preferredSessionMinutes,minutes)}});
test('signal screen exposes the two locked paths and routes into existing production branches',()=>{const signal=read('app/onboarding/signal.tsx');assert.equal((signal.match(/我剛考完模考/g)||[]).length,1);assert.equal((signal.match(/直接幫我測/g)||[]).length,1);assert.match(signal,/source==='MOCK'\?'\/onboarding\/exam':'\/quick-calibration'/);assert.match(signal,/initialSignalSource:source/)});
test('optional mock and adaptive diagnostic both converge on handoff',()=>{const mock=read('app/onboarding/exam.tsx'),quick=read('app/quick-calibration.tsx');assert.match(mock,/setupStage:'HANDOFF'/);assert.match(mock,/router\.push\('\/onboarding\/handoff'\)/);assert.match(mock,/mockScoreDraft:next/);assert.match(quick,/gsatCalibrationEnoughEarlyV1/);assert.match(quick,/quickDiagnosticPracticeFamily/);assert.match(quick,/router\.replace\('\/onboarding\/handoff'/)});
test('handoff uses promoted production content and starts its exact persisted route',()=>{const handoff=read('app/onboarding/handoff.tsx');assert.match(handoff,/我先從這裡幫你搶分。/);assert.match(handoff,/開始第一回/);assert.match(handoff,/loadTodayCurriculumVMV1/);assert.match(handoff,/resolveProductionExamContentForTargetV1/);assert.match(handoff,/examBetaTaskForLearner/);assert.match(handoff,/taskId=\$\{encodeURIComponent\(task\.task_id\)\}/);assert.match(handoff,/TODAY_STARTED:current\.milestones\.TODAY_STARTED/);assert.match(handoff,/learningRoute:mission\.route/);assert.match(handoff,/router\.replace\(mission\.route/)});
test('kill before start resumes handoff; start resumes mission; returning learner skips first run',()=>{const initial=product.createInitialProductProfileV2(seed,now),base={...initial,onboarding:{...initial.onboarding,status:'IN_PROGRESS',setupStage:'HANDOFF',firstDay:{version:1,milestones:{OPENING_COMPLETED:milestone('open','/onboarding/goals'),INITIAL_CONTEXT_COMPLETED:milestone('context','/onboarding/time')}}}};assert.equal(tutorial.firstDayResumeRoute(base),'/onboarding/handoff');const mission='/exam-practice?practiceFamily=VOCABULARY_USAGE&taskId=VOC-G-001&origin=TODAY',started={...base,onboarding:{...base.onboarding,setupStage:'MISSION_STARTED',firstDay:{...base.onboarding.firstDay,learningRoute:mission,milestones:{...base.onboarding.firstDay.milestones,TODAY_STARTED:milestone('start','/onboarding/handoff')}}}};assert.equal(tutorial.firstDayResumeRoute(started),mission);const returning={...started,onboarding:{...started.onboarding,status:'COMPLETED'}};assert.equal(tutorial.firstDayResumeRoute(returning),'/(tabs)')});
