const test=require('node:test');const assert=require('node:assert/strict');const path=require('node:path');
const req=rel=>require(path.join(__dirname,'..','..','.domain-test-build',rel));
const bank=req('content/examBetaBank.js'),receipt=req('content/examValidationReceipts.js'),promotion=req('content/examCanonicalPromotions.js');
test('exact reviewed bytes have an immutable passing receipt and remain deliverable',()=>{const task=bank.examBetaTaskById('VOCABULARY','VOC-G-001');assert.ok(task);const row=receipt.examValidationReceiptV1(task.task_id);assert.equal(row.immutable,true);assert.equal(receipt.validateExamReceiptV1(task,row).valid,true)});
test('changing one distractor invalidates the reviewed content hash',()=>{const task=bank.examBetaTaskById('VOCABULARY','VOC-G-001'),mutated={...task,payload:{...task.payload,questions:[{...task.payload.questions[0],options:task.payload.questions[0].options.map((x,i)=>i===1?{...x,text:'changed after review'}:x)}]}};assert.deepEqual(receipt.validateExamReceiptV1(mutated).reasons,['CONTENT_HASH_MISMATCH'])});
test('absent receipt and failed uniqueness gate fail closed',()=>{const task={task_id:'UNREVIEWED',family:'VOCABULARY',subtype:'X',payload:{},canonicalBinding:{}};assert.deepEqual(receipt.validateExamReceiptV1(task).reasons,['VALIDATION_RECEIPT_ABSENT']);const contentHash=receipt.examContentHashV1(task),gates={FORMAT_AUTHENTICITY:'PASS',ANSWER_RUBRIC_VALIDITY:'PASS',ANSWER_UNIQUENESS:'FAIL',DISTRACTOR_CAUSALITY:'PASS',SEMANTIC_RUBRIC_SAFETY:'NOT_APPLICABLE',FRESHNESS_LINEAGE:'PASS',CANONICAL_BINDING:'PASS',PROVENANCE_LICENSE:'PASS',PRE_USE_VALIDATION:'PASS'},failed={schemaVersion:1,taskId:'UNREVIEWED',contentHash,bindingVersion:'exam-binding-v1',reviewedAt:'2026-09-06',reviewer:'EOT_EDITORIAL',gates,immutable:true};assert.deepEqual(receipt.validateExamReceiptV1(task,failed).reasons,['ANSWER_UNIQUENESS_FAIL'])});
test('receipt alone cannot create explicit promotion authority',()=>{assert.equal(promotion.canonicalExamPromotionV1('UNREVIEWED'),undefined)});
test('the old ambiguous COMP-G-004 receipt is not an eligible current receipt',()=>{assert.notEqual(receipt.examValidationReceiptV1('COMP-G-004').contentHash,receipt.OLD_AMBIGUOUS_COMP_G_004_HASH)});
test('V35 rows require both immutable receipts and explicit promotion',()=>{for(const [family,taskId] of [['READING','V14-READ-F-001'],['MIXED','V10-MIX-001']]){const task=bank.examBetaTaskById(family,taskId);assert.ok(task);assert.equal(receipt.validateExamReceiptV1(task).valid,true);assert.equal(receipt.examValidationReceiptV1(task.task_id).immutable,true);assert.equal(promotion.canonicalExamPromotionV1(task.task_id).status,'PROMOTED')}});
