const test=require('node:test');const assert=require('node:assert/strict');const path=require('node:path');
const req=rel=>require(path.join(__dirname,'..','..','.domain-test-build',rel));
const bank=req('content/examBetaBank.js'),semantic=req('application/exam/examSemanticAssessment.js'),admission=req('application/exam/examEvidenceAdmission.js'),authority=req('application/exam/examV35SemanticRubricAuthority.js'),receipts=req('content/examValidationReceipts.js');

test('V35 Translation uses its compiled task-scoped meaning and relation rubric for natural alternatives',()=>{const task=bank.examBetaTaskById('TRANSLATION','V18-TRANS-001');assert.ok(task);assert.equal(authority.hasV35SemanticRubricAuthorityV1(task),true);assert.equal(receipts.validateExamReceiptV1(task).valid,true);const result=semantic.assessExamSemanticUnitsV1({task,response:{0:'If you set a small target first, it becomes easier to take action.'}});const decision=Object.values(result.decisionsByUnitId)[0];assert.equal(decision.authority,'BOUNDED_RUBRIC');assert.equal(decision.outcome,'CORRECT');assert.ok(decision.reasonCodes.includes('NATURAL_PARAPHRASES_ALLOWED'))});

test('V35 Mixed keeps P3 bounded and separate from exact-key P1 and P2',()=>{const task=bank.examBetaTaskById('MIXED','V10-MIX-001');assert.ok(task);const result=semantic.assessExamSemanticUnitsV1({task,response:{P1:'C',P2:'13:30',P3:'Registration closes 30 minutes before the class, at 10:30, so arriving at 10:45 is too late.'}});assert.deepEqual(Object.keys(result.decisionsByUnitId),['V10-MIX-001:P3']);assert.equal(result.outcomesByUnitId['V10-MIX-001:P3'],'CORRECT');assert.equal(task.canonicalBinding.units.find(x=>x.responseKey==='P1').evaluatorKind,'EXACT_KEY');assert.equal(task.canonicalBinding.units.find(x=>x.responseKey==='P2').evaluatorKind,'EXACT_KEY')});

test('V35 Writing scores task constraints without a reference answer',()=>{const task=bank.examBetaTaskById('WRITING','V19-WRITE-S-05');assert.ok(task);const response='In my opinion, students should keep a study progress log every day. This record helps them notice weak areas because they can compare each session. It also makes the next study plan clearer.';const result=semantic.assessExamSemanticUnitsV1({task,response:{writing:response}});const purpose=result.decisionsByUnitId[task.canonicalBinding.units.find(x=>x.canonicalTargetRef==='writing.purpose-audience').unitId];assert.equal(purpose.outcome,'CORRECT');assert.ok(purpose.reasonCodes.includes('MULTIPLE_IDEAS_AND_ORGANIZATIONS_ALLOWED'))});

test('part-scoped answer or model exposure assists Mixed P3 without contaminating P1 or P2',()=>{const task=bank.examBetaTaskById('MIXED','V10-MIX-001'),semanticResult=semantic.assessExamSemanticUnitsV1({task,response:{P3:'Registration closes 30 minutes before the class, at 10:30, so arriving at 10:45 is too late.'}}),units=task.canonicalBinding.units.map(unit=>({unitId:unit.unitId,targetRef:unit.canonicalTargetRef,facet:unit.canonicalFacet,outcome:'SUCCESS',semanticAssessment:semanticResult.decisionsByUnitId[unit.unitId]})),result={assessment:'SUCCESS',reasonCodes:[],unitResults:units,triage:[],evidenceCommitAllowed:true};const admitted=admission.admitExamEvidenceV1({learnerId:'v35',sessionId:'mixed-scope',task,result,support:'NONE',lookupExposure:[],supportByUnitId:{'V10-MIX-001:P3':'MODEL'},exposureByUnitId:{'V10-MIX-001:P3':['ANSWER_REVEAL:P1']},freshnessIdentity:'fresh-v35',occurredAt:'2026-09-09T00:00:00.000Z'});assert.equal(admitted.find(x=>x.unitId.endsWith(':P1')).proofMode,'INDEPENDENT');assert.equal(admitted.find(x=>x.unitId.endsWith(':P2')).proofMode,'INDEPENDENT');const p3=admitted.find(x=>x.unitId.endsWith(':P3'));assert.equal(p3.proofMode,'ASSISTED');assert.equal(p3.candidate.performanceDimension,'PRODUCTION')});
