const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');
const read=p=>fs.readFileSync(p,'utf8');
test('mock-result production route is Android keyboard-aware and distinguishes wrong count from earned score',()=>{const shell=read('components/experience/OnboardingShell.tsx'),exam=read('app/onboarding/exam.tsx');assert.match(shell,/KeyboardAwareScrollView/);assert.match(shell,/bottomOffset=\{96\}/);assert.match(shell,/paddingBottom:160/);assert.match(exam,/選擇題：填「錯幾題」/);assert.match(exam,/非選擇題：填「拿幾分」/);assert.doesNotMatch(exam,/能力證據/)});
test('every visible Exam practice card directly invokes its real route handler',()=>{const practice=read('app/(tabs)/practice.tsx');assert.match(practice,/entries\.map\(entry=><Pressable[\s\S]*onPress=\{\(\)=>start\(entry\)\}/);assert.match(practice,/practiceRouteParamsV1\(\{entry,origin:'PRACTICE'\}\)/);assert.match(practice,/router\.push\(`\$\{entry\.destination\}\?\$\{query\}`/);assert.match(practice,/accessibilityLabel=\{`開始\$\{entry\.label\}`\}/)});
test('universal lookup retains phrase-first resolver and degrades to the production native corpus',()=>{const lookup=read('components/learning/UniversalLookupText.tsx');assert.match(lookup,/resolveTapPhraseFirstContextV1/);assert.match(lookup,/nativeCorpusServiceV1\.get\(\)/);assert.match(lookup,/corpus\.port\.lookupLemma/);assert.match(lookup,/sense\.glosses\[0\]/);assert.match(lookup,/assessmentMode/)});
test('first-open transition is a persisted, skippable first-use bridge while production copy hides Learner placeholder',()=>{const intro=read('components/experience/EOTFirstLaunchIntro.tsx'),state=read('src/experience/firstUseState.ts'),goals=read('app/onboarding/goals.tsx'),today=read('app/(tabs)/index.tsx');assert.match(intro,/學過的，讓你真正用得出來。/);assert.match(intro,/onPress=\{\(\)=>finish\(\)\}/);assert.match(intro,/2300/);assert.match(intro,/AccessibilityInfo\.isReduceMotionEnabled/);assert.match(state,/onboarding\.status!==['"]COMPLETED['"]&&!profile\.gsatBeta\.coachMarks\.opening/);assert.match(goals,/coachMarks:\{opening:true\}/);assert.match(today,/displayName==='Learner'\?'':/);assert.doesNotMatch(today,/能力證據/)});
test('normal first run has no standalone lookup tutorial and coach marks require real actions',()=>{const layout=read('app/_layout.tsx'),time=read('app/onboarding/time.tsx'),today=read('app/(tabs)/index.tsx'),practice=read('app/(tabs)/practice.tsx'),exam=read('app/exam-practice.tsx');assert.equal(fs.existsSync('app/onboarding/lookup.tsx'),false);assert.doesNotMatch(layout,/onboarding\/lookup/);assert.match(time,/router\.replace\('\/\(tabs\)'\)/);assert.match(today,/coldStart\?\.kind==='CALIBRATION'\?'\/quick-calibration'/);assert.match(practice,/function start[\s\S]*coachMarks:\{practice:true\}/);assert.doesNotMatch(practice,/coachAction|知道了/);assert.match(exam,/recordLookup[\s\S]*markCoach\('lookup'\)/);assert.match(exam,/await applyDecision\(next[\s\S]*markCoach\('teacher'\)/)});
test('production icon config points to EOT regular and adaptive assets',()=>{const config=JSON.parse(read('app.json'));assert.equal(config.expo.icon,'./assets/images/eot-icon.png');assert.equal(config.expo.android.icon,'./assets/images/eot-icon.png');assert.equal(config.expo.android.adaptiveIcon.foregroundImage,'./assets/images/eot-adaptive-foreground.png');assert.equal(config.expo.android.adaptiveIcon.backgroundColor,'#F5F0E6');assert.ok(fs.statSync('assets/images/eot-icon.png').size>10000);assert.ok(fs.statSync('assets/images/eot-adaptive-foreground.png').size>10000)});
test('review-only exhaustion is visible and cannot submit as unsupported independent proof',()=>{const exam=read('app/exam-practice.tsx');assert.match(exam,/allocationPurpose==='REVIEW_ONLY'\?'LIGHT'/);assert.match(exam,/support: assessmentSupport/);assert.match(exam,/這題是複習題，不會當成一題全新的獨立能力確認/)});
