const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const build=process.env.EOT_DOMAIN_TEST_BUILD||'.domain-test-build-wave-m';const req=rel=>require(path.resolve(process.cwd(),build,rel));
const life=req('lesson-runtime/sessionLifecycle.js');const time=req('teacher-runtime/sessionTime.js');const {lessonRuntimeCapabilityStatesV1,lessonRuntimeWaveSummaryV1}=req('lesson-runtime/capabilities.js');
const draft=req('lesson-runtime/learnerDraft.js');
const baseRuntime=(status='LEARNING')=>({id:'runtime-1',learnerId:'learner',artifact:{id:'artifact',learnerId:'learner',source:'PASTE',mode:'WRITING',pages:[{page:1,mimeType:'text/plain',originalText:'x'}],submittedAt:'2026-08-28T00:00:00.000Z',schemaVersion:4,immutable:true},spans:[],confirmations:[],usableSourceText:'x',status,tutorSession:{startedAt:'2026-08-28T00:00:00.000Z',budgetMinutes:10,accumulatedPausedMs:0},decision:{objectiveId:'o',lessonPlanId:'l',focusFacet:'CONSTRUCTION',targetReference:'allow-object-infinitive',pedagogicalIntent:'PRACTICE',selectedBlockId:'guided-sentence-builder',supportLevel:'LIGHT',contextProvenance:'SAME_CONTEXT',evidenceToObserve:[],successTransitionIntent:'ASSESS',failureTransitionIntent:'INCREASE_SUPPORT',confidence:'HIGH',unresolvedAmbiguity:null,internalDecisionReason:'fixture',configuration:{decisionPointId:'point-1'}},blockState:{instanceId:'block-instance-1',blockId:'guided-sentence-builder',supportLevel:'LIGHT',visibleBeforeResponse:[],attempt:1,status:'INTERACTING'},blockEvents:[],observations:[],evidenceCandidates:[],trace:[]});

test('lesson action identity is stable for an exact duplicate and changes with opportunity or response',async()=>{const r=baseRuntime(),a=await life.lessonActionIdentityV1({runtime:r,type:'ANSWER_SUBMITTED',taskId:'task-1',response:'same answer'}),b=await life.lessonActionIdentityV1({runtime:r,type:'ANSWER_SUBMITTED',taskId:'task-1',response:'same answer'}),whitespaceChange=await life.lessonActionIdentityV1({runtime:r,type:'ANSWER_SUBMITTED',taskId:'task-1',response:'same  answer'}),c=await life.lessonActionIdentityV1({runtime:r,type:'ANSWER_SUBMITTED',taskId:'task-1',response:'different'}),d=await life.lessonActionIdentityV1({runtime:{...r,blockState:{...r.blockState,instanceId:'block-instance-2'}},type:'ANSWER_SUBMITTED',taskId:'task-1',response:'same answer'}),e=await life.lessonActionIdentityV1({runtime:{...r,decision:{...r.decision,configuration:{...r.decision.configuration,decisionPointId:'point-2'}}},type:'ANSWER_SUBMITTED',taskId:'task-1',response:'same answer'}),f=await life.lessonActionIdentityV1({runtime:r,type:'ANSWER_SUBMITTED',taskId:'task-2',response:'same answer'});assert.equal(a,b);assert.match(a,/^lesson-action:sha256:[0-9a-f]{64}$/);assert.notEqual(a,whitespaceChange);assert.notEqual(a,c);assert.notEqual(a,d);assert.notEqual(a,e);assert.notEqual(a,f)});

test('known FNV-1a collision cannot alias two genuinely different learner answers',async()=>{const r=baseRuntime(),firstInput={runtime:r,type:'ANSWER_SUBMITTED',taskId:'task-1',response:'answer-n98sdp-11lkl3j'},secondInput={runtime:r,type:'ANSWER_SUBMITTED',taskId:'task-1',response:'answer-1v047b3-1bzblp'},firstPayload=life.canonicalLessonActionPayloadV1(firstInput),secondPayload=life.canonicalLessonActionPayloadV1(secondInput),first=await life.lessonActionIdentityV1(firstInput),second=await life.lessonActionIdentityV1(secondInput);assert.notEqual(first,second);const restored={...r,blockEvents:[{id:'event-first',instanceId:r.blockState.instanceId,type:'ANSWER_SUBMITTED',payload:{actionIdentity:first,actionPayloadCanonical:firstPayload,response:firstInput.response,taskId:'task-1'},supportLevel:'LIGHT',visibleBeforeResponse:[],occurredAt:'2026-08-28T00:01:00Z'}]};assert.equal(life.lessonActionAlreadyRecordedV1(restored,first,firstPayload),true);assert.equal(life.lessonActionAlreadyRecordedV1(restored,second,secondPayload),false)});

test('canonical action payload resists delimiter ambiguity and normalizes equivalent Unicode',async()=>{const r=baseRuntime(),splitA=await life.lessonActionIdentityV1({runtime:r,type:'ANSWER|SUBMITTED',taskId:'task',response:'answer'}),splitB=await life.lessonActionIdentityV1({runtime:r,type:'ANSWER',taskId:'SUBMITTED|task',response:'answer'}),composed=await life.lessonActionIdentityV1({runtime:r,type:'ANSWER_SUBMITTED',taskId:'task',response:'caf\u00e9'}),decomposed=await life.lessonActionIdentityV1({runtime:r,type:'ANSWER_SUBMITTED',taskId:'task',response:'cafe\u0301'});assert.notEqual(splitA,splitB);assert.equal(composed,decomposed)});
test('pause and resume preserve the exact pre-pause pedagogical status and exclude paused time',()=>{let r=baseRuntime('READY');r=life.pauseLessonSessionV1(r,'2026-08-28T00:02:00.000Z');assert.equal(r.status,'PAUSED');assert.equal(r.sessionControl.pausedFromStatus,'READY');assert.equal(time.tutorTimeRemainingMinutesV1(r,'2026-08-28T00:08:00.000Z'),8);r=life.resumeLessonSessionV1(r,'2026-08-28T00:08:00.000Z');assert.equal(r.status,'READY');assert.equal(r.tutorSession.accumulatedPausedMs,6*60*1000);assert.equal(time.tutorTimeRemainingMinutesV1(r,'2026-08-28T00:09:00.000Z'),7)});
test('return-to-source closes tutor time and cannot be resumed as an active lesson',()=>{const closed=life.closeReturnedLessonSessionV1(baseRuntime(),'2026-08-28T00:05:00.000Z');assert.equal(closed.status,'RETURNED');assert.equal(closed.tutorSession.endedAt,'2026-08-28T00:05:00.000Z');assert.equal(life.sessionCanResumeV1(closed),false);assert.throws(()=>life.resumeLessonSessionV1(closed),/cannot_resume/)});
test('background/foreground pauses timer without changing pedagogical status',()=>{let r=baseRuntime('LEARNING');r=life.backgroundLessonSessionV1(r,'2026-08-28T00:02:00.000Z');assert.equal(r.status,'LEARNING');assert.equal(r.sessionControl.lifecycle,'BACKGROUND');r=life.foregroundLessonSessionV1(r,'2026-08-28T00:12:00.000Z');assert.equal(r.status,'LEARNING');assert.equal(r.sessionControl.lifecycle,'ACTIVE');assert.equal(r.tutorSession.accumulatedPausedMs,10*60*1000)});
test('native and web active-session readers exclude RETURNED as well as COMPLETED',()=>{const native=fs.readFileSync('src/persistence/operationalDatabase.native.ts','utf8'),web=fs.readFileSync('src/repositories/Stage4RuntimeStorage.ts','utf8');assert.match(native,/status NOT IN \('COMPLETED','RETURNED'\)/);assert.match(web,/item\.status!==['"]COMPLETED['"]&&item\.status!==['"]RETURNED['"]/)});
test('native evidence transaction can atomically include the corresponding lesson runtime checkpoint',()=>{const types=fs.readFileSync('src/persistence/operationalTypes.ts','utf8'),native=fs.readFileSync('src/persistence/operationalDatabase.native.ts','utf8'),daily=fs.readFileSync('app/daily-lesson.tsx','utf8');assert.match(types,/sessionCheckpoint\?:\{lessonPlan:LessonPlanV1;runtime:Stage4RuntimeV4\}/);assert.match(native,/if\(command\.sessionCheckpoint\)await upsertSessionRuntimeCoreV1\(tx/);assert.match(daily,/sessionCheckpoint:\{lessonPlan,runtime:checkpointRuntime\}/)});
test('daily learner event path has explicit in-flight action suppression',()=>{const daily=fs.readFileSync('app/daily-lesson.tsx','utf8');assert.match(daily,/inFlightActions=useRef\(new Set<string>\(\)\)/);assert.match(daily,/inFlightActions\.current\.has\(actionIdentity\)/);assert.match(daily,/finally\{inFlightActions\.current\.delete\(actionIdentity\)/)});
test('Writing and Translation nested work survive lifecycle transforms structurally',()=>{const r={...baseRuntime(),writingWork:{original:'immutable'},translationWork:{source:'中文'}};const paused=life.pauseLessonSessionV1(r,'2026-08-28T00:01:00.000Z'),resumed=life.resumeLessonSessionV1(paused,'2026-08-28T00:03:00.000Z');assert.deepEqual(resumed.writingWork,r.writingWork);assert.deepEqual(resumed.translationWork,r.translationWork)});
test('learner draft survives JSON process reconstruction without creating evidence',()=>{const saved=draft.saveLearnerDraftV1(baseRuntime(),'unfinished learner sentence','2026-08-28T00:01:00.000Z'),restored=JSON.parse(JSON.stringify(saved));assert.equal(draft.hydrateLearnerDraftV1(restored,'fallback'),'unfinished learner sentence');assert.equal(restored.trace.at(-1).kind,'DRAFT_SAVED');assert.equal(restored.observations.length,0);assert.equal(restored.evidenceCandidates.length,0);assert.equal(draft.saveLearnerDraftV1(restored,'unfinished learner sentence'),restored)});

test('lifecycle transitions create distinct persisted logical steps and idempotent repeated transitions',()=>{
  const r=baseRuntime('READY'),paused=life.pauseLessonSessionV1(r,'2026-08-28T00:02:00.000Z');
  assert.equal(paused.trace.at(-1).kind,'PAUSED');assert.equal(paused.trace.at(-1).payload.action,'MANUAL_PAUSE');assert.notEqual(paused.trace.at(-1).id,r.trace.at(-1)?.id);
  const pausedAgain=life.pauseLessonSessionV1(paused,'2026-08-28T00:02:00.000Z');assert.equal(pausedAgain,paused);
  const resumed=life.resumeLessonSessionV1(paused,'2026-08-28T00:08:00.000Z');assert.equal(resumed.trace.at(-1).kind,'RESUMED');assert.equal(resumed.trace.at(-1).payload.action,'MANUAL_RESUME');assert.notEqual(resumed.trace.at(-1).id,paused.trace.at(-1).id);
});
test('background and foreground create lifecycle steps without changing pedagogical status',()=>{
  const r=baseRuntime('LEARNING'),bg=life.backgroundLessonSessionV1(r,'2026-08-28T00:02:00.000Z');assert.equal(bg.status,'LEARNING');assert.equal(bg.trace.at(-1).payload.action,'APP_BACKGROUND');
  const bgAgain=life.backgroundLessonSessionV1(bg,'2026-08-28T00:02:00.000Z');assert.equal(bgAgain,bg);
  const fg=life.foregroundLessonSessionV1(bg,'2026-08-28T00:12:00.000Z');assert.equal(fg.status,'LEARNING');assert.equal(fg.trace.at(-1).payload.action,'APP_FOREGROUND');assert.notEqual(fg.trace.at(-1).id,bg.trace.at(-1).id);
});
test('closed return creates its own final lifecycle step',()=>{const r=baseRuntime('LEARNING'),closed=life.closeReturnedLessonSessionV1(r,'2026-08-28T00:05:00.000Z');assert.equal(closed.trace.at(-1).kind,'EXPERIENCE_ACTION');assert.equal(closed.trace.at(-1).payload.action,'SESSION_CLOSED');assert.equal(closed.trace.at(-1).payload.closeReason,'RETURNED_TO_SOURCE')});
test('daily production wires AppState lifecycle to M checkpoint semantics without reopening pedagogy',()=>{const daily=fs.readFileSync('app/daily-lesson.tsx','utf8');assert.match(daily,/AppState\.addEventListener\('change'/);assert.match(daily,/persistLifecycle\('BACKGROUND'\)/);assert.match(daily,/persistLifecycle\('FOREGROUND'\)/);assert.match(daily,/backgroundLessonSessionV1/);assert.match(daily,/foregroundLessonSessionV1/)});
test('M architecture registry declares U persistence dependency and lifecycle public contract',()=>{const registry=fs.readFileSync('src/architecture/registry.ts','utf8'),contracts=fs.readFileSync('src/architecture/contracts.ts','utf8');assert.match(registry,/\['C','D','E','F','K','L','Q','U'\],\['LessonSessionPortV1','LessonSessionLifecycleV1'\]/);assert.match(contracts,/interface LessonSessionLifecycleV1/)});
test('M capability status does not overclaim physical background/interruption acceptance',()=>{const s=lessonRuntimeWaveSummaryV1();assert.ok(s.firstPass>0);assert.equal(lessonRuntimeCapabilityStatesV1.find(x=>x.id==='M.background-foreground').status,'CONTRACT_ONLY');assert.equal(lessonRuntimeCapabilityStatesV1.find(x=>x.id==='M.interruption').status,'CONTRACT_ONLY')});


test('native evidence replay uses durable learner-action identity rather than retry-generated observation ids',()=>{
  const daily=fs.readFileSync('app/daily-lesson.tsx','utf8');
  assert.match(daily,/operationId=`evidence:\$\{actionIdentity\}`/);
  assert.match(daily,/inputFingerprint:await fingerprintV1\(semanticEvidenceFingerprint\)/);
  assert.match(daily,/causationId:actionIdentity/);
  assert.match(daily,/opportunityId:actionIdentity/);
  assert.doesNotMatch(daily,/operationId=`evidence:\$\{observation\.id\}/);
});


test('restored checkpoint suppresses an already committed learner action before creating another runtime event',async()=>{
  const r=baseRuntime();
  const input={runtime:r,type:'ANSWER_SUBMITTED',taskId:'task-1',response:'same answer'},payload=life.canonicalLessonActionPayloadV1(input),action=await life.lessonActionIdentityV1(input);
  const restored={...r,blockEvents:[{id:'event-old',instanceId:r.blockState.instanceId,type:'ANSWER_SUBMITTED',payload:{actionIdentity:action,actionPayloadCanonical:payload,response:'same answer',taskId:'task-1'},supportLevel:'LIGHT',visibleBeforeResponse:[],occurredAt:'2026-08-28T00:01:00Z'}]};
  assert.equal(life.lessonActionAlreadyRecordedV1(restored,action,payload),true);
  const newInput={runtime:r,type:'ANSWER_SUBMITTED',taskId:'task-1',response:'new answer'},newPayload=life.canonicalLessonActionPayloadV1(newInput),newAction=await life.lessonActionIdentityV1(newInput);
  assert.equal(life.lessonActionAlreadyRecordedV1(restored,newAction,newPayload),false);
  const daily=fs.readFileSync('app/daily-lesson.tsx','utf8');
  assert.match(daily,/lessonActionAlreadyRecordedV1\(runtime,actionIdentity,actionPayloadCanonical\)/);
});

test('legacy short-hash checkpoints are matched by reconstructable semantics rather than trusting the hash',async()=>{const r=baseRuntime(),same={runtime:r,type:'ANSWER_SUBMITTED',taskId:'task-1',response:'same answer'},different={...same,response:'different answer'},restored={...r,blockEvents:[{id:'legacy',instanceId:r.blockState.instanceId,type:'ANSWER_SUBMITTED',payload:{actionIdentity:'lesson-action:baacf9ad',response:'same answer',taskId:'task-1'},supportLevel:'LIGHT',visibleBeforeResponse:[],occurredAt:'2026-08-28T00:01:00Z'}]};assert.equal(life.lessonActionAlreadyRecordedV1(restored,await life.lessonActionIdentityV1(same),life.canonicalLessonActionPayloadV1(same)),true);assert.equal(life.lessonActionAlreadyRecordedV1(restored,await life.lessonActionIdentityV1(different),life.canonicalLessonActionPayloadV1(different)),false)});

test('pending Teacher continuation is durable, idempotent across repeated restores, and completes only for its event',()=>{const action='lesson-action:sha256:'+'a'.repeat(64),marked=life.markPendingTeacherContinuationV1(baseRuntime(),action,'event-1');assert.deepEqual(marked.pendingTeacherContinuation,{schemaVersion:1,continuationId:`teacher-continuation:${action}`,actionIdentity:action,eventId:'event-1',status:'PENDING'});assert.equal(life.markPendingTeacherContinuationV1(marked,action,'event-1'),marked);const restoredTwice=JSON.parse(JSON.stringify(JSON.parse(JSON.stringify(marked))));assert.equal(restoredTwice.pendingTeacherContinuation.continuationId,marked.pendingTeacherContinuation.continuationId);assert.throws(()=>life.markPendingTeacherContinuationV1(marked,action,'event-2'),/conflicting_pending_teacher_continuation/);assert.throws(()=>life.completePendingTeacherContinuationV1(marked,'event-2'),/teacher_continuation_event_mismatch/);const completed=life.completePendingTeacherContinuationV1(restoredTwice,'event-1');assert.equal(completed.pendingTeacherContinuation,undefined);assert.equal(life.completePendingTeacherContinuationV1(completed,'event-1'),completed)});

test('daily production resumes pending redecision without learner resubmit and atomically checkpoints completion',()=>{const daily=fs.readFileSync('app/daily-lesson.tsx','utf8'),native=fs.readFileSync('src/persistence/operationalDatabase.native.ts','utf8'),types=fs.readFileSync('src/persistence/operationalTypes.ts','utf8');assert.match(daily,/if\(runtime\?\.pendingTeacherContinuation&&lessonPlan\)void resumePendingTeacherContinuation\(runtime\)/);assert.match(daily,/pendingTeacherContinuation\?\.actionIdentity===actionIdentity\)await resumePendingTeacherContinuation\(runtime\)/);assert.match(daily,/markPendingTeacherContinuationV1\(next,actionIdentity,committedEvent\.id\)/);assert.match(daily,/completePendingTeacherContinuationV1\(finalRuntime,event\.id\)/);assert.match(daily,/sessionCheckpoint:\{lessonPlan,runtime:finalRuntime\}/);assert.match(types,/TeacherLineageCommandV1[\s\S]*sessionCheckpoint\?:\{lessonPlan:LessonPlanV1;runtime:Stage4RuntimeV4\}/);assert.match(native,/commitTeacherLineage[\s\S]*if\(command\.sessionCheckpoint\)await upsertSessionRuntimeCoreV1\(tx/)});
