const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');const build=process.env.EOT_DOMAIN_TEST_BUILD||'.domain-test-build-native-corpus',req=r=>require(path.resolve(process.cwd(),build,r));const n=req('persistence/nativeCorpusCore.js');
const tables=['source_registry','lexemes','senses','morphology','examples','translation_pairs','sentence_provenance'];
function db({integrity='ok',missingTable=false,badVersion=false}={}){const calls=[];return{calls,getFirstAsync:async sql=>sql.includes('query_only')?{query_only:1}:{integrity_check:integrity},getAllAsync:async(sql)=>sql.includes('sqlite_master')?tables.slice(missingTable?1:0).map(name=>({name})):Object.entries(n.nativeCorpusManifestV1.requiredSources).map(([source_id,version])=>({source_id,version:badVersion?'bad':version})),execAsync:async sql=>calls.push(sql),closeAsync:async()=>calls.push('CLOSE')}}
test('valid already-provisioned corpus is reused and forced query-only',async()=>{const existing=db();let installs=0;const state=await n.provisionNativeCorpusV1({open:async()=>existing,installAsset:async()=>{installs++}});assert.equal(state.status,'READY');assert.equal(state.reused,true);assert.equal(installs,0);assert.deepEqual(existing.calls,['PRAGMA query_only=ON'])});
test('missing database installs bundled asset once and constructs production retrieval port',async()=>{const installed=db();let opens=0,installs=0;const state=await n.provisionNativeCorpusV1({open:async()=>{if(opens++===0)throw Error('missing');return installed},installAsset:async force=>{assert.equal(force,true);installs++}});assert.equal(state.status,'READY');assert.equal(state.reused,false);assert.equal(installs,1);assert.equal(typeof state.port.query,'function')});
test('corrupt or incompatible installed asset fails closed without fake content',async()=>{for(const options of[{integrity:'bad'},{missingTable:true},{badVersion:true}]){let opens=0;const state=await n.provisionNativeCorpusV1({open:async()=>{opens++;return db(options)},installAsset:async()=>{}});assert.equal(state.status,'UNAVAILABLE');assert.equal(state.learnerMessage,'查詢內容暫時無法使用。');assert.equal('port'in state,false)}});
test('manifest pins corpus identity and source versions',()=>{assert.equal(n.nativeCorpusManifestV1.schemaVersion,1);assert.match(n.nativeCorpusManifestV1.sha256,/^[a-f0-9]{64}$/);assert.equal(Object.keys(n.nativeCorpusManifestV1.requiredSources).length,3)});
test('daily lesson invokes native corpus, typed gateway and shared lookup runtime',()=>{const source=fs.readFileSync(path.resolve(process.cwd(),'app/daily-lesson.tsx'),'utf8');assert.match(source,/nativeCorpusServiceV1\.get\(\)/);assert.match(source,/createLearningContentGatewayV1\(corpus\.port\)/);assert.match(source,/createContextualLookupRuntimeV1/);assert.match(source,/lookupRequestsFromTapV1/);assert.match(source,/recordContextualLookupExposureV4/)});
test('native runtime is read-only and has no fake corpus fallback',()=>{const core=fs.readFileSync(path.resolve(process.cwd(),'src/persistence/nativeCorpusCore.ts'),'utf8'),daily=fs.readFileSync(path.resolve(process.cwd(),'app/daily-lesson.tsx'),'utf8');assert.match(core,/PRAGMA query_only=ON/);assert.doesNotMatch(core,/\b(INSERT|UPDATE|DELETE)\b/);assert.doesNotMatch(daily,/fakeLookup|hardcodedLookup|demoLookup/i)});
test('bundled corpus asset and Metro sqlite declaration exist',()=>{const asset=path.resolve(process.cwd(),'assets/corpus/eot-corpus-20260827.sqlite'),metro=fs.readFileSync(path.resolve(process.cwd(),'metro.config.js'),'utf8');assert.ok(fs.statSync(asset).size>300_000_000);assert.match(metro,/assetExts.*sqlite/)});
