const test=require('node:test');const assert=require('node:assert/strict');const path=require('node:path');
const req=rel=>require(path.join(__dirname,'..','..','.domain-test-build',rel));
const encounter=req('learner-truth/lexicalEncounter.js'),ledger=req('learner-truth/observationLedger.js'),capture=req('lookup/lexicalEncounterCapture.js'),curriculum=req('curriculum/engine.js'),english=req('domain/english/index.js');
const at='2026-09-10T08:00:00.000Z';
const event=(id,extra={})=>encounter.createLexicalEncounterEventV1({eventId:id,learnerId:'L1',occurredAt:at,captureMethod:'QUICK_MANUAL_ADD',sourceType:'BROWSER',selectedSpan:'carry out',phraseOrChunkCandidate:'carry out',canonicalTargetRef:'lexical.contextual-fit',canonicalFacet:'COLLOCATION',resolutionStatus:'RESOLVED',candidateSenseRefs:['sense:carry-out:perform'],resolvedContextualSense:'sense:carry-out:perform',lookupRequested:false,lookupResultExposed:false,userMarkedRemember:false,privacyScope:'EXTERNAL_MINIMIZED',...extra});

test('repeated encounters append while accidental transaction replay is idempotent',async()=>{const store=new encounter.CanonicalLexicalEncounterStoreV1(new ledger.InMemoryCanonicalObservationLedgerV1());assert.equal(await store.append(event('e1')),'APPENDED');assert.equal(await store.append(event('e1')),'IDEMPOTENT_REPLAY');assert.equal(await store.append(event('e2',{occurredAt:'2026-09-10T09:00:00.000Z'})),'APPENDED');assert.equal((await store.listForLearner('L1')).length,2)});
test('raw external context is transient unless learner explicitly keeps a bounded excerpt',()=>{const minimal=capture.prepareManualLexicalCaptureV1({eventId:'e1',learnerId:'L1',occurredAt:at,sourceType:'BROWSER',sentence:'They carry out private medical research.',selectedSpan:'carry out'});assert.equal(minimal.keptContext,undefined);assert.equal(minimal.privacyScope,'EXTERNAL_MINIMIZED');const kept=capture.prepareManualLexicalCaptureV1({eventId:'e2',learnerId:'L1',occurredAt:at,sourceType:'BROWSER',sentence:'They carry out private medical research.',selectedSpan:'carry out',keepContext:true,maxPersistedContextCharacters:12});assert.equal(kept.keptContext.length,12)});
test('unknown sense remains unresolved instead of being forced',()=>{const x=capture.prepareManualLexicalCaptureV1({eventId:'e1',learnerId:'L1',occurredAt:at,sourceType:'NOTE',word:'florp',sentence:'A florp appeared.'});assert.equal(x.resolutionStatus,'UNRESOLVED');assert.equal(x.resolvedContextualSense,undefined)});
test('lookup action records assisted encounter but never independent evidence',async()=>{const store=new encounter.CanonicalLexicalEncounterStoreV1(new ledger.InMemoryCanonicalObservationLedgerV1()),runtime=capture.createEncounterRecordingLookupRuntimeV1({source:{candidates:async()=>[{id:'sense:carry-out:perform',label:'carry out',kind:'PHRASE',start:5,end:14,meaningZhTw:'執行',wouldRevealTargetAnswer:false}]},store,learnerId:'L1',sessionId:'S1',eventId:()=> 'lookup-1',now:()=>at});const result=await runtime.lookup({text:'They carry out a test.',selectionStart:5,selectionEnd:10,contextText:'They carry out a test.',assessmentMode:'NONE',activeTargetRefs:[]});assert.equal(result.allowed,true);const [saved]=await store.listForLearner('L1');assert.equal(saved.lookupResultExposed,true);assert.equal(saved.capabilityEvidenceAllowed,false)});
test('recognition retrieval and production remain separate operation projections',()=>{const observations=[{id:'r',learnerId:'L1',identity:{lemmaId:'x',senseId:'sense:x'},facet:'SENSE_RECOGNITION',control:'CONTROLLED',occurredAt:at,productContext:'GENERAL',evidenceEligible:true,support:'NONE'}];const common={learnerId:'L1',targetRef:'lexical.contextual-fit',senseId:'sense:x',facet:'SENSE_RECOGNITION',encounters:[],lexicalObservations:observations};assert.equal(encounter.projectOperationSpecificLexicalMemoryV1({...common,operation:'RECOGNITION_COMPREHENSION'}).state,'CURRENTLY_AVAILABLE');assert.equal(encounter.projectOperationSpecificLexicalMemoryV1({...common,operation:'RETRIEVAL'}).state,'NEW_OR_UNSEEN');assert.equal(encounter.projectOperationSpecificLexicalMemoryV1({...common,operation:'PRODUCTION_USE'}).state,'NEW_OR_UNSEEN')});
test('failure lowers current operation availability without erasing historical attainment',()=>{const observations=[{id:'ok',learnerId:'L1',identity:{lemmaId:'x',senseId:'sense:x'},facet:'FREE_RETRIEVAL',control:'CONTROLLED',occurredAt:at,productContext:'GENERAL',evidenceEligible:true,support:'NONE'},{id:'fail',learnerId:'L1',identity:{lemmaId:'x',senseId:'sense:x'},facet:'FREE_RETRIEVAL',control:'NEEDS_WORK',occurredAt:'2026-09-11T08:00:00.000Z',productContext:'GENERAL',evidenceEligible:true,support:'NONE'}],p=encounter.projectOperationSpecificLexicalMemoryV1({learnerId:'L1',targetRef:'lexical.contextual-fit',senseId:'sense:x',facet:'FREE_RETRIEVAL',operation:'RETRIEVAL',encounters:[],lexicalObservations:observations});assert.equal(p.state,'PREVIOUSLY_AVAILABLE_NOW_FAILED');assert.equal(p.historicalIndependentAttainment,true)});
test('我要記 changes priority but never capability',()=>{const e=event('e1',{userMarkedRemember:true}),p=encounter.projectOperationSpecificLexicalMemoryV1({learnerId:'L1',targetRef:'lexical.contextual-fit',senseId:'sense:carry-out:perform',facet:'COLLOCATION',operation:'PRODUCTION_USE',encounters:[e]}),signal=encounter.lexicalTodayPrioritySignalV1({projection:p,encounters:[e]});assert.ok(signal.priorityBoost>0);assert.equal(signal.capabilityDelta,0);assert.ok(signal.reasonCodes.includes('USER_WANTS_TO_REMEMBER'))});
test('reencounter cue is conservative and configuration bounded',()=>{assert.equal(encounter.shouldShowLexicalReencounterCueV1([event('e1')],'carry out'),false);assert.equal(encounter.shouldShowLexicalReencounterCueV1([event('e1',{lookupResultExposed:true}),event('e2',{lookupResultExposed:true})],'carry out'),true);assert.equal(encounter.shouldShowLexicalReencounterCueV1([event('e1',{userMarkedRemember:true})],'carry out'),true)});
test('Today candidate scoring consumes encounter priority without a fixed vocabulary quota',()=>{const context={learnerId:'L1',goals:['general'],learningPurpose:'GENERAL',useContexts:['WRITING'],studyMinutes:10,productMode:'GENERAL',entitlement:{status:'DEVELOPMENT',source:'test',planId:'test'}},truth={learnerId:'L1',generatedFromEvidenceIds:[],capabilitySlice:[],interactionSlice:[],exposureSlice:[],goalContext:{}},base=curriculum.buildCurriculumCandidatesV1(context,truth,english.coreEnglishDomainPortV2,{now:at}),target=base.find(x=>x.area==='LEXICAL'&&x.frontier!=='BLOCKED')??base.find(x=>x.area==='LEXICAL');const signal={targetRef:target.targetRef,facet:target.facet,operation:'RECOGNITION_COMPREHENSION',repeatedEncounter:true,repeatedLookup:false,userWantsToRemember:false,recentFailure:false,reactivationRisk:false,crossFamilyTransferValue:false,priorityBoost:8,reasonCodes:['REPEATED_ENCOUNTER'],capabilityDelta:0},boosted=curriculum.buildCurriculumCandidatesV1(context,truth,english.coreEnglishDomainPortV2,{now:at,lexicalEncounterSignals:[signal]}).find(x=>x.targetRef===target.targetRef&&x.facet===target.facet);assert.equal(boosted.score,target.score+8);assert.equal(Object.hasOwn(boosted,'dailyVocabularyQuota'),false)});
