const test=require('node:test');
const assert=require('node:assert/strict');
const path=require('node:path');
const root=path.resolve(__dirname,'../..');
const req=rel=>require(path.join(root,'.domain-test-build',rel));
const reading=req('specializations/language/readingExamRuntime.js');
const diagnosis=req('specializations/language/readingDiagnosis.js');
const reviewRuntime=req('specializations/language/readingReviewRuntime.js');
const teacher=req('teacher-runtime/index.js');
const experience=req('experience/teacherDecisionExperience.js');
const stage4=req('application/stage4/learnerRuntimeV4.js');
const workspace=req('lesson-runtime/adaptiveOutputWorkspaceRuntime.js');
const registry=req('application/v4/blockRegistryV4.js').blockRegistryV4;
const pck=req('teaching/pckCatalog.js');

const startedAt='2026-08-30T00:00:00.000Z';
const source=Object.freeze({id:'reading-source-wave1d',passage:'The library stayed open because students needed a quiet place to finish their projects.',questions:Object.freeze([{id:'q1',passageId:'reading-source-wave1d',stem:'Why did the library stay open?',options:Object.freeze([{id:'a',text:'Students needed a quiet place.'},{id:'b',text:'The teachers had a meeting.'}])}]),sourceRef:'frozen-exam:reading-1',immutable:true});
function committedAttempt(){let attempt=reading.startReadingAttemptV1({id:'attempt-wave1d',learnerId:'learner-wave1d',mode:'PRACTICE',source,startedAt});attempt=reading.answerReadingItemV1(attempt,{questionId:'q1',response:'The teachers had a meeting.',updatedAt:'2026-08-30T00:01:00.000Z'});attempt=reading.submitReadingAttemptV1(attempt,'2026-08-30T00:02:00.000Z');return reading.commitReadingResultV1(attempt,'2026-08-30T00:02:01.000Z')}
const focus=Object.freeze({questionId:'q1',kind:'INFERENCE_BRIDGE',anchorText:'because students needed a quiet place',reasonRef:'review:learner-selected'});
function canonical(){return reviewRuntime.createCanonicalReadingReviewV1({id:'review-wave1d',attempt:committedAttempt(),focus,timeBudgetMinutes:12,productMode:'GENERAL'})}
const product={learnerId:'learner-wave1d',goals:['read with evidence'],learningPurpose:'school',useContexts:['reading'],studyMinutes:12,productMode:'GENERAL',entitlement:{status:'DEVELOPMENT',source:'test',planId:'test'}};
const truth={learnerId:'learner-wave1d',generatedFromEvidenceIds:[],capabilitySlice:[],interactionSlice:[],exposureSlice:[],goalContext:{},projectionVersion:1};
const event={id:'reading-decision-wave1d',kind:'LEARNER_RESPONSE',occurredAt:'2026-08-30T00:03:00.000Z',outcome:'FAILURE',support:'NONE',observationIds:['attempt-wave1d'],attemptId:'attempt-wave1d'};

test('READING-HANDOFF-01 committed result creates canonical review LessonPlan',()=>{const review=canonical();assert.equal(review.originalAttemptId,'attempt-wave1d');assert.equal(review.lessonPlan.targetRef,'reading.inference');assert.equal(review.lessonPlan.facet,'SELECTION');assert.equal(review.lessonPlan.reason,'POST_ATTEMPT_REVIEW')});

test('READING-HANDOFF-02 bounded Teacher context retains original refs, FocusAnchor and objective',()=>{const review=canonical();const sourceTaskContext={kind:'READING_REVIEW',reviewId:review.id,originalAttemptId:review.originalAttemptId,focusAnchor:review.focus.anchorText,reviewObjective:review.lessonPlan.objective,assessmentMode:review.assessment.mode};const context=teacher.compilePedagogicalContextV1({lessonPlan:review.lessonPlan,sourceTaskContext,productContext:product,learnerTruth:truth,event,recentAttempts:[],recentTreatmentResponses:[],timeRemainingMinutes:12,provider:async()=>{throw new Error('unused')}});assert.deepEqual(context.sourceTaskContext,sourceTaskContext);assert.equal(context.lessonPlan.targetRef,'reading.inference')});

test('READING-HANDOFF-03 qualified decision executes through Experience authority into production Workspace',async()=>{const review=canonical();const initial=reviewRuntime.startCanonicalReadingReviewSessionV1(review,'2026-08-30T00:03:00.000Z');const decision=await teacher.decideInnerTutorV1({lessonPlan:review.lessonPlan,sourceTaskContext:{kind:'READING_REVIEW',reviewId:review.id,originalAttemptId:review.originalAttemptId,focusAnchor:review.focus.anchorText,reviewObjective:review.lessonPlan.objective},productContext:product,learnerTruth:truth,event,recentAttempts:[],recentTreatmentResponses:[],timeRemainingMinutes:12,provider:async()=>{throw new Error('offline fallback')}});const contract=experience.teacherDecisionToExperienceContractV1(decision);const executed=experience.executeTeacherExperienceV1(initial,contract,'2026-08-30T00:03:01.000Z');assert.equal(executed.effect,'SELECT_BLOCK');const selected=stage4.selectBlockV4(executed.runtime,executed.blockDecision);const vm=workspace.projectAdaptiveWorkspaceV4({runtime:selected,draft:review.submittedAnswer,sourceMeaning:`${review.passage}\n\n${review.question}`});assert.equal(selected.experienceState,'INTERVENTION');assert.equal(vm.source.text.includes(review.question),true);assert.equal(vm.output.text,review.submittedAnswer)});

test('READING-HANDOFF-04 selected Teaching Block comes only from canonical registry',async()=>{const review=canonical();const decision=await teacher.decideInnerTutorV1({lessonPlan:review.lessonPlan,productContext:product,learnerTruth:truth,event,recentAttempts:[],recentTreatmentResponses:[],timeRemainingMinutes:12,provider:async()=>{throw new Error('offline fallback')}});assert.ok(registry.get(decision.blockDecision.selectedBlockId));assert.equal(decision.blockDecision.targetReference,review.lessonPlan.targetRef)});

test('READING-HANDOFF-05 official submitted attempt stays logically immutable after learner actions',async()=>{const attempt=committedAttempt(),before=JSON.stringify(attempt),review=reviewRuntime.createCanonicalReadingReviewV1({id:'review-wave1d',attempt,focus,timeBudgetMinutes:12,productMode:'GENERAL'});let runtime=reviewRuntime.startCanonicalReadingReviewSessionV1(review,'2026-08-30T00:03:00.000Z');const decision=await teacher.decideInnerTutorV1({lessonPlan:review.lessonPlan,productContext:product,learnerTruth:truth,event,recentAttempts:[],recentTreatmentResponses:[],timeRemainingMinutes:12,provider:async()=>{throw new Error('offline fallback')}});runtime=stage4.selectBlockV4(runtime,decision.blockDecision);runtime=stage4.recordBlockEventStage4V4(runtime,'ANSWER_SUBMITTED',{taskId:'reading-review-task',response:'Students needed a quiet place.'},true);assert.ok(runtime.evidenceCandidates.length);reviewRuntime.assertReadingAttemptUnchangedV1(review,attempt);assert.equal(JSON.stringify(attempt),before);assert.throws(()=>reading.answerReadingItemV1(attempt,{questionId:'q1',response:'changed',updatedAt:startedAt}),/already_submitted/)});

test('READING-HANDOFF-06 learning evidence is separate from assessment attempt truth',async()=>{const attempt=committedAttempt(),review=canonical();let runtime=reviewRuntime.startCanonicalReadingReviewSessionV1(review,'2026-08-30T00:03:00.000Z');const decision=await teacher.decideInnerTutorV1({lessonPlan:review.lessonPlan,productContext:product,learnerTruth:truth,event,recentAttempts:[],recentTreatmentResponses:[],timeRemainingMinutes:12,provider:async()=>{throw new Error('offline fallback')}});runtime=stage4.selectBlockV4(runtime,decision.blockDecision);runtime=stage4.recordBlockEventStage4V4(runtime,'ANSWER_SUBMITTED',{taskId:'reading-review-task',response:'Students needed a quiet place.'},true);assert.equal('evidenceCandidates' in attempt,false);assert.equal(runtime.artifact.id,`artifact:${review.id}`);assert.equal(runtime.readingReview.originalAttemptSnapshot,JSON.stringify(attempt))});

test('READING-REVIEW-IMMUTABLE-01 first save contract accepts a new canonical review',()=>{const review=canonical();assert.doesNotThrow(()=>reviewRuntime.assertCanonicalReadingReviewReplayV1(review,review))});
test('READING-REVIEW-IMMUTABLE-02 semantically identical replay ignores property ordering',()=>{const review=canonical(),reordered={immutable:review.immutable,lessonPlan:{...review.lessonPlan},assessment:{...review.assessment},focus:{...review.focus},submittedAnswer:review.submittedAnswer,question:review.question,passage:review.passage,originalAttemptSnapshot:review.originalAttemptSnapshot,originalAttemptId:review.originalAttemptId,learnerId:review.learnerId,id:review.id,schemaVersion:review.schemaVersion};assert.doesNotThrow(()=>reviewRuntime.assertCanonicalReadingReviewReplayV1(review,reordered))});
test('READING-REVIEW-IMMUTABLE-03 changed focus fails closed',()=>{const review=canonical(),changed={...review,focus:{...review.focus,anchorText:'different evidence anchor'}};assert.throws(()=>reviewRuntime.assertCanonicalReadingReviewReplayV1(review,changed),/canonical_reading_review_is_immutable/)});
test('READING-REVIEW-IMMUTABLE-04 changed original attempt snapshot fails closed',()=>{const review=canonical(),changed={...review,originalAttemptSnapshot:`${review.originalAttemptSnapshot} `};assert.throws(()=>reviewRuntime.assertCanonicalReadingReviewReplayV1(review,changed),/canonical_reading_review_is_immutable/)});
test('READING-REVIEW-IMMUTABLE-05 changed LessonPlan-bound semantics or time budget fails closed',()=>{const review=canonical();assert.throws(()=>reviewRuntime.assertCanonicalReadingReviewReplayV1(review,{...review,lessonPlan:{...review.lessonPlan,objective:'different objective'}}),/canonical_reading_review_is_immutable/);assert.throws(()=>reviewRuntime.assertCanonicalReadingReviewReplayV1(review,{...review,lessonPlan:{...review.lessonPlan,timeBudgetMinutes:13}}),/canonical_reading_review_is_immutable/)});

test('READING-HANDOFF-07 persisted serialization restores identities and replays without provider call',async()=>{
  const attempt=committedAttempt(),review=reviewRuntime.createCanonicalReadingReviewV1({id:'review-wave1d',attempt,focus,timeBudgetMinutes:12,productMode:'GENERAL'}),initial=reviewRuntime.startCanonicalReadingReviewSessionV1(review,'2026-08-30T00:03:00.000Z');let providerCalls=0;
  const first=await teacher.decideInnerTutorV1({lessonPlan:review.lessonPlan,productContext:product,learnerTruth:truth,event,recentAttempts:[],recentTreatmentResponses:[],timeRemainingMinutes:12,provider:async()=>{providerCalls++;throw new Error('offline fallback')}});
  const selected=stage4.selectBlockV4(initial,first.blockDecision),checkpoint={review,lessonPlan:review.lessonPlan,runtime:{...selected,decisionProvenance:first.provenance},officialAttempt:attempt};
  const persistedReview=JSON.stringify(review),persistedCheckpoint=JSON.stringify(checkpoint),restoredReview=JSON.parse(persistedReview),restored=JSON.parse(persistedCheckpoint);
  reviewRuntime.assertCanonicalReadingReviewReplayV1(restoredReview,review);
  assert.equal(restored.runtime.id,selected.id);assert.deepEqual(restored.runtime.tutorSession,selected.tutorSession);assert.equal(restored.runtime.readingReview.reviewId,review.id);assert.equal(restored.runtime.readingReview.originalAttemptId,attempt.id);assert.equal(restored.lessonPlan.id,review.lessonPlan.id);assert.equal(restored.runtime.decision.configuration.decisionPointId,event.id);assert.equal(restored.runtime.decision.selectedBlockId,first.blockDecision.selectedBlockId);assert.deepEqual(restored.runtime.decisionProvenance,first.provenance);assert.equal(restored.officialAttempt.id,attempt.id);assert.equal(restored.officialAttempt.immutableSubmit,true);assert.equal(restored.officialAttempt.resultCommittedAt,attempt.resultCommittedAt);
  const replay=await teacher.decideInnerTutorV1({lessonPlan:restored.lessonPlan,productContext:product,learnerTruth:truth,event,recentAttempts:[],recentTreatmentResponses:[],timeRemainingMinutes:11,currentDecision:restored.runtime.decision,currentProvenance:restored.runtime.decisionProvenance,provider:async()=>{providerCalls++;throw new Error('provider must not run on restored replay')}});
  assert.equal(providerCalls,1);assert.equal(replay.reused,true);assert.equal(replay.blockDecision.configuration.decisionPointId,event.id);assert.equal(replay.blockDecision.selectedBlockId,first.blockDecision.selectedBlockId);assert.ok(replay.provenance.reasonCodes.includes('IDEMPOTENT_REPLAY'));
});

test('READING-DIAGNOSIS-01 abstains without authorized result or learner diagnostic evidence',()=>{const d=diagnosis.diagnoseReadingPostAttemptV1({attempt:committedAttempt(),questionId:'q1'});assert.equal(d.status,'NEED_DIAGNOSTIC');assert.ok(d.probes.some(x=>x.needed==='EVIDENCE_SELECTION'));assert.ok(d.probes.some(x=>x.needed==='AUTHORIZED_RESULT'))});
test('READING-DIAGNOSIS-02 authorized wrong result binds passage evidence and demand',()=>{const d=diagnosis.diagnoseReadingPostAttemptV1({attempt:committedAttempt(),questionId:'q1',authorizedResults:[{questionId:'q1',authorityRef:'assessment:key-v1',correctResponseIds:['a'],evidenceAnchors:['because students needed a quiet place'],diagnosticDemand:'INFERENCE_BRIDGE'}]});assert.equal(d.status,'FOCUS_READY');assert.equal(d.focus.kind,'INFERENCE_BRIDGE');assert.match(d.focus.reasonRef,/AUTHORIZED_READING_DIAGNOSIS/)});
test('READING-DIAGNOSIS-03 learner focus is real only with explanation and evidence anchor',()=>{const insufficient=diagnosis.diagnoseReadingPostAttemptV1({attempt:committedAttempt(),questionId:'q1',learnerSelectedFocus:'OPTION_CONTRAST'});assert.equal(insufficient.status,'NEED_DIAGNOSTIC');const ready=diagnosis.diagnoseReadingPostAttemptV1({attempt:committedAttempt(),questionId:'q1',learnerSelectedFocus:'OPTION_CONTRAST',learnerExplanation:'I could not rule out option b.',learnerEvidenceAnchor:'because students needed a quiet place'});assert.equal(ready.status,'FOCUS_READY');assert.equal(ready.focus.reasonRef,'LEARNER_SELECTED_REVIEW_FOCUS_WITH_EXPLANATION')});
test('READING-PCK-01 eight registered mechanisms require learner evidence operations and forbid direct answer exposure',()=>{const ids=['inference-evidence-bridge','reference-chain','text-structure-map','paragraph-function-map','sentence-insertion-continuity','distractor-evidence-contrast','claim-strength-contrast','cross-representation-evidence-integration'];for(const id of ids){const mechanism=pck.pckMechanismByIdV1(id),block=registry.get(id);assert.ok(mechanism,id);assert.ok(block,id);assert.equal(mechanism.answerExposureConstraint,'NO_DIRECT_ANSWER');assert.ok(mechanism.requiredLearnerAction);assert.ok(mechanism.supportProgression.length);assert.ok(mechanism.fadeConditions.length);assert.ok(mechanism.replanConditions.length);assert.ok(mechanism.stopConditions.length);assert.equal(block.exposesTargetAnswer,false);assert.equal(block.evidenceCeiling,'EXPOSURE_ONLY')}});
