const test=require('node:test');
const assert=require('node:assert/strict');
const path=require('node:path');
const build=process.env.EOT_DOMAIN_TEST_BUILD||'.domain-test-build';
const fromBuild=rel=>require(path.join(__dirname,'..','..',build,rel));
const e=fromBuild('teacher-runtime/index.js');
const experience=fromBuild('experience/teacherDecisionExperience.js');

const lesson={id:'lesson:today:l:allow',learnerId:'l',targetRef:'allow-object-infinitive',facet:'CONSTRUCTION',needKind:'NEW_LEARNING',objective:'allow + object + to-infinitive',reason:'NEW_CAPABILITY',reasonCodes:['NEW_CAPABILITY'],timeBudgetMinutes:20,productMode:'GENERAL'};
const product={learnerId:'l',goals:['write clearly'],learningPurpose:'real output',useContexts:['WRITING'],studyMinutes:20,productMode:'GENERAL',entitlement:{status:'DEVELOPMENT',source:'test',planId:'dev'}};
const truth={learnerId:'l',generatedFromEvidenceIds:[],capabilitySlice:[],interactionSlice:[],exposureSlice:[],goalContext:{},projectionVersion:1};
const event=(overrides={})=>({id:'event-1',kind:'LESSON_STARTED',occurredAt:'2026-08-27T00:00:00Z',outcome:'NOT_EVALUATED',support:'NONE',observationIds:['obs-1'],...overrides});
const proposal=(overrides={})=>({teacherAction:'TEACH',lessonPlanId:lesson.id,pedagogicalIntent:'TEACH',focusFacet:lesson.facet,targetReference:lesson.targetRef,selectedBlockId:'grammar-role-map',supportLevel:'EXPLICIT',contextProvenance:'SAME_CONTEXT',evidenceToObserve:[],successTransitionIntent:'REDECIDE',failureTransitionIntent:'CHANGE_REPRESENTATION',confidence:'HIGH',unresolvedAmbiguity:null,internalDecisionReason:'hidden',...overrides});
const input=(overrides={})=>({lessonPlan:lesson,productContext:product,learnerTruth:truth,event:event(),recentAttempts:[],recentTreatmentResponses:[],timeRemainingMinutes:20,provider:async()=>proposal(),...overrides});

test('context compiler keeps only relevant target truth, prerequisites, bounded attempts and treatment response',()=>{const many=Array.from({length:10},(_,i)=>event({id:`e${i}`}));const context=e.compilePedagogicalContextV1(input({recentAttempts:many,recentTreatmentResponses:many.map(x=>({mechanismId:'m',support:'LIGHT',outcome:'PARTIAL',eventId:x.id,occurredAt:x.occurredAt}))}),'2026-08-27T01:00:00Z');assert.equal(context.lessonPlan.id,lesson.id);assert.equal(context.recentAttempts.length,6);assert.equal(context.recentTreatmentResponses.length,6);assert.equal(context.product.productMode,'GENERAL');assert.equal('generatedFromEvidenceIds' in context,false)});
test('D target hijack and facet hijack are rejected',()=>{const context=e.compilePedagogicalContextV1(input());assert.equal(e.qualifyInnerTutorProposalV1(context,event(),proposal({targetReference:'word.allow'})).accepted,false);assert.equal(e.qualifyInnerTutorProposalV1(context,event(),proposal({focusFacet:'FREE_PRODUCTION'})).accepted,false)});
test('invented action and unregistered mechanism are rejected',()=>{const context=e.compilePedagogicalContextV1(input());assert.equal(e.qualifyInnerTutorProposalV1(context,event(),proposal({teacherAction:'ENTERTAIN'})).accepted,false);assert.equal(e.qualifyInnerTutorProposalV1(context,event(),proposal({selectedBlockId:'invented-widget'})).accepted,false)});
test('correct unsupported production permits NONE',async()=>{const result=await e.decideInnerTutorV1(input({event:event({kind:'LEARNER_RESPONSE',outcome:'SUCCESS'}),provider:async()=>{throw new Error('offline')}}));assert.equal(result.action,'NONE');assert.equal(result.blockDecision.evidenceToObserve.length,0)});
test('help before failure gives explicit cold-start support without manufacturing failure evidence',async()=>{const result=await e.decideInnerTutorV1(input({event:event({kind:'HELP_REQUESTED',outcome:'HELP_WITHOUT_ATTEMPT'}),provider:async()=>{throw new Error('offline')}}));assert.equal(result.action,'TEACH');assert.equal(result.blockDecision.supportLevel,'EXPLICIT');assert.equal(result.blockDecision.configuration.dAssistanceLevel,'H4_PARTIAL_COMPLETION_OR_CONTRAST');assert.equal(result.blockDecision.evidenceToObserve.length,0);assert.ok(result.provenance.reasonCodes.includes('NO_FAILURE_EVIDENCE'))});
test('supported success fades support without claiming independent in place',async()=>{const result=await e.decideInnerTutorV1(input({event:event({kind:'LEARNER_RESPONSE',outcome:'SUCCESS',support:'GUIDED'}),provider:async()=>{throw new Error('offline')}}));assert.equal(result.action,'PRACTICE');assert.equal(result.blockDecision.supportLevel,'CUED');assert.equal(result.blockDecision.contextProvenance,'SAME_CONTEXT');assert.ok(result.provenance.reasonCodes.includes('F_CONTINGENT_SUPPORT_FADE'))});
test('partial success routes to local repair',async()=>{const result=await e.decideInnerTutorV1(input({event:event({kind:'LEARNER_RESPONSE',outcome:'PARTIAL'}),provider:async()=>{throw new Error('offline')}}));assert.equal(result.action,'REPAIR');assert.equal(result.blockDecision.pedagogicalIntent,'PRACTICE')});
test('failed mechanism changes representation instead of repeating the same mechanism',async()=>{const current=e.qualifyInnerTutorProposalV1(e.compilePedagogicalContextV1(input()),event(),proposal()).decision.blockDecision;const result=await e.decideInnerTutorV1(input({event:event({id:'event-2',kind:'LEARNER_RESPONSE',outcome:'FAILURE'}),currentDecision:current,provider:async()=>{throw new Error('offline')}}));assert.equal(result.action,'TEACH');assert.notEqual(result.blockDecision.selectedBlockId,current.selectedBlockId);assert.equal(result.treatmentResponse.mechanismId,current.selectedBlockId)});
test('impasse replans representation without manufacturing failure evidence',async()=>{const current=e.qualifyInnerTutorProposalV1(e.compilePedagogicalContextV1(input()),event(),proposal()).decision.blockDecision;const result=await e.decideInnerTutorV1(input({event:event({id:'event-impasse',kind:'HELP_REQUESTED',outcome:'HELP_WITHOUT_ATTEMPT',learnerIntent:'IMPASSE_REPLAN'}),currentDecision:current,provider:async()=>{throw new Error('offline')}}));assert.equal(result.action,'TEACH');assert.notEqual(result.blockDecision.selectedBlockId,current.selectedBlockId);assert.equal(result.treatmentResponse.outcome,'HELP_WITHOUT_ATTEMPT');assert.equal(result.treatmentResponse.responseSignal,'CONFUSED')});
test('bottom-out answer exposure remains teaching with zero capability claim',()=>{const context=e.compilePedagogicalContextV1(input());const result=e.qualifyInnerTutorProposalV1(context,event(),proposal({supportLevel:'MODELED',evidenceToObserve:[{facet:'CONSTRUCTION',productionCondition:'EXPOSURE_ONLY'}]}));assert.equal(result.accepted,true);assert.equal(result.decision.blockDecision.evidenceToObserve.length,0)});
test('same-item immediate check is neither transfer nor retention',async()=>{const result=await e.decideInnerTutorV1(input({event:event({kind:'LEARNER_RESPONSE',outcome:'SUCCESS',support:'GUIDED'}),provider:async()=>{throw new Error('offline')}}));assert.equal(result.blockDecision.contextProvenance,'SAME_CONTEXT');assert.notEqual(result.blockDecision.pedagogicalIntent,'TRANSFER')});
test('qualified source return uses a registered transfer mechanism and preserves the D objective',()=>{const context=e.compilePedagogicalContextV1(input());const result=e.qualifyInnerTutorProposalV1(context,event(),proposal({teacherAction:'RETURN_TO_TASK',pedagogicalIntent:'TRANSFER',selectedBlockId:'return-original-writing',contextProvenance:'SOURCE',supportLevel:'NONE',evidenceToObserve:[{facet:'CONSTRUCTION',productionCondition:'FRESH_INDEPENDENT'}]}));assert.equal(result.accepted,true);assert.equal(result.decision.action,'RETURN_TO_TASK');assert.equal(result.decision.blockDecision.objectiveId,lesson.id)});
test('same decision point is idempotent across retry or resume',async()=>{const first=await e.decideInnerTutorV1(input());const replay=await e.decideInnerTutorV1(input({currentDecision:first.blockDecision,provider:async()=>{throw new Error('must not call')}}));assert.equal(replay.reused,true);assert.equal(replay.blockDecision,first.blockDecision)});
test('time exhausted stops instead of looping',async()=>{const result=await e.decideInnerTutorV1(input({event:event({kind:'TIME_EXHAUSTED'}),timeRemainingMinutes:0,provider:async()=>{throw new Error('offline')}}));assert.equal(result.action,'STOP');assert.equal(result.experience.kind,'SESSION_STOP')});
test('time exhaustion and routine success avoid provider calls',async()=>{let calls=0;const timed=await e.decideInnerTutorV1(input({event:event({kind:'TIME_EXHAUSTED'}),timeRemainingMinutes:0,provider:async()=>{calls++;return proposal()}}));assert.equal(calls,0);assert.equal(timed.action,'STOP');const success=await e.decideInnerTutorV1(input({event:event({kind:'LEARNER_RESPONSE',outcome:'SUCCESS'}),provider:async()=>{calls++;return proposal()}}));assert.equal(success.action,'NONE');assert.equal(calls,0);assert.equal(success.provenance.modelCall.route,'AVOIDED_MODEL_CALL')});
test('provider failure and invalid provider output use qualified deterministic fallback when model reasoning is required',async()=>{const failureEvent=event({kind:'LEARNER_RESPONSE',outcome:'FAILURE'}),failed=await e.decideInnerTutorV1(input({event:failureEvent,provider:async()=>{throw new Error('timeout')}}));assert.equal(failed.provenance.provider,'FALLBACK_AFTER_REJECTION');const invalid=await e.decideInnerTutorV1(input({event:failureEvent,provider:async()=>proposal({teacherAction:'INVENTED'})}));assert.equal(invalid.provenance.provider,'FALLBACK_AFTER_REJECTION');assert.ok(invalid.provenance.rejectionReasons.length)});
test('qualified intervention carries bounded composition deterministic narrator and model-call telemetry',async()=>{const result=await e.decideInnerTutorV1(input({event:event({kind:'LEARNER_RESPONSE',outcome:'FAILURE'}),provider:async()=>proposal()}));assert.equal(result.composition.masteryMutationAllowed,false);assert.equal(result.composition.pieces[0].blockId,result.provenance.selectedMechanismId);assert.ok(result.experience.narrator.message.length>10);assert.equal(result.experience.internalReasoningVisible,false);assert.equal(result.provenance.modelCall.route,'MODEL_REQUIRED')});
test('production composition cursor survives JSON restart and advances without a duplicate model decision',async()=>{let calls=0;const first=await e.decideInnerTutorV1(input({event:event({kind:'LEARNER_RESPONSE',outcome:'FAILURE'}),provider:async()=>{calls++;return proposal()}})),persisted=JSON.parse(JSON.stringify(first.blockDecision)),resumed=await e.decideInnerTutorV1(input({event:event({id:'event-after-restart',kind:'LEARNER_RESPONSE',outcome:'SUCCESS',support:'GUIDED'}),currentDecision:persisted,provider:async()=>{calls++;return proposal()}}));const saved=JSON.parse(resumed.blockDecision.configuration.teacherComposition);assert.equal(saved.planId,first.composition.planId);assert.equal(saved.cursor,1);assert.equal(resumed.blockDecision.configuration.compositionCursor,1);assert.equal(calls,1);assert.equal(resumed.provenance.modelCall.route,'DETERMINISTIC_CONTINUATION')});
test('decision provenance must remain bound to canonical LessonPlan and hide internal reasoning',()=>{const context=e.compilePedagogicalContextV1(input());assert.equal(e.qualifyInnerTutorProposalV1(context,event(),proposal({lessonPlanId:'wrong'})).accepted,false);const ok=e.qualifyInnerTutorProposalV1(context,event(),proposal());assert.equal(ok.accepted,true);assert.equal(ok.decision.provenance.lessonPlanId,lesson.id);assert.equal(ok.decision.experience.internalReasoningVisible,false);assert.equal('internalDecisionReason' in ok.decision.provenance,false)});
test('General and Exam compile against the same learner truth object without mutation or fork',()=>{const general=e.compilePedagogicalContextV1(input());const exam=e.compilePedagogicalContextV1(input({lessonPlan:{...lesson,productMode:'EXAM'},productContext:{...product,productMode:'EXAM'}}));assert.equal(general.product.productMode,'GENERAL');assert.equal(exam.product.productMode,'EXAM');assert.equal(truth.capabilitySlice.length,0)});

const artifact={schemaVersion:4,id:'artifact-1',learnerId:'l',source:'DIRECT_TEXT',mode:'WRITING',pages:[{page:1,mimeType:'text/plain',originalText:'Learner text'}],submittedAt:'2026-08-27T00:00:00Z',immutable:true};
const runtime=()=>({id:'runtime-1',learnerId:'l',artifact,spans:[],confirmations:[],usableSourceText:'Learner text',status:'LEARNING',blockEvents:[],observations:[],evidenceCandidates:[],trace:[]});

test('Experience execution makes NONE no-intervention, STOP/EXIT terminal, and RETURN_TO_TASK original-task state',async()=>{
  const none=await e.decideInnerTutorV1(input({event:event({kind:'LEARNER_RESPONSE',outcome:'SUCCESS'}),provider:async()=>{throw new Error('offline')}}));
  const n=experience.executeTeacherExperienceV1(runtime(),experience.teacherDecisionToExperienceContractV1(none));assert.equal(n.effect,'CONTINUE_ORIGINAL_TASK');assert.equal(n.runtime.decision,undefined);assert.equal(n.runtime.blockState,undefined);assert.equal(n.runtime.experienceState,'ORIGINAL_TASK');
  const stopped=await e.decideInnerTutorV1(input({event:event({kind:'TIME_EXHAUSTED'}),timeRemainingMinutes:0,provider:async()=>{throw new Error('offline')}}));
  const s=experience.executeTeacherExperienceV1(runtime(),experience.teacherDecisionToExperienceContractV1(stopped));assert.equal(s.effect,'STOP_SESSION');assert.equal(s.runtime.status,'COMPLETED');assert.equal(s.runtime.blockState,undefined);
  const context=e.compilePedagogicalContextV1(input()),exit=e.qualifyInnerTutorProposalV1(context,event(),proposal({teacherAction:'EXIT',pedagogicalIntent:'SYSTEM',selectedBlockId:'continue-source',supportLevel:'NONE',contextProvenance:'NOT_APPLICABLE'}));assert.equal(exit.accepted,true);const x=experience.executeTeacherExperienceV1(runtime(),experience.teacherDecisionToExperienceContractV1(exit.decision));assert.equal(x.effect,'EXIT_SESSION');assert.equal(x.runtime.status,'COMPLETED');
  const returned=e.qualifyInnerTutorProposalV1(context,event(),proposal({teacherAction:'RETURN_TO_TASK',pedagogicalIntent:'TRANSFER',selectedBlockId:'return-original-writing',supportLevel:'NONE',contextProvenance:'SOURCE'}));assert.equal(returned.accepted,true);const r=experience.executeTeacherExperienceV1(runtime(),experience.teacherDecisionToExperienceContractV1(returned.decision));assert.equal(r.effect,'RETURN_TO_ORIGINAL_TASK');assert.equal(r.runtime.experienceState,'RETURNED_TO_TASK');assert.equal(r.runtime.decision,undefined);
  const teach=e.qualifyInnerTutorProposalV1(context,event(),proposal());assert.equal(teach.accepted,true);const learning=experience.executeTeacherExperienceV1(runtime(),experience.teacherDecisionToExperienceContractV1(teach.decision));assert.equal(learning.effect,'SELECT_BLOCK');assert.equal(learning.blockDecision.selectedBlockId,'grammar-role-map');
  const teachContract=experience.teacherDecisionToExperienceContractV1(teach.decision),divergent={...teachContract,execution:{...teachContract.execution,action:'NONE',blockDecision:undefined}};const obeyed=experience.executeTeacherExperienceV1(runtime(),divergent);assert.equal(teach.decision.action,'TEACH');assert.equal(obeyed.effect,'CONTINUE_ORIGINAL_TASK');
});

test('persisted tutor clock decreases, survives resume, and naturally reaches zero without evidence',()=>{
  const started=e.startTutorSessionV1(runtime(),20,'2026-08-27T00:00:00Z');assert.equal(e.tutorTimeRemainingMinutesV1(started,'2026-08-27T00:07:00Z'),13);
  const paused=e.pauseTutorSessionV1(started,'2026-08-27T00:07:00Z'),resumed=e.resumeTutorSessionV1(JSON.parse(JSON.stringify(paused)),'2026-08-27T00:12:00Z');assert.equal(e.tutorTimeRemainingMinutesV1(resumed,'2026-08-27T00:20:00Z'),5);assert.equal(e.tutorTimeRemainingMinutesV1(resumed,'2026-08-27T00:25:00Z'),0);assert.equal(resumed.evidenceCandidates.length,0);
});

test('event adapter keeps context-only events out of capability outcomes and preserves explicit outcomes',()=>{
  for(const type of ['SOURCE_CLARIFIED','RESUMED','ITEM_MOVED']){const adapted=e.adaptLearnerEventToPedagogyV1({id:type,type,occurredAt:'2026-08-27T00:00:00Z',support:'NONE',observationIds:[]});assert.equal(adapted.event.outcome,'NOT_EVALUATED');assert.equal(adapted.capabilityEvidenceAllowed,false);assert.equal(e.isPedagogicalDecisionPointV1(input({event:adapted.event})),true)}
  const help=e.adaptLearnerEventToPedagogyV1({id:'help',type:'HINT_REQUESTED',occurredAt:'2026-08-27T00:00:00Z',support:'NONE',observationIds:[]});assert.equal(help.event.outcome,'HELP_WITHOUT_ATTEMPT');assert.equal(help.capabilityEvidenceAllowed,false);
  for(const outcome of ['SUCCESS','PARTIAL','FAILURE','NOT_EVALUATED']){const adapted=e.adaptLearnerEventToPedagogyV1({id:outcome,type:'ANSWER_SUBMITTED',occurredAt:'2026-08-27T00:00:00Z',support:'NONE',observationIds:[],evaluatedOutcome:outcome});assert.equal(adapted.event.outcome,outcome)}
});

test('SYSTEM cannot smuggle a different target or facet past D authority',()=>{const context=e.compilePedagogicalContextV1(input());assert.equal(e.qualifyInnerTutorProposalV1(context,event(),proposal({teacherAction:'WAIT',pedagogicalIntent:'SYSTEM',selectedBlockId:'continue-source',supportLevel:'NONE',targetReference:'word.allow'})).accepted,false);assert.equal(e.qualifyInnerTutorProposalV1(context,event(),proposal({teacherAction:'WAIT',pedagogicalIntent:'SYSTEM',selectedBlockId:'continue-source',supportLevel:'NONE',focusFacet:'FREE_PRODUCTION'})).accepted,false)});

test('generic evaluator registry supports canonical non-allow targets and allow regression remains specialized',()=>{
  const registry=new e.OutcomeEvaluatorRegistryV1().register({id:'writing-sentence-fixture',version:'test',provenance:'TEST',targetRef:'writing.sentence-realization',facets:['CONSTRUCTION'],evaluate:request=>({outcome:request.response==='complete'?'SUCCESS':request.response==='partial'?'PARTIAL':request.response==='wrong'?'FAILURE':'NOT_EVALUATED',reasonCodes:['FIXTURE_SIGNAL']})});
  for(const [response,outcome] of [['complete','SUCCESS'],['partial','PARTIAL'],['wrong','FAILURE'],['','NOT_EVALUATED']])assert.equal(registry.evaluate({targetRef:'writing.sentence-realization',facet:'CONSTRUCTION',response,context:'SAME_CONTEXT'}).outcome,outcome);
  assert.equal(e.productionOutcomeEvaluatorsV1.evaluate({targetRef:'allow-object-infinitive',facet:'CONSTRUCTION',response:'Schools should allow to use phones.',context:'SOURCE'}).outcome,'PARTIAL');assert.equal(e.productionOutcomeEvaluatorsV1.evaluate({targetRef:'allow-object-infinitive',facet:'CONSTRUCTION',response:'Schools should allow students to use phones.',context:'SOURCE'}).outcome,'SUCCESS');
  const writing=request=>e.productionOutcomeEvaluatorsV1.evaluate({targetRef:'writing.sentence-realization',facet:'CONSTRUCTION',response:request,context:'SAME_CONTEXT'});assert.equal(writing('Students learn.').outcome,'SUCCESS');assert.equal(writing('Students learning').outcome,'PARTIAL');assert.equal(writing('Fragment').outcome,'FAILURE');assert.equal(writing('').outcome,'NOT_EVALUATED');assert.equal(writing('Students learn.').evaluatorId,'writing-sentence-realization-construction-v1');assert.equal(writing('Students learn.').evaluatorVersion,'1.0.0');
  assert.equal(e.productionOutcomeEvaluatorsV1.evaluate({targetRef:'writing.sentence-realization',facet:'COLLOCATION',response:'Students learn.',context:'SAME_CONTEXT'}).outcome,'NOT_EVALUATED');assert.equal(e.productionOutcomeEvaluatorsV1.evaluate({targetRef:'unknown.target',facet:'CONSTRUCTION',response:'Students learn.',context:'SAME_CONTEXT'}).outcome,'NOT_EVALUATED');
});

test('production non-allow evaluator drives E routing through Experience Contract execution',async()=>{
  const writingLesson={...lesson,id:'lesson:writing',targetRef:'writing.sentence-realization',facet:'CONSTRUCTION',objective:'realize an English sentence'},evaluate=response=>e.productionOutcomeEvaluatorsV1.evaluate({targetRef:writingLesson.targetRef,facet:writingLesson.facet,response,context:'SAME_CONTEXT'}).outcome,decide=outcome=>e.decideInnerTutorV1(input({lessonPlan:writingLesson,event:event({id:`writing-${outcome}`,kind:'LEARNER_RESPONSE',outcome}),provider:async()=>{throw new Error('offline')}}));
  const success=await decide(evaluate('Students learn.')),partial=await decide(evaluate('Students learning')),failure=await decide(evaluate('Fragment'));
  assert.equal(success.action,'NONE');assert.equal(partial.action,'REPAIR');assert.equal(failure.action,'TEACH');
  const noneExecution=experience.executeTeacherExperienceV1(runtime(),experience.teacherDecisionToExperienceContractV1(success)),repairExecution=experience.executeTeacherExperienceV1(runtime(),experience.teacherDecisionToExperienceContractV1(partial));assert.equal(noneExecution.effect,'CONTINUE_ORIGINAL_TASK');assert.equal(repairExecution.effect,'SELECT_BLOCK');
});

test('NOT_EVALUATED treatment response and original provenance survive replay',async()=>{const first=await e.decideInnerTutorV1(input()),original={...first.provenance,sourceEvidenceIds:['evidence-1'],provider:'AI'};const replay=await e.decideInnerTutorV1(input({currentDecision:first.blockDecision,currentProvenance:original,provider:async()=>{throw new Error('must not call')}}));assert.equal(replay.provenance.provider,'AI');assert.deepEqual(replay.provenance.sourceEvidenceIds,['evidence-1']);const next=await e.decideInnerTutorV1(input({event:event({id:'event-2',kind:'LEARNER_MANIPULATION',outcome:'NOT_EVALUATED'}),currentDecision:first.blockDecision,provider:async()=>{throw new Error('offline')}}));assert.equal(next.treatmentResponse.outcome,'NOT_EVALUATED')});
