import{Href,router}from'expo-router';
import React,{useEffect,useRef,useState}from'react';
import{ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,View}from'react-native';
import{SafeAreaView}from'react-native-safe-area-context';
import{useCanonicalProductData}from'../../context/AppDataContext';
import{examBetaTaskForLearner,examFamilyToPracticeFamilyV1,type ExamBetaFamily}from'../../src/content/examBetaBank';
import{canonicalLearnerTruthV1}from'../../src/persistence';
import{buildPersonalizedRoutesV1,type PersonalizedRouteFamilyV1}from'../../src/product';
import{eotLearnerTokensV1 as t}from'../../src/ui';

type Mission=NonNullable<ReturnType<typeof useCanonicalProductData>['profile']['onboarding']['firstMission']>;
type Strategy={id:string;title:string;timePlan:string;mission:Mission};
const familyLabel:Record<ExamBetaFamily,string>={VOCABULARY:'詞彙',COMPREHENSIVE:'綜合測驗',CONTEXTUAL_FILL:'文意選填',DISCOURSE:'篇章結構',READING:'閱讀測驗',MIXED:'混合題',TRANSLATION:'中譯英',WRITING:'英文作文'};
const evidenceFamily=(targetRef:string):PersonalizedRouteFamilyV1=>targetRef.startsWith('writing.')?'WRITING':targetRef.startsWith('translation.')?'TRANSLATION':targetRef==='reading.logic-structure'?'DISCOURSE':targetRef.startsWith('reading.')?'READING':targetRef.includes('cloze')?'COMPREHENSIVE':targetRef.includes('word-bank')?'CONTEXTUAL_FILL':targetRef.includes('mixed')?'MIXED':'VOCABULARY';

export default function FirstMissionHandoff(){
 const{profile,learnerPreferences,updateProductContext,recordTutorialAction}=useCanonicalProductData();
 const[strategies,setStrategies]=useState<Strategy[]>([]),[selected,setSelected]=useState(0);const launching=useRef(false);
 useEffect(()=>{let live=true;void(async()=>{
  const truth=await canonicalLearnerTruthV1.project(learnerPreferences.learnerId),grouped=new Map<PersonalizedRouteFamilyV1,{fragile:number;independent:number}>();
  for(const item of truth.capabilitySlice){const family=evidenceFamily(item.targetRef),row=grouped.get(family)??{fragile:0,independent:0};if(['OBSERVED_FRAGILE','ASSISTED_CONTROL'].includes(item.state))row.fragile+=1;if(['INDEPENDENT_LOCAL_CONTROL','TRANSFER_SUPPORTED','RETENTION_SUPPORTED'].includes(item.state))row.independent+=1;grouped.set(family,row)}
  const candidates=buildPersonalizedRoutesV1({results:profile.gsatBeta.recentResults,dailyMinutes:profile.study.dailyStudyMinutes,examDate:profile.exam.deadline,nextMockDate:profile.onboarding.nextMockDate,evidence:[...grouped].map(([family,row])=>({family,...row}))});
  const built:Strategy[]=[];for(const candidate of candidates){const family=candidate.family as ExamBetaFamily,task=examBetaTaskForLearner(family,learnerPreferences.learnerId,'suggested',`first-${candidate.id}`);if(!task)continue;built.push({id:candidate.id,title:candidate.title,timePlan:candidate.timePlan,mission:{family:familyLabel[family],taskLabel:String(task.payload.title??familyLabel[family]),reason:candidate.reason,durationMinutes:candidate.durationMinutes,route:`/exam-practice?practiceFamily=${encodeURIComponent(examFamilyToPracticeFamilyV1(family))}&taskId=${encodeURIComponent(task.task_id)}&origin=TODAY`,selectedAt:new Date().toISOString()}})}
  if(live)setStrategies(built);
 })();return()=>{live=false}},[learnerPreferences.learnerId,profile.exam.deadline,profile.gsatBeta.recentResults,profile.onboarding.nextMockDate,profile.study.dailyStudyMinutes]);
 const mission=strategies[selected]?.mission;
 async function start(){if(!mission||launching.current)return;launching.current=true;try{const startedAt=new Date().toISOString();await updateProductContext({onboarding:{firstMission:{...mission,startedAt},activationHandoffCompleted:true,setupStage:'MISSION_STARTED'}});await recordTutorialAction('TODAY_STARTED',`first-mission:${mission.route}`,'/onboarding/handoff',mission.route);router.replace(mission.route as Href)}finally{launching.current=false}}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Text style={s.heading}>接下來怎麼練</Text><Text style={s.context}>{profile.onboarding.nextMockDate?`離下次模考還有一段時間，每天 ${profile.study.dailyStudyMinutes} 分鐘。`:`你每天有 ${profile.study.dailyStudyMinutes} 分鐘，我會先追回最值得補的地方。`}</Text>{strategies.length?strategies.map((strategy,index)=><Pressable accessibilityRole="radio" accessibilityState={{selected:index===selected}} key={strategy.id} onPress={()=>setSelected(index)} style={[s.strategy,index===selected&&s.strategyOn]}><View style={s.strategyTop}><Text style={s.strategyTitle}>{strategy.title}</Text><Text style={s.timePlan}>{strategy.timePlan}</Text></View><Text style={s.reason}>{strategy.mission.reason}</Text><Text style={s.family}>{strategy.mission.family}</Text></Pressable>):<ActivityIndicator color={t.colors.deepWood}/>}{mission?<><Text style={s.note}>你之後可以再調整。</Text><Pressable accessibilityRole="button" onPress={()=>void start()} style={s.primary}><Text style={s.primaryText}>用這條路開始</Text></Pressable></>:null}</ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:t.colors.background},page:{width:'100%',maxWidth:t.layout.learnerShellMaxWidth,alignSelf:'center',paddingHorizontal:20,paddingTop:40,paddingBottom:40},heading:{fontSize:30,lineHeight:37,fontWeight:'600',color:t.colors.ink},context:{fontSize:16,lineHeight:24,color:t.colors.muted,marginTop:12,marginBottom:32},strategy:{minHeight:132,paddingVertical:16,paddingHorizontal:0,borderBottomWidth:1,borderBottomColor:t.colors.line,gap:8},strategyOn:{borderLeftWidth:3,borderLeftColor:t.colors.focus,paddingLeft:16,backgroundColor:t.colors.focusWash},strategyTop:{flexDirection:'row',justifyContent:'space-between',gap:12},strategyTitle:{flex:1,fontSize:18,lineHeight:25,fontWeight:'600',color:t.colors.ink},reason:{fontSize:14,lineHeight:21,color:t.colors.muted},timePlan:{fontSize:12,lineHeight:18,color:t.colors.muted},family:{fontSize:12,lineHeight:18,color:t.colors.subtle},note:{fontSize:14,lineHeight:21,color:t.colors.muted,marginTop:28,marginBottom:12},primary:{minHeight:52,borderRadius:14,backgroundColor:t.colors.deepWood,alignItems:'center',justifyContent:'center'},primaryText:{fontSize:16,fontWeight:'600',color:t.colors.paper}});
