import type { FreshTaskLoadProfileV1,TaskMeasurementProvenanceV1 } from '../domain/task/TaskContract';
import { buildFreshEvidenceOpportunityV1, classifyFreshnessRelationshipV1 } from '../domain/task/freshEvidence';
import type { CapabilityFacet } from '../domain/english/EnglishDomain';
const normalize=(value:string)=>value.trim().replace(/\s+/g,' ').toLowerCase();
function fnv1a32(value:string){let hash=0x811c9dc5;for(let i=0;i<value.length;i++){hash^=value.charCodeAt(i);hash=Math.imul(hash,0x01000193)>>>0}return hash.toString(16).padStart(8,'0')}
export function measurementContentIdentityV1(value:string):string{return`fnv1a32:${fnv1a32(normalize(value))}`}
export function sourceWorkMeasurementProvenanceV1(input:{taskId:string;sourceText:string;sourceContextKey:string;authenticOutputText?:string;targetRef?:string;facet?:CapabilityFacet;senseId?:string}):TaskMeasurementProvenanceV1{const content=measurementContentIdentityV1(input.sourceText),authentic=Boolean(input.authenticOutputText?.trim()&&input.targetRef&&input.facet),validatorRefs=authentic?Object.freeze(['G:authentic-source-contract-v1']):Object.freeze([] as string[]),freshEvidenceOpportunity=authentic?buildFreshEvidenceOpportunityV1({relationship:'F4_AUTHENTIC_REDEPLOYMENT',comparedSourceId:input.sourceContextKey,comparedItemId:input.taskId,sourceText:input.sourceText,itemText:input.authenticOutputText!,templateGeometry:'LEARNER_AUTHENTIC_OUTPUT',solutionGeometry:'SEMANTIC_RUBRIC',targetRef:input.targetRef!,facet:input.facet!,senseId:input.senseId,topicContext:input.sourceContextKey,genreRepresentation:'LEARNER_OWN_CONTENT',validatorRefs,acceptedAnswerRule:'SEMANTIC_RUBRIC',provenanceStatus:'KNOWN_ALLOWED',examFormatStatus:'NOT_EXAM'}):undefined;return Object.freeze({opportunityKind:'SOURCE_WORK',taskId:input.taskId,sourceContentIdentity:content,taskContentIdentity:authentic?measurementContentIdentityV1(input.authenticOutputText!):content,sourceContextKey:input.sourceContextKey,taskContextKey:input.sourceContextKey,validatorRefs,freshEvidenceOpportunity})}
export function deliveredMeasurementProvenanceV1(input:{taskId:string;sourceText:string;taskText:string;sourceContextKey:string;taskContextKey:string;purpose:'FRESH_CHECK'|'CHANGED_CONTEXT_TRANSFER';deliveryRef:string;validatorRefs:readonly string[];deliveredAt:string;targetRef?:string;facet?:CapabilityFacet;senseId?:string;templateGeometry?:string;solutionGeometry?:string;genreRepresentation?:string;load?:FreshTaskLoadProfileV1;gateFailures?:Parameters<typeof buildFreshEvidenceOpportunityV1>[0]['gateFailures']}):TaskMeasurementProvenanceV1{
  const geometry=input.templateGeometry??'CURATED_OPEN_PRODUCTION_V1',solution=input.solutionGeometry??'SEMANTIC_RUBRIC',classified=classifyFreshnessRelationshipV1({sourceId:input.sourceContextKey,itemId:input.taskId,sourceText:input.sourceText,itemText:input.taskText,sourceTemplateGeometry:geometry,itemTemplateGeometry:geometry,sourceSolutionGeometry:solution,itemSolutionGeometry:solution,sourceContext:input.sourceContextKey,itemContext:input.taskContextKey,sourceGenre:input.genreRepresentation??'AUTHENTIC_SOURCE',itemGenre:input.genreRepresentation??'AUTHENTIC_SOURCE'}),relationship=input.purpose==='CHANGED_CONTEXT_TRANSFER'?'F3_CONTEXT_DIVERSE_EQUIVALENT':classified.relationship;
  const freshEvidenceOpportunity=input.targetRef&&input.facet?buildFreshEvidenceOpportunityV1({relationship,comparedSourceId:input.sourceContextKey,comparedItemId:input.taskId,sourceText:input.sourceText,itemText:input.taskText,templateGeometry:geometry,solutionGeometry:solution,targetRef:input.targetRef,facet:input.facet,senseId:input.senseId,topicContext:input.taskContextKey,genreRepresentation:input.genreRepresentation??'AUTHENTIC_OUTPUT',load:input.load,validatorRefs:input.validatorRefs,gateFailures:input.gateFailures,acceptedAnswerRule:'SEMANTIC_RUBRIC',provenanceStatus:input.validatorRefs.length?'KNOWN_ALLOWED':'UNKNOWN',examFormatStatus:'NOT_EXAM'}):undefined;
  return Object.freeze({opportunityKind:input.purpose==='FRESH_CHECK'?'VALIDATED_FRESH':'VALIDATED_CHANGED_CONTEXT',taskId:input.taskId,sourceContentIdentity:measurementContentIdentityV1(input.sourceText),taskContentIdentity:measurementContentIdentityV1(input.taskText),sourceContextKey:input.sourceContextKey,taskContextKey:input.taskContextKey,deliveryRef:input.deliveryRef,validatorRefs:Object.freeze([...input.validatorRefs]),deliveredAt:input.deliveredAt,freshEvidenceOpportunity});
}
