export type SemanticAssessmentOutcomeV1='CORRECT'|'PARTIALLY_CORRECT'|'INCORRECT'|'AMBIGUOUS'|'UNINTERPRETABLE'|'ABSTAIN';
export type SemanticAssessmentAuthorityV1='DETERMINISTIC_RULE'|'BOUNDED_RUBRIC'|'VALIDATED_MODEL'|'NONE';
export type SemanticAssessmentFailureV1='PROVIDER_TIMEOUT'|'PROVIDER_FAILURE'|'INVALID_SCHEMA'|'ASSESSOR_CONFLICT'|'INVALID_CONTENT'|'UNVALIDATED_MODEL'|'ITEM_VALIDATOR_FAILURE';
export interface SemanticDimensionJudgmentV1{dimension:string;outcome:'CORRECT'|'PARTIALLY_CORRECT'|'INCORRECT'|'UNRESOLVED';reasonCodes:readonly string[]}
export interface BoundedSemanticJudgmentV1{outcome:Exclude<SemanticAssessmentOutcomeV1,'ABSTAIN'>;dimensions:readonly SemanticDimensionJudgmentV1[];rubricId:string;rubricVersion:string;reasonCodes:readonly string[]}
export interface SemanticModelJudgmentV1 extends BoundedSemanticJudgmentV1{provider:string;model:string;modelVersion:string;promptVersion:string;schemaVersion:'semantic-assessment-v1';requestId:string;rawModelConfidence?:number;independentVerificationRef?:string}
export interface SemanticAssessmentDecisionV1{outcome:SemanticAssessmentOutcomeV1;authority:SemanticAssessmentAuthorityV1;dimensions:readonly SemanticDimensionJudgmentV1[];learnerEvidenceConfidence:'NONE'|'LOW'|'MEDIUM'|'HIGH';candidateEvidenceAllowed:boolean;negativeEvidenceAllowed:boolean;consumeEvidenceOpportunity:boolean;abstained:boolean;failure?:SemanticAssessmentFailureV1;reasonCodes:readonly string[];provenance:{rubricId?:string;rubricVersion?:string;provider?:string;model?:string;modelVersion?:string;promptVersion?:string;schemaVersion?:string;requestId?:string;independentVerificationRef?:string};canonicalAuthority:false}

const abstain=(failure:SemanticAssessmentFailureV1|undefined,reasons:readonly string[]):SemanticAssessmentDecisionV1=>Object.freeze({outcome:'ABSTAIN',authority:'NONE',dimensions:Object.freeze([]),learnerEvidenceConfidence:'NONE',candidateEvidenceAllowed:false,negativeEvidenceAllowed:false,consumeEvidenceOpportunity:false,abstained:true,failure,reasonCodes:Object.freeze([...reasons]),provenance:Object.freeze({}),canonicalAuthority:false});
const ambiguous=(judgment:BoundedSemanticJudgmentV1,authority:SemanticAssessmentAuthorityV1):SemanticAssessmentDecisionV1=>Object.freeze({outcome:judgment.outcome,authority,dimensions:Object.freeze([...judgment.dimensions]),learnerEvidenceConfidence:'NONE',candidateEvidenceAllowed:false,negativeEvidenceAllowed:false,consumeEvidenceOpportunity:false,abstained:true,reasonCodes:Object.freeze([...judgment.reasonCodes,'SEMANTIC_UNCERTAINTY_REQUIRES_ABSTENTION']),provenance:Object.freeze({rubricId:judgment.rubricId,rubricVersion:judgment.rubricVersion}),canonicalAuthority:false});
const validJudgment=(value:unknown):value is BoundedSemanticJudgmentV1=>Boolean(value&&typeof value==='object'&&['CORRECT','PARTIALLY_CORRECT','INCORRECT','AMBIGUOUS','UNINTERPRETABLE'].includes(String((value as BoundedSemanticJudgmentV1).outcome))&&Array.isArray((value as BoundedSemanticJudgmentV1).dimensions)&&typeof (value as BoundedSemanticJudgmentV1).rubricId==='string'&&typeof (value as BoundedSemanticJudgmentV1).rubricVersion==='string'&&Array.isArray((value as BoundedSemanticJudgmentV1).reasonCodes));
const validModelJudgment=(value:unknown):value is SemanticModelJudgmentV1=>validJudgment(value)&&typeof (value as SemanticModelJudgmentV1).provider==='string'&&typeof (value as SemanticModelJudgmentV1).model==='string'&&typeof (value as SemanticModelJudgmentV1).modelVersion==='string'&&typeof (value as SemanticModelJudgmentV1).promptVersion==='string'&&(value as SemanticModelJudgmentV1).schemaVersion==='semantic-assessment-v1'&&typeof (value as SemanticModelJudgmentV1).requestId==='string';

export function qualifySemanticAssessmentV1(input:{deterministic?:BoundedSemanticJudgmentV1;rubric?:BoundedSemanticJudgmentV1;model?:unknown;modelRequired?:boolean;providerFailure?:SemanticAssessmentFailureV1;assessorConflict?:boolean;taskValidated:boolean;contentValidated:boolean;supportIntegrityValid:boolean;allowedModels?:readonly {provider:string;model:string;modelVersion:string;schemaVersion:'semantic-assessment-v1'}[]}):SemanticAssessmentDecisionV1{
  if(!input.taskValidated)return abstain('ITEM_VALIDATOR_FAILURE',['SEMANTIC_TASK_NOT_VALIDATED','AI_FAILURE_IS_NOT_LEARNER_FAILURE']);
  if(!input.contentValidated)return abstain('INVALID_CONTENT',['SEMANTIC_CONTENT_INVALID','AI_FAILURE_IS_NOT_LEARNER_FAILURE']);
  if(!input.supportIntegrityValid)return abstain(undefined,['SEMANTIC_SUPPORT_CONFOUNDED','SUPPORT_EXPOSURE_BLOCKS_EVIDENCE']);
  if(input.providerFailure)return abstain(input.providerFailure,['SEMANTIC_PROVIDER_FAILURE','AI_FAILURE_IS_NOT_LEARNER_FAILURE']);
  if(input.assessorConflict)return abstain('ASSESSOR_CONFLICT',['SEMANTIC_ASSESSORS_CONFLICT','SAME_MODEL_AGREEMENT_IS_NOT_INDEPENDENT_VERIFICATION']);
  const selected=input.deterministic??input.rubric;
  if(selected){if(!validJudgment(selected))return abstain('INVALID_SCHEMA',['SEMANTIC_JUDGMENT_SCHEMA_INVALID']);if(selected.outcome==='AMBIGUOUS'||selected.outcome==='UNINTERPRETABLE')return ambiguous(selected,input.deterministic?'DETERMINISTIC_RULE':'BOUNDED_RUBRIC');const authority=input.deterministic?'DETERMINISTIC_RULE' as const:'BOUNDED_RUBRIC' as const;return Object.freeze({outcome:selected.outcome,authority,dimensions:Object.freeze([...selected.dimensions]),learnerEvidenceConfidence:'HIGH',candidateEvidenceAllowed:true,negativeEvidenceAllowed:selected.outcome==='INCORRECT',consumeEvidenceOpportunity:true,abstained:false,reasonCodes:Object.freeze([...selected.reasonCodes]),provenance:Object.freeze({rubricId:selected.rubricId,rubricVersion:selected.rubricVersion}),canonicalAuthority:false});}
  if(!input.modelRequired)return abstain(undefined,['SEMANTIC_EVIDENCE_INSUFFICIENT']);
  if(!validModelJudgment(input.model))return abstain('INVALID_SCHEMA',['SEMANTIC_MODEL_SCHEMA_INVALID','AI_FAILURE_IS_NOT_LEARNER_FAILURE']);
  const model=input.model as SemanticModelJudgmentV1,allowed=input.allowedModels?.some(x=>x.provider===model.provider&&x.model===model.model&&x.modelVersion===model.modelVersion&&x.schemaVersion===model.schemaVersion);
  if(!allowed)return abstain('UNVALIDATED_MODEL',['SEMANTIC_MODEL_VERSION_NOT_ALLOWED','AI_FAILURE_IS_NOT_LEARNER_FAILURE']);
  if(model.outcome==='AMBIGUOUS'||model.outcome==='UNINTERPRETABLE')return ambiguous(model,'VALIDATED_MODEL');
  const verified=Boolean(model.independentVerificationRef);return Object.freeze({outcome:model.outcome,authority:'VALIDATED_MODEL',dimensions:Object.freeze([...model.dimensions]),learnerEvidenceConfidence:verified?'HIGH':'MEDIUM',candidateEvidenceAllowed:true,negativeEvidenceAllowed:model.outcome==='INCORRECT'&&verified,consumeEvidenceOpportunity:true,abstained:false,reasonCodes:Object.freeze([...model.reasonCodes,...(verified?[]:['RAW_MODEL_CONFIDENCE_IS_NOT_EVIDENCE_CONFIDENCE'])]),provenance:Object.freeze({rubricId:model.rubricId,rubricVersion:model.rubricVersion,provider:model.provider,model:model.model,modelVersion:model.modelVersion,promptVersion:model.promptVersion,schemaVersion:model.schemaVersion,requestId:model.requestId,independentVerificationRef:model.independentVerificationRef}),canonicalAuthority:false});
}

export type ScoringArenaV1='MIXED'|'TRANSLATION'|'WRITING';
export interface ScoringAwareObservationV1{dimension:string;layer:'ENGLISH_ABILITY'|'EXAM_EXECUTION';outcome:'CORRECT'|'PARTIALLY_CORRECT'|'INCORRECT'|'UNRESOLVED';reasonCodes:readonly string[]}
export interface ScoringAwareDiagnosisV1{arena:ScoringArenaV1;observations:readonly ScoringAwareObservationV1[];preservedPositiveDimensions:readonly string[];repairDimensions:readonly string[];highValueBottleneck?:string;maxConcurrentTeachingTargets:1;canWriteMastery:false;canQualifyEvidence:false;reasonCodes:readonly string[]}
export function scoringAwareDiagnosisV1(input:{arena:ScoringArenaV1;observations:readonly {dimension:string;outcome:ScoringAwareObservationV1['outcome'];reasonCodes?:readonly string[]}[]}):ScoringAwareDiagnosisV1{const observations=input.observations.map(x=>Object.freeze({...x,layer:/format|time|procedure/i.test(x.dimension)?'EXAM_EXECUTION' as const:'ENGLISH_ABILITY' as const,reasonCodes:Object.freeze([...(x.reasonCodes??[])])})),positive=observations.filter(x=>x.outcome==='CORRECT').map(x=>x.dimension),repair=observations.filter(x=>x.outcome==='INCORRECT'||x.outcome==='PARTIALLY_CORRECT').map(x=>x.dimension),highValue=repair.find(x=>!/format|time|procedure/i.test(x))??repair[0];return Object.freeze({arena:input.arena,observations:Object.freeze(observations),preservedPositiveDimensions:Object.freeze(positive),repairDimensions:Object.freeze(repair),highValueBottleneck:highValue,maxConcurrentTeachingTargets:1,canWriteMastery:false,canQualifyEvidence:false,reasonCodes:Object.freeze(['SCORING_DIMENSIONS_ARE_OBSERVATIONS','FEEDBACK_BUDGET_ONE_TARGET','C_K_RETAINS_EVIDENCE_AUTHORITY'])})}
