import React,{useEffect,useRef,useState}from'react';
import{Pressable,StyleSheet,Text,TextInput,View}from'react-native';
import type{LearnerActionSurface}from'../../src/ui/learnerActionSurface';
import{eotLearnerTokensV1 as t}from'../../src/ui/tokens';
import{UniversalLookupText}from'./UniversalLookupText';

type Props={family:'TRANSLATION'|'WRITING';prompt:string;requirements?:string[];value:string;surface?:LearnerActionSurface;busy:boolean;onChange:(value:string)=>void;onSubmit:(value:string)=>void;onLookupUsed?:(result:{senseId?:string;lemma?:string})=>void};
export function AuthoredResponseWorkspace({family,prompt,requirements=[],value,surface,busy,onChange,onSubmit,onLookupUsed}:Props){const input=useRef<TextInput>(null),[promptOpen,setPromptOpen]=useState(!value.trim());const focus=surface&&'targetSpan'in surface?surface.targetSpan:undefined;useEffect(()=>{if(!focus||!value.includes(focus))return;const start=value.indexOf(focus);requestAnimationFrame(()=>{input.current?.focus();input.current?.setNativeProps({selection:{start,end:start+focus.length}})})},[focus,value]);const guidance=surface?.instruction??('goal'in(surface??{})?String((surface as {goal?:string}).goal??''):'');return <View style={s.workspace}>
 <Pressable accessibilityRole="button" accessibilityState={{expanded:promptOpen}} onPress={()=>setPromptOpen(open=>!open)} style={s.promptHead}><Text style={s.kicker}>{family==='WRITING'?'題目':'中文'}</Text><Text style={s.fold}>{promptOpen?'收起':'查看'}</Text></Pressable>
 {promptOpen?<View style={s.prompt}><UniversalLookupText text={prompt} instruction onLookupUsed={onLookupUsed} style={s.promptText}/>{requirements.map(item=><Text key={item} style={s.requirement}>• {item}</Text>)}</View>:null}
 {guidance?<View style={s.guidance}><Text style={s.guidanceTitle}>這次只改一件事</Text><Text style={s.guidanceText}>{guidance}</Text>{focus?<Text style={s.focus}>{focus}</Text>:null}</View>:null}
 <Text style={s.kicker}>{family==='WRITING'?'你的文章':'你的翻譯'}</Text>
 <TextInput ref={input} accessibilityLabel={family==='WRITING'?'你的文章':'你的翻譯'} multiline value={value} onChangeText={text=>{onChange(text);if(!value.trim()&&text.trim())setPromptOpen(false)}} placeholder={family==='WRITING'?'寫下你的第一版':'從這裡開始寫'} placeholderTextColor={t.colors.subtle} style={[s.editor,family==='WRITING'&&s.long]}/>
 {value.trim()?<UniversalLookupText text={value} sourceFamily={family} lookupGesture="LONG_PRESS" onLookupUsed={onLookupUsed} style={s.preview}/>:null}
 <Pressable disabled={busy||!value.trim()} onPress={()=>onSubmit(value)} style={[s.submit,(busy||!value.trim())&&s.disabled]}><Text style={s.submitText}>{busy?'正在確認…':surface?'完成修改':family==='WRITING'?'完成這一版':'完成翻譯'}</Text></Pressable>
 </View>}
const s=StyleSheet.create({workspace:{gap:14},promptHead:{minHeight:44,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:t.colors.divider},kicker:{fontSize:12,lineHeight:18,fontWeight:'700',letterSpacing:.7,color:t.colors.muted},fold:{fontSize:13,color:t.colors.muted},prompt:{gap:8},promptText:{fontSize:18,lineHeight:29,color:t.colors.ink},requirement:{fontSize:14,lineHeight:21,color:t.colors.muted},guidance:{gap:7,paddingVertical:12,borderTopWidth:1,borderBottomWidth:1,borderColor:t.colors.divider},guidanceTitle:{fontSize:14,fontWeight:'700',color:t.colors.deepWood},guidanceText:{fontSize:16,lineHeight:24,color:t.colors.ink},focus:{alignSelf:'flex-start',paddingHorizontal:7,paddingVertical:3,backgroundColor:t.colors.amberSoft,color:t.colors.deepWood,fontSize:15},editor:{minHeight:150,fontSize:17,lineHeight:28,color:t.colors.ink,textAlignVertical:'top',paddingVertical:10,borderBottomWidth:2,borderBottomColor:t.colors.dividerStrong},long:{minHeight:260},preview:{fontSize:15,lineHeight:25,color:t.colors.ink},submit:{minHeight:50,borderRadius:13,backgroundColor:t.colors.deepWood,alignItems:'center',justifyContent:'center'},submitText:{fontSize:16,fontWeight:'600',color:t.colors.paper},disabled:{opacity:.38}});
