import React,{useEffect,useRef,useState}from'react';
import{Pressable,StyleSheet,Text,TextInput,View}from'react-native';
import type{LearnerActionSurface}from'../../src/ui/learnerActionSurface';
import{eotLearnerTokensV1 as t}from'../../src/ui/tokens';
import{UniversalLookupText}from'./UniversalLookupText';

type Props={family:'TRANSLATION'|'WRITING';prompt:string;requirements?:string[];value:string;surface?:LearnerActionSurface;busy:boolean;onChange:(value:string)=>void;onSubmit:(value:string)=>void;onLookupUsed?:(result:{senseId?:string;lemma?:string})=>void};
export function AuthoredResponseWorkspace({family,prompt,requirements=[],value,surface,busy,onChange,onSubmit,onLookupUsed}:Props){const input=useRef<TextInput>(null),[promptOpen,setPromptOpen]=useState(!value.trim()),[editing,setEditing]=useState(false);const focus=surface&&'targetSpan'in surface?surface.targetSpan:undefined;useEffect(()=>{if(!focus||!value.includes(focus))return;const start=value.indexOf(focus);requestAnimationFrame(()=>{input.current?.focus();input.current?.setNativeProps({selection:{start,end:start+focus.length}})})},[focus,value]);return <View style={s.workspace}>
 {family==='TRANSLATION'?<View style={s.sourcePinned}><Text style={s.kicker}>中文</Text><UniversalLookupText text={prompt} instruction onLookupUsed={onLookupUsed} style={s.sourceText}/></View>:<><Pressable accessibilityRole="button" accessibilityState={{expanded:promptOpen}} onPress={()=>setPromptOpen(open=>!open)} style={s.promptHead}><Text style={s.kicker}>題目</Text><Text style={s.fold}>{promptOpen?'收起':'查看'}</Text></Pressable>{promptOpen?<View style={s.prompt}><UniversalLookupText text={prompt} instruction onLookupUsed={onLookupUsed} style={s.promptText}/>{requirements.map(item=><Text key={item} style={s.requirement}>• {item}</Text>)}</View>:null}</>}
 <View style={[s.paper,editing&&s.paperEditing,focus&&s.paperFocus]}><TextInput ref={input} accessibilityLabel={family==='WRITING'?'你的文章':'你的翻譯'} multiline value={value} onFocus={()=>setEditing(true)} onBlur={()=>setEditing(false)} onChangeText={text=>{onChange(text);if(family==='WRITING'&&!value.trim()&&text.trim())setPromptOpen(false)}} placeholder={family==='WRITING'?'Start writing…':'Write it in English…'} placeholderTextColor={t.colors.subtle} style={[s.editor,family==='WRITING'&&s.long]}/>{busy?<Text style={s.processing}>···</Text>:null}</View>
 <Pressable disabled={busy||!value.trim()} onPress={()=>onSubmit(value)} style={({pressed})=>[s.submit,(busy||!value.trim())&&s.disabled,pressed&&s.submitPressed]}><Text style={s.submitText}>{busy?'':surface?'改好了':family==='WRITING'?'完成這一版':'完成翻譯'}</Text></Pressable>
 </View>}
const s=StyleSheet.create({workspace:{gap:14},sourcePinned:{gap:5,paddingBottom:10,borderBottomWidth:1,borderBottomColor:t.colors.divider},sourceText:{fontSize:17,lineHeight:26,color:t.colors.ink},promptHead:{minHeight:40,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:t.colors.divider},kicker:{fontSize:12,lineHeight:18,fontWeight:'700',letterSpacing:.7,color:t.colors.muted},fold:{fontSize:13,color:t.colors.muted},prompt:{gap:8,paddingBottom:6},promptText:{fontSize:18,lineHeight:29,color:t.colors.ink},requirement:{fontSize:14,lineHeight:21,color:t.colors.muted},paper:{minHeight:180,paddingHorizontal:4,borderBottomWidth:2,borderBottomColor:t.colors.dividerStrong,backgroundColor:'transparent'},paperEditing:{borderBottomColor:t.colors.focus},paperFocus:{backgroundColor:t.colors.focusWash},editor:{minHeight:176,fontSize:19,lineHeight:32,color:t.colors.ink,textAlignVertical:'top',paddingHorizontal:0,paddingVertical:12,outlineStyle:'none' as never},long:{minHeight:330},processing:{position:'absolute',right:4,bottom:6,fontSize:20,color:t.colors.focus},submit:{minHeight:48,borderRadius:12,backgroundColor:t.colors.deepWood,alignItems:'center',justifyContent:'center'},submitPressed:{transform:[{scale:.985}],opacity:.9},submitText:{fontSize:16,fontWeight:'600',color:t.colors.paper},disabled:{opacity:.34}});
