import React from 'react';
import {Pressable,StyleSheet,Text,View,ViewStyle} from 'react-native';
import {eotLearnerTokensV1 as t} from '../../src/ui/tokens';

export function EotPrimaryAction({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={({pressed})=>[s.primary,disabled&&s.disabled,pressed&&s.pressed]}><Text style={s.primaryText}>{label}</Text></Pressable>}
export function EotTextAction({label,onPress}:{label:string;onPress:()=>void}){return <Pressable accessibilityRole="button" onPress={onPress} style={s.textAction}><Text style={s.textActionText}>{label}</Text></Pressable>}
export function EotDivider(){return <View style={s.divider}/>}
export function EotProgressLine({value}:{value:number}){return <View accessibilityRole="progressbar" accessibilityValue={{min:0,max:1,now:Math.max(0,Math.min(1,value))}} style={s.progress}><View style={[s.progressValue,{width:`${Math.max(0,Math.min(1,value))*100}%`} as ViewStyle]}/></View>}
export function InlineStatus({children,tone='neutral'}:{children:React.ReactNode;tone?:'neutral'|'success'|'error'}){return <View accessibilityRole="alert" style={[s.status,tone==='success'&&s.success,tone==='error'&&s.error]}><Text style={s.statusText}>{children}</Text></View>}

const s=StyleSheet.create({primary:{minHeight:52,borderRadius:t.radius.action,backgroundColor:t.colors.deepWood,alignItems:'center',justifyContent:'center',paddingHorizontal:20},primaryText:{color:t.colors.paper,fontSize:16,lineHeight:20,fontWeight:'600'},disabled:{backgroundColor:t.colors.disabled},pressed:{opacity:.9,transform:[{scale:.98}]},textAction:{minHeight:44,alignItems:'center',justifyContent:'center',paddingHorizontal:8},textActionText:{color:t.colors.deepWood,fontSize:14,lineHeight:21,fontWeight:'600'},divider:{height:1,backgroundColor:t.colors.divider},progress:{height:2,backgroundColor:t.colors.divider,overflow:'hidden'},progressValue:{height:2,backgroundColor:t.colors.amberSoft},teacher:{flexDirection:'row',gap:14,marginVertical:20},teacherCompact:{marginVertical:12},rail:{width:3,borderRadius:2,backgroundColor:t.colors.focus},teacherBody:{flex:1,gap:8},status:{paddingVertical:10,borderTopWidth:1,borderBottomWidth:1,borderColor:t.colors.divider},success:{borderColor:t.colors.success,backgroundColor:t.colors.successWash},error:{borderColor:t.colors.danger,backgroundColor:t.colors.dangerWash},statusText:{fontSize:14,lineHeight:21,color:t.colors.ink}});
