import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Pressable,StyleSheet,Text,TextInput,View} from 'react-native';
import {useCanonicalProductData} from '../../context/AppDataContext';
import {prepareManualLexicalCaptureV1} from '../../src/lookup';
import {canonicalLexicalEncounterStoreV1} from '../../src/persistence';
import type {LexicalEncounterEventV1} from '../../src/learner-truth/lexicalEncounter';
import {eotLearnerTokensV1 as t} from '../../src/ui';

const eventId=(learnerId:string,action:string)=>`lexical:${learnerId}:${action}:${Date.now()}:${Math.random().toString(36).slice(2,8)}`;
const sourceLabel=(event:LexicalEncounterEventV1)=>event.captureMethod==='EOT_IN_APP_LOOKUP'?'EOT 查詢':event.sourceType==='CLASS'?'課堂':event.sourceType==='NOTE'?'筆記':'自己記下';

export function LexicalEncounterPanel(){
 const {learnerPreferences}=useCanonicalProductData(),[text,setText]=useState(''),[remember,setRemember]=useState(false),[message,setMessage]=useState(''),[saving,setSaving]=useState(false),[events,setEvents]=useState<readonly LexicalEncounterEventV1[]>([]),[open,setOpen]=useState<string>(),savingRef=useRef(false);
 const reload=useCallback(()=>canonicalLexicalEncounterStoreV1.listForLearner(learnerPreferences.learnerId).then(setEvents),[learnerPreferences.learnerId]);
 useEffect(()=>{void reload().catch(()=>setMessage('目前無法讀取遇過的英文，稍後再試。'))},[reload]);
 async function save(){if(savingRef.current)return;const value=text.trim();if(!value){setMessage('先輸入一個單字、片語或一句英文。');return}savingRef.current=true;setSaving(true);setMessage('');try{const event=prepareManualLexicalCaptureV1({eventId:eventId(learnerPreferences.learnerId,'manual'),learnerId:learnerPreferences.learnerId,occurredAt:new Date().toISOString(),sourceType:'UNKNOWN',plainText:value,userMarkedRemember:remember,keepContext:false});await canonicalLexicalEncounterStoreV1.append(event);setText('');setRemember(false);setMessage(event.resolutionStatus==='RESOLVED'?'已記下；之後遇到合適情境時，EOT 可以再帶回來。':'已記下。這次語境還不足，所以不會猜它的意思。');await reload()}catch{setMessage('這次沒有儲存成功，內容還留在上面，請再試一次。')}finally{savingRef.current=false;setSaving(false)}}
 const groups=useMemo(()=>{const map=new Map<string,LexicalEncounterEventV1[]>();for(const event of [...events].reverse()){const rows=map.get(event.normalizedTargetCandidate)??[];rows.push(event);map.set(event.normalizedTargetCandidate,rows)}return [...map.entries()].slice(0,8)},[events]);
 return <View style={s.section}><Text style={s.title}>記下遇到的英文</Text><Text style={s.help}>貼上一個單字、片語或一句英文。語境不夠時也可以先留下來。</Text><TextInput accessibilityLabel="遇到的英文" multiline value={text} onChangeText={setText} placeholder="例如：carry out / 一句剛看到的英文" placeholderTextColor={t.colors.subtle} style={s.input}/><View style={s.actions}><Pressable accessibilityRole="checkbox" accessibilityState={{checked:remember}} onPress={()=>setRemember(v=>!v)} style={s.remember}><Text style={s.rememberText}>{remember?'✓ 我要記':'我要記'}</Text></Pressable><Pressable accessibilityRole="button" disabled={saving} onPress={()=>void save()} style={s.save}><Text style={s.saveText}>{saving?'儲存中…':'記下來'}</Text></Pressable></View>{message?<Text accessibilityLiveRegion="polite" style={s.message}>{message}</Text>:null}
 {groups.length?<View style={s.history}><Text style={s.title}>最近遇過</Text>{groups.map(([key,rows])=>{const looked=rows.some(x=>x.lookupResultExposed),expanded=open===key;return <View key={key} style={s.row}><Pressable accessibilityRole="button" onPress={()=>setOpen(expanded?undefined:key)} style={s.rowHead}><View><Text style={s.word}>{rows[0].phraseOrChunkCandidate??rows[0].selectedSpan}</Text><Text style={s.status}>{looked?'查過':'遇過'} · {rows.length} 次</Text></View><Text style={s.detail}>{expanded?'收起':'詳細'}</Text></Pressable>{expanded?<View style={s.detailBox}>{rows.slice(0,4).map(x=><Text key={x.eventId} style={s.detailText}>{new Date(x.occurredAt).toLocaleDateString('zh-TW')} · {sourceLabel(x)}{x.userMarkedRemember?' · 我要記':''}{x.resolutionStatus!=='RESOLVED'?' · 尚未確定語境':''}</Text>)}</View>:null}</View>})}</View>:<Text style={s.empty}>還沒有記錄。這裡只會顯示你真的遇過或查過的英文。</Text>}</View>
}
const s=StyleSheet.create({section:{gap:10},title:{fontSize:17,fontWeight:'900',color:t.colors.ink},help:{fontSize:13,lineHeight:20,color:t.colors.muted},input:{minHeight:74,borderWidth:1,borderColor:t.colors.line,borderRadius:t.radius.medium,padding:12,fontSize:16,color:t.colors.ink,backgroundColor:t.colors.paper,textAlignVertical:'top'},actions:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},remember:{paddingVertical:10,paddingHorizontal:4},rememberText:{fontSize:14,fontWeight:'800',color:t.colors.deepWood},save:{minHeight:44,paddingHorizontal:22,borderRadius:t.radius.medium,backgroundColor:t.colors.deepWood,alignItems:'center',justifyContent:'center'},saveText:{color:t.colors.paper,fontWeight:'900'},message:{fontSize:13,lineHeight:20,color:t.colors.muted},history:{gap:8,marginTop:10},row:{borderTopWidth:1,borderTopColor:t.colors.line,paddingTop:9},rowHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},word:{fontSize:16,fontWeight:'800',color:t.colors.ink},status:{fontSize:12,color:t.colors.muted,marginTop:2},detail:{fontSize:13,fontWeight:'800',color:t.colors.deepWood},detailBox:{paddingTop:7,gap:4},detailText:{fontSize:12,lineHeight:18,color:t.colors.muted},empty:{fontSize:13,color:t.colors.subtle}});

