import React,{useEffect,useState} from 'react';
import {AccessibilityInfo,Animated,Easing,Pressable,StyleSheet,Text,TextInput,View} from 'react-native';
import type {LearnerActionEvent,LearnerActionSurface,LearnerItem} from '../../src/ui/learnerActionSurface';
import {eotLearnerTokensV1 as t} from '../../src/ui/tokens';

type Props={surface:LearnerActionSurface;onEvent:(event:LearnerActionEvent)=>void};
const send=(p:Props,kind:LearnerActionEvent['kind'],value:unknown)=>p.onEvent({surfaceId:p.surface.id,kind,value});
export function LearnerActionRenderer(props:Props){return <Motion identity={`${props.surface.id}:${props.surface.kind}`}><View style={s.root}>{props.surface.instruction?<Text style={s.instruction}>{props.surface.instruction}</Text>:null}<Surface {...props}/></View></Motion>}

function Motion({identity,children}:{identity:string;children:React.ReactNode}){const[value]=useState(()=>new Animated.Value(0)),[reduced,setReduced]=useState(true);useEffect(()=>{const sub=AccessibilityInfo.addEventListener('reduceMotionChanged',setReduced);void AccessibilityInfo.isReduceMotionEnabled().then(setReduced);return()=>sub.remove()},[]);useEffect(()=>{value.setValue(reduced?1:0);if(!reduced)Animated.timing(value,{toValue:1,duration:220,easing:Easing.out(Easing.cubic),useNativeDriver:true}).start()},[identity,reduced,value]);return <Animated.View style={{opacity:value,transform:[{translateY:value.interpolate({inputRange:[0,1],outputRange:[4,0]})}]}}>{children}</Animated.View>}
function Surface(p:Props){switch(p.surface.kind){
  case'CHOICE':return <Choice p={p} sentence={p.surface.sentence} values={p.surface.choices} selected={p.surface.selectedAnswer}/>;
  case'EVIDENCE':return <Evidence p={p}/>;
  case'MEANING_CONTRAST':return <Meaning p={p}/>;
  case'SLOT':return <Slot p={p}/>;
  case'CHUNK_BUILD':return <Build p={p} values={p.surface.tokens}/>;
  case'COLLOCATION':return <Collocation p={p}/>;
  case'WORD_BUILD':return <Build p={p} values={p.surface.pieces} original={p.surface.original}/>;
  case'REFERENCE_TRACE':return <Reference p={p}/>;
  case'INSERTION':return <Insertion p={p}/>;
  case'ORDER':return <Build p={p} values={p.surface.items}/>;
  case'SOURCE_TRACE':return <SourceTrace p={p}/>;
  case'SOURCE_TRANSFORM':return <TextAction p={p} source={p.surface.source} goal={p.surface.goal} event="TRANSFORM" label="送出"/>;
  case'RECALL':return <TextAction p={p} source={p.surface.context} event="RECALL" label="送出"/>;
  case'SPAN_REPAIR':return <TextAction p={p} source={p.surface.authoredText} focus={p.surface.targetSpan} goal={p.surface.goal} event="REPAIR" label="完成修改"/>;
  case'TRANSLATION_EDITOR':return <TextAction p={p} source={p.surface.sourceZh} authored={p.surface.authoredText} focus={p.surface.targetSpan} event="REPAIR" label="完成修改"/>;
  case'WRITING_EDITOR':return <TextAction p={p} source={p.surface.prompt} authored={p.surface.authoredText} focus={p.surface.targetSpan} event="REPAIR" label="完成修改"/>;
  case'WRITING_DEVELOPMENT':return <TextAction p={p} source={p.surface.authoredText} focus={p.surface.targetSpan} goal="用你自己的內容把這裡寫具體。" event="DEVELOP" label="完成修改"/>;
}}
function Choice({p,sentence,values,selected}:{p:Props;sentence:string;values:readonly LearnerItem[];selected?:string}){return <View><Text style={s.object}>{sentence}</Text>{selected?<Text style={s.wrong}>×　{values.find(x=>x.id===selected)?.label??selected}</Text>:null}{values.map(x=><Pressable key={x.id} onPress={()=>send(p,'CHOICE',x.id)} style={s.row}><Text style={s.rowText}>{x.label}</Text></Pressable>)}</View>}
function Evidence({p}:{p:Props}){const surface=p.surface.kind==='EVIDENCE'?p.surface:null,[chosen,setChosen]=useState<string[]>([]);if(!surface)return null;const commit=(id:string)=>{if(surface.single){setChosen([id]);send(p,'EVIDENCE',id)}else setChosen(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])};return <View style={s.section}>{surface.selectedAnswer?<Text style={s.wrong}>×　剛才的選擇保留在下方</Text>:null}<Text style={s.evidence}>{surface.spans.map(span=><Text key={span.id} onPress={()=>commit(span.id)} onLongPress={()=>{}} style={[s.evidenceSpan,chosen.includes(span.id)&&s.on]}>{span.text}{' '}</Text>)}</Text>{!surface.single?<Action label="確認證據" disabled={!chosen.length} onPress={()=>send(p,'EVIDENCE',chosen)}/>:null}</View>}
function Meaning({p}:{p:Props}){const surface=p.surface.kind==='MEANING_CONTRAST'?p.surface:null;if(!surface)return null;return <View style={s.section}><Text style={s.object}>{surface.sentence}</Text>{surface.selectedAnswer?<Text style={s.wrong}>×　{surface.contrasts.find(x=>x.id===surface.selectedAnswer)?.word??surface.selectedAnswer}</Text>:null}<View style={s.contrast}>{surface.contrasts.map(x=><Pressable key={x.id} onPress={()=>send(p,'CHOICE',x.id)} style={s.contrastRow}><Text style={s.word}>{x.word}</Text><View style={s.flex}><Text style={s.meaning}>{x.meaning}</Text><Text style={s.example}>{x.example}</Text></View></Pressable>)}</View></View>}
function fillSentence(sentence:string,id:string,value?:string){return sentence.replace(new RegExp(`___${id}___|_{2,}|\\[blank\\]`),value?`[${value}]`:'＿＿＿')}
function Slot({p}:{p:Props}){const surface=p.surface.kind==='SLOT'?p.surface:null,[placed,setPlaced]=useState(surface?.placed);if(!surface)return null;const place=(x:LearnerItem)=>{setPlaced(x.label);send(p,'PLACEMENT',{blankId:surface.blankId,itemId:x.id,label:x.label})};return <View style={s.section}><Text style={s.object}>{fillSentence(surface.sentence,surface.blankId,placed)}</Text>{placed?<Text style={s.wrong}>×　目前放入：{placed}</Text>:null}<View style={s.tokens}>{surface.candidates.map(x=><Pressable key={x.id} accessibilityHint="可拖到空格；點一下也能直接放入" onPress={()=>place(x)} style={s.token}><Text style={s.rowText}>{x.label}</Text></Pressable>)}</View></View>}
function Build({p,values,original}:{p:Props;values:readonly LearnerItem[];original?:string}){const[answer,setAnswer]=useState<LearnerItem[]>([]);return <View style={s.section}>{original?<Text style={s.wrong}>×　{original}</Text>:null}<View style={s.build}>{answer.map((x,i)=><Pressable key={`${x.id}-${i}`} onPress={()=>setAnswer(v=>v.filter((_,n)=>n!==i))} style={s.built}><Text>{x.label}</Text></Pressable>)}</View><View style={s.tokens}>{values.map(x=><Pressable key={x.id} onPress={()=>setAnswer(v=>[...v,x])} style={s.token}><Text>{x.label}</Text></Pressable>)}</View><Action label="送出" disabled={!answer.length} onPress={()=>send(p,'BUILD',answer.map(x=>x.id))}/></View>}
function Collocation({p}:{p:Props}){const surface=p.surface.kind==='COLLOCATION'?p.surface:null,[head,setHead]=useState<LearnerItem>();if(!surface)return null;return <View style={s.section}><View style={s.tokens}>{surface.heads.map(x=><Pressable key={x.id} onPress={()=>setHead(x)} style={[s.token,head?.id===x.id&&s.on]}><Text>{x.label}</Text></Pressable>)}</View><View style={s.tokens}>{surface.collocates.map(x=><Pressable key={x.id} disabled={!head} onPress={()=>{send(p,'MATCH',{head:head!.id,collocate:x.id});setHead(undefined)}} style={[s.token,!head&&s.dim]}><Text>{x.label}</Text></Pressable>)}</View></View>}
function Reference({p}:{p:Props}){const surface=p.surface.kind==='REFERENCE_TRACE'?p.surface:null,[reference,setReference]=useState(false);if(!surface)return null;return <View style={s.section}><Pressable onPress={()=>setReference(true)} style={[s.reference,reference&&s.on]}><Text style={s.word}>{surface.reference}</Text></Pressable><Text style={s.evidence}>{surface.antecedents.map(x=><Text key={x.id} onPress={()=>reference&&send(p,'REFERENCE',x.id)} style={s.evidenceSpan}>{x.text}{' '}</Text>)}</Text></View>}
function Insertion({p}:{p:Props}){const surface=p.surface.kind==='INSERTION'?p.surface:null,[point,setPoint]=useState(surface?.placed);if(!surface)return null;return <View style={s.section}><Text style={s.candidate}>{surface.candidate}</Text><Text style={s.object}>{surface.passage}</Text>{surface.points.map(x=><Pressable key={x.id} onPress={()=>{setPoint(x.id);send(p,'PLACEMENT',x.id)}} style={[s.drop,point===x.id&&s.on]}><Text>{point===x.id?surface.candidate:x.label}</Text></Pressable>)}</View>}
function SourceTrace({p}:{p:Props}){if(p.surface.kind!=='SOURCE_TRACE')return null;return <View>{p.surface.regions.map(x=><Pressable key={x.id} onPress={()=>send(p,'EVIDENCE',x.id)} style={s.sourceRegion}><Text style={s.object}>{x.text}</Text></Pressable>)}</View>}
function TextAction({p,source,authored,focus,goal,event,label}:{p:Props;source:string;authored?:string;focus?:string;goal?:string;event:'TRANSFORM'|'RECALL'|'REPAIR'|'DEVELOP';label:string}){const[value,setValue]=useState(focus??'');return <View style={s.section}><Text style={s.object}>{source}</Text>{authored!==undefined?<Text style={s.authored}>{authored}</Text>:null}{focus?<Text style={s.focus}>{focus}</Text>:null}{goal?<Text style={s.goal}>{goal}</Text>:null}<TextInput multiline value={value} onChangeText={setValue} style={s.input}/><Action label={label} disabled={!value.trim()} onPress={()=>send(p,event,value)}/></View>}
function Action({label,onPress,disabled}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.action,disabled&&s.dim]}><Text style={s.actionText}>{label}</Text></Pressable>}
const s=StyleSheet.create({root:{gap:14},section:{gap:14},instruction:{fontSize:15,lineHeight:23,color:t.colors.ink},object:{fontSize:17,lineHeight:28,color:t.colors.ink},wrong:{paddingVertical:8,paddingHorizontal:10,backgroundColor:t.colors.dangerWash,color:t.colors.danger,fontSize:15,lineHeight:22,alignSelf:'stretch'},row:{minHeight:54,justifyContent:'center',borderBottomWidth:1,borderBottomColor:t.colors.divider},rowText:{fontSize:16,lineHeight:24,color:t.colors.ink},evidence:{fontSize:17,lineHeight:31,color:t.colors.ink},evidenceSpan:{fontSize:17,lineHeight:31},on:{backgroundColor:t.colors.amberSoft,borderColor:t.colors.focus},contrast:{borderTopWidth:1,borderTopColor:t.colors.divider},contrastRow:{minHeight:78,flexDirection:'row',alignItems:'center',gap:16,borderBottomWidth:1,borderBottomColor:t.colors.divider},word:{fontSize:17,fontWeight:'700',color:t.colors.deepWood},flex:{flex:1},meaning:{fontSize:15,color:t.colors.ink},example:{fontSize:14,color:t.colors.muted,marginTop:4},tokens:{flexDirection:'row',flexWrap:'wrap',gap:8},token:{minHeight:46,paddingHorizontal:13,justifyContent:'center',borderWidth:1,borderColor:t.colors.divider,borderRadius:12,backgroundColor:t.colors.surface},build:{minHeight:62,flexDirection:'row',flexWrap:'wrap',gap:8,borderBottomWidth:2,borderBottomColor:t.colors.dividerStrong,paddingBottom:10},built:{padding:10,backgroundColor:t.colors.amberSoft,borderRadius:10},reference:{alignSelf:'flex-start',padding:10,borderBottomWidth:2,borderBottomColor:t.colors.focus},candidate:{fontSize:17,lineHeight:27,color:t.colors.ink,padding:12,backgroundColor:t.colors.surfaceSoft},drop:{minHeight:48,justifyContent:'center',padding:10,borderTopWidth:1,borderBottomWidth:1,borderColor:t.colors.divider},sourceRegion:{paddingVertical:12,borderBottomWidth:1,borderBottomColor:t.colors.divider},authored:{fontSize:17,lineHeight:28,color:t.colors.ink,paddingVertical:16,borderTopWidth:1,borderBottomWidth:1,borderColor:t.colors.divider},focus:{fontSize:17,lineHeight:27,color:t.colors.deepWood,backgroundColor:t.colors.amberSoft,padding:8,alignSelf:'flex-start'},goal:{fontSize:14,lineHeight:21,color:t.colors.muted},input:{minHeight:108,borderBottomWidth:1,borderBottomColor:t.colors.dividerStrong,fontSize:17,lineHeight:27,color:t.colors.ink,textAlignVertical:'top'},action:{minHeight:50,borderRadius:13,backgroundColor:t.colors.deepWood,alignItems:'center',justifyContent:'center'},actionText:{fontSize:16,fontWeight:'600',color:t.colors.paper},dim:{opacity:.4}});
