import { blockRegistryV4 } from '../application/v4/blockRegistryV4';
import type { BlockSupportV4, LearningBlockDefinitionV4 } from '../domain/v4/LearningBlockV4';
import { deriveTeachingOptionsV1 } from './intelligence';
import { canonicalPckMechanismsV1 } from './pckCatalog';
import type { TeacherCompositionPieceKindV1, TeacherCompositionPlanV1, TeachingRequestV1, TeachingResponseSignalV1 } from './types';

const stable=(value:string)=>value.normalize('NFKC').toLocaleLowerCase('en').replace(/[^a-z0-9._:-]+/g,'-');
const practiceFor=(facet:string)=>blockRegistryV4.byRole('PRACTICE').find(block=>block.suitableFacets.includes(facet as never));
const assessFor=(facet:string)=>blockRegistryV4.byRole('ASSESS').find(block=>block.suitableFacets.includes(facet as never));
function piece(kind:TeacherCompositionPieceKindV1,block:LearningBlockDefinitionV4,support:BlockSupportV4,index:number,mechanismId?:string){return Object.freeze({id:`piece:${index}:${block.id}`,kind,blockId:block.id,mechanismId,learnerAction:block.learnerAction,support,advanceWhen:Object.freeze(['HELPED','SELF_REPAIRED','ASSISTED_SUCCESS','INDEPENDENT_SUCCESS'] as TeachingResponseSignalV1[]),recomposeWhen:Object.freeze(['NO_PROGRESS','CONFUSED','FAILURE'] as TeachingResponseSignalV1[]),evidenceCeiling:block.evidenceCeiling})}
export function composeTeacherPlanV1(input:{request:TeachingRequestV1;occurredAt:string;sessionId:string;mode?:'WRITING'|'TRANSLATION'|'READING'|'LANGUAGE';excludeMechanismIds?:readonly string[]}):TeacherCompositionPlanV1{const options=deriveTeachingOptionsV1(input.request),excluded=new Set(input.excludeMechanismIds??[]),mechanismId=options.preferredMechanismIds.find(id=>!excluded.has(id)),mechanism=canonicalPckMechanismsV1.find(item=>item.id===mechanismId);if(!mechanism)throw new Error('no_admissible_composition_mechanism');const teach=blockRegistryV4.get(mechanism.id);if(!teach||teach.role!=='TEACH')throw new Error('composition_requires_registered_teaching_piece');const practice=practiceFor(input.request.facet),assess=assessFor(input.request.facet),returnId=input.mode==='TRANSLATION'?'return-original-translation':'return-original-writing',returnBlock=blockRegistryV4.get(returnId)??blockRegistryV4.get('continue-source');if(!practice||!assess||!returnBlock)throw new Error('composition_piece_coverage_missing');const support=options.supportPolicy.recommendedSupport,pieces=Object.freeze([piece('REPRESENT',teach,support,0,mechanism.id),piece('GUIDED_ACTION',practice,support,1),piece('FADE_SUPPORT',practice,support==='NONE'?'NONE':'LIGHT',2),piece('FRESH_ATTEMPT',assess,'NONE',3),piece('RETURN_TO_OUTPUT',returnBlock,'NONE',4)]);return Object.freeze({schemaVersion:1,planId:`composition:${stable(input.sessionId)}:${stable(input.request.targetRef)}:${stable(input.request.facet)}:${stable(input.occurredAt)}`,targetRef:input.request.targetRef,facet:input.request.facet,pieces,cursor:0,status:'ACTIVE',excludedMechanismIds:Object.freeze([...excluded]),createdAt:input.occurredAt,updatedAt:input.occurredAt,masteryMutationAllowed:false})}
export function validateTeacherCompositionV1(plan:TeacherCompositionPlanV1){const reasons:string[]=[];if(plan.pieces.length<2||plan.pieces.length>7)reasons.push('composition_must_be_bounded');for(const item of plan.pieces){const block=blockRegistryV4.get(item.blockId);if(!block)reasons.push(`unregistered_piece:${item.blockId}`);if(item.mechanismId&&!canonicalPckMechanismsV1.some(m=>m.id===item.mechanismId))reasons.push(`unregistered_mechanism:${item.mechanismId}`);if(block&&block.evidenceCeiling!==item.evidenceCeiling)reasons.push(`evidence_ceiling_drift:${item.blockId}`)}return Object.freeze({valid:reasons.length===0,reasons:Object.freeze(reasons)})}
export function advanceTeacherCompositionV1(plan:TeacherCompositionPlanV1,signal:TeachingResponseSignalV1,occurredAt:string){const current=plan.pieces[plan.cursor];if(!current||plan.status==='STOPPED'||plan.status==='RETURN_READY')return plan;if(current.recomposeWhen.includes(signal))return Object.freeze({...plan,status:'RECOMPOSED' as const,excludedMechanismIds:Object.freeze([...new Set([...plan.excludedMechanismIds,...(current.mechanismId?[current.mechanismId]:[])])]),updatedAt:occurredAt});if(!current.advanceWhen.includes(signal))return plan;const cursor=Math.min(plan.cursor+1,plan.pieces.length-1),status=plan.pieces[cursor]?.kind==='RETURN_TO_OUTPUT'?'RETURN_READY' as const:'ACTIVE' as const;return Object.freeze({...plan,cursor,status,updatedAt:occurredAt})}
export function recomposeTeacherPlanV1(input:{prior:TeacherCompositionPlanV1;request:TeachingRequestV1;occurredAt:string;sessionId:string;mode?:'WRITING'|'TRANSLATION'|'READING'|'LANGUAGE'}){if(input.prior.status!=='RECOMPOSED')return input.prior;return composeTeacherPlanV1({...input,excludeMechanismIds:input.prior.excludedMechanismIds})}
