import type { CapabilityFacet } from '../domain/english/EnglishDomain';
import type { TeachingRequestV1 } from './types';
import { bundledPckAssetValuesV1 } from './pckAssetCatalog.generated';

export type PckAssetKindV1='TEACHING_HEURISTIC'|'MISCONCEPTION'|'CONFUSION_SET'|'LEXICAL_SENSE_CONTRAST'|'COLLOCATION_CHUNK'|'GRAMMAR_REPRESENTATION'|'CONTEXTUAL_FILL_STRATEGY'|'DISCOURSE_STRATEGY'|'READING_STRATEGY'|'EXAM_PROCEDURE'|'WRITING_FRAME'|'EXAMPLE_CONTRAST_SET'|'CONTRAINDICATION'|'RECOMPOSE_RULE';
export type PckAssetStatusV1='RAW_SOURCE'|'EXTRACTED_CANDIDATE'|'REVIEW_REQUIRED'|'VALIDATED_PCK'|'PRODUCTION_ELIGIBLE'|'REJECTED'|'DISABLED';
export type PckProvenanceKindV1='PRINTED_TEACHING_MATERIAL'|'TEACHER_HANDWRITTEN_NOTE'|'LEARNER_NOTE_MARK'|'INTERNALLY_INFERRED_PATTERN'|'CANONICAL_EOT_PCK'|'VALIDATED_EXTERNAL_RESEARCH'|'GENERATED_EXAMPLE_CONTENT';
export interface PckAssetV1{schemaVersion:1;assetId:string;kind:PckAssetKindV1;domain:'LEXICAL'|'GRAMMAR'|'WRITING'|'TRANSLATION'|'READING'|'DISCOURSE'|'EXAM';family:string;targetRefs:readonly string[];facets:readonly CapabilityFacet[];lexical?:{lemma?:string;form?:string;pos?:string;morphology?:string;senseId?:string;contextualSenseId?:string;collocationId?:string;chunkId?:string;confusionSetId?:string};learnerStates:readonly string[];compatibleMechanismIds:readonly string[];representation:string;learnerAction:string;supportCompatibility:readonly string[];contraindications:readonly string[];recomposeConditions:readonly string[];fadeConditions:readonly string[];productModes:readonly ('GENERAL'|'EXAM')[];examTiming?:{minimumEvidenceWindowSeconds?:number;readDepthEscalation?:string;stopRule?:string;skipCondition?:string;returnCondition?:string;accuracyTimeTradeoff?:string;recurringTimeFailurePattern?:string;languageAbilityInferenceAllowed:false};provenance:{sourceKind:PckProvenanceKindV1;sourceId:string;sourceVersion?:string;sourceLocation?:string;originalTextHash?:string;attribution?:string};confidence:'LOW'|'MEDIUM'|'HIGH';status:PckAssetStatusV1;productionEligible:boolean;reviewedBy?:string;reviewedAt?:string}
export interface PckAssetValidationV1{accepted:boolean;productionEligible:boolean;reasonCodes:readonly string[];asset?:PckAssetV1}
const statuses:PckAssetStatusV1[]=['RAW_SOURCE','EXTRACTED_CANDIDATE','REVIEW_REQUIRED','VALIDATED_PCK','PRODUCTION_ELIGIBLE','REJECTED','DISABLED'];
export function validatePckAssetV1(value:unknown):PckAssetValidationV1{const reasons:string[]=[];if(!value||typeof value!=='object')return{accepted:false,productionEligible:false,reasonCodes:['PCK_OBJECT_REQUIRED']};const a=value as Partial<PckAssetV1>;if(a.schemaVersion!==1)reasons.push('PCK_SCHEMA_VERSION_UNSUPPORTED');if(!a.assetId?.trim())reasons.push('PCK_ASSET_ID_REQUIRED');if(!a.kind)reasons.push('PCK_KIND_REQUIRED');if(!a.domain)reasons.push('PCK_DOMAIN_REQUIRED');if(!a.family?.trim())reasons.push('PCK_FAMILY_REQUIRED');if(!a.representation?.trim()||!a.learnerAction?.trim())reasons.push('PCK_REPRESENTATION_AND_ACTION_REQUIRED');if(!Array.isArray(a.facets)||!a.facets.length)reasons.push('PCK_FACET_REQUIRED');if(!Array.isArray(a.compatibleMechanismIds)||!a.compatibleMechanismIds.length)reasons.push('PCK_MECHANISM_COMPATIBILITY_REQUIRED');if(!a.provenance?.sourceKind||!a.provenance.sourceId?.trim())reasons.push('PCK_PROVENANCE_REQUIRED');if(!a.status||!statuses.includes(a.status))reasons.push('PCK_STATUS_INVALID');if(a.kind==='LEXICAL_SENSE_CONTRAST'&&!a.lexical?.senseId&&!a.lexical?.contextualSenseId)reasons.push('PCK_EXACT_SENSE_REQUIRED');if(a.kind==='EXAM_PROCEDURE'&&a.examTiming?.languageAbilityInferenceAllowed!==false)reasons.push('PCK_EXAM_PROCEDURE_CANNOT_INFER_LANGUAGE_ABILITY');const eligible=a.status==='PRODUCTION_ELIGIBLE'&&a.productionEligible===true&&a.confidence==='HIGH'&&Boolean(a.reviewedBy&&a.reviewedAt);if(a.productionEligible&&!eligible)reasons.push('PCK_PRODUCTION_ELIGIBILITY_REQUIREMENTS_NOT_MET');return{accepted:reasons.length===0,productionEligible:eligible&&reasons.length===0,reasonCodes:Object.freeze(reasons),asset:reasons.length?undefined:Object.freeze(a as PckAssetV1)}}
export function ingestPckAssetsV1(values:readonly unknown[]){const validations=values.map(validatePckAssetV1),seen=new Set<string>(),accepted:PckAssetV1[]=[],rejected:{index:number;reasonCodes:readonly string[]}[]=[];validations.forEach((result,index)=>{if(!result.accepted||!result.asset){rejected.push({index,reasonCodes:result.reasonCodes});return}if(seen.has(result.asset.assetId)){rejected.push({index,reasonCodes:['PCK_DUPLICATE_ASSET_ID']});return}seen.add(result.asset.assetId);accepted.push(result.asset)});return Object.freeze({accepted:Object.freeze(accepted),productionEligible:Object.freeze(accepted.filter(asset=>validatePckAssetV1(asset).productionEligible)),rejected:Object.freeze(rejected)})}
export function bundledPckAssetsV1(){return ingestPckAssetsV1(bundledPckAssetValuesV1)}
export function eligiblePckAssetsForRequestV1(assets:readonly PckAssetV1[],input:{request:TeachingRequestV1;productMode:'GENERAL'|'EXAM';senseId?:string}){
  return Object.freeze(assets.filter(asset=>
    validatePckAssetV1(asset).productionEligible
    &&asset.productModes.includes(input.productMode)
    &&(asset.targetRefs.length===0||asset.targetRefs.includes(input.request.targetRef))
    &&asset.facets.includes(input.request.facet)
    &&(!asset.lexical?.senseId||asset.lexical.senseId===input.senseId)
    &&asset.compatibleMechanismIds.some(id=>!input.request.recentTreatment.some(treatment=>
      treatment.mechanismId===id&&(treatment.outcome==='FAILURE'||treatment.responseSignal==='CONFUSED'||treatment.responseSignal==='NO_PROGRESS')
    ))
  ));
}
