import type { PckMechanismV1 } from './types';

const requirements:Record<string,PckMechanismV1['contentRequirements']>={
  'meaning-representation':['SENSE_EVIDENCE','EXAMPLE'],'form-contrast':['SENSE_EVIDENCE','EXAMPLE'],'morphology-decomposition':['MORPHOLOGY_EVIDENCE'],
  'grammar-role-map':['CURATED_SEMANTIC_TASK'],'chunk-as-unit':['EXAMPLE'],'collocation-network':['EXAMPLE'],'worked-transformation':['CURATED_SEMANTIC_TASK'],
};
const m=(value:Omit<PckMechanismV1,'contentRequirements'|'supportProgression'|'answerExposureConstraint'> & {contentRequirements?:PckMechanismV1['contentRequirements'];supportProgression?:PckMechanismV1['supportProgression'];answerExposureConstraint?:PckMechanismV1['answerExposureConstraint']})=>Object.freeze({...value,contentRequirements:Object.freeze([...(value.contentRequirements??requirements[value.id]??[])]),supportProgression:Object.freeze([...(value.supportProgression??['mark evidence with guidance','remove labels','require learner reconstruction'])]),answerExposureConstraint:value.answerExposureConstraint??'NO_DIRECT_ANSWER',suitableAreas:Object.freeze([...value.suitableAreas]),suitableKinds:Object.freeze([...value.suitableKinds]),suitableFacets:Object.freeze([...value.suitableFacets]),suitableBottlenecks:Object.freeze([...value.suitableBottlenecks]),primitives:Object.freeze([...value.primitives]),inappropriateWhen:Object.freeze([...value.inappropriateWhen]),expectedResponseSignals:Object.freeze([...value.expectedResponseSignals]),fadeConditions:Object.freeze([...value.fadeConditions]),replanConditions:Object.freeze([...value.replanConditions]),stopConditions:Object.freeze([...value.stopConditions])});

const readingMechanism=(id:string,label:string,facet:PckMechanismV1['suitableFacets'][number],action:string,applicability:string,inappropriateWhen:string[])=>m({id,label,suitableAreas:['READING'],suitableKinds:['READING_CAPABILITY'],suitableFacets:[facet],suitableBottlenecks:['REPRESENTATION','SELECTION'],primitives:['MARK','SELECT','EXPLAIN'],requiredLearnerAction:action,applicability,inappropriateWhen,expectedResponseSignals:['HELPED','SELF_REPAIRED'],fadeConditions:['learner identifies and uses the relation without visible labels'],replanConditions:['selected evidence does not support the learner explanation','a different reading bottleneck is better supported'],stopConditions:['learner completes the evidence operation without answer reveal'],contentRequirements:['CURATED_SEMANTIC_TASK'],supportProgression:['Teacher bounds the evidence region','learner marks relations with labels','labels fade and learner reconstructs the reasoning'],answerExposureConstraint:'NO_DIRECT_ANSWER'});
const readingPckMechanismsV1=Object.freeze([
 readingMechanism('inference-evidence-bridge','Inference Evidence Bridge','SELECTION','select textual premises and state the bridge to the conclusion','an inference is unsupported or its bridge is missing',['no passage evidence is available','the failure is only stem decoding']),
 readingMechanism('reference-chain','Reference Chain','FORM_TO_MEANING','mark antecedent and reference links across the passage','reference continuity is unresolved',['the referent is already independently established']),
 readingMechanism('text-structure-map','Text Structure Map','SELECTION','label the function and relation of passage sections','global text organization affects the answer',['only a local word sense is unresolved']),
 readingMechanism('paragraph-function-map','Paragraph Function Map','SELECTION','state what each paragraph contributes to the author claim','paragraph role is confused with topic similarity',['the task contains no paragraph structure']),
 readingMechanism('sentence-insertion-continuity','Sentence Insertion Continuity','SELECTION','test backward and forward links at candidate insertion points','sentence placement requires two-sided cohesion',['only one side of the insertion context is available']),
 readingMechanism('distractor-evidence-contrast','Distractor Evidence Contrast','SELECTION','contrast each option with an explicit supporting or contradicting span','a plausible distractor survives without evidence checking',['options or authorized task structure are unavailable']),
 readingMechanism('claim-strength-contrast','Claim Strength Contrast','SELECTION','compare claim strength with what the passage actually licenses','the learner overstates or understates a conclusion',['the problem is reference resolution rather than inference strength']),
 readingMechanism('cross-representation-evidence-integration','Cross-representation Evidence Integration','SELECTION','map each claim to evidence from text and the accompanying representation','mixed-format sources must be integrated',['one or more referenced representations are missing'])
]);

export const canonicalPckMechanismsV1:readonly PckMechanismV1[]=Object.freeze([
  ...readingPckMechanismsV1,
  m({id:'meaning-representation',label:'Meaning Representation',suitableAreas:['LEXICAL','MEANING_ENCODING','TRANSLATION'],suitableKinds:['LEXEME','SENSE','MEANING_INTENT','TRANSLATION_CAPABILITY'],suitableFacets:['FORM_TO_MEANING','SENSE_DISCRIMINATION','FORM_MEANING_MAPPING'],suitableBottlenecks:['REPRESENTATION','MEANING_FORM_MAPPING'],primitives:['COMPARE','EXPLAIN'],requiredLearnerAction:'differentiate the intended meaning from nearby alternatives',applicability:'meaning or sense representation is missing or unstable',inappropriateWhen:['current evidence points primarily to retrieval or assembly','learner already demonstrates the meaning distinction independently'],expectedResponseSignals:['HELPED','SELF_REPAIRED'],fadeConditions:['learner can identify the intended meaning without the representation'],replanConditions:['meaning representation produces no progress','learner reports the distinction is already clear'],stopConditions:['meaning distinction is usable and learner is ready to produce']}),
  m({id:'grammar-role-map',label:'Grammar Role Map',suitableAreas:['GRAMMAR','WRITING','TRANSLATION','MEANING_ENCODING'],suitableKinds:['GRAMMAR_CONSTRUCTION','WRITING_CAPABILITY','TRANSLATION_CAPABILITY','MEANING_INTENT','PHRASE_FRAME'],suitableFacets:['FORM_MEANING_MAPPING','CONSTRUCTION','CONTROLLED_PRODUCTION','FREE_PRODUCTION'],suitableBottlenecks:['MEANING_FORM_MAPPING','LEXICAL_SLOT_FILLING','FORM_ASSEMBLY'],primitives:['MARK','CONSTRUCT','EXPLAIN'],requiredLearnerAction:'map semantic roles to construction slots before rebuilding the expression',applicability:'the learner has relevant meaning but role/slot structure is unstable',inappropriateWhen:['the main bottleneck is simple lexical retrieval','the learner already assembles the construction but fails to select it in open choice'],expectedResponseSignals:['HELPED','SELF_REPAIRED'],fadeConditions:['roles can be reconstructed without visible labels'],replanConditions:['role mapping is understood but authentic deployment still fails','learner cannot identify the intended meaning relation'],stopConditions:['learner can assemble the target from meaning']}),
  m({id:'form-contrast',label:'Form–Meaning Mapping',suitableAreas:['GRAMMAR','MEANING_ENCODING','TRANSLATION','READING'],suitableKinds:['GRAMMAR_CONSTRUCTION','MEANING_INTENT','TRANSLATION_CAPABILITY','PHRASE_FRAME','READING_CAPABILITY'],suitableFacets:['FORM_MEANING_MAPPING','SELECTION','CONTEXTUAL_APPROPRIACY'],suitableBottlenecks:['MEANING_FORM_MAPPING','SELECTION'],primitives:['COMPARE','SELECT'],requiredLearnerAction:'compare alternatives and identify the meaning feature that changes the choice',applicability:'multiple forms are known but their meaning/function boundary is unstable',inappropriateWhen:['only orthographic form is unstable','a single construction cannot yet be assembled at all'],expectedResponseSignals:['HELPED','SELF_REPAIRED'],fadeConditions:['learner can select from meaning without labeled contrast'],replanConditions:['contrast is recognized but target cannot be assembled'],stopConditions:['meaning-driven selection is stable enough for production']}),
  m({id:'l1-collision',label:'L1 Collision',suitableAreas:['GRAMMAR','TRANSLATION','MEANING_ENCODING'],suitableKinds:['GRAMMAR_CONSTRUCTION','TRANSLATION_CAPABILITY','MEANING_INTENT'],suitableFacets:['FORM_MEANING_MAPPING','SELECTION','CONSTRUCTION','FREE_PRODUCTION'],suitableBottlenecks:['COMPETING_REPRESENTATION','MEANING_FORM_MAPPING'],primitives:['COMPARE','EXPLAIN'],requiredLearnerAction:'compare the learner-used mapping with a viable English organization',applicability:'repeated evidence or an explicit competing hypothesis supports an L1-shaped representation',inappropriateWhen:['L1 influence is inferred from a single error','a valid alternative is merely different from a preferred wording'],expectedResponseSignals:['HELPED','SELF_REPAIRED'],fadeConditions:['learner selects the English organization without the L1 contrast'],replanConditions:['no evidence supports the L1 hypothesis','contrast increases confusion'],stopConditions:['competing representation no longer drives output across opportunities']}),
  m({id:'chunk-as-unit',label:'Chunk as a Unit',suitableAreas:['FORMULAIC','LEXICAL','WRITING','TRANSLATION'],suitableKinds:['CHUNK','COLLOCATION','PHRASE_FRAME','LEXEME','WRITING_CAPABILITY','TRANSLATION_CAPABILITY'],suitableFacets:['MEANING_TO_RETRIEVAL','COLLOCATION','LEXICAL_SYNTACTIC_BEHAVIOR','CONTROLLED_PRODUCTION','FREE_PRODUCTION'],suitableBottlenecks:['RETRIEVAL','LEXICAL_SLOT_FILLING','FORM_ASSEMBLY'],primitives:['MARK','RECALL','CONSTRUCT'],requiredLearnerAction:'retrieve and manipulate the multiword unit as a production resource',applicability:'component knowledge exists but a recurring multiword unit is not retrieved or assembled efficiently',inappropriateWhen:['the issue is a whole-text organization problem','the expression is not supported by the target/source context'],expectedResponseSignals:['HELPED','ASSISTED_SUCCESS'],fadeConditions:['whole-unit retrieval survives removal of visible chunk parts'],replanConditions:['learner retrieves the unit but fills slots inappropriately'],stopConditions:['chunk can be retrieved and adapted without model wording']}),
  m({id:'collocation-network',label:'Collocation Network',suitableAreas:['FORMULAIC','LEXICAL','WRITING','TRANSLATION'],suitableKinds:['COLLOCATION','CHUNK','LEXEME','SENSE','WRITING_CAPABILITY','TRANSLATION_CAPABILITY'],suitableFacets:['COLLOCATION','CONTEXTUAL_APPROPRIACY','LEXICAL_SYNTACTIC_BEHAVIOR'],suitableBottlenecks:['SELECTION','LEXICAL_SLOT_FILLING'],primitives:['MATCH','COMPARE','SELECT'],requiredLearnerAction:'distinguish compatible lexical partners and choose one for the intended context',applicability:'word meanings are available but natural lexical partnership is unstable',inappropriateWhen:['the error is purely spelling','the learner has not yet identified the intended meaning'],expectedResponseSignals:['HELPED','ASSISTED_SUCCESS'],fadeConditions:['collocate can be selected without option lists'],replanConditions:['learner knows partners but cannot retrieve them in production'],stopConditions:['collocation is selected and produced in a new lexical frame']}),
  m({id:'sentence-anatomy',label:'Sentence Anatomy',suitableAreas:['WRITING','TRANSLATION','MEANING_ENCODING'],suitableKinds:['WRITING_CAPABILITY','TRANSLATION_CAPABILITY','MEANING_INTENT','GRAMMAR_CONSTRUCTION'],suitableFacets:['FORM_MEANING_MAPPING','CONSTRUCTION','FREE_PRODUCTION'],suitableBottlenecks:['REPRESENTATION','MEANING_FORM_MAPPING','FORM_ASSEMBLY','DEPLOYMENT_UNDER_LOAD'],primitives:['MARK','PLAN','CONSTRUCT','EXPLAIN'],requiredLearnerAction:'segment intended meaning into clause roles before producing the sentence',applicability:'the learner owns the idea but sentence realization collapses or overload obscures the clause structure',inappropriateWhen:['only one local lexical item is inaccessible','teacher would have to invent the learner idea'],expectedResponseSignals:['HELPED','SELF_REPAIRED'],fadeConditions:['learner can segment and realize the sentence without the map'],replanConditions:['segmentation is clear but lexical retrieval remains the bottleneck'],stopConditions:['learner-owned meaning survives reintegration into the original task']}),
  m({id:'reformulation-map',label:'Reformulation Map',suitableAreas:['WRITING','TRANSLATION','FORMULAIC'],suitableKinds:['WRITING_CAPABILITY','TRANSLATION_CAPABILITY','CHUNK','PHRASE_FRAME'],suitableFacets:['SELECTION','CONTEXTUAL_APPROPRIACY','FREE_PRODUCTION','FORM_MEANING_MAPPING'],suitableBottlenecks:['SELECTION','OPPORTUNITY_RECOGNITION','DEPLOYMENT_UNDER_LOAD'],primitives:['COMPARE','REPAIR','PRODUCE'],requiredLearnerAction:'preserve the intended meaning while choosing among multiple valid realizations',applicability:'learner is stuck on one wording route or needs to distinguish valid alternatives',inappropriateWhen:['a valid learner alternative is already adequate and no learning value remains','the learner does not yet control source meaning'],expectedResponseSignals:['HELPED','SELF_REPAIRED'],fadeConditions:['learner can generate an alternative without supplied wording'],replanConditions:['alternatives increase lexical overload','meaning changes during reformulation'],stopConditions:['learner can escape the dead end with learner-owned wording']}),
  m({id:'cohesion-relation-map',label:'Cohesion / Relation Map',suitableAreas:['WRITING','DISCOURSE','TRANSLATION'],suitableKinds:['WRITING_CAPABILITY','DISCOURSE_MOVE','TRANSLATION_CAPABILITY'],suitableFacets:['FORM_MEANING_MAPPING','SELECTION','CONSTRUCTION','FREE_PRODUCTION'],suitableBottlenecks:['OPPORTUNITY_RECOGNITION','MEANING_FORM_MAPPING','SELECTION'],primitives:['MATCH','PLAN','SELECT','EXPLAIN'],requiredLearnerAction:'identify the relation between ideas before selecting language',applicability:'ideas exist but relation recognition or language selection is unstable',inappropriateWhen:['the learner lacks the underlying ideas','a linker list would replace rather than support relation reasoning'],expectedResponseSignals:['HELPED','SELF_REPAIRED'],fadeConditions:['relation is recognized without labels and language is independently selected'],replanConditions:['relation is clear but form assembly fails'],stopConditions:['learner can connect new ideas from meaning rather than a named grammar cue']}),
  m({id:'task-requirement-map',label:'Task Requirement Map',suitableAreas:['WRITING'],suitableKinds:['WRITING_CAPABILITY'],suitableFacets:['CONTEXTUAL_APPROPRIACY','FREE_PRODUCTION'],suitableBottlenecks:['OPPORTUNITY_RECOGNITION','SELECTION'],primitives:['MATCH','PLAN','EXPLAIN'],requiredLearnerAction:'map each prompt requirement to the learner own text and identify the first missing requirement',applicability:'the response is linguistically plausible but may not fulfill all explicit task requirements',inappropriateWhen:['task requirements are unavailable or ambiguous','the primary bottleneck is sentence-level language realization rather than task fulfillment'],expectedResponseSignals:['HELPED','SELF_REPAIRED'],fadeConditions:['learner can independently check prompt coverage before drafting or revising'],replanConditions:['all requirements are present but development remains thin'],stopConditions:['the learner can identify and repair the missing requirement without supplied content']}),
  m({id:'idea-development-ladder',label:'Idea Development Ladder',suitableAreas:['WRITING'],suitableKinds:['WRITING_CAPABILITY'],suitableFacets:['FREE_PRODUCTION'],suitableBottlenecks:['OPPORTUNITY_RECOGNITION','DEPLOYMENT_UNDER_LOAD'],primitives:['PLAN','CONSTRUCT','EXPLAIN'],requiredLearnerAction:'extend one learner-owned claim by adding the next needed why, mechanism, example, or link-back step',applicability:'the task is answered but reasoning is thin, repetitive, or unsupported',inappropriateWhen:['the prompt requirement itself is missing','Teacher would need to invent a new idea for the learner'],expectedResponseSignals:['HELPED','SELF_REPAIRED'],fadeConditions:['learner can extend a claim without the ladder'],replanConditions:['development exists but organization or language realization becomes the new bottleneck'],stopConditions:['the learner can add a relevant development move in the original writing']}),
  m({id:'worked-transformation',label:'Worked Transformation',suitableAreas:['GRAMMAR','WRITING','TRANSLATION','MEANING_ENCODING'],suitableKinds:['GRAMMAR_CONSTRUCTION','WRITING_CAPABILITY','TRANSLATION_CAPABILITY','MEANING_INTENT'],suitableFacets:['FORM_MEANING_MAPPING','CONSTRUCTION','CONTROLLED_PRODUCTION','FREE_PRODUCTION'],suitableBottlenecks:['FORM_ASSEMBLY','MEANING_FORM_MAPPING','DEPLOYMENT_UNDER_LOAD'],primitives:['EXPLAIN','CONSTRUCT','REPAIR'],requiredLearnerAction:'trace a transformation, then reproduce the operation with fading support',applicability:'lower-control learner needs a concrete worked path from current output to a valid construction',inappropriateWhen:['strong independent history makes a worked example redundant','the worked answer would contaminate an imminent independent check'],expectedResponseSignals:['HELPED','ASSISTED_SUCCESS'],fadeConditions:['worked stages can be removed and learner reconstructs the transformation'],replanConditions:['learner copies the model without reconstructing the operation'],stopConditions:['the transformation can be independently reproduced']}),
  m({id:'morphology-decomposition',label:'Morphology Decomposition Map',suitableAreas:['LEXICAL'],suitableKinds:['LEXEME','WORD_FORM','MORPHOLOGICAL_PATTERN'],suitableFacets:['MORPHOLOGY','ORTHOGRAPHIC_PRODUCTION'],suitableBottlenecks:['REPRESENTATION','FORM_ASSEMBLY'],primitives:['MARK','EXPLAIN','CONSTRUCT'],requiredLearnerAction:'identify meaningful form parts and rebuild the target form from them',applicability:'morphological structure is relevant to the observed written-form problem',inappropriateWhen:['meaning retrieval is the primary bottleneck','morphology is not part of the authorized target/facet'],expectedResponseSignals:['HELPED','SELF_REPAIRED'],fadeConditions:['learner rebuilds the form without visible morpheme segmentation'],replanConditions:['segmentation is understood but spelling retrieval remains unstable'],stopConditions:['morphological relation supports independent form production']}),
  m({id:'meaning-segmentation',label:'Meaning Segmentation Map',suitableAreas:['TRANSLATION','MEANING_ENCODING'],suitableKinds:['TRANSLATION_CAPABILITY','MEANING_INTENT'],suitableFacets:['FORM_MEANING_MAPPING','SELECTION','CONSTRUCTION'],suitableBottlenecks:['REPRESENTATION','MEANING_FORM_MAPPING','DEPLOYMENT_UNDER_LOAD'],primitives:['PLAN','MARK','EXPLAIN'],requiredLearnerAction:'segment source meaning into learner-controlled units before choosing English realizations',applicability:'source meaning is too bundled or unclear to realize directly in English',inappropriateWhen:['source meaning is already stable and the bottleneck is only lexical retrieval','Teacher would replace learner meaning with a new interpretation'],expectedResponseSignals:['HELPED','SELF_REPAIRED'],fadeConditions:['learner can segment a new source without the map'],replanConditions:['segmentation is stable but English resource retrieval fails'],stopConditions:['learner can preserve and organize source meaning for production']}),
  m({id:'alternative-translation-compare',label:'Alternative Translation Comparison',suitableAreas:['TRANSLATION','MEANING_ENCODING'],suitableKinds:['TRANSLATION_CAPABILITY','MEANING_INTENT'],suitableFacets:['FORM_MEANING_MAPPING','SELECTION','CONTEXTUAL_APPROPRIACY'],suitableBottlenecks:['SELECTION','MEANING_FORM_MAPPING'],primitives:['COMPARE','SELECT','EXPLAIN'],requiredLearnerAction:'compare meaning-preserving alternatives and identify why more than one realization is valid',applicability:'learner needs to distinguish valid English realizations without treating one reference answer as truth',inappropriateWhen:['source meaning is not yet established','the learner already produced an adequate alternative and no contrast is needed'],expectedResponseSignals:['HELPED','SELF_REPAIRED'],fadeConditions:['learner can generate/select a valid alternative without the comparison set'],replanConditions:['comparison distracts from a more basic source-meaning problem'],stopConditions:['learner can preserve meaning while selecting a viable English realization']}),
]);

export const establishedTeachingRepresentationIdsV1=Object.freeze(['meaning-representation','grammar-role-map','form-contrast','l1-collision','chunk-as-unit','collocation-network','sentence-anatomy','reformulation-map','cohesion-relation-map','worked-transformation'] as const);

export function pckMechanismByIdV1(id:string):PckMechanismV1|undefined{return canonicalPckMechanismsV1.find(item=>item.id===id)}
