export type CapabilityReleaseV1='V1'|'FUTURE';
export type CapabilityImplementationStatusV1='NOT_AUDITED'|'CONTRACT_ONLY'|'FIRST_PASS'|'BLOCKED_EXTERNAL';
export interface FineGrainedCapabilityV1 {id:string;subsystem:string;name:string;release:CapabilityReleaseV1;implementation_status:CapabilityImplementationStatusV1;}
const c=(subsystem:string,id:string,name:string,release:CapabilityReleaseV1='V1',implementation_status:CapabilityImplementationStatusV1='NOT_AUDITED'):FineGrainedCapabilityV1=>({id:`${subsystem}.${id}`,subsystem,name,release,implementation_status});
const cA=(id:string,name:string,release:CapabilityReleaseV1='V1')=>c('A',id,name,release,'FIRST_PASS');
const cB=(id:string,name:string,release:CapabilityReleaseV1='V1')=>c('B',id,name,release,'FIRST_PASS');
const cC=(id:string,name:string,release:CapabilityReleaseV1='V1')=>c('C',id,name,release,'FIRST_PASS');
const cD=(id:string,name:string,release:CapabilityReleaseV1='V1')=>c('D',id,name,release,'FIRST_PASS');
const cE=(id:string,name:string,release:CapabilityReleaseV1='V1')=>c('E',id,name,release,'FIRST_PASS');
const cF=(id:string,name:string,release:CapabilityReleaseV1='V1')=>c('F',id,name,release,'FIRST_PASS');
const cG=(id:string,name:string,status:CapabilityImplementationStatusV1='CONTRACT_ONLY',release:CapabilityReleaseV1='V1')=>c('G',id,name,release,status);
const cH=(id:string,name:string,status:CapabilityImplementationStatusV1='CONTRACT_ONLY',release:CapabilityReleaseV1='V1')=>c('H',id,name,release,status);
const cI=(id:string,name:string,status:CapabilityImplementationStatusV1='CONTRACT_ONLY',release:CapabilityReleaseV1='V1')=>c('I',id,name,release,status);
const cK=(id:string,name:string,status:CapabilityImplementationStatusV1='CONTRACT_ONLY',release:CapabilityReleaseV1='V1')=>c('K',id,name,release,status);
const cL=(id:string,name:string,status:CapabilityImplementationStatusV1='CONTRACT_ONLY',release:CapabilityReleaseV1='V1')=>c('L',id,name,release,status);
const cM=(id:string,name:string,status:CapabilityImplementationStatusV1='CONTRACT_ONLY',release:CapabilityReleaseV1='V1')=>c('M',id,name,release,status);
const cN=(id:string,name:string,status:CapabilityImplementationStatusV1='CONTRACT_ONLY',release:CapabilityReleaseV1='V1')=>c('N',id,name,release,status);
const cO=(id:string,name:string,status:CapabilityImplementationStatusV1='CONTRACT_ONLY',release:CapabilityReleaseV1='V1')=>c('O',id,name,release,status);
const cQ=(id:string,name:string,status:CapabilityImplementationStatusV1='CONTRACT_ONLY',release:CapabilityReleaseV1='V1')=>c('Q',id,name,release,status);
const cR=(id:string,name:string,status:CapabilityImplementationStatusV1='CONTRACT_ONLY',release:CapabilityReleaseV1='V1')=>c('R',id,name,release,status);
const cS=(id:string,name:string,status:CapabilityImplementationStatusV1='CONTRACT_ONLY',release:CapabilityReleaseV1='V1')=>c('S',id,name,release,status);
const cT=(id:string,name:string,status:CapabilityImplementationStatusV1='CONTRACT_ONLY',release:CapabilityReleaseV1='V1')=>c('T',id,name,release,status);
const cU=(id:string,name:string,release:CapabilityReleaseV1='V1')=>c('U',id,name,release,'FIRST_PASS');
export const eotFineGrainedCapabilityCatalogV1:readonly FineGrainedCapabilityV1[]=Object.freeze([
  cA('identity',"Learner identity"),
  cA('goals',"Long-term and current learning goals"),
  cA('learning-purpose',"Learning purpose"),
  cA('use-context',"Real use context"),
  cA('current-priority',"Current learner priority override"),
  cA('study-time',"Study-time availability"),
  cA('session-duration',"Preferred/current session duration"),
  cA('general-entitlement',"General product entitlement"),
  cA('exam-entitlement',"Exam product entitlement"),
  cA('exam-scope',"Exam scope"),
  cA('exam-deadline',"Exam deadline"),
  cA('exam-rubric',"Exam rubric/scoring context"),
  c('A','product-plan',"Product/plan identity",'V1','CONTRACT_ONLY'),
  c('A','trial-access',"Trial/access state",'V1','CONTRACT_ONLY'),
  c('A','subscription-boundary',"Subscription/payment boundary",'V1','CONTRACT_ONLY'),
  cA('context-provenance',"Context provenance"),
  cA('context-update',"Context update rules"),
  cA('active-experience',"Current active General/Exam experience"),
  cA('onboarding-context',"Onboarding-derived product context"),
  cA('runtime-projection',"Product context projection for curriculum/Teacher runtime"),
  cA('persistence',"Versioned per-learner product-context persistence and migration"),
  cA('account-access-rules',"Account/product access decision rules"),
  cB('word',"Lexical word"),
  cB('sense',"Lexical sense"),
  cB('form',"Word form"),
  cB('spelling',"Spelling"),
  cB('morphology',"Morphology"),
  c('B','chunk',"Chunks",'V1','CONTRACT_ONLY'),
  c('B','collocation',"Collocations",'V1','CONTRACT_ONLY'),
  cB('phrase-frame',"Phrases and reusable frames"),
  cB('register',"Register"),
  cB('grammar-construction',"Grammar/constructions"),
  cB('meaning-encoding',"Meaning-to-English encoding"),
  cB('writing-graph',"Writing capability graph"),
  cB('translation-graph',"Translation capability graph"),
  cB('reading-graph',"Reading capability graph"),
  cB('retrieval',"Retrieval dimension"),
  cB('production',"Production dimension"),
  cB('transfer',"Transfer dimension"),
  cB('stability',"Stability/retention dimension"),
  cB('support-dependence',"Support dependence"),
  cB('load-recurrence',"Load/recurrence conditions"),
  cB('prerequisite-edges',"Prerequisite/dependency edges"),
  cB('target-identity',"Stable target identity and alias resolution"),
  cB('semantic-intent',"Meaning-intent nodes and realization mapping"),
  cB('relation-semantics',"Typed semantic/contrast/alternative relation semantics"),
  cB('condition-schema',"Capability observation condition schema"),
  cB('graph-governance',"Canonical graph provenance/version/validation"),
  cB('graph-query',"Canonical graph query/traversal port"),
  cC('original-artifact',"Immutable original artifact"),
  cC('observation',"Observation"),
  cC('evidence-candidate',"Evidence candidate"),
  cC('canonical-event',"Canonical evidence event"),
  cC('provenance',"Evidence provenance"),
  cC('assistance-contamination',"Assistance/support contamination"),
  cC('independent-proof',"Independent production evidence"),
  cC('transfer-proof',"Transfer evidence"),
  cC('delayed-proof',"Delayed evidence"),
  cC('negative-evidence',"Negative evidence rules"),
  cC('unknown',"Unknown handling"),
  cC('hypotheses',"Competing hypotheses"),
  cC('projection',"Learner-state projection"),
  cC('dedup',"Evidence deduplication"),
  cC('idempotency',"Event idempotency"),
  cC('uncertainty',"Uncertainty representation"),
  cC('condition-reliability',"Condition reliability"),
  cD('goal-policy',"Goal policy",'V1'),
  cD('coverage-governor',"Coverage governor",'V1'),
  cD('prerequisites',"Prerequisite readiness",'V1'),
  cD('ready-frontier',"Ready frontier",'V1'),
  cD('reinforcement-frontier',"Reinforcement frontier",'V1'),
  cD('blocked-territory',"Unknown/blocked territory",'V1'),
  cD('allocation',"Learning allocation",'V1'),
  cD('general-allocation',"General allocation",'V1'),
  cD('exam-allocation',"Exam allocation",'V1'),
  cD('spacing',"Spacing",'V1'),
  cD('reencounter',"Re-encounter planning",'V1'),
  cD('retention-need',"Retention need",'V1'),
  cD('transfer-need',"Transfer need",'V1'),
  cD('time-architecture',"5/10/20/30/60 time architecture",'V1'),
  cD('today-plan',"Today planning",'V1'),
  cD('lesson-plan',"Lesson planning",'V1'),
  cD('priority-override',"Learner priority override reconciliation",'V1'),
  cE('context-compiler',"Pedagogical Context Compiler"),
  cE('decision-point',"Pedagogical Decision Point"),
  cE('observation-input',"Observation to decision input"),
  cE('hypothesis-use',"Hypothesis-aware diagnosis"),
  cE('lowest-entry-point',"Lowest useful instructional entry point"),
  cE('legal-actions',"Legal Teacher action set"),
  cE('correct-repair-teach',"CORRECT / REPAIR / TEACH routing"),
  cE('none-vs-intervene',"NONE vs intervention decision"),
  cE('support-policy',"Support Policy"),
  cE('help-before-failure',"Help before failure"),
  cE('support-qualification',"Support qualification into evidence"),
  cE('mechanism-selection',"Teaching mechanism selection"),
  cE('success-transition',"Success transition"),
  cE('partial-transition',"Partial-success transition"),
  cE('failure-transition',"Failure transition"),
  cE('representation-change',"Representation change"),
  cE('bottom-out',"Bottom-out / prerequisite move"),
  cE('support-fade',"Support fading"),
  cE('return-to-task',"Return to meaningful task"),
  cE('stop-exit',"Stop/exit conditions"),
  cE('decision-validation',"Qualified decision validation"),
  cE('deterministic-fallback',"Deterministic provider fallback"),
  cE('decision-provenance',"Teacher decision provenance"),
  cE('treatment-response',"Treatment-response history hook"),
  cE('idempotency-resume',"Decision idempotency and resume"),
  cE('experience-contract',"Teacher Decision to Experience Contract boundary"),
  cF('mode-registry',"Teaching Mode registry"),
  cF('pck-metadata',"Pedagogical content knowledge metadata"),
  cF('entry-conditions',"Entry conditions"),
  cF('inappropriate-cases',"Inappropriate-use rules"),
  cF('teaching-moves',"Teaching Moves"),
  cF('cognitive-action',"Required learner cognitive action"),
  cF('content-binding',"Content bindings"),
  cF('reveal-rules',"Reveal rules"),
  cF('evaluation-scope',"Evaluation scope"),
  cF('evidence-implication',"Evidence implications"),
  cF('accessibility-contract',"Mechanism accessibility contract"),
  cF('primitive-select',"Select primitive"),
  cF('primitive-match',"Match primitive"),
  cF('primitive-order',"Order primitive"),
  cF('primitive-mark',"Mark primitive"),
  cF('primitive-complete',"Complete primitive"),
  cF('primitive-recall',"Recall/type primitive"),
  cF('primitive-construct',"Construct primitive"),
  cF('primitive-produce',"Produce primitive"),
  cF('primitive-repair',"Repair primitive"),
  cF('primitive-compare',"Compare primitive"),
  cF('primitive-explain',"Explain primitive"),
  cF('primitive-plan',"Plan primitive"),
  cF('primitive-full-task',"Full-task primitive"),
  cG('prompt-generation',"Prompt generation",'FIRST_PASS'),
  cG('examples',"Examples",'CONTRACT_ONLY'),
  cG('counterexamples',"Counterexamples",'CONTRACT_ONLY'),
  cG('distractors',"Distractors",'CONTRACT_ONLY'),
  cG('fresh-task',"Fresh tasks",'FIRST_PASS'),
  cG('changed-context',"Changed-context tasks",'FIRST_PASS'),
  cG('difficulty',"Difficulty control",'CONTRACT_ONLY'),
  cG('load',"Cognitive load control",'CONTRACT_ONLY'),
  cG('semantic-validity',"Semantic validity",'FIRST_PASS'),
  cG('valid-alternatives',"Valid alternative handling",'FIRST_PASS'),
  cG('content-safety',"Content safety",'CONTRACT_ONLY'),
  cG('context-relevance',"Context relevance",'FIRST_PASS'),
  cG('generated-validation',"Generated-content validation",'FIRST_PASS'),
  cG('content-packs',"Content/material packs",'FIRST_PASS'),
  cH('purpose-audience-genre',"Purpose/audience/genre",'CONTRACT_ONLY'),
  cH('idea-generation',"Idea generation",'CONTRACT_ONLY'),
  cH('reasoning-depth',"Reasoning depth",'CONTRACT_ONLY'),
  cH('planning',"Planning",'CONTRACT_ONLY'),
  cH('organization',"Organization",'CONTRACT_ONLY'),
  cH('cohesion',"Cohesion",'CONTRACT_ONLY'),
  cH('sentence-realization',"Sentence realization",'FIRST_PASS'),
  cH('meaning-encoding',"Meaning-to-English encoding",'FIRST_PASS'),
  cH('feedback-budget',"Feedback attention budget",'CONTRACT_ONLY'),
  cH('local-repair',"Local repair",'CONTRACT_ONLY'),
  cH('joint-construction',"Joint construction",'CONTRACT_ONLY'),
  cH('revision',"Revision",'FIRST_PASS'),
  cH('return-original',"Return to original writing",'FIRST_PASS'),
  cH('fresh-writing-transfer',"Fresh writing transfer",'FIRST_PASS'),
  cH('writing-evaluation',"Writing-specific evaluation",'CONTRACT_ONLY'),
  cI('source-meaning',"Source meaning decomposition"),
  cI('meaning-fidelity',"Meaning fidelity"),
  cI('lexical-retrieval',"Lexical retrieval"),
  cI('collocation',"Collocation"),
  cI('verb-pattern',"Verb patterns"),
  cI('grammar-form',"Grammar/form"),
  cI('role-mapping',"Sentence-role mapping"),
  cI('l1-l2-contrast',"L1/L2 contrast"),
  cI('restructuring',"Restructuring"),
  cI('guided-reconstruction',"Guided reconstruction"),
  cI('valid-realizations',"Alternative valid realizations"),
  cI('naturalness-precision',"Naturalness/precision"),
  cI('exam-alignment',"Exam scoring alignment"),
  cI('changed-context-retranslation',"Changed-context retranslation",'FIRST_PASS'),
  cI('translation-evaluation',"Translation-specific evaluation"),
  c('J','vocab-representation',"Lexical representation",'V1'),
  c('J','vocab-retrieval',"Vocabulary retrieval",'V1'),
  c('J','vocab-production',"Vocabulary productive use",'V1'),
  c('J','morphology-teaching',"Morphology teaching",'V1'),
  c('J','collocation-teaching',"Collocation teaching",'V1'),
  c('J','chunk-reuse',"Chunk productive reuse",'V1'),
  c('J','register-teaching',"Register teaching",'V1'),
  c('J','grammar-meaning-form',"Grammar meaning-form mapping",'V1'),
  c('J','grammar-construction',"Construction teaching",'V1'),
  c('J','grammar-contrast',"Grammar contrast",'V1'),
  c('J','reading-decomposition',"Reading decomposition",'V1'),
  c('J','reading-reference',"Reference tracking",'V1'),
  c('J','reading-logic',"Reading logic",'V1'),
  c('J','reading-structure',"Reading structure",'V1'),
  c('J','reading-inference',"Reading inference",'V1'),
  c('J','input-output-reuse',"Input-to-output reuse",'V1'),
  c('J','domain-repertoire-selection',"Domain-specific repertoire selection",'V1'),
  cK('diagnostic',"Diagnostic measurement",'FIRST_PASS'),
  cK('practice-evidence',"Practice evidence",'FIRST_PASS'),
  cK('fresh-assessment',"Fresh assessment",'FIRST_PASS'),
  cK('formal-exam',"Formal Exam assessment"),
  cK('answer-reveal',"Answer reveal policy"),
  cK('lookup-lock',"Assessment lookup locking"),
  cK('unsupported-production',"Unsupported production",'FIRST_PASS'),
  cK('same-vs-fresh',"Same-item vs fresh-item distinction",'FIRST_PASS'),
  cK('changed-context-transfer',"Changed-context transfer",'FIRST_PASS'),
  cK('delayed-probe',"Delayed probe"),
  cK('retention',"Retention/stability measurement"),
  cK('scoring-rubric',"Scoring/rubric alignment"),
  cK('measurement-uncertainty',"Measurement uncertainty",'FIRST_PASS'),
  cK('assessment-separation',"Assessment/teaching separation",'FIRST_PASS'),
  cL('reencounter-scheduler',"Re-encounter scheduler",'FIRST_PASS'),
  c('L','spacing',"Spacing execution",'V1'),
  cL('delayed-verification',"Delayed verification",'FIRST_PASS'),
  cL('transfer-scheduling',"Transfer scheduling",'FIRST_PASS'),
  cL('recurrence-trend',"Recurring-error/capability trends",'FIRST_PASS'),
  c('L','treatment-response',"Treatment-response history",'V1'),
  cL('retention-history',"Retention history",'FIRST_PASS'),
  cL('future-allocation-input',"Next-learning allocation inputs",'FIRST_PASS'),
  c('L','stability-refresh',"Stability refresh",'V1'),
  cL('longitudinal-causality',"Future Today affected by prior outcomes",'FIRST_PASS'),
  cM('lesson-session',"LessonSession",'FIRST_PASS'),
  cM('episode-lifecycle',"Episode/task lifecycle",'FIRST_PASS'),
  cM('pause',"Pause",'FIRST_PASS'),
  cM('resume',"Resume",'FIRST_PASS'),
  cM('background-foreground',"Background/foreground"),
  cM('crash-recovery',"Crash recovery",'FIRST_PASS'),
  cM('duplicate-action',"Duplicate-action protection",'FIRST_PASS'),
  cM('hydration',"State hydration",'FIRST_PASS'),
  cM('time-budget',"Time budget",'FIRST_PASS'),
  cM('interruption',"Interruption handling"),
  cM('session-close',"Session close",'FIRST_PASS'),
  cM('cross-surface-continuity',"Cross-surface lesson continuity",'FIRST_PASS'),
  cN('ia-navigation',"Information architecture/navigation",'FIRST_PASS'),
  cN('onboarding-ux',"Onboarding UX",'FIRST_PASS'),
  cN('today-ux',"Today UX",'FIRST_PASS'),
  cN('lesson-ux',"Lesson/Output Workspace UX",'FIRST_PASS'),
  cN('authentic-intake-ux',"Authentic-work intake UX",'FIRST_PASS'),
  cN('writing-ux',"Writing UX",'FIRST_PASS'),
  cN('translation-ux',"Translation UX",'FIRST_PASS'),
  cN('assessment-ux',"Assessment UX",'CONTRACT_ONLY'),
  cN('result-ux',"Result UX",'FIRST_PASS'),
  cN('my-english-ux',"My English / Next Frontier UX",'FIRST_PASS'),
  cN('journey-ux',"Progress / History UX (legacy stable capability id)",'FIRST_PASS'),
  cN('explore-ux',"Secondary Explore UX",'CONTRACT_ONLY'),
  cN('help-stuck-ux',"Help/stuck UX",'FIRST_PASS'),
  cN('source-correction-ux',"Source-intent correction UX",'FIRST_PASS'),
  cN('loading-error-ux',"Loading/error/offline UX",'FIRST_PASS'),
  cN('resume-ux',"Resume UX",'FIRST_PASS'),
  cN('keyboard-back',"Keyboard/back/interruption UX",'CONTRACT_ONLY'),
  cN('general-exam-experience',"General/Exam experience differences",'CONTRACT_ONLY'),
  cN('information-hierarchy',"Learner-facing information hierarchy",'FIRST_PASS'),
  cN('internal-hiding',"Internal truth hiding rules",'FIRST_PASS'),
  cN('experience-contract',"Teacher decision to experience contract",'FIRST_PASS'),
  cO('tokens',"Design tokens",'FIRST_PASS'),
  cO('typography',"Typography",'FIRST_PASS'),
  cO('spacing-layout',"Spacing/layout",'FIRST_PASS'),
  cO('material-language',"Material/visual language",'FIRST_PASS'),
  cO('manuscript',"Manuscript surface",'FIRST_PASS'),
  cO('language-object',"Language objects",'FIRST_PASS'),
  cO('inputs',"Inputs",'FIRST_PASS'),
  cO('actions',"Actions/buttons",'FIRST_PASS'),
  cO('intervention-renderers',"Intervention renderers",'FIRST_PASS'),
  cO('feedback-states',"Feedback states",'FIRST_PASS'),
  cO('sheets-overlays',"Sheets/overlays",'CONTRACT_ONLY'),
  cO('motion',"Motion",'CONTRACT_ONLY'),
  cO('accessibility',"Accessibility",'CONTRACT_ONLY'),
  cO('touch-targets',"Touch targets",'FIRST_PASS'),
  cO('responsive',"Responsive web/mobile",'FIRST_PASS'),
  cO('dev-separation',"Production vs review/dev visual separation",'FIRST_PASS'),
  c('P','phrase-first',"Phrase/chunk-first lookup",'V1'),
  c('P','word-fallback',"Word fallback",'V1'),
  c('P','context-sense',"Contextual sense selection",'V1'),
  c('P','zh-tw-explanation',"Concise zh-TW explanation",'V1'),
  c('P','lookup-history',"Lookup history",'V1'),
  c('P','assessment-lock',"Assessment lookup lock",'V1'),
  c('P','teaching-lookup',"Teaching/example lookup",'V1'),
  c('P','lookup-not-evidence',"Lookup never capability evidence",'V1'),
  cQ('typing',"Direct typing intake",'FIRST_PASS'),
  cQ('paste',"Paste intake",'FIRST_PASS'),
  cQ('writing-artifact',"Existing writing artifact",'FIRST_PASS'),
  cQ('translation-prompt',"Translation prompt/source",'FIRST_PASS'),
  cQ('school-material',"School material intake",'CONTRACT_ONLY'),
  cQ('teacher-material',"Teacher material intake",'CONTRACT_ONLY'),
  cQ('image-intake',"Existing robust image intake",'FIRST_PASS'),
  cQ('pdf-intake',"Existing robust PDF intake",'FIRST_PASS'),
  cQ('artifact-normalization',"Artifact normalization",'FIRST_PASS'),
  c('Q','future-capture-boundary',"Future Capture boundary",'FUTURE'),
  cR('durable-use',"Durable usable-English objective",'FIRST_PASS'),
  c('R','coverage',"Broad-domain coverage",'V1'),
  cR('transfer',"General transfer priority",'FIRST_PASS'),
  cR('retention',"General retention priority",'FIRST_PASS'),
  cR('real-use',"Real-use integration",'FIRST_PASS'),
  c('R','allocation',"General allocation policy",'V1'),
  c('R','frontier',"General frontier selection",'V1'),
  cR('shared-truth',"Shared learner truth enforcement",'FIRST_PASS'),
  cS('scope',"Exam scope",'FIRST_PASS'),
  cS('deadline',"Deadline optimization",'FIRST_PASS'),
  cS('rubric',"Rubric optimization",'FIRST_PASS'),
  cS('time-pressure',"Time pressure",'FIRST_PASS'),
  cS('score-value',"Expected score value",'FIRST_PASS'),
  c('S','weakness-parking',"Weakness parking",'V1'),
  c('S','allocation',"Exam allocation",'V1'),
  cS('formal-integrity',"Formal assessment integrity",'FIRST_PASS'),
  c('S','post-assessment-teaching',"Post-assessment teaching",'V1'),
  c('S','mock-behavior',"Mock behavior",'V1'),
  cS('shared-truth',"Shared learner truth enforcement",'FIRST_PASS'),
  cT('provider-abstraction',"Model provider abstraction",'FIRST_PASS'),
  cT('structured-output',"Structured output",'FIRST_PASS'),
  cT('semantic-diagnosis',"Semantic diagnosis",'CONTRACT_ONLY'),
  cT('content-generation',"Model-assisted content generation",'CONTRACT_ONLY'),
  cT('fallback-model',"Fallback model",'CONTRACT_ONLY'),
  cT('timeout-retry',"Timeout/retry",'FIRST_PASS'),
  cT('hallucination-guards',"Hallucination/grounding guards",'FIRST_PASS'),
  cT('prompt-versioning',"Prompt/schema versioning",'FIRST_PASS'),
  cT('cost-control',"Cost controls",'CONTRACT_ONLY'),
  cT('rate-control',"Rate controls",'CONTRACT_ONLY'),
  cT('model-evaluation',"Model evaluation hooks",'CONTRACT_ONLY'),
  cT('deterministic-fallback',"Deterministic fallback where appropriate",'FIRST_PASS'),
  cU('local-persistence',"Local persistence",'V1'),
  c('U','server-truth',"Server-truth boundary",'V1'),
  c('U','sync',"Sync",'V1'),
  cU('db-schema',"Database schema",'V1'),
  cU('migration',"Data migrations",'V1'),
  c('U','backup-restore',"Backup/restore",'V1'),
  cU('file-storage',"File/object storage",'V1'),
  cU('artifact-storage',"Artifact storage",'V1'),
  cU('event-ledger',"Event ledger persistence",'V1'),
  cU('user-deletion',"User deletion",'V1'),
  cU('privacy-boundary',"Privacy/data boundary",'V1'),
  c('U','cross-device',"Cross-device continuity",'V1'),
  c('V','network-failure',"Network failure",'V1'),
  c('V','model-failure',"AI/model failure",'V1'),
  c('V','partial-response',"Partial response",'V1'),
  c('V','crash-recovery',"Crash recovery",'V1'),
  c('V','logging',"Operational logging",'V1'),
  c('V','error-monitoring',"Error monitoring",'V1'),
  c('V','secret-handling',"Secret handling",'V1'),
  c('V','release-config',"Release configuration",'V1'),
  c('V','android-ios',"Android/iOS behavior",'V1'),
  c('V','keyboard-ime',"Keyboard/IME",'V1'),
  c('V','safe-area-back',"Safe area/back navigation",'V1'),
  c('V','rate-cost-guardrails',"Rate/cost guardrails",'V1'),
  c('W','activation',"Activation",'V1'),
  c('W','lesson-start-finish',"Lesson start/finish",'V1'),
  c('W','help-intervention',"Help/intervention telemetry",'V1'),
  c('W','dropoff-return',"Drop-off/return",'V1'),
  c('W','d1-d7',"D1/D7 retention",'V1'),
  c('W','teacher-decision',"Teacher decision telemetry",'V1'),
  c('W','support-outcome',"Support/outcome relation",'V1'),
  c('W','latency',"Latency",'V1'),
  c('W','cost',"AI/infra cost",'V1'),
  c('W','crash',"Crash telemetry",'V1'),
  c('W','learning-events',"Learning-event analytics",'V1'),
  c('X','architecture-gates',"Architecture gates",'V1'),
  c('X','pedagogical-invariants',"Pedagogical invariants",'V1'),
  c('X','scenario-harness',"Scenario harness",'V1'),
  c('X','teacher-regression',"Teacher regression corpus",'V1'),
  c('X','writing-eval',"Writing evaluation",'V1'),
  c('X','translation-eval',"Translation evaluation",'V1'),
  c('X','general-exam-eval',"General/Exam differentiation evaluation",'V1'),
  c('X','longitudinal-sim',"Longitudinal simulation",'V1'),
  c('X','visual-acceptance',"Visual acceptance",'V1'),
  c('X','device-acceptance',"Device acceptance",'V1'),
  c('X','model-eval',"Model evaluation",'V1'),
  c('X','time-architecture-stress',"5/10/20/30/60 stress tests",'V1'),
  c('X','regression-suite',"Cross-subsystem regression suite",'V1'),
  c('Y','target-cohorts',"Target-user cohorts",'V1'),
  c('Y','problem-interviews',"Problem interview protocol",'V1'),
  c('Y','concept-tests',"Concept tests",'V1'),
  c('Y','prototype-tests',"Prototype tests",'V1'),
  c('Y','pricing-wtp',"Pricing/WTP tests",'V1'),
  c('Y','paid-beta',"Paid-beta readiness",'V1'),
  c('Y','general-exam-wedge',"General vs Exam wedge test",'V1'),
  c('Y','conversion',"Conversion measurement",'V1'),
  c('Y','retention',"Market retention measurement",'V1'),
  c('Y','learning-outcomes',"Real learning-outcome measurement",'V1'),
  c('Y','real-evidence',"Real-market-evidence-only rule",'V1'),
]);
export const capabilitiesForSubsystemV1=(subsystem:string)=>eotFineGrainedCapabilityCatalogV1.filter(item=>item.subsystem===subsystem);
export const subsystemCapabilityCountV1=(subsystem:string)=>capabilitiesForSubsystemV1(subsystem).length;
