import type { ReadingAttemptV1, ReadingReviewFocusV1 } from './readingExamRuntime';
export interface AuthorizedReadingItemResultV1{questionId:string;authorityRef:string;correctResponseIds:readonly string[];evidenceAnchors:readonly string[];diagnosticDemand?:ReadingReviewFocusV1['kind']}
export interface ReadingDiagnosticProbeV1{questionId:string;needed:'LEARNER_EXPLANATION'|'EVIDENCE_SELECTION'|'AUTHORIZED_RESULT'|'OPTION_CONTRAST';prompt:string}
export type ReadingPostAttemptDiagnosisV1={status:'FOCUS_READY';focus:ReadingReviewFocusV1;reasonCodes:readonly string[]}|{status:'NEED_DIAGNOSTIC';questionId?:string;probes:readonly ReadingDiagnosticProbeV1[];reasonCodes:readonly string[]}|{status:'ABSTAIN';reasonCodes:readonly string[]};
const response=(a:ReadingAttemptV1,id:string)=>a.answers.find(x=>x.questionId===id)?.response.trim();
export function diagnoseReadingPostAttemptV1(input:{attempt:ReadingAttemptV1;questionId?:string;authorizedResults?:readonly AuthorizedReadingItemResultV1[];learnerSelectedFocus?:ReadingReviewFocusV1['kind'];learnerExplanation?:string;learnerEvidenceAnchor?:string}):ReadingPostAttemptDiagnosisV1{
 const a=input.attempt;if(!a.immutableSubmit||!a.resultCommittedAt)return{status:'ABSTAIN',reasonCodes:Object.freeze(['COMMITTED_ATTEMPT_REQUIRED'])};
 const q=input.questionId?a.source.questions.find(x=>x.id===input.questionId):a.source.questions.find(x=>response(a,x.id)!==undefined);if(!q)return{status:'NEED_DIAGNOSTIC',probes:Object.freeze([]),reasonCodes:Object.freeze(['NO_ANSWERED_QUESTION_AVAILABLE'])};
 const submitted=response(a,q.id);if(!submitted)return{status:'NEED_DIAGNOSTIC',questionId:q.id,probes:Object.freeze([{questionId:q.id,needed:'LEARNER_EXPLANATION',prompt:'先說明你當時如何理解題目。'}]),reasonCodes:Object.freeze(['ANSWER_MISSING'])};
 const authorized=input.authorizedResults?.find(x=>x.questionId===q.id);if(authorized?.correctResponseIds.includes(submitted))return{status:'ABSTAIN',reasonCodes:Object.freeze(['AUTHORIZED_RESULT_SHOWS_NO_FAILURE'])};
 if(authorized?.diagnosticDemand&&authorized.evidenceAnchors.length)return{status:'FOCUS_READY',focus:Object.freeze({questionId:q.id,kind:authorized.diagnosticDemand,anchorText:authorized.evidenceAnchors[0],reasonRef:`AUTHORIZED_READING_DIAGNOSIS:${authorized.authorityRef}`}),reasonCodes:Object.freeze(['AUTHORIZED_WRONG_RESPONSE','PASSAGE_EVIDENCE_AVAILABLE'])};
 if(input.learnerSelectedFocus&&input.learnerExplanation?.trim()&&input.learnerEvidenceAnchor?.trim())return{status:'FOCUS_READY',focus:Object.freeze({questionId:q.id,kind:input.learnerSelectedFocus,anchorText:input.learnerEvidenceAnchor.trim(),reasonRef:'LEARNER_SELECTED_REVIEW_FOCUS_WITH_EXPLANATION'}),reasonCodes:Object.freeze(['LEARNER_SELECTED_FOCUS','LEARNER_EXPLANATION','LEARNER_EVIDENCE_ANCHOR'])};
 const probes:ReadingDiagnosticProbeV1[]=[{questionId:q.id,needed:'LEARNER_EXPLANATION',prompt:'你當時為什麼選這個答案？'},{questionId:q.id,needed:'EVIDENCE_SELECTION',prompt:'請指出文章中支持你想法的句子。'}];if(q.options?.length)probes.push({questionId:q.id,needed:'OPTION_CONTRAST',prompt:'哪一個選項最難排除？為什麼？'});if(!authorized)probes.push({questionId:q.id,needed:'AUTHORIZED_RESULT',prompt:'目前沒有可驗證正誤的授權結果。'});return{status:'NEED_DIAGNOSTIC',questionId:q.id,probes:Object.freeze(probes),reasonCodes:Object.freeze(['INSUFFICIENT_EVIDENCE_FOR_READING_DIAGNOSIS'])};
}
