import type { LessonPlanV1 } from '../../architecture/contracts';
import { readingReviewLessonPlanV1 } from '../../curriculum/readingReviewPlan';
import { beginStage4RuntimeV4 } from '../../application/stage4/learnerRuntimeV4';
import { startTutorSessionV1 } from '../../teacher-runtime/sessionTime';
import type { ReadingAttemptV1, ReadingReviewFocusV1 } from './readingExamRuntime';

export interface CanonicalReadingReviewV1{schemaVersion:1;id:string;learnerId:string;originalAttemptId:string;originalAttemptSnapshot:string;passage:string;question:string;submittedAnswer:string;focus:ReadingReviewFocusV1;assessment:{mode:ReadingAttemptV1['mode'];submittedAt:string;resultCommittedAt:string};lessonPlan:LessonPlanV1;immutable:true}
const stable=(value:unknown):string=>{if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(stable).join(',')}]`;const record=value as Record<string,unknown>;return`{${Object.keys(record).sort().map(key=>`${JSON.stringify(key)}:${stable(record[key])}`).join(',')}}`};
export function canonicalReadingReviewSemanticsV1(review:CanonicalReadingReviewV1){return{schemaVersion:review.schemaVersion,reviewId:review.id,learnerId:review.learnerId,originalAttemptId:review.originalAttemptId,originalAttemptSnapshot:review.originalAttemptSnapshot,passage:review.passage,question:review.question,submittedAnswer:review.submittedAnswer,assessment:{mode:review.assessment.mode,submittedAt:review.assessment.submittedAt,resultCommittedAt:review.assessment.resultCommittedAt},focus:{questionId:review.focus.questionId,kind:review.focus.kind,anchorText:review.focus.anchorText,reasonRef:review.focus.reasonRef},lessonPlan:{id:review.lessonPlan.id,learnerId:review.lessonPlan.learnerId,targetRef:review.lessonPlan.targetRef,facet:review.lessonPlan.facet,needKind:review.lessonPlan.needKind,objective:review.lessonPlan.objective,reason:review.lessonPlan.reason,reasonCodes:[...review.lessonPlan.reasonCodes],timeBudgetMinutes:review.lessonPlan.timeBudgetMinutes,productMode:review.lessonPlan.productMode},immutable:review.immutable}}
export function assertCanonicalReadingReviewReplayV1(existing:CanonicalReadingReviewV1,incoming:CanonicalReadingReviewV1){if(stable(canonicalReadingReviewSemanticsV1(existing))!==stable(canonicalReadingReviewSemanticsV1(incoming)))throw new Error('canonical_reading_review_is_immutable')}
const snapshot=(attempt:ReadingAttemptV1)=>JSON.stringify(attempt);
export function createCanonicalReadingReviewV1(input:{id:string;attempt:ReadingAttemptV1;focus:ReadingReviewFocusV1;timeBudgetMinutes:number;productMode:'GENERAL'|'EXAM'}):CanonicalReadingReviewV1{const{attempt}=input;if(!attempt.immutableSubmit||!attempt.submittedAt||!attempt.resultCommittedAt)throw new Error('reading_review_requires_committed_result');const question=attempt.source.questions.find(item=>item.id===input.focus.questionId);if(!question)throw new Error('reading_review_focus_question_missing');return Object.freeze({schemaVersion:1,id:input.id,learnerId:attempt.learnerId,originalAttemptId:attempt.id,originalAttemptSnapshot:snapshot(attempt),passage:attempt.source.passage,question:question.stem,submittedAnswer:attempt.answers.find(item=>item.questionId===question.id)?.response??'',focus:Object.freeze({...input.focus}),assessment:Object.freeze({mode:attempt.mode,submittedAt:attempt.submittedAt,resultCommittedAt:attempt.resultCommittedAt}),lessonPlan:readingReviewLessonPlanV1({reviewId:input.id,learnerId:attempt.learnerId,focusKind:input.focus.kind,timeBudgetMinutes:input.timeBudgetMinutes,productMode:input.productMode}),immutable:true})}
export function startCanonicalReadingReviewSessionV1(review:CanonicalReadingReviewV1,occurredAt:string){const artifact=Object.freeze({schemaVersion:4 as const,id:`artifact:${review.id}`,learnerId:review.learnerId,source:'DIRECT_TEXT' as const,mode:'READING' as const,pages:Object.freeze([{page:1,mimeType:'text/plain',originalText:review.submittedAnswer}]),submittedAt:occurredAt,immutable:true as const});const base=beginStage4RuntimeV4(artifact,[{id:`span:${review.id}`,artifactId:artifact.id,region:'LEARNER_WRITING',text:review.submittedAnswer,confidence:'HIGH',alternatives:[]}]);return startTutorSessionV1({...base,readingReview:{schemaVersion:1,reviewId:review.id,originalAttemptId:review.originalAttemptId,originalAttemptSnapshot:review.originalAttemptSnapshot,passage:review.passage,question:review.question,submittedAnswer:review.submittedAnswer,focus:review.focus,assessment:review.assessment,immutable:true}},review.lessonPlan.timeBudgetMinutes,occurredAt)}
export function assertReadingAttemptUnchangedV1(review:CanonicalReadingReviewV1,attempt:ReadingAttemptV1){if(review.originalAttemptSnapshot!==snapshot(attempt))throw new Error('official_reading_attempt_mutated_after_review_handoff')}
