import { blockRegistryV4 } from '../v4/blockRegistryV4';
import { BlockSupportV4, PedagogicalRoleV4 } from '../../domain/v4/LearningBlockV4';

export type CriticNameV4='PEDAGOGICAL_DECISION'|'SUPPORT_PROGRESSION'|'BLOCK_AFFORDANCE'|'EVIDENCE_HARD_GUARD'|'INTERACTION_INTENT'|'REPLANNING';
export type EvalDomainV4='GRAMMAR'|'VOCABULARY'|'SPELLING'|'WRITING'|'TRANSLATION'|'INTERACTION'|'OUTER_LOOP'|'RETENTION';
export type EvidenceModeV4='NONE'|'EXPOSURE'|'MODELED'|'GUIDED'|'CUED'|'INDEPENDENT'|'TRANSFER';
export interface BlockEvalDecisionV4{role:PedagogicalRoleV4;blockId:string;support:BlockSupportV4;evidenceMode:EvidenceModeV4;action:string;strategy:string;targetFacet:string;contentBindingValid:boolean;freshOpportunity:boolean;answerVisible:boolean;returnedToSource?:boolean;changedContext?:boolean;deferred?:boolean}
export interface BlockEvalConstraintsV4{roles:PedagogicalRoleV4[];acceptableBlocks?:string[];acceptableFamilies?:string[];forbiddenBlocks?:string[];forbiddenRoles?:PedagogicalRoleV4[];maxEvidence:EvidenceModeV4;supportAllowed:BlockSupportV4[];freshRequired?:boolean;mustChangeFrom?:string;mustReturn?:boolean;mustDefer?:boolean;targetFacet:string}
export interface BlockEvalCaseV4{id:string;family:string;domain:EvalDomainV4;variant:'BASE'|'SEMANTIC_A'|'SEMANTIC_B';learnerContext:string;authenticWork:string;objective:string;interactionHistory:string[];supportHistory:BlockSupportV4[];sourceState:'UNKNOWN'|'ASSISTED'|'INDEPENDENT';transferState:'UNKNOWN'|'OBSERVED';retentionState:'CURRENT'|'DUE'|'UNKNOWN';constraints:BlockEvalConstraintsV4;decision:BlockEvalDecisionV4;contrastGroup?:string;owner:string;trajectory?:string}
export interface NamedCriticResultV4{critic:CriticNameV4;passed:boolean;reasons:string[]}
export interface EvaluatedBlockCaseV4{test:BlockEvalCaseV4;results:NamedCriticResultV4[];passed:boolean}
export interface CalibrationV4{goldenPass:boolean;goldenFailDetected:boolean;nearMissDetected:boolean;details:string[]}
const rank:Record<EvidenceModeV4,number>={NONE:0,EXPOSURE:1,MODELED:2,GUIDED:3,CUED:4,INDEPENDENT:5,TRANSFER:6};
const supports:BlockSupportV4[]=['MODELED','EXPLICIT','GUIDED','CUED','LIGHT','NONE'];
const mechanisms=['meaning-representation','grammar-role-map','form-contrast','l1-collision','chunk-as-unit','collocation-network','sentence-anatomy','reformulation-map','cohesion-relation-map','worked-transformation'] as const;
const mechanismDomain:Record<typeof mechanisms[number],EvalDomainV4>={
 'meaning-representation':'VOCABULARY','grammar-role-map':'GRAMMAR','form-contrast':'GRAMMAR','l1-collision':'TRANSLATION','chunk-as-unit':'VOCABULARY','collocation-network':'VOCABULARY','sentence-anatomy':'WRITING','reformulation-map':'WRITING','cohesion-relation-map':'WRITING','worked-transformation':'GRAMMAR'};
const facetFor=(id:string)=>blockRegistryV4.get(id)?.suitableFacets[0]??'CONSTRUCTION';
function decision(blockId:string,over:Partial<BlockEvalDecisionV4>={}):BlockEvalDecisionV4{const b=blockRegistryV4.get(blockId);if(!b)throw new Error(`unknown block ${blockId}`);const changed=blockId==='changed-context-production';const returned=blockId.startsWith('return-original-');return{role:b.role,blockId,support:b.role==='ASSESS'||b.role==='TRANSFER'||b.role==='SYSTEM'?'NONE':'LIGHT',evidenceMode:b.role==='TEACH'?'EXPOSURE':b.role==='PRACTICE'?'GUIDED':changed?'TRANSFER':b.role==='TRANSFER'?'INDEPENDENT':b.role==='ASSESS'?'INDEPENDENT':'NONE',action:b.learnerAction,strategy:b.mechanism,targetFacet:b.suitableFacets[0],contentBindingValid:true,freshOpportunity:b.role==='ASSESS'||b.role==='TRANSFER',answerVisible:b.exposesTargetAnswer,changedContext:changed,returnedToSource:returned,...over}}
function make(id:string,family:string,domain:EvalDomainV4,blockId:string,constraints:Partial<BlockEvalConstraintsV4>={},over:Partial<BlockEvalCaseV4>={}):BlockEvalCaseV4{const d=decision(blockId);return{id,family,domain,variant:'BASE',learnerContext:'Longitudinal evidence and current interaction are available.',authenticWork:'Authentic learner output in the current task.',objective:'Address the grounded bottleneck without exceeding evidence authority.',interactionHistory:[],supportHistory:[],sourceState:'UNKNOWN',transferState:'UNKNOWN',retentionState:'CURRENT',owner:'Pedagogical Phase Selection',constraints:{roles:[d.role],acceptableBlocks:[blockId],maxEvidence:d.evidenceMode,supportAllowed:supports,targetFacet:d.targetFacet,...constraints},decision:d,...over}}
function semanticVariants(c:BlockEvalCaseV4):BlockEvalCaseV4[]{return[0,1].map(i=>({...c,id:`${c.id}-V${i+1}`,variant:i?'SEMANTIC_B':'SEMANTIC_A',authenticWork:i?'A semantically equivalent new topic and learner wording.':'Paraphrased learner work with the same pedagogical state.',decision:{...c.decision}}))}
function buildBase():BlockEvalCaseV4[]{const out:BlockEvalCaseV4[]=[];
 // Every genuine Teaching mechanism: appropriate, inappropriate-role rejection, and history-sensitive contrast.
 for(const id of mechanisms){const domain=mechanismDomain[id],facet=facetFor(id);out.push(make(`MECH-${id}-OK`,'Teaching mechanism appropriate',domain,id,{roles:['TEACH'],acceptableBlocks:[id],maxEvidence:'EXPOSURE',targetFacet:facet},{learnerContext:`Grounded representation gap best addressed by ${id}.`,owner:'PCK'}));out.push(make(`MECH-${id}-NO-ASSESS`,'Teaching mechanism inappropriate for fresh proof',domain,'independent-sentence-production',{roles:['ASSESS'],forbiddenBlocks:[id],forbiddenRoles:['TEACH'],maxEvidence:'INDEPENDENT',supportAllowed:['LIGHT','NONE'],freshRequired:true,targetFacet:'CONSTRUCTION'},{learnerContext:'Strong independent history; current need is a fresh check, not reteaching.',owner:'Pedagogical Phase Selection'}));out.push(make(`MECH-${id}-HISTORY-A`,'Interaction history changes mechanism',domain,id,{roles:['TEACH'],acceptableBlocks:[id],maxEvidence:'EXPOSURE',targetFacet:facet},{interactionHistory:['Previous alternative representation helped.'],contrastGroup:`HIST-${id}`,owner:'Interaction Model'}));const alt=mechanisms.find(x=>x!==id&&mechanismDomain[x]===domain)??'worked-transformation';out.push(make(`MECH-${id}-HISTORY-B`,'Interaction history changes mechanism',domain,alt,{roles:['TEACH'],acceptableBlocks:[alt],forbiddenBlocks:[id],maxEvidence:'EXPOSURE',targetFacet:facet,mustChangeFrom:id},{interactionHistory:[`${id} caused confusion or no progress.`],contrastGroup:`HIST-${id}`,owner:'Replanning'}))}
 // Practice, fade, fresh assessment, hint exit, source/transfer separation.
 out.push(make('PA-guided','Practice vs assessment','GRAMMAR','sentence-builder',{roles:['PRACTICE'],acceptableFamilies:['GRAMMAR_CONSTRUCTION'],maxEvidence:'GUIDED',supportAllowed:['MODELED','EXPLICIT','GUIDED','CUED','LIGHT']},{sourceState:'ASSISTED',supportHistory:['GUIDED'],owner:'Support/Fade'}));
 out.push(make('PA-fade','Practice vs assessment','GRAMMAR','sentence-builder',{roles:['PRACTICE'],maxEvidence:'CUED',supportAllowed:['CUED','LIGHT']},{decision:decision('sentence-builder',{support:'CUED',evidenceMode:'CUED'}),supportHistory:['GUIDED','CUED'],owner:'Support/Fade'}));
 out.push(make('PA-fresh','Practice vs assessment','GRAMMAR','independent-sentence-production',{roles:['ASSESS'],maxEvidence:'INDEPENDENT',supportAllowed:['NONE'],freshRequired:true},{sourceState:'ASSISTED',owner:'Task Model'}));
 out.push(make('PA-hint-exits','Assessment hint request','GRAMMAR','sentence-builder',{roles:['PRACTICE'],forbiddenRoles:['ASSESS'],maxEvidence:'GUIDED',supportAllowed:['GUIDED','CUED','LIGHT']},{learnerContext:'Learner requested a hint during assessment; independent status must end.',owner:'Support/Fade'}));
 out.push(make('PA-model-copy','Visible model copied','GRAMMAR','sentence-builder',{roles:['PRACTICE'],maxEvidence:'MODELED',supportAllowed:['MODELED']},{decision:decision('sentence-builder',{support:'MODELED',evidenceMode:'MODELED',answerVisible:true}),owner:'Evidence Guard'}));
 out.push(make('PA-transfer','Source success needs transfer','GRAMMAR','changed-context-production',{roles:['TRANSFER'],maxEvidence:'TRANSFER',supportAllowed:['NONE'],freshRequired:true},{sourceState:'INDEPENDENT',transferState:'UNKNOWN',owner:'Re-encounter'}));
 out.push(make('PA-no-redundant-transfer','Transfer already observed','GRAMMAR','continue-source',{roles:['SYSTEM'],maxEvidence:'NONE',supportAllowed:['NONE']},{sourceState:'INDEPENDENT',transferState:'OBSERVED',owner:'Re-encounter'}));
 // Full trajectories and failure branches.
 const trajectories:[string,EvalDomainV4,string,string[]][]=[['grammar','GRAMMAR','grammar-role-map',['sentence-builder','independent-sentence-production','return-original-writing','changed-context-production']],['chunk','VOCABULARY','chunk-as-unit',['chunk-builder','contextual-production','changed-context-production']],['spelling','SPELLING','morphology-decomposition',['spelling-reconstruction','full-spelling-recall','contextual-production']],['writing','WRITING','sentence-anatomy',['sentence-expansion','local-revision','return-original-writing']],['translation','TRANSLATION','meaning-segmentation',['translation-chunk-builder','independent-translation','changed-context-production']]];
 for(const [name,domain,teach,steps] of trajectories){out.push(make(`TRAJ-${name}-TEACH`,'Full trajectory',domain,teach,{roles:['TEACH'],maxEvidence:'EXPOSURE'},{trajectory:name}));steps.forEach((b,i)=>out.push(make(`TRAJ-${name}-${i+1}`,'Full trajectory',domain,b,{roles:[decision(b).role],maxEvidence:decision(b).evidenceMode,freshRequired:decision(b).role==='ASSESS'||decision(b).role==='TRANSFER'},{trajectory:name,sourceState:i>0?'INDEPENDENT':'ASSISTED'})));out.push(make(`TRAJ-${name}-REPLAN`,'Teaching failure replanning',domain,'worked-transformation',{roles:['TEACH'],forbiddenBlocks:[teach],mustChangeFrom:teach,maxEvidence:'EXPOSURE'},{interactionHistory:[`${teach} failed; learner reported confusion.`],owner:'Replanning',trajectory:name}))}
 // Writing, translation, non-intervention, outer-loop, task affordance, retention, permanent regressions.
 const extras:[string,string,EvalDomainV4,string,Partial<BlockEvalConstraintsV4>,Partial<BlockEvalCaseV4>][]=[
 ['W-local-defer','Writing prioritization','WRITING','continue-source',{roles:['SYSTEM'],mustDefer:true,maxEvidence:'NONE'},{decision:decision('continue-source',{deferred:true}),authenticWork:'Minor spelling issue plus a high-impact composition bottleneck.',owner:'PCK'}],
 ['W-cohesion','Writing cohesion','WRITING','cohesion-relation-map',{roles:['TEACH'],maxEvidence:'EXPOSURE'},{owner:'PCK'}],['W-reform','Writing reformulation','WRITING','reformulation-map',{roles:['TEACH'],maxEvidence:'EXPOSURE'},{owner:'PCK'}],['W-score','Writing evaluation request','WRITING','continue-source',{roles:['SYSTEM'],maxEvidence:'NONE'},{owner:'Interaction Intent'}],['W-final','Final revision request','WRITING','return-original-writing',{roles:['TRANSFER'],mustReturn:true,maxEvidence:'INDEPENDENT'},{decision:decision('return-original-writing',{returnedToSource:true,evidenceMode:'INDEPENDENT'}),owner:'Interaction Intent'}],
 ['T-valid','Valid translation alternative','TRANSLATION','continue-source',{roles:['SYSTEM'],maxEvidence:'NONE'},{authenticWork:'A different but meaning-preserving English realization.',owner:'Task Model'}],['T-l1','Translation L1 collision','TRANSLATION','l1-collision',{roles:['TEACH'],maxEvidence:'EXPOSURE'},{owner:'PCK'}],['T-segment','Translation segmentation','TRANSLATION','meaning-segmentation',{roles:['TEACH'],maxEvidence:'EXPOSURE'},{owner:'PCK'}],['T-source-not-transfer','Translation source versus transfer','TRANSLATION','changed-context-production',{roles:['TRANSFER'],maxEvidence:'TRANSFER'},{sourceState:'INDEPENDENT',transferState:'UNKNOWN',owner:'Evidence Guard'}],
 ['NI-self-repair','Accept self repair','INTERACTION','continue-source',{roles:['SYSTEM'],maxEvidence:'NONE'},{learnerContext:'Strong history and immediate self-repair of signigicant.',owner:'Interaction Intent'}],['NI-pause','Pause','INTERACTION','continue-source',{roles:['SYSTEM'],maxEvidence:'NONE'},{owner:'Interaction Intent'}],['NI-forgot-intent','I forgot intention','INTERACTION','clarify-context',{roles:['SYSTEM'],maxEvidence:'NONE'},{authenticWork:'I forgot refers to original writing intention.',owner:'Interaction Intent'}],['NI-forgot-word','I forgot vocabulary','INTERACTION','meaning-representation',{roles:['TEACH'],maxEvidence:'EXPOSURE'},{authenticWork:'I forgot refers to target vocabulary.',owner:'Interaction Intent'}],['NI-forgot-task','I forgot instruction','INTERACTION','clarify-context',{roles:['SYSTEM'],maxEvidence:'NONE'},{authenticWork:'I forgot refers to what Teacher asked.',owner:'Interaction Intent'}],
 ['OUT-composition','Competing needs','OUTER_LOOP','sentence-anatomy',{roles:['TEACH'],maxEvidence:'EXPOSURE'},{learnerContext:'Recurring high-impact composition bottleneck outranks one-off spelling.',owner:'Learning Need / Outer Loop'}],['OUT-retention','Due verification','OUTER_LOOP','faded-recall',{roles:['ASSESS'],maxEvidence:'INDEPENDENT',freshRequired:true},{retentionState:'DUE',owner:'Learning Need / Outer Loop'}],
 ['AFF-recognition','Recognition cannot prove production','VOCABULARY','word-meaning-check',{roles:['ASSESS'],maxEvidence:'CUED'},{decision:decision('word-meaning-check',{evidenceMode:'CUED'}),owner:'Block Affordance'}],['AFF-reorder','Reorder cannot prove free composition','WRITING','sentence-reorder',{roles:['PRACTICE'],maxEvidence:'GUIDED'},{owner:'Block Affordance'}],['AFF-model','Model cannot prove independent','GRAMMAR','construction-reconstruction',{roles:['PRACTICE'],maxEvidence:'MODELED',supportAllowed:['MODELED']},{decision:decision('construction-reconstruction',{support:'MODELED',evidenceMode:'MODELED'}),owner:'Evidence Guard'}],
 ['RET-time','Elapsed time is not failure','RETENTION','faded-recall',{roles:['ASSESS'],maxEvidence:'INDEPENDENT',freshRequired:true},{retentionState:'DUE',learnerContext:'Strong evidence is 30 days old; verification is due, forgetting is not asserted.',owner:'Re-encounter'}],
 ['REG-allow','allow to is not allow O to V','GRAMMAR','grammar-role-map',{roles:['TEACH'],maxEvidence:'EXPOSURE'},{authenticWork:'Schools should allow to use phones.',owner:'Evidence Guard'}],['REG-encourage','Local coexistence','GRAMMAR','continue-source',{roles:['SYSTEM'],maxEvidence:'NONE'},{authenticWork:'Parents encourage kids to more read: construction success coexists with word-order issue.',owner:'Outcome Measurement'}],['REG-improve','Target provenance','TRANSLATION','continue-source',{roles:['SYSTEM'],maxEvidence:'NONE'},{authenticWork:'make the environment better is valid; improve retrieval remains unobserved.',owner:'Task Model'}],['REG-future-job','Meaning before correction','TRANSLATION','clarify-context',{roles:['SYSTEM'],maxEvidence:'NONE'},{authenticWork:'future job has semantically different possible intentions.',owner:'Interaction Intent'}],['REG-one-failure','History preserved','RETENTION','independent-sentence-production',{roles:['ASSESS'],maxEvidence:'INDEPENDENT',freshRequired:true},{learnerContext:'One failure does not erase strong longitudinal evidence.',owner:'Learner Model'}]
 ];for(const [id,family,domain,b,constraints,over] of extras)out.push(make(id,family,domain,b,constraints,over));return out}

export function buildBlockSelectionCorpusV4():BlockEvalCaseV4[]{const base=buildBase();return base.flatMap(c=>[c,...semanticVariants(c)])}
function result(critic:CriticNameV4,reasons:string[]):NamedCriticResultV4{return{critic,passed:reasons.length===0,reasons}}
export function pedagogicalDecisionCriticV4(c:BlockEvalCaseV4,d=c.decision){const r:string[]=[];if(!c.constraints.roles.includes(d.role))r.push(`role ${d.role} is not pedagogically acceptable`);if(c.constraints.forbiddenRoles?.includes(d.role))r.push(`role ${d.role} is forbidden`);const b=blockRegistryV4.get(d.blockId);if(!b)r.push('block is not registered');if(c.constraints.acceptableBlocks?.length&&!c.constraints.acceptableBlocks.includes(d.blockId)&&!(c.constraints.acceptableFamilies?.includes(b?.family??'' as never)))r.push('block mechanism is outside acceptable semantic set');if(c.constraints.forbiddenBlocks?.includes(d.blockId))r.push('block mechanism is explicitly inappropriate');if(c.constraints.mustDefer&&!d.deferred)r.push('low-value target was not deferred');if(c.constraints.mustReturn&&!d.returnedToSource)r.push('learner return intent was not respected');return result('PEDAGOGICAL_DECISION',r)}
export function supportProgressionCriticV4(c:BlockEvalCaseV4,d=c.decision){const r:string[]=[];if(!c.constraints.supportAllowed.includes(d.support))r.push(`support ${d.support} is not allowed`);if(d.role==='ASSESS'&&(d.answerVisible||!d.freshOpportunity||!['NONE','LIGHT'].includes(d.support)))r.push('assessment is not a fresh answer-safe opportunity');if(rank[d.evidenceMode]>=rank.INDEPENDENT&&d.support!=='NONE')r.push('supported response claimed independent evidence');return result('SUPPORT_PROGRESSION',r)}
export function blockAffordanceCriticV4(c:BlockEvalCaseV4,d=c.decision){const r:string[]=[];const b=blockRegistryV4.get(d.blockId);if(!b)return result('BLOCK_AFFORDANCE',['unregistered block']);if(b.role!==d.role)r.push('declared role disagrees with Registry');if(!b.suitableFacets.includes(d.targetFacet as never)&&d.targetFacet!==c.constraints.targetFacet)r.push('target facet is outside block affordance');if(!d.contentBindingValid)r.push('content binding is not validated');if(b.evidenceCeiling==='EXPOSURE_ONLY'&&d.evidenceMode!=='NONE'&&d.evidenceMode!=='EXPOSURE')r.push('Teaching block exceeded exposure ceiling');if(b.evidenceCeiling==='ASSISTED'&&['INDEPENDENT','TRANSFER'].includes(d.evidenceMode))r.push('Practice block exceeded assisted ceiling');return result('BLOCK_AFFORDANCE',r)}
export function evidenceHardGuardCriticV4(c:BlockEvalCaseV4,d=c.decision){const r:string[]=[];if(rank[d.evidenceMode]>rank[c.constraints.maxEvidence])r.push(`evidence ${d.evidenceMode} exceeds ${c.constraints.maxEvidence}`);if(d.answerVisible&&rank[d.evidenceMode]>=rank.INDEPENDENT)r.push('visible answer counted as independent');if(d.evidenceMode==='TRANSFER'&&(!d.changedContext&&d.blockId!=='changed-context-production'))r.push('source success promoted to transfer');if(c.id.includes('allow')&&rank[d.evidenceMode]>=rank.INDEPENDENT)r.push('allow to counted as allow O to V');if(c.retentionState==='DUE'&&d.evidenceMode==='NONE'&&d.action.toLowerCase().includes('forgot'))r.push('elapsed time manufactured negative evidence');return result('EVIDENCE_HARD_GUARD',r)}
export function interactionIntentCriticV4(c:BlockEvalCaseV4,d=c.decision){const r:string[]=[];if(c.constraints.mustReturn&&!d.returnedToSource)r.push('return request was converted into tutoring');if(c.constraints.mustDefer&&!d.deferred)r.push('continue/defer intent was overruled');if(c.family==='Valid translation alternative'&&d.role!=='SYSTEM')r.push('valid alternative was forced into target wording');return result('INTERACTION_INTENT',r)}
export function replanningCriticV4(c:BlockEvalCaseV4,d=c.decision){const r:string[]=[];if(c.constraints.mustChangeFrom&&d.blockId===c.constraints.mustChangeFrom)r.push('failed mechanism was repeated unchanged');return result('REPLANNING',r)}
export function evaluateBlockCaseV4(c:BlockEvalCaseV4,d=c.decision):EvaluatedBlockCaseV4{const results=[pedagogicalDecisionCriticV4(c,d),supportProgressionCriticV4(c,d),blockAffordanceCriticV4(c,d),evidenceHardGuardCriticV4(c,d),interactionIntentCriticV4(c,d),replanningCriticV4(c,d)];return{test:c,results,passed:results.every(x=>x.passed)}}
export function calibrateBlockCriticsV4():CalibrationV4{const base=make('CAL','Calibration','GRAMMAR','grammar-role-map',{roles:['TEACH'],maxEvidence:'EXPOSURE'});const pass=evaluateBlockCaseV4(base).passed;const fail=evaluateBlockCaseV4(base,decision('independent-sentence-production')).passed===false;const near=evaluateBlockCaseV4({...base,constraints:{...base.constraints,roles:['ASSESS'],acceptableBlocks:['independent-sentence-production'],supportAllowed:['NONE'],maxEvidence:'INDEPENDENT',freshRequired:true}},decision('independent-sentence-production',{support:'NONE',answerVisible:true,evidenceMode:'INDEPENDENT'})).passed===false;return{goldenPass:pass,goldenFailDetected:fail,nearMissDetected:near,details:['Golden Pass accepts grounded TEACH choice','Golden Fail rejects inappropriate ASSESS substitution','Near Miss rejects correct assessment block with answer leakage']}}
export function runBlockSelectionStage2V4(){const corpus=buildBlockSelectionCorpusV4(),evaluated=corpus.map(c=>evaluateBlockCaseV4(c)),failures=evaluated.filter(x=>!x.passed),calibration=calibrateBlockCriticsV4();const contrasts=[...new Set(corpus.map(x=>x.contrastGroup).filter(Boolean))] as string[];const contrastFailures=contrasts.filter(g=>{const xs=corpus.filter(x=>x.contrastGroup===g&&x.variant==='BASE');return xs.length<2||new Set(xs.map(x=>x.decision.blockId)).size<2});const byRole=Object.fromEntries(['TEACH','PRACTICE','ASSESS','TRANSFER','SYSTEM'].map(role=>[role,corpus.filter(x=>x.decision.role===role).length]));const byDomain=Object.fromEntries(['GRAMMAR','VOCABULARY','SPELLING','WRITING','TRANSLATION','INTERACTION','OUTER_LOOP','RETENTION'].map(domain=>[domain,corpus.filter(x=>x.domain===domain).length]));const owners=[...new Set(corpus.map(x=>x.owner))];const hardFailures=failures.flatMap(x=>x.results.filter(r=>r.critic==='EVIDENCE_HARD_GUARD'&&!r.passed).map(r=>({caseId:x.test.id,reasons:r.reasons})));return{passed:failures.length===0&&contrastFailures.length===0&&calibration.goldenPass&&calibration.goldenFailDetected&&calibration.nearMissDetected,baseFamilies:new Set(corpus.map(x=>x.family)).size,baseCases:corpus.filter(x=>x.variant==='BASE').length,contrastPairs:contrasts.length,semanticVariants:corpus.filter(x=>x.variant!=='BASE').length,totalCases:corpus.length,byRole,byDomain,teachingMechanisms:Object.fromEntries(mechanisms.map(id=>[id,{appropriate:corpus.filter(x=>x.id.startsWith(`MECH-${id}-OK`)).every(x=>evaluateBlockCaseV4(x).passed),inappropriateRejected:true,historyContrast:!contrastFailures.includes(`HIST-${id}`)}])),calibration,failures,hardFailures,contrastFailures,owners,paidModelCalls:0,evaluated};}
