import { guardEvidenceCandidateV3 } from '../evidence/evidenceGuardsV3';
import { CapabilityFacet, EnglishFacet } from '../../domain/english/EnglishDomain';
import { LearningNeed } from '../../domain/learning/LearningNeed';
import { TaskBlueprintV4 } from '../../domain/v4/CoreArchitectureV4';
import { FacetBeliefV4, BeliefStateV4 } from '../../domain/v4/LearnerBeliefV4';
import { validateTaskBlueprintV4 } from '../v4/taskGenerationV4';
import { decideTeacherPolicyV4, PedagogicalActionV4, TeacherEvalDecisionV4, TeacherEvalInputV4 } from './teacherPolicyV4';

export type EvalSuiteV4='INTERACTION'|'WRITING'|'TRANSLATION'|'KNOWLEDGE'|'LONGITUDINAL'|'INTERACTION_MODEL'|'TEACHING_FAILURE'|'EVIDENCE'|'OUTER_LOOP'|'TASK_GENERATION'|'REENCOUNTER'|'COST_ROUTING'|'REAL_REPLAY';
export interface OutcomeExpectationV4{strategyChanged?:boolean;independentAfterSupport?:boolean;returnedToSource?:boolean;transferSeparated?:boolean;delayedSeparated?:boolean}
export interface TeacherEvalCaseV4{id:string;suite:EvalSuiteV4;family:string;variant:string;input:TeacherEvalInputV4;expected:{actions:PedagogicalActionV4[];intent?:string;strategy?:string;modelTier?:string;evidenceMode?:string;reencounter?:string;selectedNeedId?:string;noCapabilityEvidence?:boolean};outcome?:OutcomeExpectationV4}
export interface CriticResultV4{caseId:string;critic:'PROCESS'|'OUTCOME'|'HARD_GUARD';passed:boolean;reasons:string[]}
export interface Stage2ReportV4{passed:boolean;baseFamilies:number;cases:number;counts:Record<string,number>;processFailures:CriticResultV4[];outcomeFailures:CriticResultV4[];hardFailures:CriticResultV4[];contrastFailures:string[];unownedFamilies:string[];architectureGaps:string[];modelCalls:{zeroAi:number;aiEligible:number;imageResends:number;criticEscalations:number};evaluatorRegressions:{equivalentSafeActions:boolean;paraphraseInvariant:boolean;contextSensitive:boolean}}

const FACET:CapabilityFacet='ORTHOGRAPHIC_PRODUCTION';
const canonicalTargetForFacet=(facet:EnglishFacet):string=>{
  switch(facet){
    case 'FORM_RECOGNITION':
    case 'ORTHOGRAPHIC_PRODUCTION':
    case 'MORPHOLOGY': return 'form.allow.base';
    case 'MEANING_TO_RETRIEVAL':
    case 'LEXICAL_SYNTACTIC_BEHAVIOR': return 'word.allow';
    case 'COLLOCATION': return 'translation.naturalness-precision';
    case 'FORM_MEANING_MAPPING':
    case 'CONSTRUCTION':
    case 'CONTEXTUAL_APPROPRIACY': return 'allow-object-infinitive';
    case 'FREE_PRODUCTION': return 'writing.sentence-realization';
    default: return 'allow-object-infinitive';
  }
};
const signal=(kind:TeacherEvalInputV4['signals'][number]['kind'],referent='active work',confidence:'LOW'|'MEDIUM'|'HIGH'='HIGH')=>({kind,referent,confidence});
function task(id:string,facet:CapabilityFacet=FACET,context:'SOURCE'|'SAME_CONTEXT'|'CHANGED_CONTEXT'|'DELAYED_CONTEXT'='SOURCE',support:TaskBlueprintV4['task']['supportExposed']=['NONE'],family:TaskBlueprintV4['task']['taskFamily']='WRITING'):TaskBlueprintV4{const targetRef=canonicalTargetForFacet(facet);return{task:{id,purpose:context==='CHANGED_CONTEXT'?'TRANSFER':context==='DELAYED_CONTEXT'?'RETENTION':'SOURCE_WORK',taskFamily:family,targetRefs:[targetRef],contextNovelty:context,responseOpenness:'OPEN',supportExposed:support,meaningProvenance:support.includes('SEMANTIC_CONTENT')?'TEACHER_SUPPLIED':'LEARNER_ORIGINATED',eligibleClaims:[{targetRef,facet}],forbiddenClaims:[]},objectiveId:`o-${id}`,responseMode:'TEXT',promptScope:'target',answerScope:'target',evaluatorScope:'target',revealScope:'target',validAnswerPolicy:'SEMANTIC_OPEN',expectedAlternatives:[],contaminationRisks:[],load:{length:'MEDIUM',ideaGeneration:'LOW',clauses:2,timePressure:false},generationProvenance:'CURATED'}}
function belief(state:BeliefStateV4='UNKNOWN',possibleSlip=false):FacetBeliefV4{return{learnerId:'l',targetRef:canonicalTargetForFacet(FACET),facet:FACET,contextScope:'writing',state,confidence:state==='UNKNOWN'?'LOW':'HIGH',supportingEvidenceIds:state==='UNKNOWN'?[]:['prior'],contradictoryEvidenceIds:[],contextsObserved:[],supportDependence:state==='ASSISTED_USE'?'HIGH':'NONE_OBSERVED',verificationDue:state==='VERIFICATION_DUE',possibleSlip,possibleGuess:false,evidenceVolume:state==='UNKNOWN'?0:4,evidenceDiversity:state==='UNKNOWN'?0:2}}
const observation=(polarity:'POSITIVE'|'NEGATIVE'|'MIXED'|'UNKNOWN',facet:EnglishFacet=FACET,extra:Partial<TeacherEvalInputV4['observations'][number]>={})=>({targetRef:canonicalTargetForFacet(facet),facet,polarity,scope:'LOCAL' as const,opportunity:true,...extra});
function input(id:string,overrides:Partial<TeacherEvalInputV4>={}):TeacherEvalInputV4{return{id,learnerId:'l',signals:[signal('TASK_RESPONSE')],task:task(`t-${id}`),observations:[observation('NEGATIVE')],beliefs:[belief()],interactionHistory:[],...overrides}}
function c(id:string,suite:EvalSuiteV4,family:string,overrides:Partial<TeacherEvalInputV4>,expected:TeacherEvalCaseV4['expected'],outcome?:OutcomeExpectationV4):TeacherEvalCaseV4{const built=input(id,overrides);if(built.task){const eligibleClaims=built.observations.filter(x=>x.opportunity).map(x=>({targetRef:x.targetRef,facet:x.facet as CapabilityFacet}));built.task={...built.task,task:{...built.task.task,targetRefs:[...new Set(eligibleClaims.map(x=>x.targetRef))],eligibleClaims}}}return{id,suite,family,variant:'base',input:built,expected,outcome}}

function bases():TeacherEvalCaseV4[]{
 const cases:TeacherEvalCaseV4[]=[
  c('INT-production','INTERACTION','learner production',{}, {actions:['DISCRIMINATING_PROBE'],intent:'LANGUAGE_PERFORMANCE'}),
  c('INT-help','INTERACTION','help request',{signals:[signal('HELP')]},{actions:['TEACH'],intent:'HELP_REQUEST',noCapabilityEvidence:true}),
  c('INT-clarify','INTERACTION','clarification',{signals:[signal('QUESTION')]},{actions:['ANSWER_REQUEST'],intent:'CLARIFICATION_REQUEST',noCapabilityEvidence:true}),
  c('INT-unknown','INTERACTION','uncertainty',{signals:[signal('SELF_REPORT','', 'LOW')]},{actions:['CLARIFY'],noCapabilityEvidence:true}),
  c('INT-correct','INTERACTION','learner corrects Teacher',{signals:[signal('TEACHER_CORRECTION')]},{actions:['ACKNOWLEDGE'],intent:'CORRECT_TEACHER',noCapabilityEvidence:true}),
  c('INT-artifact','INTERACTION','artifact result request',{signals:[signal('ARTIFACT_OPERATION')]},{actions:['DELIVER_ARTIFACT'],intent:'ARTIFACT_RESULT_REQUEST',noCapabilityEvidence:true}),
  c('INT-eval','INTERACTION','evaluation request',{signals:[signal('EVALUATION')]},{actions:['EVALUATE_ARTIFACT'],intent:'EVALUATION_REQUEST',noCapabilityEvidence:true}),
  c('INT-nav','INTERACTION','navigation control',{signals:[signal('NAVIGATION')]},{actions:['NAVIGATE'],modelTier:'ZERO_AI',noCapabilityEvidence:true}),
  c('INT-pause','INTERACTION','pause skip',{signals:[signal('PAUSE')]},{actions:['ACKNOWLEDGE','DEFER'],intent:'PAUSE_DEFER',noCapabilityEvidence:true}),
  c('INT-goal','INTERACTION','goal switch',{signals:[signal('GOAL_CHANGE')]},{actions:['ACKNOWLEDGE'],intent:'GOAL_SWITCH',noCapabilityEvidence:true}),
  c('INT-multi','INTERACTION','multi intent',{signals:[signal('TASK_RESPONSE'),signal('HELP')]},{actions:['TEACH'],intent:'HELP_REQUEST',noCapabilityEvidence:true}),
  c('WRT-surface','WRITING','surface error deep success',{observations:[observation('POSITIVE','CONSTRUCTION',{deepSuccess:true}),observation('NEGATIVE',FACET,{surfaceIssue:true})]},{actions:['DISCRIMINATING_PROBE']}),
  c('WRT-composition','WRITING','composition bottleneck',{observations:[observation('NEGATIVE','FREE_PRODUCTION',{scope:'WHOLE_OUTPUT',loadHigh:true})]},{actions:['DISCRIMINATING_PROBE']}),
  c('WRT-multiple','WRITING','multiple issues prioritization',{observations:[observation('NEGATIVE','COLLOCATION'),observation('NEGATIVE','CONSTRUCTION')]},{actions:['DISCRIMINATING_PROBE']}),
  c('WRT-old','WRITING','old work forgotten intent',{signals:[signal('AMBIGUOUS','old work','LOW')]},{actions:['CLARIFY'],noCapabilityEvidence:true}),
  c('TR-valid','TRANSLATION','valid alternative',{observations:[observation('POSITIVE','FORM_MEANING_MAPPING',{validAlternative:true,meaningPreserved:true,targetProvenance:false})]},{actions:['ACKNOWLEDGE'],noCapabilityEvidence:true}),
  c('TR-distort','TRANSLATION','fluent meaning distortion',{observations:[observation('NEGATIVE','FORM_MEANING_MAPPING',{meaningPreserved:false})]},{actions:['DISCRIMINATING_PROBE']}),
  c('TR-partial','TRANSLATION','partial correctness',{observations:[observation('POSITIVE','CONSTRUCTION'),observation('NEGATIVE','FORM_MEANING_MAPPING')]},{actions:['DISCRIMINATING_PROBE']}),
 ];
 const facets:CapabilityFacet[]=['FORM_RECOGNITION','MEANING_TO_RETRIEVAL','ORTHOGRAPHIC_PRODUCTION','MORPHOLOGY','COLLOCATION','LEXICAL_SYNTACTIC_BEHAVIOR','CONSTRUCTION','CONTEXTUAL_APPROPRIACY','FREE_PRODUCTION'];
 for(const facet of facets)cases.push(c(`KN-${facet}`,'KNOWLEDGE',`resource ${facet}`,{observations:[observation('POSITIVE',facet)],task:task(`t-${facet}`,facet)}, {actions:['CONTINUE'],evidenceMode:'INDEPENDENT'}));
 cases.push(
  c('LONG-strong','LONGITUDINAL','spelling slip strong history',{beliefs:[belief('STABLE_FOR_SCOPE',true)]},{actions:['SELF_REPAIR_PROMPT']}),
  c('LONG-repeated','LONGITUDINAL','spelling instability repeated failure',{beliefs:[belief('RETRIEVAL_FRAGILE')]},{actions:['DISCRIMINATING_PROBE']}),
  c('LONG-assisted','LONGITUDINAL','assisted only',{observations:[observation('POSITIVE')],beliefs:[belief('ASSISTED_USE')],visibleModel:true,task:task('t-assisted',FACET,'SAME_CONTEXT',['MODEL'])},{actions:['FADE_SUPPORT'],evidenceMode:'MODELED',reencounter:'SAME_SESSION_FADE'}, {independentAfterSupport:true}),
  c('LONG-transfer','LONGITUDINAL','recent transfer',{observations:[observation('POSITIVE')],beliefs:[belief('TRANSFER_OBSERVED')],task:task('t-transfer',FACET,'CHANGED_CONTEXT')},{actions:['CONTINUE'],reencounter:'DELAYED_PRODUCTION'}),
  c('LONG-stale','LONGITUDINAL','stale evidence',{observations:[observation('POSITIVE')],beliefs:[belief('VERIFICATION_DUE')],task:task('t-stale',FACET,'DELAYED_CONTEXT')},{actions:['CONTINUE'],reencounter:'DELAYED_PRODUCTION'}),
  c('IM-explain','INTERACTION_MODEL','explanations fail contrasts help',{interactionHistory:[{strategy:'EXPLAIN',effect:'CONFUSED',comparable:true},{strategy:'FORM_CONTRAST',effect:'HELPED',comparable:true}]},{actions:['TEACH'],strategy:'FORM_CONTRAST'}),
  c('IM-model','INTERACTION_MODEL','visible models cause copying',{interactionHistory:[{strategy:'MODEL',effect:'NO_PROGRESS',comparable:true}],visibleModel:true},{actions:['TEACH'],strategy:'RECONSTRUCT_WITHOUT_MODEL'}),
 );
 const failures:NonNullable<TeacherEvalInputV4['teachingFailure']>[]=['SUPPORT_TOO_LOW','REPRESENTATION_MISMATCH','DIAGNOSIS_WRONG','PREREQUISITE_MISSING','TASK_LOAD_TOO_HIGH','PERFORMANCE_NOISE','TEACHER_INDUCED_CONFUSION'];
 for(const failure of failures)cases.push(c(`FAIL-${failure}`,'TEACHING_FAILURE',failure,{teachingFailure:failure,previousMove:'EXPLAIN'},{actions:['CHANGE_STRATEGY']},{strategyChanged:true}));
 cases.push(
  c('EV-model','EVIDENCE','modeled not independent',{observations:[observation('POSITIVE')],visibleModel:true,task:task('t-model',FACET,'SAME_CONTEXT',['MODEL'])},{actions:['FADE_SUPPORT'],evidenceMode:'MODELED'}),
  c('EV-ocr','EVIDENCE','OCR correction',{ocrCorrection:true},{actions:['ACKNOWLEDGE'],modelTier:'ZERO_AI',noCapabilityEvidence:true}),
  c('EV-allow','EVIDENCE','allow to not allow O to V',{observations:[observation('NEGATIVE','CONSTRUCTION')],task:task('t-allow','CONSTRUCTION')},{actions:['DISCRIMINATING_PROBE']}),
  c('OUT-compete','OUTER_LOOP','competing learning needs',{needs:needs()},{actions:['DISCRIMINATING_PROBE'],selectedNeedId:'composition'}),
  c('TASK-valid','TASK_GENERATION','aligned task contract',{observations:[observation('POSITIVE')],task:task('t-aligned')},{actions:['CONTINUE'],evidenceMode:'INDEPENDENT'}),
  c('REEN-source','REENCOUNTER','source to transfer',{observations:[observation('POSITIVE')],beliefs:[belief('LOCAL_INDEPENDENT')]},{actions:['CONTINUE'],reencounter:'CHANGED_CONTEXT_TRANSFER'},{returnedToSource:true,transferSeparated:true}),
  c('COST-nav','COST_ROUTING','zero AI navigation',{signals:[signal('NAVIGATION')]},{actions:['NAVIGATE'],modelTier:'ZERO_AI'}),
  c('COST-vision','COST_ROUTING','persisted vision transcript',{artifactAlreadyTranscribed:true},{actions:['DISCRIMINATING_PROBE'],modelTier:'TEACHER_REASONING'}),
  c('COST-critic','COST_ROUTING','exceptional critic escalation',{teachingFailure:'REPRESENTATION_MISMATCH',interactionHistory:[{strategy:'EXPLAIN',effect:'CONFUSED',comparable:true},{strategy:'MODEL',effect:'NO_PROGRESS',comparable:true}]},{actions:['CHANGE_STRATEGY'],modelTier:'CRITIC_SECOND_PASS'}),
  c('REPLAY-final','REAL_REPLAY','final revised artifact',{signals:[signal('ARTIFACT_OPERATION')]},{actions:['DELIVER_ARTIFACT']}),
  c('REPLAY-original','REAL_REPLAY','original artifact',{signals:[signal('ARTIFACT_OPERATION')],originalArtifactRequest:true},{actions:['NAVIGATE'],modelTier:'ZERO_AI'}),
  c('REPLAY-local','REAL_REPLAY','local revision',{signals:[signal('TASK_RESPONSE')],observations:[observation('NEGATIVE','CONSTRUCTION')]},{actions:['DISCRIMINATING_PROBE']}),
 );
 return cases;
}
function needs():LearningNeed[]{const make=(id:string,source:LearningNeed['source'],impact:'LOW'|'MEDIUM'|'HIGH',whyNow:string):LearningNeed=>({id,targetRef:id,facet:'FREE_PRODUCTION',sourceEvidenceIds:[`e-${id}`],outcomeImpact:impact,evidenceStrength:'HIGH',recurrence:'REPEATED',goalRelevance:impact,readiness:'HIGH',teachability:'HIGH',transferValue:impact,informationValue:'MEDIUM',timeCost:id==='composition'?'MEDIUM':'LOW',whyNow,allowedTaskFamilies:['WRITING'],source});return[make('spelling','REPEATED_FRAGILITY','LOW','Repeated but low-impact surface issue'),make('composition','COMPOSITION','HIGH','Current composition bottleneck blocks the writing goal'),make('retention','RETENTION_DUE','MEDIUM','Due for verification, not assumed forgotten')]}
function variants(base:TeacherEvalCaseV4):TeacherEvalCaseV4[]{return['paraphrase-a','paraphrase-b'].map((variant,i)=>({...base,id:`${base.id}-${i+1}`,variant,input:{...base.input,id:`${base.id}-${i+1}`,signals:base.input.signals.map(s=>({...s,referent:s.referent?i?'current learner goal':'the active source passage':s.referent}))}}))}
export function buildStage2CorpusV4():TeacherEvalCaseV4[]{const root=bases();return root.flatMap(x=>[x,...variants(x)])}

export function processCriticV4(test:TeacherEvalCaseV4,decision:TeacherEvalDecisionV4):CriticResultV4{const r:string[]=[];if(!test.expected.actions.includes(decision.action))r.push(`action ${decision.action} not in ${test.expected.actions.join('|')}`);if(test.expected.intent&&!decision.intents.includes(test.expected.intent))r.push(`missing intent ${test.expected.intent}`);if(test.expected.strategy&&decision.strategy!==test.expected.strategy)r.push(`strategy ${decision.strategy??'none'} != ${test.expected.strategy}`);if(test.expected.modelTier&&decision.modelCall.tier!==test.expected.modelTier)r.push(`model tier ${decision.modelCall.tier} != ${test.expected.modelTier}`);if(test.expected.evidenceMode&&!decision.evidenceCandidates.some(x=>x.productionMode===test.expected.evidenceMode))r.push(`missing evidence mode ${test.expected.evidenceMode}`);if(test.expected.reencounter&&decision.reencounter!==test.expected.reencounter)r.push(`reencounter ${decision.reencounter??'none'} != ${test.expected.reencounter}`);if(test.expected.selectedNeedId&&decision.selectedNeedId!==test.expected.selectedNeedId)r.push(`need ${decision.selectedNeedId??'none'} != ${test.expected.selectedNeedId}`);if(test.expected.noCapabilityEvidence&&decision.evidenceCandidates.some(x=>x.candidateKind==='CAPABILITY'))r.push('interaction incorrectly produced capability evidence');return{caseId:test.id,critic:'PROCESS',passed:!r.length,reasons:r}}
export function outcomeCriticV4(test:TeacherEvalCaseV4,decision:TeacherEvalDecisionV4):CriticResultV4{const r:string[]=[];const o=test.outcome;if(o?.strategyChanged&&(decision.action!=='CHANGE_STRATEGY'||decision.strategy===test.input.previousMove))r.push('strategy did not materially change');if(o?.independentAfterSupport&&decision.reencounter!=='SAME_SESSION_FADE')r.push('support was not scheduled to fade before independent proof');if(o?.transferSeparated&&decision.reencounter!=='CHANGED_CONTEXT_TRANSFER')r.push('source success was not kept separate from transfer');return{caseId:test.id,critic:'OUTCOME',passed:!r.length,reasons:r}}
export function hardGuardCriticV4(test:TeacherEvalCaseV4,decision:TeacherEvalDecisionV4):CriticResultV4{const r:string[]=[];for(const [i,candidate] of decision.evidenceCandidates.entries()){const guarded=guardEvidenceCandidateV3({candidate,task:test.input.task?.task??null,learnerId:'l',id:`${test.id}-e${i}`,occurredAt:'2026-08-23T00:00:00Z'});if(candidate.evidenceEligibility==='ELIGIBLE'&&!guarded.accepted)r.push(...guarded.reasons.map(x=>`eligible candidate rejected: ${x}`));if(candidate.candidateKind!=='CAPABILITY'&&guarded.accepted)r.push(`${candidate.candidateKind} entered capability ledger`);if(candidate.productionMode==='INDEPENDENT'&&candidate.supportBeforeResponse!=='NONE')r.push('assisted response promoted to independent');}if(test.family.includes('allow to')&&decision.evidenceCandidates.some(x=>x.evidencePolarity==='POSITIVE'&&x.targetRef==='target'))r.push('allow to counted as successful allow O to V');return{caseId:test.id,critic:'HARD_GUARD',passed:!r.length,reasons:r}}
export function runStage2GateV4():Stage2ReportV4{const corpus=buildStage2CorpusV4(),process:CriticResultV4[]=[],outcome:CriticResultV4[]=[],hard:CriticResultV4[]=[],decisions=new Map<string,TeacherEvalDecisionV4>(),counts:Record<string,number>={};let zeroAi=0,aiEligible=0,imageResends=0,criticEscalations=0;for(const test of corpus){counts[test.suite]=(counts[test.suite]??0)+1;const d=decideTeacherPolicyV4(test.input);decisions.set(test.id,d);const p=processCriticV4(test,d),o=outcomeCriticV4(test,d),h=hardGuardCriticV4(test,d);if(!p.passed)process.push(p);if(!o.passed)outcome.push(o);if(!h.passed)hard.push(h);if(d.modelCall.tier==='ZERO_AI')zeroAi++;else aiEligible++;if(d.modelCall.includeImage&&test.input.artifactAlreadyTranscribed)imageResends++;if(d.modelCall.tier==='CRITIC_SECOND_PASS')criticEscalations++}const contrastFailures:string[]=[];const contrast=(a:string,b:string,key:(d:TeacherEvalDecisionV4)=>string)=>{const x=decisions.get(a),y=decisions.get(b);if(!x||!y||key(x)===key(y))contrastFailures.push(`${a}/${b} did not differ materially`)};contrast('LONG-strong','LONG-repeated',d=>d.action);contrast('IM-explain','INT-production',d=>`${d.action}/${d.strategy}`);const unownedFamilies=[...new Set(corpus.filter(x=>{const d=decisions.get(x.id);return !d?.intents.length&&d?.grounding!=='UNRESOLVED'}).map(x=>x.family))];const aligned=validateTaskBlueprintV4(task('reg-task'),{linguisticValid:true,hiddenTargetLeak:false,validatorStatus:'VALIDATED'}).deliveryAllowed;const evaluatorRegressions={equivalentSafeActions:processCriticV4({...corpus[0],expected:{actions:['CONTINUE','ACKNOWLEDGE']}},{...decisions.get('INT-production')!,action:'ACKNOWLEDGE'}).passed,paraphraseInvariant:corpus.filter(x=>x.variant!=='base').every(x=>{const base=decisions.get(x.id.replace(/-[12]$/,''));const v=decisions.get(x.id);return base&&v&&base.action===v.action}),contextSensitive:contrastFailures.length===0&&aligned};const passed=!process.length&&!outcome.length&&!hard.length&&!contrastFailures.length&&!unownedFamilies.length&&Object.values(evaluatorRegressions).every(Boolean);return{passed,baseFamilies:bases().length,cases:corpus.length,counts,processFailures:process,outcomeFailures:outcome,hardFailures:hard,contrastFailures,unownedFamilies,architectureGaps:[],modelCalls:{zeroAi,aiEligible,imageResends,criticEscalations},evaluatorRegressions}}
export function capabilityProvenanceContrastsV4():{passed:boolean;failures:string[]}{const failures:string[]=[],candidate=(facet:CapabilityFacet,context:'SOURCE'|'CHANGED_CONTEXT')=>({candidateKind:'CAPABILITY' as const,observation:'independent production',capabilityDomain:'ENGLISH',capabilityFacet:facet,evidenceEligibility:'ELIGIBLE' as const,evidencePolarity:'POSITIVE' as const,evidenceScope:'LOCAL' as const,productionMode:'INDEPENDENT' as const,supportBeforeResponse:'NONE' as const,semanticProvenance:'LEARNER_ORIGINATED' as const,contextNovelty:context,confidence:'HIGH' as const,competingExplanations:[],taskAffordanceChecked:true,targetRef:canonicalTargetForFacet(facet)}),check=(name:string,candidateValue:ReturnType<typeof candidate>,taskValue:TaskBlueprintV4['task'],expected:boolean)=>{const accepted=guardEvidenceCandidateV3({candidate:candidateValue,task:taskValue,learnerId:'l',id:name,occurredAt:'2026-08-24T00:00:00Z'}).accepted;if(accepted!==expected)failures.push(`${name}:${accepted}!=${expected}`)};const source=task('source-construction','CONSTRUCTION','SOURCE').task,changed=task('changed-construction','CONSTRUCTION','CHANGED_CONTEXT').task,sourceSpelling=task('source-spelling','ORTHOGRAPHIC_PRODUCTION','SOURCE').task;check('construction-source',candidate('CONSTRUCTION','SOURCE'),source,true);check('construction-changed',candidate('CONSTRUCTION','CHANGED_CONTEXT'),changed,true);check('correct-capability-wrong-provenance',candidate('CONSTRUCTION','CHANGED_CONTEXT'),source,false);check('wrong-capability-correct-provenance',candidate('ORTHOGRAPHIC_PRODUCTION','SOURCE'),source,false);check('same-source-different-afforded-capability',candidate('ORTHOGRAPHIC_PRODUCTION','SOURCE'),sourceSpelling,true);return{passed:!failures.length,failures}}
