import { TeacherPlanningContext, TeacherTurnPlan, TeachingTurn, planTeacherTurn } from '../../domain/teacher/TeacherRuntime';

export interface RegressionCase { id:string; name:string; initial:Partial<TeacherPlanningContext>&Pick<TeacherPlanningContext,'learnerResponse'>; responses?:string[]; must:string[]; mustNot:string[] }
export interface SimulatedLearnerWorld{id:string;visible:TeacherPlanningContext;hidden:{behavior:string;knowledge?:Record<string,string>}}
export interface ProcessCritic{score(plan:TeacherTurnPlan,visible:TeacherPlanningContext):number;notes(plan:TeacherTurnPlan):string[]}
export interface OutcomeCritic{score(trace:EvaluationTrace,hidden:SimulatedLearnerWorld['hidden']):number}
export interface TraceTurn{response:string;observations:string[];hypotheses:string[];decision:string;action?:string;support:string;hardFails:string[]}
export interface EvaluationTrace{worldId:string;candidatePlans:TeacherTurnPlan[];preferred:number;rejected:number[];hardFails:string[];turns:TraceTurn[];readable:string}
const ctx=(x:RegressionCase['initial']):TeacherPlanningContext=>({sourceText:x.sourceText??x.learnerResponse,learnerResponse:x.learnerResponse,priorEvidence:x.priorEvidence??[],priorTurns:x.priorTurns??[],visibleModel:x.visibleModel,ocrUnresolved:x.ocrUnresolved,targetProvenance:x.targetProvenance,pckUnits:x.pckUnits,contextNovelty:x.contextNovelty,originalSourceControlled:x.originalSourceControlled});
const successHistory=[1,2,3].map(n=>({id:`spelling-${n}`,knowledgePointId:'significant-orthography',result:'SUCCESS',responseText:'significant'}));

export const REGRESSION_CASES:RegressionCase[]=[
 {id:'REG-001',name:'typo-self-repair',initial:{learnerResponse:'AI will have a signigicant impact on future jobs.',priorEvidence:successHistory},responses:['AI will have a significant impact on future jobs.'],must:['stop spelling intervention'],mustNot:['start spelling drill']},
 {id:'REG-002',name:'same-surface-real-spelling-gap',initial:{learnerResponse:'AI will have a signigicant impact on future jobs.'},responses:["I always forget how to spell this."],must:['orthographic teaching plausible'],mustNot:['reteach meaning']},
 {id:'REG-003',name:'orthographic-recognition-gap',initial:{learnerResponse:'signigicant'},responses:["I can't decide which spelling is right."],must:['recognition separate from production'],mustNot:['simple typo fact']},
 {id:'REG-004',name:'encourage-partial-success',initial:{learnerResponse:'Parents encourage kids to more read.'},responses:['Parents encourage kids to read more.'],must:['preserve encourage success','self repair'],mustNot:['teach encourage']},
 {id:'REG-005',name:'encourage-no-self-repair',initial:{learnerResponse:'Parents encourage kids to more read.'},responses:["I don't know what's wrong."],must:['contingent support'],mustNot:['dump answer']},
 {id:'REG-006',name:'more-books-challenge',initial:{learnerResponse:"But 'more books' is correct, right?"},must:['recognize challenge'],mustNot:['false absolute']},
 {id:'REG-007',name:'allow-to',initial:{learnerResponse:'Schools should allow to use phones.'},must:['reject target success'],mustNot:['allow target success']},
 {id:'REG-008',name:'valid-alternative-improve',initial:{learnerResponse:'make the environment better',targetProvenance:['improve']},must:['accept English'],mustNot:['target mismatch wrong']},
 {id:'REG-009',name:'retrieval-provenance',initial:{learnerResponse:'改善 → ?',targetProvenance:[]},must:['block probe'],mustNot:['invent improve']},
 {id:'REG-010',name:'future-job-intent',initial:{learnerResponse:'future job'},must:['resolve intent'],mustNot:['blind substitute']},
 {id:'REG-011',name:'model-imitation',initial:{learnerResponse:'Schools should allow students to use phones.',visibleModel:'Schools should allow students to use phones.'},must:['modeled'],mustNot:['independent']},
 {id:'REG-012',name:'strategy-failure',initial:{learnerResponse:'I am still confused.',priorTurns:[]},must:['change strategy'],mustNot:['repeat explanation']},
 {id:'REG-013',name:'diagnosis-reversal',initial:{learnerResponse:'I rushed it.'},responses:['I independently repaired it.'],must:['diagnosis revisable'],mustNot:['fixed lesson']},
 {id:'REG-014',name:'multi-error-interruption',initial:{learnerResponse:'A paragraph with eight possible issues but a clear message.'},must:['prioritize'],mustNot:['eight corrections']},
 {id:'REG-015',name:'vision-autocorrect',initial:{learnerResponse:'significant',ocrUnresolved:true},must:['resolve transcript'],mustNot:['teach normalized evidence']},
 {id:'REG-016',name:'teacher-red-ink',initial:{learnerResponse:'future job'},must:['separate channels'],mustNot:['annotation as production']},
 {id:'REG-017',name:'controlled-success-source-failure',initial:{learnerResponse:'The source still has allow to use phones.'},must:['source unresolved'],mustNot:['close learned']},
 {id:'REG-018',name:'transfer-failure',initial:{learnerResponse:'New context failed.',originalSourceControlled:true,contextNovelty:'NEW'},must:['separate transfer'],mustNot:['stable mastery']},
 {id:'REG-019',name:'teacher-is-wrong',initial:{learnerResponse:'have a major impact on'},must:['accept alternative'],mustNot:['force significant']},
 {id:'REG-020',name:'teacher-induced-confusion',initial:{learnerResponse:'I understood before, but that explanation confused me.'},must:['teacher failure possible'],mustNot:['learner deficit only']},
 {id:'REG-021',name:'same-output-different-state',initial:{learnerResponse:'signigicant'},must:['competing hypotheses'],mustNot:['single diagnosis']},
 {id:'REG-022',name:'photo-uncertainty-before-spelling',initial:{learnerResponse:'signigicant',ocrUnresolved:true},must:['clarify transcript'],mustNot:['machine error teaching']},
 {id:'REG-023',name:'open-question-not-wrong-answer',initial:{learnerResponse:'What does flying colours mean?'},must:['respond to question'],mustNot:['failed attempt']},
 {id:'REG-024',name:'accepted-answer-no-overteach',initial:{learnerResponse:'This answer is adequate for the task.'},must:['progress'],mustNot:['manufacture correction']},
];

export function loadRegressionCorpusYaml(yaml:string):RegressionCase[]{const ids=[...yaml.matchAll(/^- \{id:\s*(REG-\d+),\s*name:\s*([^,}]+)/gm)].map(m=>({id:m[1],name:m[2].trim()}));if(ids.length!==24)throw new Error(`Expected 24 regression cases, found ${ids.length}`);return ids.map(({id,name})=>{const found=REGRESSION_CASES.find(x=>x.id===id);if(!found||found.name!==name)throw new Error(`Runtime case does not match supplied corpus: ${id}`);return found})}

export function hardFailChecks(plan:TeacherTurnPlan,context:TeacherPlanningContext):string[]{const f:string[]=[];const lower=context.learnerResponse.toLowerCase();if(/allow\s+to\b/.test(lower)&&plan.positiveEvidence.some(x=>/allow.*(?:successful|o to v)/i.test(x.claim)))f.push('allow-to-counted-success');if(context.visibleModel&&context.learnerResponse.trim()===context.visibleModel.trim()&&plan.supportLevel==='NONE')f.push('model-imitation-independent');if(context.ocrUnresolved&&plan.teacherAction!=='CLARIFY_TRANSCRIPT')f.push('ocr-uncertainty-not-resolved');if(/make the environment better|major impact/.test(lower)&&plan.interventionDecision==='INTERVENE')f.push('valid-alternative-overteach');if(/改善\s*[→>-]/.test(context.learnerResponse)&&!(context.targetProvenance?.length)&&plan.teacherAction!=='DEFER')f.push('invented-retrieval-target');if(lower.trim()==='future job'&&plan.teacherAction!=='CLARIFY_INTENT')f.push('ambiguous-intent-not-resolved');if(context.contextNovelty==='NEW'&&context.originalSourceControlled&&plan.teacherAction!=='TRANSFER_CHECK')f.push('source-transfer-collapsed');return f}
const cautious=(c:TeacherPlanningContext):TeacherTurnPlan=>({...planTeacherTurn(c),interventionDecision:'DEFER',teacherAction:'DEFER',supportLevel:'NONE',teacherUtterance:'先保留觀察，暫時不介入。'});
const explicit=(c:TeacherPlanningContext):TeacherTurnPlan=>({...planTeacherTurn(c),interventionDecision:'INTERVENE',teacherAction:'MODEL',supportLevel:'MODEL',teacherUtterance:'我先提供完整示範，再請你模仿。'});
export function runOfflineWorld(world:SimulatedLearnerWorld,candidates:Array<(c:TeacherPlanningContext)=>TeacherTurnPlan>=[planTeacherTurn,cautious,explicit]):EvaluationTrace{const plans=candidates.map(fn=>fn(world.visible));const ranked=plans.map((plan,index)=>({index,fails:hardFailChecks(plan,world.visible)})).sort((a,b)=>a.fails.length-b.fails.length||a.index-b.index);const turns=runMultiTurn(world.visible,[]);return{worldId:world.id,candidatePlans:plans,preferred:ranked[0].index,rejected:ranked.slice(1).map(x=>x.index),hardFails:ranked[0].fails,turns,readable:formatTrace(world.id,turns)}}
export function runMultiTurn(initial:TeacherPlanningContext,responses:string[]):TraceTurn[]{const turns:TraceTurn[]=[];let context=initial;for(const response of [initial.learnerResponse,...responses]){context={...context,learnerResponse:response};const plan=planTeacherTurn(context);turns.push({response,observations:plan.observations.map(x=>x.claim),hypotheses:plan.competingHypotheses.map(x=>`${x.id}:${x.confidence}`),decision:plan.interventionDecision,action:plan.teacherAction,support:plan.supportLevel,hardFails:hardFailChecks(plan,context)});const prior:TeachingTurn={id:`eval-${turns.length}`,learnerResponse:response,plan,createdAt:new Date(0).toISOString()};context={...context,priorTurns:[...context.priorTurns,prior]};}return turns}
export function runRegressionCorpus():EvaluationTrace[]{return REGRESSION_CASES.map(c=>{const visible=ctx(c.initial);const world={id:c.id,visible,hidden:{behavior:c.name}};const baseTrace=runOfflineWorld(world);const turns=runMultiTurn(visible,c.responses??[]);return{...baseTrace,turns,readable:formatTrace(c.id,turns)}})}
export function formatTrace(id:string,turns:TraceTurn[]):string{return [`CASE ${id}`,...turns.map((t,i)=>`T${i+1} response=${JSON.stringify(t.response)} | observe=${t.observations.join('; ')} | hypotheses=${t.hypotheses.join(', ')||'none'} | decision=${t.decision} | action=${t.action??'none'} | support=${t.support} | hardFails=${t.hardFails.join(',')||'none'}`)].join('\n')}
export function serializeTraces(traces:EvaluationTrace[]):string{return JSON.stringify({schemaVersion:1,generatedAt:new Date().toISOString(),traces},null,2)}
export function diffTraceActions(before:EvaluationTrace,after:EvaluationTrace):string{return before.turns.map((turn,index)=>{const next=after.turns[index];return next&&turn.action!==next.action?`${before.worldId} T${index+1}: ${turn.action??'none'} -> ${next.action??'none'}`:null}).filter(Boolean).join('\n')||'no pedagogical action changes'}
