import { TeacherDomain } from '../../domain/teacher/TeacherRuntime';

export interface TeachingKnowledgeUnit { id: string; domain: TeacherDomain; state: string; goal: string; entryMoves: string[]; doNot: string[]; responseRules: Array<{ signal: string; interpretation: string; next?: string }>; independentSuccess: string; transfer?: string }
const unit=(id:string,domain:TeacherDomain,state:string,goal:string,entryMoves:string[],doNot:string[],independentSuccess:string,responseRules:TeachingKnowledgeUnit['responseRules']=[],transfer?:string):TeachingKnowledgeUnit=>({id,domain,state,goal,entryMoves,doNot,responseRules,independentSuccess,transfer});

export const PCK_CORE: TeachingKnowledgeUnit[] = [
 unit('V01_UNKNOWN_LEXICAL_REPRESENTATION','VOCABULARY','form meaning use representation absent or not evidenced','build usable form meaning use representation',['CLARIFY_INTENT','EXPLAIN','EXAMPLE','ELICIT'],['infer absence from one failure','mark a valid alternative wrong'],'retrieve and use from meaning without model',[{signal:'known but inaccessible',interpretation:'retrieval may be the issue',next:'V03_RETRIEVAL_FAILURE'}],'use appropriately with changed content'),
 unit('V02_RECOGNITION_ONLY','VOCABULARY','recognition evidenced but productive access unproven','strengthen meaning to form retrieval',['RETRIEVE','ELICIT'],['reteach definition first','call cued retrieval independent'],'retrieve from meaning without cue'),
 unit('V03_RETRIEVAL_FAILURE','VOCABULARY','known target inaccessible now with learner-specific provenance','restore lexical access',['RETRIEVE','HINT','CONTEXT_CONTRAST'],['probe a target without provenance'],'retrieve target without cue',[{signal:'partial form',interpretation:'partial retrieval',next:'V04_PARTIAL_RETRIEVAL'}]),
 unit('V04_PARTIAL_RETRIEVAL','VOCABULARY','partial lexical phonological or orthographic form','complete representation without resetting knowledge',['HINT','RECONSTRUCT','GUIDED_REVISION'],['label target wholly unknown'],'complete form independently'),
 unit('V05_ORTHOGRAPHIC_INSTABILITY','VOCABULARY','meaning available while written form unstable','stabilize independent written production',['SELF_REPAIR_PROMPT','FORM_CONTRAST','RECONSTRUCT','REPRESENT_DIFFERENTLY'],['autocorrect before capture','reteach meaning by default'],'hidden-model full-form production',[{signal:'immediate repair with strong history',interpretation:'likely slip',next:'STOP_INTERVENTION'}]),
 unit('V06_SENSE_CONFUSION','VOCABULARY','word known but intended sense boundary unstable','align intended meaning with sense',['CLARIFY_INTENT','SEMANTIC_CONTRAST','CONTEXT_CONTRAST','COUNTEREXAMPLE'],['change intended meaning'],'select sense in unseen context'),
 unit('V07_COLLOCATION_GAP','CHUNK','component meanings known but lexical partnership unstable','build productive collocation',['FORM_CONTRAST','CONTEXT_CONTRAST','EXAMPLE','RECONSTRUCT'],['only say unnatural','treat as generic grammar'],'construct collocation without options'),
 unit('V08_LEXICAL_SYNTACTIC_PATTERN','CHUNK','lexical argument or complement frame unstable','link meaning roles to frame',['SEMANTIC_CONTRAST','DECOMPOSE','GUIDED_REVISION','ELICIT'],['teach false absolute rules'],'use a legal frame for new meaning'),
 unit('V09_PRODUCTIVE_DEPLOYMENT','VOCABULARY','controlled knowledge does not appear in authentic output','make target deployable',['GUIDED_NOTICE','ELICIT','RETURN_TO_SOURCE'],['equate valid alternative with failure'],'choose target independently in authentic output'),
 unit('G01_FORM_UNKNOWN','GRAMMAR','grammatical form not represented','build form and communicative function',['EXPLAIN','EXAMPLE','MODEL','ELICIT'],['force discovery of every rule'],'construct form for new meaning without model'),
 unit('G02_MEANING_UNKNOWN','GRAMMAR','form recognizable but function weak','build form meaning relation',['SEMANTIC_CONTRAST','CONTEXT_CONTRAST','EXAMPLE'],['teach form detached from meaning'],'choose form from intended relation'),
 unit('G03_FORM_MEANING_MAPPING','GRAMMAR','form and meaning familiar but mapping unstable','stabilize meaning-driven selection',['SEMANTIC_CONTRAST','GUIDED_REVISION','ELICIT'],['teach form detached from meaning'],'select from meaning in unfamiliar context'),
 unit('G04_SELECTION_CONFUSION','GRAMMAR','competing structures known but selection inconsistent','locate discriminating feature',['DISCRIMINATING_PROBE','FORM_CONTRAST','SEMANTIC_CONTRAST'],['reteach every candidate rule'],'choose structure from relevant distinction'),
 unit('G05_CONSTRUCTION_GAP','GRAMMAR','recognizes form but cannot assemble it','build independent construction',['COMPLETE','GUIDED_REVISION','DECOMPOSE','FADE_SUPPORT'],['call scaffold completion independent'],'build full construction without frame'),
 unit('G06_CONTROLLED_TO_FREE_INSTABILITY','GRAMMAR','controlled success degrades in authentic output','control target under meaningful load',['GUIDED_NOTICE','SELF_REPAIR_PROMPT','REDUCE_LOAD','RETURN_TO_SOURCE'],['restart beginner explanation'],'target survives return to original work'),
 unit('G07_L1_COMPETING_PATTERN','GRAMMAR','recurring output suggests competing L1 representation','build stable L2 mapping',['FORM_CONTRAST','SEMANTIC_CONTRAST','REFORMULATE'],['diagnose L1 from one event'],'error stops recurring across contexts'),
 unit('C01_MEANING_SEGMENTATION','COMPOSITION','idea cannot be segmented into propositions','develop learner-controlled segmentation',['CLARIFY_INTENT','DECOMPOSE','ELICIT'],['teacher does all segmentation'],'identify own meaning units'),
 unit('C02_MEANING_TO_CLAUSE','COMPOSITION','intended proposition lacks viable clause','map meaning to clause and locate bottleneck',['DISCRIMINATING_PROBE','DECOMPOSE','GUIDED_REVISION','REFORMULATE'],['supply whole answer immediately'],'produce own clause for a new proposition'),
 unit('C03_CLAUSE_RELATION','COMPOSITION','clauses possible but relation and linking unstable','establish meaning relation before form',['SEMANTIC_CONTRAST','CLARIFY_INTENT','COMBINE'],['teach linker lists detached from meaning'],'choose relation for new ideas'),
 unit('C04_INTEGRATION_UNDER_LOAD','COMPOSITION','components degrade when combined','reduce bottleneck then reintegrate',['REDUCE_LOAD','DECOMPOSE','CHANGE_STRATEGY','RETURN_TO_SOURCE'],['relabel degraded parts as absent knowledge'],'whole output survives scaffold removal'),
 unit('C05_REFORMULATION','COMPOSITION','learner stuck on one expression route','develop meaning-preserving alternatives',['REFORMULATE','CONTEXT_CONTRAST','MODEL'],['force sophisticated target'],'escape dead end without teacher wording'),
];

const tokens=(text:string)=>new Set(text.toLowerCase().split(/[^a-z]+/).filter(x=>x.length>3));
export function retrievePck(domain:TeacherDomain,stateText:string,limit=4):TeachingKnowledgeUnit[]{const query=tokens(stateText);const ranked=PCK_CORE.filter(x=>x.domain===domain).map(unit=>({unit,score:[...query].filter(t=>`${unit.id} ${unit.state} ${unit.goal}`.toLowerCase().includes(t)).length})).sort((a,b)=>b.score-a.score||a.unit.id.localeCompare(b.unit.id));return ranked.slice(0,limit).map(x=>x.unit)}
