import { EnglishDomainObjectType,EnglishFacet } from '../../domain/english/EnglishDomain';
import { TeacherActionV3 } from '../../domain/teacher/TeacherDecisionV3';
export interface TeachingMechanism{ id:string;objectTypes:EnglishDomainObjectType[];facets:EnglishFacet[];entryMoves:TeacherActionV3[];avoid:string[];fadeTo:TeacherActionV3;strongerEvidence:string;reintegration:'WRITING'|'TRANSLATION'|'BOTH'}
export const TEACHING_MECHANISMS:TeachingMechanism[]=[
 {id:'LEXICAL_RETRIEVAL',objectTypes:['WORD','WORD_FAMILY','SENSE'],facets:['MEANING_TO_RETRIEVAL'],entryMoves:['RETRIEVE','HINT','FADE_SUPPORT'],avoid:['recognition as retrieval','target without provenance'],fadeTo:'RETRIEVE',strongerEvidence:'unsupported contextual retrieval',reintegration:'BOTH'},
 {id:'ORTHOGRAPHIC_PRODUCTION',objectTypes:['WORD','WORD_FAMILY'],facets:['ORTHOGRAPHIC_PRODUCTION'],entryMoves:['SELF_REPAIR_PROMPT','RECONSTRUCT','REPRESENT_DIFFERENTLY'],avoid:['reteach meaning by default'],fadeTo:'RECONSTRUCT',strongerEvidence:'hidden-model full-form production',reintegration:'BOTH'},
 {id:'CHUNK_COLLOCATION',objectTypes:['CHUNK','COLLOCATION'],facets:['COLLOCATION','LEXICAL_SYNTACTIC_BEHAVIOR'],entryMoves:['FORM_CONTRAST','DECOMPOSE','RECONSTRUCT'],avoid:['generic grammar label'],fadeTo:'RECONSTRUCT',strongerEvidence:'independent slot manipulation',reintegration:'BOTH'},
 {id:'GRAMMAR_CONSTRUCTION',objectTypes:['GRAMMAR_CONSTRUCTION'],facets:['FORM_MEANING_MAPPING','SELECTION','CONSTRUCTION','FREE_PRODUCTION'],entryMoves:['SEMANTIC_CONTRAST','FORM_CONTRAST','GUIDED_REVISION'],avoid:['fixed rule script','L1 label from one event'],fadeTo:'FADE_SUPPORT',strongerEvidence:'free production in changed context',reintegration:'BOTH'},
 {id:'FORMULAIC_APPROPRIACY',objectTypes:['IDIOM_PROVERB','FORMULAIC_SEQUENCE','REUSABLE_EXPRESSION'],facets:['CONTEXTUAL_APPROPRIACY','SPONTANEOUS_DEPLOYMENT'],entryMoves:['CONTEXT_CONTRAST','REFORMULATE','ELICIT'],avoid:['meaning reteach when deployment is issue'],fadeTo:'ELICIT',strongerEvidence:'learner-owned content and appropriate deployment',reintegration:'WRITING'},
 {id:'COMPOSITION_INTEGRATION',objectTypes:['COMPOSITION_CAPABILITY','DISCOURSE_MOVE'],facets:['CONSTRUCTION','FREE_PRODUCTION'],entryMoves:['DECOMPOSE','REDUCE_LOAD','COMBINE','RETURN_TO_SOURCE'],avoid:['vocabulary fallback','teacher-authored idea as learner composition'],fadeTo:'RETURN_TO_SOURCE',strongerEvidence:'learner-owned integrated source revision',reintegration:'BOTH'},
];
export function retrieveTeachingMechanisms(type:EnglishDomainObjectType,facet:EnglishFacet):TeachingMechanism[]{return TEACHING_MECHANISMS.filter(m=>m.objectTypes.includes(type)&&m.facets.includes(facet))}
