import { EvidenceCandidateV3 } from '../../domain/evidence/EvidenceCandidateV3';
import { LearnerModelSnapshotV3 } from '../../domain/learner/LearnerModelV3';
import { TaskContract } from '../../domain/task/TaskContract';
import { TeacherActionV3,TeacherDecisionV3,TeacherInterventionDecisionV3 } from '../../domain/teacher/TeacherDecisionV3';
export interface RelevantTeacherContextV3{learnerEvent:string;sourceExcerpt?:string;artifactAge?:'FRESH'|'OLD';originalIntentAvailable?:boolean;ocrUnresolved?:boolean;visibleModel?:string;task:TaskContract|null;learningNeedId?:string|null;targetRef?:string|null;learnerModel:LearnerModelSnapshotV3;relevantInteractionHistory?:Array<{strategy:string;effect:'HELPED'|'NO_PROGRESS'|'CONFUSED'}>;previousAction?:TeacherActionV3;teacherHypothesis?:string;contextSupplement?:string;requestKind?:string;modelCallAllowed?:boolean}
const noEvidence=(observation:string):EvidenceCandidateV3=>({candidateKind:'NO_CAPABILITY_EVIDENCE',observation,evidenceEligibility:'INELIGIBLE',evidencePolarity:'NOT_APPLICABLE',evidenceScope:'NOT_APPLICABLE',productionMode:'NOT_PRODUCTION',supportBeforeResponse:'NONE',semanticProvenance:'NOT_APPLICABLE',contextNovelty:'NOT_APPLICABLE',confidence:'HIGH',competingExplanations:[],taskAffordanceChecked:true});
function decision(input:RelevantTeacherContextV3,kind:TeacherInterventionDecisionV3,action:TeacherActionV3,utterance:string,options:{eventType?:string;family?:TeacherDecisionV3['eventInterpretation']['eventFamily'];grounded?:boolean;ambiguous?:boolean;support?:TeacherDecisionV3['decision']['supportLevel'];hypotheses?:TeacherDecisionV3['competingHypotheses'];evidence?:EvidenceCandidateV3[];objective?:string;goalEffect?:TeacherDecisionV3['eventInterpretation']['currentGoalEffect'];interaction?:TeacherDecisionV3['interactionEffectCandidates']}={}):TeacherDecisionV3{const ambiguous=options.ambiguous??false;return{taskAlignment:{taskId:input.task?.id??null,learningNeedId:input.learningNeedId??null,targetRef:input.targetRef??null,evidenceLimitsRespected:true},eventInterpretation:{eventFamily:options.family??'ENGLISH_PERFORMANCE',eventType:options.eventType??'PRODUCTION',isTaskAnswer:(options.family??'ENGLISH_PERFORMANCE')==='ENGLISH_PERFORMANCE',currentGoalEffect:options.goalEffect??'UNCHANGED'},grounding:{status:ambiguous?'UNRESOLVED':options.grounded===false?'PARTIAL':'GROUNDED',materialAmbiguity:ambiguous,referentStatus:ambiguous?'UNRESOLVED':'RESOLVED',candidateInterpretations:ambiguous?[{interpretation:'The short turn may refer to more than one current object',confidence:'MEDIUM',wouldChangeAction:true}]:[],clarificationNeeded:ambiguous},observations:[{observation:input.learnerEvent||input.requestKind||'system event',scope:(options.family??'ENGLISH_PERFORMANCE')==='ENGLISH_PERFORMANCE'?'WHOLE_OUTPUT':'DIALOGUE',confidence:'HIGH'}],competingHypotheses:options.hypotheses??[],decision:{interventionDecision:kind,teacherAction:action,supportLevel:options.support??'NONE',objective:options.objective??utterance,rationale:`Selected from current task, grounding, evidence limits, and relevant history; not a fixed step.`,replanIf:['learner supplies contradictory meaning','the teaching move causes confusion','task or goal changes'],stopIf:['the current need is resolved or no longer worth interrupting']},evidenceCandidates:options.evidence??[noEvidence('No justified capability evidence from this event')],interactionEffectCandidates:options.interaction??[],learnerFacing:{utterance,requiresLearnerOutput:['CLARIFY_REFERENT','CLARIFY_INTENT','CLARIFY_TRANSCRIPT','SELF_REPAIR_PROMPT','GUIDED_REVISION','RECONSTRUCT','TRANSFER_CHECK'].includes(action),outputScope:null}}}
export function planTeacherDecisionV3(input:RelevantTeacherContextV3):TeacherDecisionV3{const text=input.learnerEvent.trim(),lower=text.toLowerCase();
 if(input.requestKind==='AMBIGUOUS_REFERENT')return decision(input,'CLARIFY','CLARIFY_REFERENT','Clarify the material referent minimally before diagnosis.',{family:'UNRESOLVED',eventType:'AMBIGUOUS_ELLIPSIS',ambiguous:true});
 if(input.requestKind==='HELP_SIGNAL')return decision(input,'INTERVENE','DISCRIMINATING_PROBE','Use the current prompt to locate the difficulty without declaring a broad gap.',{family:'PEDAGOGICAL_RESPONSE',eventType:'HELP_REQUEST',support:'LIGHT'});
 if(input.requestKind==='RESTATE_TASK')return decision(input,'ANSWER','ANSWER_QUESTION','Restate the current instruction succinctly.',{family:'DIALOGUE_MANAGEMENT',eventType:'QUESTION'});
 if(input.requestKind==='DEFER_INTENT')return decision(input,'DEFER','DEFER','Meaning-dependent claims are deferred while intent remains unavailable.',{family:'UNRESOLVED',eventType:'AMBIGUOUS_ELLIPSIS',grounded:false});
 if(input.requestKind==='ACKNOWLEDGE')return decision(input,'ACKNOWLEDGE','ACKNOWLEDGE','Acknowledge the learner context without capability inference.',{family:'DIALOGUE_MANAGEMENT',eventType:'CONTEXT_SUPPLEMENT'});
 if(input.requestKind==='ANSWER')return decision(input,'ANSWER','ANSWER_QUESTION','Answer the current request without scoring it as production.',{family:'DIALOGUE_MANAGEMENT',eventType:'QUESTION'});
 if(input.requestKind==='ARTIFACT_RESULT_REQUEST')return decision(input,'ANSWER','ANSWER_QUESTION','Deliver the coherent revised artifact using confirmed context and preferences; do not treat Teacher-authored text as learner evidence.',{family:'DIALOGUE_MANAGEMENT',eventType:'ARTIFACT_RESULT_REQUEST',goalEffect:'CHANGED'});
 if(input.requestKind==='INTERVENE')return decision(input,'INTERVENE','DISCRIMINATING_PROBE','Intervene on the justified local bottleneck while preserving uncertainty.',{support:'LIGHT'});
 if(input.requestKind==='CONTINUE')return decision(input,'CONTINUE','CONTINUE_TASK','Continue; no additional intervention is justified.');
 if(input.requestKind==='SELF_REPAIR_COMPLETE')return decision(input,'CONTINUE','RETURN_TO_SOURCE','Independent self-repair is observed; stop the micro-intervention and return to authentic work.',{eventType:'SELF_REPAIR'});
 if(input.requestKind==='TRANSFER_SUCCESS')return decision(input,'ACKNOWLEDGE','ACKNOWLEDGE','Record changed-context performance separately from source evidence.',{eventType:'TRANSFER_ATTEMPT'});
 if(input.requestKind==='DELAYED_SUCCESS')return decision(input,'ACKNOWLEDGE','ACKNOWLEDGE','Record delayed-context evidence separately without rewriting earlier support history.',{eventType:'TRANSFER_ATTEMPT'});
 if(input.requestKind==='FORM_CONTRAST')return decision(input,'INTERVENE','FORM_CONTRAST','Use the repeatedly helpful comparable strategy, while keeping it revisable.',{support:'LIGHT'});
 if(input.requestKind==='SPELLING_REPRESENTATION')return decision(input,'INTERVENE','REPRESENT_DIFFERENTLY','Use a spelling-specific representation; do not generalize a grammar strategy.',{support:'LIGHT'});
 if(input.requestKind==='OCR_CORRECTION')return decision(input,'ACKNOWLEDGE','ACKNOWLEDGE','Transcript corrected. This is not learning evidence.',{family:'DIALOGUE_MANAGEMENT',eventType:'CLARIFICATION',evidence:[{...noEvidence('OCR transcript correction'),candidateKind:'OCR_CORRECTION'}]});
 if(input.requestKind==='RETURN_TO_SOURCE'||/original (?:artifact|version|source)/i.test(text))return decision(input,'ANSWER','RETURN_TO_SOURCE','Returning the immutable original artifact.',{family:'DIALOGUE_MANAGEMENT',eventType:'GOAL_SHIFT',goalEffect:'CHANGED'});
 if(input.ocrUnresolved)return decision(input,'CLARIFY','CLARIFY_TRANSCRIPT','Confirm the uncertain transcript before diagnosis.',{family:'UNRESOLVED',eventType:'CLARIFICATION',ambiguous:true});
 if(/\?|what does|right\?|score|final version|how (?:many|much)/i.test(text))return decision(input,'ANSWER','ANSWER_QUESTION','Answer the learner’s current question, then resume only if useful.',{family:'DIALOGUE_MANAGEMENT',eventType:'QUESTION',goalEffect:'REFINED'});
 if(/pause|later|not now|defer/i.test(text)||input.requestKind==='PAUSE')return decision(input,'ACKNOWLEDGE','ACKNOWLEDGE','Pause without recording failure.',{family:'DIALOGUE_MANAGEMENT',eventType:'PAUSE_SKIP_DEFER'});
 if(/don'?t understand|more confused|huh|who is missing|understood before/i.test(lower))return decision(input,'INTERVENE','CHANGE_STRATEGY','The prior representation may have caused confusion; change strategy.',{family:'PEDAGOGICAL_RESPONSE',eventType:'CONFUSION',support:'MEDIUM',interaction:[{strategy:input.previousAction??'UNKNOWN',effect:'CONFUSED',confidence:'HIGH',confounds:['grounding may also have failed']}],hypotheses:[{hypothesis:'TEACHER_INDUCED_CONFUSION or representation mismatch',confidence:'HIGH',evidenceFor:[text],evidenceAgainst:[],unknowns:['whether prerequisite is also missing']}]});
 if(/teacher.*wrong|that is not what i mean|i meant|no[, ]|but .*correct|darkening/i.test(lower)||input.requestKind==='CORRECT_TEACHER')return decision(input,'ACKNOWLEDGE','ACKNOWLEDGE','Withdraw the contradicted Teacher hypothesis and rebuild from learner-owned meaning.',{family:'DIALOGUE_MANAGEMENT',eventType:'CORRECT_TEACHER',goalEffect:'REFINED',hypotheses:[{hypothesis:'Prior Teacher interpretation is contradicted',confidence:'HIGH',evidenceFor:[text],evidenceAgainst:[],unknowns:[]}]});
 if(input.artifactAge==='OLD'&&input.originalIntentAvailable===false){if(/spell|enviroment|signigicant/i.test(`${text} ${input.sourceExcerpt??''}`))return decision(input,'INTERVENE','SELF_REPAIR_PROMPT','Address the observable form while keeping original intent unavailable.',{support:'LIGHT'});return decision(input,'DEFER','DEFER','Intent-dependent diagnosis is deferred; memory loss is not English evidence.',{family:'UNRESOLVED',eventType:'AMBIGUOUS_ELLIPSIS',grounded:false});}
 if(input.visibleModel&&text===input.visibleModel)return decision(input,'INTERVENE','FADE_SUPPORT','Correct model reproduction remains modeled; now fade support.',{support:'MODEL',evidence:[{candidateKind:'CAPABILITY',observation:'Exact visible-model reproduction',capabilityDomain:'FORM',capabilityFacet:'CONTROLLED_PRODUCTION',evidenceEligibility:'ELIGIBLE',evidencePolarity:'POSITIVE',evidenceScope:'LOCAL',productionMode:'MODELED',supportBeforeResponse:'MODEL',semanticProvenance:input.task?.meaningProvenance??'TEACHER_SUPPLIED',contextNovelty:input.task?.contextNovelty??'SAME_CONTEXT',confidence:'HIGH',competingExplanations:['imitation rather than control'],taskAffordanceChecked:true,taskId:input.task?.id,targetRef:input.targetRef}]});
 if(/make the environment better|major impact|students should be allowed to/i.test(lower))return decision(input,'ACKNOWLEDGE','ACKNOWLEDGE','Accept the valid English alternative without forcing a planned wording.');
 if(/allow\s+to\b/i.test(lower))return decision(input,'INTERVENE','DECOMPOSE','Make the missing semantic/syntactic role visible; active and passive meanings remain possible.',{support:'LIGHT',hypotheses:[{hypothesis:'allow + receiver + to-infinitive frame is unstable',confidence:'MEDIUM',evidenceFor:[text],evidenceAgainst:[],unknowns:['active or passive intended meaning']},{hypothesis:'object omitted under writing load',confidence:'LOW',evidenceFor:[text],evidenceAgainst:[],unknowns:['history and independent retry']}]});
 if(/signigicant/i.test(lower)){const facet=input.learnerModel.capabilitySlice.find(x=>x.targetRef.includes('significant')&&x.facet==='ORTHOGRAPHIC_PRODUCTION');const strong=facet?.state==='RETENTION_SUPPORTED'||facet?.state==='TRANSFER_SUPPORTED'||facet?.state==='INDEPENDENT_LOCAL_CONTROL';return strong?decision(input,'INTERVENE','SELF_REPAIR_PROMPT','Strong history makes a slip plausible; request minimal self-repair.',{support:'LIGHT',hypotheses:[{hypothesis:'performance slip',confidence:'HIGH',evidenceFor:facet.sourceEvidenceIds,evidenceAgainst:[],unknowns:[]},{hypothesis:'orthographic instability',confidence:'LOW',evidenceFor:[text],evidenceAgainst:facet.sourceEvidenceIds,unknowns:[]}] }):decision(input,'INTERVENE','DISCRIMINATING_PROBE','Distinguish recognition, retrieval, and orthographic production before teaching.',{support:'LIGHT',hypotheses:[{hypothesis:'orthographic production is fragile',confidence:'MEDIUM',evidenceFor:[text],evidenceAgainst:[],unknowns:['recognition and history']},{hypothesis:'one performance slip',confidence:'LOW',evidenceFor:[text],evidenceAgainst:[],unknowns:['recurrence']}]});}
 if(/encourage .* to more read/i.test(lower))return decision(input,'INTERVENE','SELF_REPAIR_PROMPT','Preserve local encourage + object + to-verb success and isolate read more word order.',{support:'LIGHT'});
 if(input.requestKind==='TRANSFER_CHECK')return decision(input,'INTERVENE','TRANSFER_CHECK','Check independent production in a changed context.',{support:'NONE'});
 if(input.requestKind==='DELAYED_CHECK')return decision(input,'INTERVENE','DELAYED_CHECK','Check retention independently after delay.',{support:'NONE'});
 return decision(input,'CONTINUE','CONTINUE_TASK','Continue without manufacturing an intervention.');}
