import type{LexicalEncounterEventV1,LexicalLookupDirectionV1}from'../../learner-truth/lexicalEncounter';
export type TeachingHypothesisV1='RECOGNITION_PRESENT'|'SENSE_CONFUSION'|'PHRASE_BOUNDARY_CONFUSION'|'CHUNK_VS_WORD_CONFUSION'|'RETRIEVAL_FAILURE'|'READING_EVIDENCE_GAP'|'READING_REASONING_GAP'|'TRANSLATION_LOCAL_BOTTLENECK';
export type VerificationHorizonV1='IMMEDIATE_TREATMENT'|'INTERLEAVED_SURPRISE'|'DELAYED_FRESH';
export type GsatFamilyV1='VOCABULARY'|'COMPREHENSIVE'|'CONTEXTUAL_FILL'|'DISCOURSE'|'READING'|'MIXED'|'TRANSLATION'|'WRITING';
export const gsatProductionFamiliesV1:readonly GsatFamilyV1[]=Object.freeze(['VOCABULARY','COMPREHENSIVE','CONTEXTUAL_FILL','DISCOURSE','READING','MIXED','TRANSLATION','WRITING']);
const familyAlias:Readonly<Record<string,GsatFamilyV1|undefined>>=Object.freeze({VOCABULARY:'VOCABULARY',VOCABULARY_USAGE:'VOCABULARY',PHRASES_COLLOCATIONS:'VOCABULARY',COMPREHENSIVE:'COMPREHENSIVE',CLOZE:'COMPREHENSIVE',GRAMMAR:'COMPREHENSIVE',CONTEXTUAL_FILL:'CONTEXTUAL_FILL',DISCOURSE:'DISCOURSE',READING:'READING',MIXED:'MIXED',TRANSLATION:'TRANSLATION',WRITING:'WRITING'});
export const canonicalGsatFamilyV1=(family:string|undefined)=>family?familyAlias[family.toUpperCase()]:undefined;
export function gsatPriorityScoreV1(input:{expectedScoreGain:number;recurrence:number;crossFamilyTransfer:number;learnerNeed:number;recoverability:number;urgency:number;timeCost:number}){const numerator=input.expectedScoreGain*input.recurrence*input.crossFamilyTransfer*input.learnerNeed*input.recoverability*input.urgency;return input.timeCost>0?numerator/input.timeCost:0}
export function validateGsatFreshContentV1(input:{family:string;highSchoolAppropriate:boolean;naturalContemporaryEnglish:boolean;gsatDifficultyAppropriate:boolean;constructAligned:boolean;obscureKnowledgeDependency:boolean;answerLeakage:boolean;syntheticPhrasing:boolean;boundedLength:boolean}){const family=canonicalGsatFamilyV1(input.family),reasons:string[]=[];if(!family)reasons.push('NON_GSAT_FAMILY');if(!input.highSchoolAppropriate)reasons.push('NOT_HIGH_SCHOOL_APPROPRIATE');if(!input.naturalContemporaryEnglish)reasons.push('UNNATURAL_ENGLISH');if(!input.gsatDifficultyAppropriate)reasons.push('NON_GSAT_DIFFICULTY');if(!input.constructAligned)reasons.push('CONSTRUCT_MISMATCH');if(input.obscureKnowledgeDependency)reasons.push('OBSCURE_KNOWLEDGE_DEPENDENCY');if(input.answerLeakage)reasons.push('ANSWER_LEAKAGE');if(input.syntheticPhrasing)reasons.push('SYNTHETIC_PHRASING');if(!input.boundedLength)reasons.push('UNBOUNDED_MOVE');return Object.freeze({accepted:reasons.length===0,family,reasons:Object.freeze(reasons)})}
export interface BoundedTeachingRouteV1{hypothesis:TeachingHypothesisV1;attempt:number;blockId:string;learnerAction:string;support:'NONE'|'LIGHT'|'CUED'|'GUIDED'|'EXPLICIT'|'MODELED';next:'FADE'|'SWITCH_REPRESENTATION'|'CHECK_PREREQUISITE'|'SCHEDULE_REACTIVATION'|'MOVE_ON';capabilityEvidenceAllowed:false}
const accountFor:Readonly<Record<string,TeachingHypothesisV1>>=Object.freeze({'占、構成':'RECOGNITION_PRESENT','占、构成':'RECOGNITION_PRESENT','解釋／造成':'SENSE_CONFUSION','解释／造成':'SENSE_CONFUSION','考慮到':'PHRASE_BOUNDARY_CONFUSION','考虑到':'PHRASE_BOUNDARY_CONFUSION','登入帳戶':'CHUNK_VS_WORD_CONFUSION','登录账户':'CHUNK_VS_WORD_CONFUSION'});
export function diagnoseAccountForDistractorV1(label:string):TeachingHypothesisV1{return accountFor[label.trim()]??'RETRIEVAL_FAILURE'}
const routes:Readonly<Record<TeachingHypothesisV1,readonly string[]>>=Object.freeze({
 RECOGNITION_PRESENT:['meaning-word-retrieval','chunk-builder'],SENSE_CONFUSION:['sense-contrast','meaning-representation','form-contrast'],PHRASE_BOUNDARY_CONFUSION:['chunk-as-unit','phrase-reconstruction','slot-completion'],CHUNK_VS_WORD_CONFUSION:['chunk-as-unit','collocation-match','meaning-word-retrieval'],RETRIEVAL_FAILURE:['meaning-word-retrieval','chunk-completion','chunk-builder'],READING_EVIDENCE_GAP:['inference-evidence-bridge','reading-evidence-operation','fresh-reading-check'],READING_REASONING_GAP:['distractor-evidence-contrast','claim-strength-contrast','fresh-reading-check'],TRANSLATION_LOCAL_BOTTLENECK:['meaning-segmentation','translation-chunk-builder','independent-translation']});
export function boundedTeachingRouteV1(hypothesis:TeachingHypothesisV1,attempt:number):BoundedTeachingRouteV1{const index=Math.max(0,Math.min(attempt-1,2)),blockId=routes[hypothesis][index],third=attempt>=3;return Object.freeze({hypothesis,attempt,blockId,learnerAction:index===0?'完成診斷對應的互動':index===1?'用不同表示重新操作':'縮小目標或檢查先備能力',support:index===0?'LIGHT':index===1?'GUIDED':'EXPLICIT',next:attempt===1?'SWITCH_REPRESENTATION':attempt===2?'CHECK_PREREQUISITE':third?'SCHEDULE_REACTIVATION':'MOVE_ON',capabilityEvidenceAllowed:false})}
export function verificationPolicyV1(input:{horizon:VerificationHorizonV1;supportVisible:boolean;targetAnnounced:boolean;surfaceChanged:boolean;unrelatedWorkIntervened:boolean;delayed:boolean;learnerAuthored:boolean;usedTarget:boolean;validAlternative:boolean}){const immediate=input.horizon==='IMMEDIATE_TREATMENT',independent=input.learnerAuthored&&!input.supportVisible&&!input.targetAnnounced,eligible=independent&&!immediate&&input.surfaceChanged&&(input.horizon==='INTERLEAVED_SURPRISE'?input.unrelatedWorkIntervened:input.delayed),targetRetrievalCredited=eligible&&input.usedTarget;return Object.freeze({translationOrTaskCorrect:input.usedTarget||input.validAlternative,treatmentResponseRecorded:immediate,durableMasteryAllowed:eligible,targetRetrievalCredited,alternativePreserved:input.validAlternative&&!input.usedTarget,reasonCodes:Object.freeze(immediate?['IMMEDIATE_EXPECTANCY_CEILING']:input.validAlternative&&!input.usedTarget?['VALID_ALTERNATIVE_NO_TARGET_INFERENCE']:eligible?['FRESH_INDEPENDENT_EVIDENCE']:['ASSISTED_OR_NOT_FRESH'])})}
export function lookupTeacherProbeV1(events:readonly LexicalEncounterEventV1[],target:string,gsatUseValue=1){const relevant=events.filter(event=>event.normalizedTargetCandidate===target&&event.lookupResultExposed&&Boolean(canonicalGsatFamilyV1(event.sourceFamily))),priorityEligible=gsatUseValue>0&&relevant.length>0,en=relevant.filter(event=>event.lookupDirection==='EN_TO_ZH').length,zh=relevant.filter(event=>event.lookupDirection==='ZH_TO_EN').length;return Object.freeze({target,firstProbe:!priorityEligible?'QUICK_DIAGNOSTIC':zh>en?'RETRIEVAL_OR_PHRASE_PRODUCTION':en?'RECOGNITION_OR_CONTEXTUAL_SENSE':'QUICK_DIAGNOSTIC',reactivateBeforeReteach:priorityEligible,lookupCount:relevant.length,priorityEligible,capabilityDelta:0})}
export function lookupContaminatesConstructV1(input:{event:Pick<LexicalEncounterEventV1,'responsePhase'|'lookupDirection'|'canonicalTargetRef'>;claimTargetRef:string;direction:LexicalLookupDirectionV1}){return input.event.responsePhase==='PRE_RESPONSE'&&input.event.lookupDirection===input.direction&&Boolean(input.event.canonicalTargetRef===input.claimTargetRef||input.event.canonicalTargetRef==='lexical.contextual-fit')}
export const teachingLookupRetentionFrontstageBanV1=Object.freeze(['evidence tier','support level','diagnosis confidence','treatment response','activation score','retention score','scheduler reason','target id','block id']);
