import {router} from 'expo-router';
import React,{useMemo,useRef,useState} from 'react';
import {Pressable,StyleSheet,Text,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {useLearnerBack} from '../components/experience/useLearnerBack';
import {useCanonicalProductData} from '../context/AppDataContext';
import {savePrivateBetaProductEventV1} from '../src/market-validation/privateBetaPulse';
import {GSAT_STAGE1_PROBES_V1,routeGsatCalibrationStage2V1,type GsatCalibrationProbeV1} from '../src/product-policy/exam/gsatCalibrationRuntime';
import {eotLearnerTokensV1 as t} from '../src/ui';

export default function QuickCalibration(){
  const{learnerPreferences}=useCanonicalProductData(),[started,setStarted]=useState(false),[stage,setStage]=useState<1|2>(1),[index,setIndex]=useState(0),[results,setResults]=useState<{probeId:string;correct:boolean;confidence:number}[]>([]),[stage2,setStage2]=useState<readonly GsatCalibrationProbeV1[]>([]);
  const probes=stage===1?GSAT_STAGE1_PROBES_V1:stage2,probe=probes[index],sessionId=useMemo(()=>`calibration:${learnerPreferences.learnerId}`,[learnerPreferences.learnerId]),actionInFlight=useRef(false);
  const exit=()=>router.replace('/(tabs)' as never);
  useLearnerBack(exit);
  async function begin(){if(actionInFlight.current)return;actionInFlight.current=true;try{setStarted(true);await savePrivateBetaProductEventV1({learnerId:learnerPreferences.learnerId,sessionId,taskId:'GSAT-CALIBRATION',family:'CALIBRATION',type:'QUICK_CALIBRATION_STARTED',eventKey:'started'})}finally{actionInFlight.current=false}}
  async function answer(correct:boolean){if(actionInFlight.current||!probe)return;actionInFlight.current=true;try{const next=[...results,{probeId:probe.id,correct,confidence:.7}];if(index+1<probes.length){setResults(next);setIndex(index+1);return}if(stage===1){const routed=routeGsatCalibrationStage2V1(next);setResults(next);setStage2(routed);if(routed.length){setStage(2);setIndex(0);await savePrivateBetaProductEventV1({learnerId:learnerPreferences.learnerId,sessionId,taskId:'GSAT-CALIBRATION',family:routed[0].family,type:'QUICK_CALIBRATION_STAGE2_ROUTED',eventKey:'stage2'});return}}await savePrivateBetaProductEventV1({learnerId:learnerPreferences.learnerId,sessionId,taskId:'GSAT-CALIBRATION',family:'CALIBRATION',type:'QUICK_CALIBRATION_COMPLETED',eventKey:'completed'});router.replace('/(tabs)' as never)}finally{actionInFlight.current=false}}
  return <SafeAreaView style={s.safe}><View style={s.page}><Pressable accessibilityRole="button" accessibilityLabel="返回" onPress={exit} style={s.back}><Text style={s.backText}>‹ 返回</Text></Pressable><Text style={s.kicker}>{started?(stage===1?'先做一個小動作':'換一點情境再試'):'第一次使用'}</Text><Text style={s.title}>{started?(stage===1?'讓 EOT 看懂怎麼教你':'再試一次，就能開始今天的學習'):'先讓 EOT 認識你的英文'}</Text>{!started?<><Text style={s.body}>先做幾個很短的英文動作，EOT 會從你的答案開始教，再安排今天最值得學的一步。</Text><Pressable onPress={()=>void begin()}style={s.primary}><Text style={s.primaryText}>做第一個小動作</Text></Pressable></>:probe?<><Text style={s.progress}>{index===0?(stage===1?'先從這裡開始':'換個情境試試'):'接著試試'}</Text><View style={s.card}><Text style={s.prompt}>{probe.prompt}</Text>{probe.choices.map(choice=><Pressable key={choice.label}onPress={()=>void answer(choice.correct)}style={s.choice}><Text style={s.choiceText}>{choice.label}</Text></Pressable>)}</View></>:<Text style={s.body}>正在安排今天的第一步…</Text>}</View></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:t.colors.background},page:{flex:1,width:'100%',maxWidth:430,alignSelf:'center',padding:22,gap:16},back:{minHeight:44,alignSelf:'flex-start',justifyContent:'center',paddingRight:18},backText:{color:t.colors.deepWood,fontWeight:'800'},kicker:{fontSize:12,fontWeight:'900',color:t.colors.midWood},title:{fontSize:29,lineHeight:37,fontWeight:'900',color:t.colors.ink},body:{fontSize:16,lineHeight:25,color:t.colors.muted},progress:{fontSize:13,color:t.colors.subtle,fontWeight:'800'},card:{padding:18,borderRadius:18,backgroundColor:t.colors.paper,gap:12},prompt:{fontSize:19,lineHeight:29,fontWeight:'800',color:t.colors.ink},choice:{minHeight:54,borderWidth:1,borderColor:t.colors.line,borderRadius:14,padding:14,justifyContent:'center'},choiceText:{fontSize:16,color:t.colors.ink},primary:{minHeight:56,borderRadius:14,backgroundColor:t.colors.deepWood,alignItems:'center',justifyContent:'center'},primaryText:{fontSize:16,fontWeight:'900',color:t.colors.paper}});
