import { eotLearnerTokensV1 as woodTheme } from '../src/ui/tokens';
import { Href, router, useLocalSearchParams } from 'expo-router';
import React,{useEffect,useMemo,useRef,useState} from 'react';
import { Pressable,StyleSheet,Text,TextInput,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { KeyboardAwareScrollView } from 'react-native-keyboard-controller';
import { useLearnerBack } from '../components/experience/useLearnerBack';
import { useCanonicalProductData } from '../context/AppDataContext';
import { readingAttemptStoreV1,saveOperationalLessonCheckpointV1 } from '../src/persistence';
import { answerReadingItemV1,commitReadingResultV1,createCanonicalReadingReviewV1,diagnoseReadingPostAttemptV1,readingClockProjectionV1,startCanonicalReadingReviewSessionV1,startReadingAttemptV1,submitReadingAttemptV1,type ReadingAttemptModeV1,type ReadingAttemptV1,type ReadingReviewFocusV1 } from '../src/specializations/language';
import { eotLearnerTokensV1 as t } from '../src/ui';
import { UniversalLookupText } from '../components/learning/UniversalLookupText';
import { productTaskByIdV1, productTaskForFamilyV1 } from '../src/content';
const modes:ReadingAttemptModeV1[]=['PRACTICE','MOCK','FORMAL'];
const reviewKinds:ReadingReviewFocusV1['kind'][]=['REFERENCE_RESOLUTION','INFERENCE_BRIDGE','OPTION_CONTRAST','LOGICAL_RELATION','VOCABULARY_IN_CONTEXT','STEM_MISREAD','EVIDENCE_SELECTION'];
const modeLabel:Record<ReadingAttemptModeV1,string>={PRACTICE:'練習',MOCK:'模擬',FORMAL:'正式'};
const reviewLabel:Record<ReadingReviewFocusV1['kind'],string>={REFERENCE_RESOLUTION:'指代關係',INFERENCE_BRIDGE:'推論連結',OPTION_CONTRAST:'選項比較',LOGICAL_RELATION:'邏輯關係',VOCABULARY_IN_CONTEXT:'上下文字義',STEM_MISREAD:'題目理解',EVIDENCE_SELECTION:'文章證據'};
export default function ReadingAttempt(){
  const routeContext=useLocalSearchParams<{origin?:string;practiceFamily?:string;practiceArea?:string;amount?:string;systemTask?:string}>();
  const{learnerPreferences,runtimeProductContext}=useCanonicalProductData();
  const[attempt,setAttempt]=useState<ReadingAttemptV1|null>(null),[passage,setPassage]=useState(''),[stem,setStem]=useState(''),[answer,setAnswer]=useState(''),[activeQuestionId,setActiveQuestionId]=useState(''),[mode,setMode]=useState<ReadingAttemptModeV1>('PRACTICE'),[now,setNow]=useState(new Date().toISOString()),[reviewQuestionId,setReviewQuestionId]=useState(''),[reviewKind,setReviewKind]=useState<ReadingReviewFocusV1['kind']>(),[reviewExplanation,setReviewExplanation]=useState(''),[reviewEvidence,setReviewEvidence]=useState(''),[reviewError,setReviewError]=useState('');
  const submitInFlight=useRef(false);
  const systemTask=routeContext.systemTask?routeContext.systemTask==='AUTO'?productTaskForFamilyV1('READING'):productTaskByIdV1(routeContext.systemTask):undefined;
  useEffect(()=>{void readingAttemptStoreV1.load(learnerPreferences.learnerId).then(value=>{if(value&&value.state!=='CLOSE'){const id=value.answers[0]?.questionId??value.source.questions[0]?.id??'';setAttempt(value);setActiveQuestionId(id);setAnswer(value.answers.find(x=>x.questionId===id)?.response??'');return}if(systemTask?.family==='READING'&&systemTask.passage){const at=new Date().toISOString(),questionId=`${systemTask.id}:q`;setActiveQuestionId(questionId);void keep(startReadingAttemptV1({id:`reading-${systemTask.id}-${Date.now()}`,learnerId:learnerPreferences.learnerId,mode:'PRACTICE',startedAt:at,source:{id:`source-${systemTask.id}`,passage:systemTask.passage,sourceRef:`${systemTask.provenance}:${systemTask.id}`,immutable:true,questions:[{id:questionId,passageId:`source-${systemTask.id}`,stem:systemTask.prompt,options:systemTask.options?.map((text,index)=>({id:String(index),text})),rubricRef:`${systemTask.id}:${systemTask.acceptedAnswers.join('|')}`}]}}))}})},[learnerPreferences.learnerId,systemTask]);
  useEffect(()=>{if(!attempt?.clock||attempt.immutableSubmit)return;const id=setInterval(()=>setNow(new Date().toISOString()),1000);return()=>clearInterval(id)},[attempt]);
  const clock=useMemo(()=>attempt?readingClockProjectionV1(attempt,now):null,[attempt,now]);
  useEffect(()=>{if(attempt&&clock?.timed&&clock.exhausted&&!attempt.immutableSubmit)void submit()},[attempt,clock]); // eslint-disable-line react-hooks/exhaustive-deps
  async function keep(next:ReadingAttemptV1){setAttempt(next);await readingAttemptStoreV1.save(next)}
  async function start(){if(!passage.trim()||!stem.trim())return;const at=new Date().toISOString(),sourceId=`source-${Date.now()}`,questionId='q1';setActiveQuestionId(questionId);await keep(startReadingAttemptV1({id:`reading-${Date.now()}`,learnerId:learnerPreferences.learnerId,mode,startedAt:at,budgetSeconds:mode==='PRACTICE'?undefined:1200,source:{id:sourceId,passage:passage.trim(),sourceRef:'LEARNER_IMPORTED_READING',immutable:true,questions:[{id:questionId,passageId:sourceId,stem:stem.trim()}]}}))}
  async function saveAnswer(value:string){setAnswer(value);if(attempt){const questionId=activeQuestionId||attempt.source.questions[0]?.id;if(questionId)await keep(answerReadingItemV1(attempt,{questionId,response:value,updatedAt:new Date().toISOString()}))}}
  const exitReading=()=>router.replace(routeContext.origin==='TODAY'?('/(tabs)' as Href):('/(tabs)/practice' as Href));
  useLearnerBack(exitReading);
  async function submit(){if(!attempt||submitInFlight.current||attempt.immutableSubmit)return;submitInFlight.current=true;try{await keep(commitReadingResultV1(submitReadingAttemptV1(attempt,new Date().toISOString()),new Date().toISOString()))}finally{submitInFlight.current=false}}
  async function beginReview(){if(!attempt)return;const diagnosis=diagnoseReadingPostAttemptV1({attempt,questionId:reviewQuestionId||undefined,learnerSelectedFocus:reviewKind,learnerExplanation:reviewExplanation,learnerEvidenceAnchor:reviewEvidence});if(diagnosis.status!=='FOCUS_READY'){setReviewError('目前證據不足以安全判斷閱讀瓶頸。請選擇題目與回看重點，說明當時想法，並貼出支持你的文章片段。');return}const review=createCanonicalReadingReviewV1({id:`reading-review-${attempt.id}-${diagnosis.focus.questionId}`,attempt,focus:diagnosis.focus,timeBudgetMinutes:Math.min(10,runtimeProductContext.studyMinutes),productMode:runtimeProductContext.productMode}),runtime=startCanonicalReadingReviewSessionV1(review,new Date().toISOString());await readingAttemptStoreV1.saveReview(review);await saveOperationalLessonCheckpointV1(review.lessonPlan,runtime);router.push(`/daily-lesson?readingReviewId=${encodeURIComponent(review.id)}&origin=${encodeURIComponent(routeContext.origin??'PRACTICE')}&practiceFamily=READING&practiceArea=${encodeURIComponent(routeContext.practiceArea??diagnosis.focus.kind)}&amount=${encodeURIComponent(routeContext.amount??'建議')}` as Href)}
  if(!attempt)return <Shell onBack={exitReading}><Text style={s.kicker}>閱讀 · 匯入自己的題目</Text><Text style={s.title}>先完成整份作答，再決定要學什麼</Text><TextInput accessibilityLabel="閱讀文章" multiline value={passage} onChangeText={setPassage} placeholder="貼上閱讀文章" style={s.input}/><TextInput accessibilityLabel="閱讀問題" value={stem} onChangeText={setStem} placeholder="貼上題目" style={s.input}/><View style={s.row}>{modes.map(item=><Pressable accessibilityRole="button" accessibilityState={{selected:mode===item}} onPress={()=>setMode(item)} key={item} style={[s.mode,mode===item&&s.modeOn]}><Text>{modeLabel[item]}</Text></Pressable>)}</View>{passage.trim()&&stem.trim()?<Pressable accessibilityRole="button" onPress={()=>void start()} style={s.primary}><Text style={s.primaryText}>開始閱讀作答</Text></Pressable>:null}</Shell>;
  if(attempt.state==='RESULT')return <Shell onBack={exitReading}><Text style={s.kicker}>作答已提交</Text><Text style={s.title}>選擇真正要回看的題目與推理</Text><Text style={s.body}>原答案保持不變。沒有授權答案時，系統不會猜你的閱讀瓶頸。</Text>{attempt.source.questions.map(q=><Pressable key={q.id} accessibilityRole="button" accessibilityState={{selected:reviewQuestionId===q.id}} onPress={()=>setReviewQuestionId(q.id)} style={[s.mode,reviewQuestionId===q.id&&s.modeOn]}><Text>{q.stem}</Text><Text style={s.note}>{attempt.answers.find(a=>a.questionId===q.id)?.response||'未作答'}</Text></Pressable>)}<View style={s.row}>{reviewKinds.map(kind=><Pressable key={kind} accessibilityRole="button" accessibilityState={{selected:reviewKind===kind}} onPress={()=>setReviewKind(kind)} style={[s.mode,reviewKind===kind&&s.modeOn]}><Text>{reviewLabel[kind]}</Text></Pressable>)}</View><TextInput accessibilityLabel="當時的閱讀推理" multiline value={reviewExplanation} onChangeText={setReviewExplanation} placeholder="我當時為什麼選這個答案？" style={s.input}/><TextInput accessibilityLabel="文章證據片段" multiline value={reviewEvidence} onChangeText={setReviewEvidence} placeholder="貼出支持你想法的文章片段" style={s.input}/>{reviewError?<Text style={s.note}>{reviewError}</Text>:null}<Pressable accessibilityRole="button" onPress={()=>void beginReview()} style={s.primary}><Text style={s.primaryText}>建立有證據的回看</Text></Pressable><Text style={s.note}>後續練習會連回這份作答，但不會改寫它。</Text></Shell>;
  const activeQuestion=attempt.source.questions.find(q=>q.id===activeQuestionId)??attempt.source.questions[0],lookupMode=attempt.mode==='PRACTICE'?'NONE' as const:'FORMAL_ASSESSMENT' as const,lookupMeta={sourceFamily:'READING',taskId:attempt.source.id,sessionId:attempt.id,responsePhase:'PRE_RESPONSE' as const};return <Shell onBack={exitReading}><View style={s.row}><Text style={s.kicker}>{modeLabel[attempt.mode]} · 閱讀作答</Text>{clock?.timed?<Text style={s.clock}>{Math.ceil(clock.remainingSeconds/60)} 分鐘</Text>:null}</View><View style={s.card}><UniversalLookupText {...lookupMeta} text={attempt.source.passage}assessmentMode={lookupMode}exposureIdentity={`${attempt.source.id}:passage`}style={s.passage}/></View>{attempt.source.questions.length>1?<View style={s.row}>{attempt.source.questions.map(q=><Pressable key={q.id} onPress={()=>{setActiveQuestionId(q.id);setAnswer(attempt.answers.find(a=>a.questionId===q.id)?.response??'')}} style={[s.mode,activeQuestion?.id===q.id&&s.modeOn]}><Text>{q.id}</Text></Pressable>)}</View>:null}{activeQuestion?<UniversalLookupText {...lookupMeta} text={activeQuestion.stem}instruction style={s.question}/>:null}{activeQuestion?.options?.length?<View style={s.options}>{activeQuestion.options.map(option=><Pressable key={option.id}onPress={()=>void saveAnswer(option.text)}style={[s.option,answer===option.text&&s.modeOn]}><UniversalLookupText {...lookupMeta} text={option.text}paragraph={attempt.source.passage}assessmentMode={lookupMode}/></Pressable>)}</View>:<TextInput accessibilityLabel="你的閱讀答案" multiline value={answer} onChangeText={value=>void saveAnswer(value)} placeholder="寫下你的答案" style={s.input}/>} {attempt.locks.teacher?<Text style={s.note}>正式作答中：Teacher、提示、揭答與查字已鎖定。</Text>:<Text style={s.note}>練習模式可在提交前使用一般支援。</Text>}{attempt.answers.some(a=>a.response.trim())?<Pressable accessibilityRole="button" onPress={()=>void submit()} style={s.primary}><Text style={s.primaryText}>提交整份作答</Text></Pressable>:null}</Shell>
}
function Shell({children,onBack}:{children:React.ReactNode;onBack:()=>void}){return <SafeAreaView style={s.safe}><KeyboardAwareScrollView style={s.safe} contentContainerStyle={s.shell} keyboardShouldPersistTaps="handled" bottomOffset={90}><Pressable accessibilityRole="button" accessibilityLabel="返回" onPress={onBack} style={s.back}><Text style={s.backText}>‹ 返回</Text></Pressable>{children}</KeyboardAwareScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:t.colors.background},shell:{flexGrow:1,width:'100%',maxWidth:430,alignSelf:'center',padding:20,paddingBottom:110,gap:16},back:{minHeight:44,alignSelf:'flex-start',justifyContent:'center',paddingRight:18},backText:{color:t.colors.deepWood,fontWeight:'800'},kicker:{fontSize:12,fontWeight:'900',color:t.colors.deepWood},title:{fontSize:27,lineHeight:36,fontWeight:'900',color:t.colors.ink},body:{fontSize:15,lineHeight:24,color:t.colors.muted},input:{minHeight:54,borderWidth:1,borderColor:t.colors.line,borderRadius:14,padding:14,fontSize:16,textAlignVertical:'top',backgroundColor:t.colors.paper},row:{flexDirection:'row',gap:8,alignItems:'center',justifyContent:'space-between',flexWrap:'wrap'},mode:{minHeight:44,paddingHorizontal:12,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:t.colors.line,borderRadius:10},modeOn:{backgroundColor:woodTheme.colors.woodWash,borderColor:woodTheme.colors.focus},options:{gap:9},option:{minHeight:48,padding:13,justifyContent:'center',borderWidth:1,borderColor:t.colors.line,borderRadius:12,backgroundColor:t.colors.paper},primary:{minHeight:54,borderRadius:14,backgroundColor:woodTheme.colors.deepWood,alignItems:'center',justifyContent:'center'},primaryText:{color:woodTheme.colors.paper,fontWeight:'900'},card:{padding:16,borderRadius:14,backgroundColor:t.colors.paper,borderWidth:1,borderColor:t.colors.line},passage:{fontSize:16,lineHeight:26,color:t.colors.ink},question:{fontSize:18,lineHeight:27,fontWeight:'800',color:t.colors.ink},note:{fontSize:12,lineHeight:18,color:t.colors.muted},clock:{fontSize:12,fontWeight:'800',color:woodTheme.colors.focus}});


