import React,{useEffect,useRef,useState}from'react';
import{AccessibilityInfo,Animated,Pressable,StyleSheet,Text,View}from'react-native';
import{eotLearnerTokensV1 as t}from'../../src/ui';

export function EOTFirstLaunchIntro({active,onFinished,children}:{active:boolean;onFinished:()=>void|Promise<void>;children:React.ReactNode}){
 const[visible,setVisible]=useState(active),finishing=useRef(false),opacity=useRef(new Animated.Value(active?1:0)).current,mark=useRef(new Animated.Value(0)).current;
 useEffect(()=>{if(!active)return;let cancelled=false;void AccessibilityInfo.isReduceMotionEnabled().then(reduced=>{if(cancelled)return;if(reduced){mark.setValue(1);finish(true);return}Animated.timing(mark,{toValue:1,duration:700,useNativeDriver:true}).start()});const timer=setTimeout(()=>finish(),2300);return()=>{cancelled=true;clearTimeout(timer)}},[active]);
 function finish(reduced=false){if(finishing.current)return;finishing.current=true;const done=()=>{setVisible(false);void onFinished()};if(reduced){opacity.setValue(0);done()}else Animated.timing(opacity,{toValue:0,duration:160,useNativeDriver:true}).start(done)}
 return <View style={s.root}>{children}{active&&visible?<Animated.View style={[StyleSheet.absoluteFill,s.overlay,{opacity}]}><Pressable accessibilityRole="button" accessibilityLabel="跳過開場，進入 EOT" onPress={()=>finish()} style={s.press}><View style={s.brand}><Animated.View style={[s.mark,{opacity:mark,transform:[{translateX:mark.interpolate({inputRange:[0,1],outputRange:[-18,0]})}]}]}><Text style={s.arrow}>→</Text></Animated.View><Text style={s.eot}>EOT</Text></View><Text style={s.line}>學過的，讓你真正用得出來。</Text><Text style={s.skip}>點一下直接開始</Text></Pressable></Animated.View>:null}</View>;
}
const s=StyleSheet.create({root:{flex:1},overlay:{backgroundColor:t.colors.background,zIndex:100},press:{flex:1,alignItems:'center',justifyContent:'center',padding:28,gap:22},brand:{flexDirection:'row',alignItems:'center',gap:10},mark:{width:48,height:48,borderRadius:16,alignItems:'center',justifyContent:'center',backgroundColor:t.colors.deepWood},arrow:{fontSize:29,fontWeight:'900',color:t.colors.paper},eot:{fontSize:28,fontWeight:'900',letterSpacing:2,color:t.colors.deepWood},line:{maxWidth:330,fontSize:27,lineHeight:38,fontWeight:'900',letterSpacing:-.4,textAlign:'center',color:t.colors.ink},skip:{position:'absolute',bottom:42,fontSize:13,fontWeight:'800',color:t.colors.subtle}});
