import React,{useEffect,useRef,useState}from'react';
import{AccessibilityInfo,Animated,Pressable,StyleSheet,Text,View}from'react-native';
import{eotLearnerTokensV1 as t}from'../../src/ui';

export function EOTFirstLaunchIntro({active,onFinished,children,duration=2300}:{active:boolean;onFinished:()=>void|Promise<void>;children:React.ReactNode;duration?:number}){
 const[visible,setVisible]=useState(active),finishing=useRef(false),opacity=useRef(new Animated.Value(active?1:0)).current,mark=useRef(new Animated.Value(0)).current;
 useEffect(()=>{if(!active)return;let cancelled=false;void AccessibilityInfo.isReduceMotionEnabled().then(reduced=>{if(cancelled)return;if(reduced){mark.setValue(1);finish(true);return}Animated.timing(mark,{toValue:1,duration:700,useNativeDriver:true}).start()});const timer=setTimeout(()=>finish(),duration);return()=>{cancelled=true;clearTimeout(timer)}},[active,duration]);
 function finish(reduced=false){if(finishing.current)return;finishing.current=true;const done=()=>{setVisible(false);void onFinished()};if(reduced){opacity.setValue(0);done()}else Animated.timing(opacity,{toValue:0,duration:160,useNativeDriver:true}).start(done)}
 return <View style={s.root}>{children}{active&&visible?<Animated.View style={[StyleSheet.absoluteFill,s.overlay,{opacity}]}><View style={s.press}><Text style={s.eot}>EOT</Text><View style={s.message}><Text style={s.line}>先把你的英文起點抓準。</Text><Text style={s.subline}>用最近一次模考，加上你每天能留的時間。</Text></View><Pressable accessibilityRole="button" accessibilityLabel="開始設定" onPress={()=>finish()} style={s.action}><Text style={s.actionText}>開始設定</Text></Pressable></View></Animated.View>:null}</View>;
}
const s=StyleSheet.create({root:{flex:1},overlay:{backgroundColor:t.colors.background,zIndex:100},press:{flex:1,paddingHorizontal:20,paddingTop:48,paddingBottom:32},eot:{fontSize:14,lineHeight:21,fontWeight:'600',letterSpacing:1.4,color:t.colors.deepWood},message:{flex:1,justifyContent:'center',gap:16},line:{maxWidth:330,fontSize:30,lineHeight:37,fontWeight:'600',color:t.colors.ink},subline:{maxWidth:330,fontSize:16,lineHeight:24,color:t.colors.muted},action:{minHeight:52,borderRadius:14,backgroundColor:t.colors.deepWood,alignItems:'center',justifyContent:'center'},actionText:{fontSize:16,fontWeight:'600',color:t.colors.paper}});
