import AsyncStorage from '@react-native-async-storage/async-storage';
import type { SQLiteDatabase } from 'expo-sqlite';
import { createOperationalIdV1, fingerprintV1 } from './identity';
import { openOperationalDatabaseInternalV1 } from './operationalDatabase.native';
import type { U1MigrationReportV1 } from './operationalTypes';

const OBS='eot.canonical-observation-ledger.v1',EVIDENCE='eot.canonical-evidence-ledger.v3',LEGACY_EVIDENCE='eot.v2.evidence.events',ARTIFACTS='eot.stage4.original-artifacts.v4',RUNTIMES='eot.stage4.runtimes.v4',TEACHER_EPISODES='eot.teacher.episodes.v1';
const KNOWN=[OBS,EVIDENCE,LEGACY_EVIDENCE,ARTIFACTS,RUNTIMES,TEACHER_EPISODES];
const array=(raw:string|null)=>{try{const value=raw?JSON.parse(raw):[];return Array.isArray(value)?value:[]}catch{return[]}};
const text=(value:unknown)=>JSON.stringify(value);
async function learner(db:SQLiteDatabase,id:string,at:string){await db.runAsync('INSERT OR IGNORE INTO learner_identities(learner_id,created_at,updated_at) VALUES(?,?,?)',id,at,at)}

export async function migrateU1AsyncStorageV1(learnerId:string):Promise<U1MigrationReportV1>{
  const keys=[...KNOWN,`eot.product-context.v2:${learnerId}`,'eot.teacher-core.profile.v1'];
  const pairs:readonly (readonly [string,string|null])[]=await Promise.all(keys.map(async key=>[key,await AsyncStorage.getItem(key)] as const));
  const db=await openOperationalDatabaseInternalV1(),values=new Map<string,string|null>(pairs),sourceHash=await fingerprintV1(pairs),prior=await db.getFirstAsync<{run_id:string;accepted_count:number;rejected_count:number;deduped_count:number;quarantined_count:number}>('SELECT run_id,accepted_count,rejected_count,deduped_count,quarantined_count FROM migration_runs WHERE migration_name=? AND source_version=? AND source_hash=?','u1-asyncstorage','1',sourceHash);
  if(prior)return{runId:prior.run_id,accepted:prior.accepted_count,rejected:prior.rejected_count,deduped:prior.deduped_count,quarantined:prior.quarantined_count,sourceDeleted:false,errors:[]};
  const runId=createOperationalIdV1('migration'),now=new Date().toISOString(),errors:string[]=[];let accepted=0,rejected=0,deduped=0,quarantined=0;
  await db.withExclusiveTransactionAsync(async tx=>{
    await tx.runAsync('INSERT INTO migration_runs(run_id,migration_name,source_version,source_hash,accepted_count,rejected_count,deduped_count,quarantined_count,status,started_at) VALUES(?,?,?,?,0,0,0,0,?,?)',runId,'u1-asyncstorage','1',sourceHash,'RUNNING',now);
    await learner(tx,learnerId,now);
    const profileRaw=values.get(`eot.product-context.v2:${learnerId}`);
    if(profileRaw){try{const profile=JSON.parse(profileRaw);if(profile?.schemaVersion!==2||profile?.identity?.learnerId!==learnerId)throw new Error('invalid_product_profile');await tx.runAsync('INSERT OR IGNORE INTO product_profile_revisions(revision_id,learner_id,revision,profile_json,occurred_at) VALUES(?,?,?,?,?)',`migration:${runId}:profile`,learnerId,1,profileRaw,profile.updatedAt??now);await tx.runAsync('INSERT OR IGNORE INTO product_profiles(learner_id,schema_version,revision,profile_json,updated_at) VALUES(?,?,?,?,?)',learnerId,2,1,profileRaw,profile.updatedAt??now);accepted++}catch(error){errors.push(String(error));rejected++}}
    for(const item of array(values.get(OBS)??null)){try{if(item?.schemaVersion!==1||item?.immutable!==true||!item.id||!item.learnerId)throw new Error('invalid_observation');await learner(tx,item.learnerId,item.occurredAt??now);const result=await tx.runAsync('INSERT OR IGNORE INTO observations(observation_id,learner_id,artifact_id,task_id,occurred_at,kind,source,action,payload_json,immutable) VALUES(?,?,?,?,?,?,?,?,?,1)',item.id,item.learnerId,item.artifactId??null,item.taskId??null,item.occurredAt,item.kind,item.source,item.action,text(item.payload??{}));if(result.changes)accepted++;else deduped++}catch(error){errors.push(String(error));rejected++}}
    for(const item of array(values.get(EVIDENCE)??null)){try{if(item?.schemaVersion!==3||item?.immutable!==true||!item.id||!item.learnerId)throw new Error('invalid_canonical_evidence');await learner(tx,item.learnerId,item.occurredAt??now);const observationId=item.observationId??item.provenance?.observationId;if(!observationId)throw new Error('canonical_evidence_missing_observation');const exists=await tx.getFirstAsync('SELECT observation_id FROM observations WHERE observation_id=?',observationId);if(!exists)throw new Error('canonical_evidence_orphan_observation');const evaluationId=`migration-eval:${item.id}`,candidateId=`migration-candidate:${item.id}`,admissionId=`migration-admission:${item.id}`;await tx.runAsync('INSERT OR IGNORE INTO evaluation_runs(evaluation_id,observation_id,evaluator_id,evaluator_version,result_json,occurred_at) VALUES(?,?,?,?,?,?)',evaluationId,observationId,'legacy-canonical-ledger','v3-migration',text({migrated:true}),item.occurredAt);await tx.runAsync('INSERT OR IGNORE INTO evidence_candidates(candidate_id,evaluation_id,candidate_json,created_at,immutable) VALUES(?,?,?,?,1)',candidateId,evaluationId,text(item),item.occurredAt);await tx.runAsync('INSERT OR IGNORE INTO evidence_admissions(admission_id,candidate_id,accepted,reason_codes_json,authority_owner,decided_at,immutable) VALUES(?,?,?,?,?,?,1)',admissionId,candidateId,1,text(['MIGRATED_FROM_CANONICAL_V3']),'C',item.occurredAt);const result=await tx.runAsync('INSERT OR IGNORE INTO canonical_evidence(evidence_id,learner_id,admission_id,dedup_key,occurred_at,evidence_json,immutable) VALUES(?,?,?,?,?,?,1)',item.id,item.learnerId,admissionId,item.dedupKey??null,item.occurredAt,text(item));if(result.changes)accepted++;else deduped++}catch(error){errors.push(String(error));quarantined++;await tx.runAsync('INSERT INTO migration_quarantine(quarantine_id,run_id,source_key,reason,payload_json,created_at) VALUES(?,?,?,?,?,?)',createOperationalIdV1('quarantine'),runId,EVIDENCE,String(error),text(item),now)}}
    for(const [sourceKey,items] of [[LEGACY_EVIDENCE,array(values.get(LEGACY_EVIDENCE)??null)],[TEACHER_EPISODES,array(values.get(TEACHER_EPISODES)??null)]] as const)for(const item of items){quarantined++;await tx.runAsync('INSERT INTO migration_quarantine(quarantine_id,run_id,source_key,reason,payload_json,created_at) VALUES(?,?,?,?,?,?)',createOperationalIdV1('quarantine'),runId,sourceKey,sourceKey===LEGACY_EVIDENCE?'LEGACY_UNQUALIFIED_EVIDENCE':'LEGACY_TREATMENT_REQUIRES_CLASSIFICATION',text(item),now)}
    for(const item of array(values.get(ARTIFACTS)??null)){try{if(item?.schemaVersion!==4||item?.immutable!==true||!item.id)throw new Error('invalid_stage4_artifact');await learner(tx,item.learnerId,item.submittedAt??now);const result=await tx.runAsync('INSERT OR IGNORE INTO artifact_intakes(artifact_id,learner_id,object_id,source_kind,mode,original_uri,metadata_json,submitted_at,immutable) VALUES(?,?,NULL,?,?,?,?,?,1)',item.id,item.learnerId,item.source,item.mode,item.pages?.[0]?.uri??null,text(item),item.submittedAt);if(result.changes)accepted++;else deduped++;if(item.pages?.some((page:{uri?:string})=>page.uri))quarantined++}catch(error){errors.push(String(error));rejected++}}
    for(const item of array(values.get(RUNTIMES)??null)){try{if(!item?.id||!item?.learnerId||!item?.artifact?.id)throw new Error('invalid_stage4_runtime');const planId=item.decisionProvenance?.lessonPlanId;if(!planId){quarantined++;await tx.runAsync('INSERT INTO migration_quarantine(quarantine_id,run_id,source_key,reason,payload_json,created_at) VALUES(?,?,?,?,?,?)',createOperationalIdV1('quarantine'),runId,RUNTIMES,'RUNTIME_WITHOUT_LESSON_PLAN_BINDING',text(item),now);continue}const planJson=text({id:planId,legacy:true}),snapshotId=`legacy:${planId}`;await tx.runAsync('INSERT OR IGNORE INTO lesson_plan_snapshots(snapshot_id,lesson_plan_id,learner_id,schema_version,plan_json,plan_hash,created_at) VALUES(?,?,?,?,?,?,?)',snapshotId,planId,item.learnerId,0,planJson,await fingerprintV1(planJson),item.tutorSession?.startedAt??item.artifact.submittedAt??now);const result=await tx.runAsync('INSERT OR IGNORE INTO lesson_sessions(session_id,learner_id,lesson_plan_snapshot_id,artifact_id,status,runtime_json,started_at,updated_at,completed_at) VALUES(?,?,?,?,?,?,?,?,?)',item.id,item.learnerId,snapshotId,item.artifact.id,item.status,text({...item,observations:undefined,evidenceCandidates:undefined}),item.tutorSession?.startedAt??null,item.trace?.at(-1)?.occurredAt??now,item.tutorSession?.endedAt??null);if(result.changes)accepted++;else deduped++}catch(error){errors.push(String(error));quarantined++}}
    await tx.runAsync('UPDATE migration_runs SET accepted_count=?,rejected_count=?,deduped_count=?,quarantined_count=?,status=?,completed_at=? WHERE run_id=?',accepted,rejected,deduped,quarantined,'COMPLETED',new Date().toISOString(),runId);
  });
  return{runId,accepted,rejected,deduped,quarantined,sourceDeleted:false,errors};
}
