import AsyncStorage from '@react-native-async-storage/async-storage';
import type { LessonPlanV1 } from '../architecture/contracts';
import type { CanonicalEvidenceEventV3, EvidenceCandidateV3 } from '../domain/evidence/EvidenceCandidateV3';
import type { TaskContract } from '../domain/task/TaskContract';
import type { QualifiedInnerTutorDecisionV1 } from '../teacher-runtime';
import { canonicalLearnerTruthV1 } from './lessonPersistenceGateway';
import type { ExamOperationalRuntimeV1 } from './operationalTypes';

export interface ExamEvidencePersistenceUnitV1{unitId:string;status:'ACCEPTED'|'REJECTED'|'SKIPPED';reasons:readonly string[];eventId?:string;occurredAt?:string;candidate?:EvidenceCandidateV3;taskContract?:TaskContract;canonicalEvent?:CanonicalEvidenceEventV3}
const key=(learnerId:string,sessionId:string)=>`eot:exam-session:v1:${learnerId}:${sessionId}`;
export async function saveExamOperationalCheckpointV1(lessonPlan:LessonPlanV1,runtime:ExamOperationalRuntimeV1){await AsyncStorage.setItem(key(runtime.learnerId,runtime.id),JSON.stringify({lessonPlan,runtime}));return{operationId:`web:${runtime.id}:${runtime.updatedAt}`,entityId:runtime.id,status:'COMMITTED' as const}}
export async function loadExamOperationalCheckpointV1(learnerId:string,sessionId:string):Promise<{lessonPlan:LessonPlanV1;runtime:ExamOperationalRuntimeV1}|null>{const raw=await AsyncStorage.getItem(key(learnerId,sessionId));return raw?JSON.parse(raw):null}
export async function loadActiveExamOperationalCheckpointV1(learnerId:string,family?:string):Promise<{lessonPlan:LessonPlanV1;runtime:ExamOperationalRuntimeV1}|null>{const prefix=`eot:exam-session:v1:${learnerId}:`,keys=(await AsyncStorage.getAllKeys()).filter(value=>value.startsWith(prefix)),rows=await AsyncStorage.multiGet(keys);let latest:{lessonPlan:LessonPlanV1;runtime:ExamOperationalRuntimeV1}|null=null;for(const[,raw]of rows){if(!raw)continue;const value=JSON.parse(raw) as{lessonPlan:LessonPlanV1;runtime:ExamOperationalRuntimeV1};if(value.runtime.runtimeKind!=='EXAM'||value.runtime.status==='COMPLETED'||(family&&value.runtime.family!==family))continue;if(!latest||value.runtime.updatedAt>latest.runtime.updatedAt)latest=value}return latest}
export async function persistExamEvidenceAdmissionsV1(input:{learnerId:string;sessionId:string;lessonPlan:LessonPlanV1;runtime:ExamOperationalRuntimeV1;units:readonly ExamEvidencePersistenceUnitV1[]}){const results=[] as {unitId:string;status:string}[];for(const unit of input.units){if(unit.status!=='ACCEPTED'||!unit.candidate||!unit.taskContract||!unit.eventId||!unit.occurredAt){results.push({unitId:unit.unitId,status:unit.status});continue}const result=await canonicalLearnerTruthV1.commitCandidate({candidate:unit.candidate,task:unit.taskContract,learnerId:input.learnerId,id:unit.eventId,occurredAt:unit.occurredAt});results.push({unitId:unit.unitId,status:result.accepted?result.writeStatus:'REJECTED'})}await saveExamOperationalCheckpointV1(input.lessonPlan,input.runtime);return results}
export async function persistExamTeacherLineageV1(input:{learnerId:string;sessionId:string;lessonPlan:LessonPlanV1;runtime:ExamOperationalRuntimeV1;decision:QualifiedInnerTutorDecisionV1;previousDecision?:QualifiedInnerTutorDecisionV1;occurredAt?:string}){await saveExamOperationalCheckpointV1(input.lessonPlan,input.runtime);return{status:'WEB_SESSION_ONLY' as const}}
