import type { EnglishCorpusRetrievalPortV1 } from '../domain/english/corpusRetrieval';
import { SqliteEnglishCorpusRetrievalPortV1, type CorpusSqlReadDatabaseV1 } from './sqliteCorpusRetrieval';
export const nativeCorpusManifestV1=Object.freeze({databaseName:'eot-corpus-20260827.sqlite',corpusVersion:'2026-08-27.wave1',schemaVersion:1,sha256:'3b24f4c5c51ae7085adf2729534755fdb724c3ad4c093531c3ea43eccee18447',requiredSources:Object.freeze({'oewn-2025':'2025-edition / dc343f2','tatoeba-eng-cmn-20260822':'weekly export 2026-08-22','unimorph-eng-master-20260827':'master snapshot 2026-08-27'})});
export type NativeCorpusFailureCodeV1='UNSUPPORTED_PLATFORM'|'ASSET_UNAVAILABLE'|'CORRUPT_DATABASE'|'INCOMPATIBLE_SCHEMA'|'INCOMPATIBLE_CORPUS';
export interface NativeCorpusDatabaseV1 extends CorpusSqlReadDatabaseV1{getFirstAsync<T>(sql:string,...params:unknown[]):Promise<T|null>;execAsync(sql:string):Promise<void>;closeAsync():Promise<void>}
export interface NativeCorpusEnvironmentV1{open():Promise<NativeCorpusDatabaseV1>;installAsset(forceOverwrite:boolean):Promise<void>}
export interface NativeCorpusDiagnosticsV1{integrity:'ok';requiredTables:readonly string[];sourceVersions:Readonly<Record<string,string>>;queryOnly:true}
export type NativeCorpusStateV1={status:'READY';corpusVersion:string;port:EnglishCorpusRetrievalPortV1;reused:boolean;diagnostics:NativeCorpusDiagnosticsV1;close():Promise<void>}|{status:'UNAVAILABLE';code:NativeCorpusFailureCodeV1;learnerMessage:'查詢內容暫時無法使用。'};
async function validate(db:NativeCorpusDatabaseV1):Promise<NativeCorpusFailureCodeV1|undefined>{const integrity=await db.getFirstAsync<{integrity_check:string}>('PRAGMA integrity_check');if(integrity?.integrity_check!=='ok')return'CORRUPT_DATABASE';const required=['source_registry','lexemes','senses','morphology','examples','translation_pairs','sentence_provenance'];const tables=await db.getAllAsync<{name:string}>(`SELECT name FROM sqlite_master WHERE type='table' AND name IN (${required.map(()=>'?').join(',')})`,...required);if(required.some(name=>!tables.some(row=>row.name===name)))return'INCOMPATIBLE_SCHEMA';const sources=await db.getAllAsync<{source_id:string;version:string}>('SELECT source_id,version FROM source_registry WHERE source_id IN (?,?,?)',...Object.keys(nativeCorpusManifestV1.requiredSources));if(Object.entries(nativeCorpusManifestV1.requiredSources).some(([id,version])=>!sources.some(row=>row.source_id===id&&row.version===version)))return'INCOMPATIBLE_CORPUS'}
export async function provisionNativeCorpusV1(env:NativeCorpusEnvironmentV1):Promise<NativeCorpusStateV1>{let db:NativeCorpusDatabaseV1|undefined,reused=true;try{db=await env.open();const failure=await validate(db);if(failure){await db.closeAsync();db=undefined;throw new Error(failure)}}catch{try{await env.installAsset(true);reused=false;db=await env.open();const failure=await validate(db);if(failure){await db.closeAsync();return{status:'UNAVAILABLE',code:failure,learnerMessage:'查詢內容暫時無法使用。'}}}catch{return{status:'UNAVAILABLE',code:'ASSET_UNAVAILABLE',learnerMessage:'查詢內容暫時無法使用。'}}}await db.execAsync('PRAGMA query_only=ON');const queryOnly=await db.getFirstAsync<{query_only:number}>('PRAGMA query_only');if(queryOnly?.query_only!==1){await db.closeAsync();return{status:'UNAVAILABLE',code:'CORRUPT_DATABASE',learnerMessage:'查詢內容暫時無法使用。'}}const requiredTables=['source_registry','lexemes','senses','morphology','examples','translation_pairs','sentence_provenance'],sourceVersions=Object.freeze({...nativeCorpusManifestV1.requiredSources});return{status:'READY',corpusVersion:nativeCorpusManifestV1.corpusVersion,port:new SqliteEnglishCorpusRetrievalPortV1(db),reused,diagnostics:Object.freeze({integrity:'ok',requiredTables:Object.freeze(requiredTables),sourceVersions,queryOnly:true}),close:()=>db!.closeAsync()}}
