import type { CapabilityFacet } from '../domain/english/EnglishDomain';
import type { ValidatedSharedDeliveryV1 } from '../content';
export type DurableRetentionStateV1='OPEN_NOT_DUE'|'DUE'|'DEFERRED'|'ALLOCATED'|'DELIVERED'|'LEARNER_OUTPUT'|'EVIDENCE_PENDING'|'SATISFIED'|'REOPENED';
export interface DurableRetentionNeedV1{schemaVersion:1;needId:string;learnerId:string;targetRef:string;facet:CapabilityFacet;senseId?:string;sourceEvidenceIds:readonly string[];priorProof:{eventId:string;occurredAt:string;sessionId:string;contentIdentity:string;contextIdentity:string};dueAt:string;minimumDelayMs:number;priority:'LOW'|'MEDIUM'|'HIGH';state:DurableRetentionStateV1;delivery?:ValidatedSharedDeliveryV1;attempt?:{sessionId:string;outputRef:string;occurredAt:string;lookupAssisted:boolean};qualification?:{authority:'C/K';accepted:boolean;proofClass:string;evidenceId?:string;targetRef:string;facet:CapabilityFacet;senseId?:string;reasonCodes:readonly string[]};history:readonly {from?:DurableRetentionStateV1;to:DurableRetentionStateV1;occurredAt:string;reason:string;createsLearnerEvidence:false}[];updatedAt:string}
const stable=(x:string)=>x.normalize('NFKC').toLocaleLowerCase('en').replace(/[^a-z0-9:._-]+/g,'-');
export function durableRetentionNeedIdV1(input:{learnerId:string;targetRef:string;facet:CapabilityFacet;senseId?:string;priorProofEventId:string}){return`retention:${stable(input.learnerId)}:${stable(input.targetRef)}:${stable(input.facet)}:${stable(input.senseId??'no-sense')}:${stable(input.priorProofEventId)}`}
export function openDurableRetentionNeedV1(input:{learnerId:string;targetRef:string;facet:CapabilityFacet;senseId?:string;sourceEvidenceIds:readonly string[];priorProof:{eventId:string;occurredAt:string;sessionId:string;contentIdentity:string;contextIdentity:string};dueAt:string;minimumDelayMs:number;priority:'LOW'|'MEDIUM'|'HIGH'}):DurableRetentionNeedV1{const needId=durableRetentionNeedIdV1({...input,priorProofEventId:input.priorProof.eventId}),at=input.priorProof.occurredAt,history:DurableRetentionNeedV1['history']=Object.freeze([{to:'OPEN_NOT_DUE',occurredAt:at,reason:'C_K_PRIOR_PROOF_CREATED_FUTURE_NEED',createsLearnerEvidence:false}]);return Object.freeze({schemaVersion:1,needId,...input,state:'OPEN_NOT_DUE',history,updatedAt:at})}
const allowed:Record<DurableRetentionStateV1,readonly DurableRetentionStateV1[]>={OPEN_NOT_DUE:['DUE','SATISFIED'],DUE:['DEFERRED','ALLOCATED','SATISFIED'],DEFERRED:['DUE','ALLOCATED','SATISFIED'],ALLOCATED:['DELIVERED','DEFERRED','SATISFIED'],DELIVERED:['LEARNER_OUTPUT'],LEARNER_OUTPUT:['EVIDENCE_PENDING'],EVIDENCE_PENDING:['SATISFIED','REOPENED'],SATISFIED:[],REOPENED:['DUE','ALLOCATED','SATISFIED']};
function move(need:DurableRetentionNeedV1,to:DurableRetentionStateV1,at:string,reason:string,extra:Partial<DurableRetentionNeedV1>={}):DurableRetentionNeedV1{if(!allowed[need.state].includes(to))throw new Error(`invalid_retention_transition:${need.state}:${to}`);return Object.freeze({...need,...extra,state:to,history:Object.freeze([...need.history,{from:need.state,to,occurredAt:at,reason,createsLearnerEvidence:false as const}]),updatedAt:at})}
export function advanceRetentionDueV1(need:DurableRetentionNeedV1,now:string){if(!['OPEN_NOT_DUE','DEFERRED','REOPENED'].includes(need.state)||Date.parse(now)<Date.parse(need.dueAt))return need;return move(need,'DUE',now,'TIME_CHANGED_SCHEDULING_ELIGIBILITY_ONLY')}
export const deferRetentionNeedV1=(need:DurableRetentionNeedV1,at:string)=>move(need,'DEFERRED',at,'TODAY_HIGHER_VALUE_TASK_ALLOCATED');
export const allocateRetentionNeedV1=(need:DurableRetentionNeedV1,at:string)=>move(need,'ALLOCATED',at,'D_ALLOCATED_DUE_RETENTION_NEED');
export function recordRetentionDeliveryV1(need:DurableRetentionNeedV1,delivery:ValidatedSharedDeliveryV1,at:string){if(delivery.purpose!=='DELAYED_RETENTION'||delivery.targetRef!==need.targetRef||delivery.facet!==need.facet)throw new Error('retention_delivery_identity_mismatch');if(delivery.contentRef===need.priorProof.contentIdentity||delivery.contextIdentity===need.priorProof.contextIdentity)throw new Error('retention_delivery_not_distinct');return move(need,'DELIVERED',at,'G_VALIDATED_DELAYED_DELIVERY',{delivery})}
export function recordRetentionOutputV1(need:DurableRetentionNeedV1,input:{sessionId:string;outputRef:string;occurredAt:string;lookupAssisted:boolean}){if(input.sessionId===need.priorProof.sessionId)throw new Error('retention_requires_later_session');return move(need,'LEARNER_OUTPUT',input.occurredAt,'LEARNER_RESPONDED_TO_DELAYED_TASK',{attempt:Object.freeze(input)})}
export const markRetentionEvidencePendingV1=(need:DurableRetentionNeedV1,at:string)=>move(need,'EVIDENCE_PENDING',at,'AWAIT_C_K_QUALIFICATION');
export function settleRetentionFromCKV1(need:DurableRetentionNeedV1,input:{authority:'C/K';accepted:boolean;proofClass:string;evidenceId?:string;targetRef:string;facet:CapabilityFacet;senseId?:string;reasonCodes:readonly string[];occurredAt:string}){const exact=input.targetRef===need.targetRef&&input.facet===need.facet&&(need.senseId??'')===(input.senseId??''),accepted=input.accepted&&input.proofClass==='DELAYED_RETENTION'&&exact&&!need.attempt?.lookupAssisted,qualification=Object.freeze({...input,accepted});return move(need,accepted?'SATISFIED':'REOPENED',input.occurredAt,accepted?'C_K_QUALIFIED_DELAYED_RETENTION':'C_K_DID_NOT_QUALIFY_RETENTION',{qualification})}
export function satisfyFromNaturalEncounterV1(need:DurableRetentionNeedV1,input:{authority:'C/K';accepted:boolean;proofClass:string;evidenceId:string;targetRef:string;facet:CapabilityFacet;senseId?:string;independent:boolean;contextValid:boolean;provenanceSufficient:boolean;occurredAt:string}){const exact=input.targetRef===need.targetRef&&input.facet===need.facet&&(need.senseId??'')===(input.senseId??'');if(!input.accepted||!input.independent||!input.contextValid||!input.provenanceSufficient||!exact)return need;return move(need,'SATISFIED',input.occurredAt,'C_K_QUALIFIED_NATURAL_AUTHENTIC_ENCOUNTER',{qualification:Object.freeze({authority:'C/K',accepted:true,proofClass:input.proofClass,evidenceId:input.evidenceId,targetRef:input.targetRef,facet:input.facet,senseId:input.senseId,reasonCodes:Object.freeze(['NATURAL_AUTHENTIC_ENCOUNTER'])})})}
export function todayRetentionProjectionV1(needs:readonly DurableRetentionNeedV1[]){const order={HIGH:0,MEDIUM:1,LOW:2},actionable=needs.filter(n=>['DUE','DEFERRED','REOPENED','ALLOCATED'].includes(n.state)).sort((a,b)=>order[a.priority]-order[b.priority]||a.dueAt.localeCompare(b.dueAt));return Object.freeze({dueCount:actionable.length,nextNeed:actionable[0],reasonCodes:Object.freeze(actionable.length?['PERSISTED_RETENTION_NEED_AVAILABLE_TO_D']:['NO_DUE_RETENTION_NEED']),masteryMutationAllowed:false})}
export interface DurableRetentionStoreV1{save(need:DurableRetentionNeedV1):Promise<'COMMITTED'|'IDEMPOTENT_REPLAY'>;load(learnerId:string):Promise<readonly DurableRetentionNeedV1[]>}
export class ReplayableRetentionStoreV1 implements DurableRetentionStoreV1{private rows=new Map<string,string>();constructor(snapshot?:string){if(snapshot)for(const item of JSON.parse(snapshot) as DurableRetentionNeedV1[])this.rows.set(item.needId,JSON.stringify(item))}async save(need:DurableRetentionNeedV1){const next=JSON.stringify(need),prior=this.rows.get(need.needId);if(prior===next)return'IDEMPOTENT_REPLAY';this.rows.set(need.needId,next);return'COMMITTED'}async load(learnerId:string){return Object.freeze([...this.rows.values()].map(x=>JSON.parse(x) as DurableRetentionNeedV1).filter(x=>x.learnerId===learnerId))}snapshot(){return JSON.stringify([...this.rows.values()].map(x=>JSON.parse(x)))}}
