import { deliverSharedWritingRequestV1, type DeliveryLoadProfileV1 } from '../content';
import type { TaskContract } from '../domain/task/TaskContract';
import type { CanonicalEvidenceEventV3 } from '../domain/evidence/EvidenceCandidateV3';
import { buildFreshEvidenceOpportunityV1 } from '../domain/task/freshEvidence';
import { openDurableRetentionNeedV1, satisfyFromNaturalEncounterV1, type DurableRetentionNeedV1 } from './durableRetention';
const retentionDelayMs=7*24*60*60*1000;
const delayedLoad:DeliveryLoadProfileV1=Object.freeze({length:'MEDIUM',reasoning:'MEDIUM',ideaGeneration:'MEDIUM',contentSupport:'NONE',clauses:2,planningSupport:'NONE',languageSupport:'NONE',selectionSupport:'NONE',functionCue:'NONE',recentModelPrime:'NONE'});
export function constructDelayedRetentionDeliveryV1(input:{need:DurableRetentionNeedV1;lessonPlanId:string;sourcePrompt:string;occurredAt:string}){const n=input.need;if(n.state!=='ALLOCATED')return undefined;return deliverSharedWritingRequestV1({request:{requestId:`${n.needId}:delivery`,lessonPlanId:input.lessonPlanId,targetRef:n.targetRef,facet:n.facet,arena:'WRITING',purpose:'DELAYED_RETENTION',semanticRequirements:Object.freeze([`preserve exact target ${n.targetRef}`,...(n.senseId?[`preserve exact sense ${n.senseId}`]:[])]),contentRequirement:'delayed unsupported production in genuinely distinct content',context:{sourceIdentity:n.priorProof.contextIdentity,requiredNovelty:'DELAYED_CONTEXT'},authenticLoad:delayedLoad,requestedLoad:delayedLoad,loadDelta:Object.freeze([]),answerExposure:'NONE',assistanceCeiling:{language:'NONE',selection:'NONE',functionCue:'NONE',planning:'NONE',recentModelPrime:'NONE'},provenanceRequirements:Object.freeze([...n.sourceEvidenceIds,n.priorProof.eventId]),measurementIntent:'RETENTION',forbiddenContentRefs:Object.freeze([n.priorProof.contentIdentity])},sourcePrompt:input.sourcePrompt,occurredAt:input.occurredAt})}
export function delayedRetentionTaskContractV1(input:{need:DurableRetentionNeedV1;sessionId:string;occurredAt:string}):TaskContract{const n=input.need,d=n.delivery;if(!d)throw new Error('delayed_delivery_required');const freshEvidenceOpportunity=buildFreshEvidenceOpportunityV1({relationship:'F5_DELAYED_CHANGED_CONTEXT',comparedSourceId:n.priorProof.contextIdentity,comparedItemId:d.deliveryId,sourceText:n.priorProof.contentIdentity,itemText:d.contentRef,templateGeometry:'PHASE_F_DELAYED_PROBE',solutionGeometry:'SEMANTIC_RUBRIC',targetRef:n.targetRef,facet:n.facet,senseId:n.senseId,topicContext:d.contextIdentity,genreRepresentation:d.arena,validatorRefs:d.validatorRefs,acceptedAnswerRule:'SEMANTIC_RUBRIC',provenanceStatus:d.validatorRefs.length?'KNOWN_ALLOWED':'UNKNOWN',examFormatStatus:'NOT_EXAM'});const task:TaskContract={id:d.deliveryId,purpose:'RETENTION',taskFamily:d.arena==='WRITING'?'WRITING':'TRANSLATION',targetRefs:[n.targetRef],contextNovelty:'DELAYED_CONTEXT',responseOpenness:'OPEN',supportExposed:['NONE'],meaningProvenance:'ARTIFACT_SUPPORTED',eligibleClaims:[{targetRef:n.targetRef,facet:n.facet,senseId:n.senseId}],forbiddenClaims:[],productionConditions:{elicitation:'OPEN_CHOICE',context:'DELAYED_CONTEXT',taskLoad:'MEDIUM',assistance:{language:'NONE',selection:'NONE',functionCue:'NONE',planning:'NONE',taskLoad:'NONE',recentModelPrime:'NONE'}},measurementProvenance:{opportunityKind:'DELAYED_PROBE',taskId:d.deliveryId,sourceContentIdentity:n.priorProof.contentIdentity,taskContentIdentity:d.contentRef,sourceContextKey:n.priorProof.contextIdentity,taskContextKey:d.contextIdentity,deliveryRef:d.deliveryId,validatorRefs:d.validatorRefs,deliveredAt:d.deliveredAt,attemptSessionId:input.sessionId,priorProofEventId:n.priorProof.eventId,priorProofOccurredAt:n.priorProof.occurredAt,priorProofSessionId:n.priorProof.sessionId,minimumDelayMs:n.minimumDelayMs,freshEvidenceOpportunity}};return Object.freeze(task)}

export function futureRetentionNeedFromQualifiedEvidenceV1(input:{event:CanonicalEvidenceEventV3;sessionId:string;contentIdentity:string;contextIdentity:string;senseId?:string;minimumDelayMs?:number}){const e=input.event;if(e.performanceDimension==='RECOGNITION'||e.evidencePolarity!=='POSITIVE'||e.productionMode!=='INDEPENDENT'||e.contextNovelty!=='CHANGED_CONTEXT'||!e.targetRef||!e.capabilityFacet)return undefined;const minimumDelayMs=input.minimumDelayMs??retentionDelayMs;return openDurableRetentionNeedV1({learnerId:e.learnerId,targetRef:e.targetRef,facet:e.capabilityFacet,senseId:input.senseId??e.senseId,sourceEvidenceIds:Object.freeze([e.id]),priorProof:{eventId:e.id,occurredAt:e.occurredAt,sessionId:input.sessionId,contentIdentity:input.contentIdentity,contextIdentity:input.contextIdentity},dueAt:new Date(Date.parse(e.occurredAt)+minimumDelayMs).toISOString(),minimumDelayMs,priority:'HIGH'})}

export function reconcileNaturalEncounterV1(input:{needs:readonly DurableRetentionNeedV1[];event:CanonicalEvidenceEventV3;contextIdentity:string;senseId?:string;provenanceSufficient:boolean}){const e=input.event;if(e.evidencePolarity!=='POSITIVE'||e.productionMode!=='INDEPENDENT'||!e.targetRef||!e.capabilityFacet)return Object.freeze({needs:input.needs,settled:false});let settled=false;const exactSense=input.senseId??e.senseId;const needs=input.needs.map(need=>{if(!['OPEN_NOT_DUE','DUE','DEFERRED','ALLOCATED','REOPENED'].includes(need.state)||need.priorProof.contextIdentity===input.contextIdentity)return need;const next=satisfyFromNaturalEncounterV1(need,{authority:'C/K',accepted:true,proofClass:e.contextNovelty==='DELAYED_CONTEXT'?'DELAYED_RETENTION':'NATURAL_AUTHENTIC',evidenceId:e.id,targetRef:e.targetRef!,facet:e.capabilityFacet!,senseId:exactSense,independent:true,contextValid:true,provenanceSufficient:input.provenanceSufficient,occurredAt:e.occurredAt});if(next!==need)settled=true;return next});return Object.freeze({needs:Object.freeze(needs),settled})}
