import {Href,router} from 'expo-router';
import React,{useEffect,useState} from 'react';
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {useCanonicalProductData} from '../../context/AppDataContext';
import {loadMyEnglishAbilityV1,loadMyEnglishVMV1,practiceEntryV1,practiceRouteParamsV1,type MyEnglishVMV1} from '../../src/experience';
import {eotLearnerTokensV1 as t} from '../../src/ui';

type Ability=Awaited<ReturnType<typeof loadMyEnglishAbilityV1>>;
export default function MyEnglish(){const{learnerPreferences}=useCanonicalProductData(),[ability,setAbility]=useState<Ability>(),[vm,setVM]=useState<MyEnglishVMV1>();useEffect(()=>{void Promise.all([loadMyEnglishAbilityV1(learnerPreferences.learnerId),loadMyEnglishVMV1(learnerPreferences.learnerId)]).then(([a,v])=>{setAbility(a);setVM(v)})},[learnerPreferences.learnerId]);if(!ability||!vm)return <SafeAreaView style={s.safe}><ActivityIndicator style={s.loading}/></SafeAreaView>;
 const stable=ability.areas.filter(x=>!['NEEDS_WORK','MOST_WORTH_PRACTICING'].includes(x.status)),stuck=ability.areas.filter(x=>['NEEDS_WORK','MOST_WORTH_PRACTICING'].includes(x.status));
 const open=(family:string)=>{const entry=practiceEntryV1(family);if(!entry?.destination)return;const query=new URLSearchParams(Object.entries(practiceRouteParamsV1({entry,origin:'MY_ENGLISH'})).filter((x):x is [string,string]=>typeof x[1]==='string')).toString();router.push(`${entry.destination}?${query}` as Href)};
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Text style={s.title}>My English</Text><Text style={s.lead}>最近留下來的英文</Text>{ability.state==='EMPTY'?<View style={s.empty}><Text style={s.emptyTitle}>還沒有內容</Text><Pressable onPress={()=>router.push('/(tabs)/practice')} style={s.practice}><Text style={s.practiceText}>開始練習</Text></Pressable></View>:<><Group title="最近比較穩" rows={stable} onPress={open}/><Group title="最近還會卡" rows={stuck} onPress={open}/>{vm.recentMemory.length?<View style={s.group}><Text style={s.heading}>最近碰到</Text>{vm.recentMemory.slice(0,3).map(x=><View key={x} style={s.memoryRow}><Text style={s.memory}>{x.replace(/：查過，但還不算已經會了。/,'')}</Text></View>)}</View>:null}</>}</ScrollView></SafeAreaView>}
const learnerTarget=(family:string)=>family==='READING'?'回到文章找答案':family==='TRANSLATION'?'把中文意思說成英文':family==='WRITING'?'把想法寫得更完整':family==='VOCABULARY'?'把字放回句子裡':family==='DISCOURSE'?'讓前後文接得起來':family==='MIXED'?'讀懂不同形式的資料':'完成一題英文';
function Group({title,rows,onPress}:{title:string;rows:Ability['areas'];onPress:(family:string)=>void}){if(!rows.length)return null;return <View style={s.group}><Text style={s.heading}>{title}</Text>{rows.slice(0,4).map(row=><Pressable key={row.id} onPress={()=>onPress(row.family)} style={({pressed})=>[s.row,pressed&&s.rowPressed]}><View style={s.flex}><Text style={s.family}>{row.label.replace('測驗','')}</Text><Text style={s.target}>{learnerTarget(row.family)}</Text></View><View style={s.practicePill}><Text style={s.practicePillText}>練</Text></View></Pressable>)}</View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:t.colors.canvas},loading:{flex:1},page:{width:'100%',maxWidth:430,alignSelf:'center',paddingHorizontal:20,paddingTop:28,paddingBottom:100},title:{fontSize:30,lineHeight:37,fontWeight:'600',color:t.colors.ink},lead:{fontSize:14,lineHeight:21,color:t.colors.muted,marginTop:3,marginBottom:34},group:{marginBottom:32},heading:{fontSize:18,lineHeight:25,fontWeight:'600',color:t.colors.ink,marginBottom:10},row:{minHeight:82,flexDirection:'row',alignItems:'center',paddingHorizontal:12,marginBottom:8,borderRadius:12,backgroundColor:t.colors.surface},rowPressed:{backgroundColor:t.colors.focusWash,transform:[{scale:.99}]},flex:{flex:1},family:{fontSize:13,lineHeight:20,color:t.colors.muted},target:{fontSize:17,lineHeight:26,fontWeight:'600',color:t.colors.ink},practicePill:{minWidth:40,height:34,borderRadius:17,backgroundColor:t.colors.woodWash,alignItems:'center',justifyContent:'center'},practicePillText:{fontSize:13,fontWeight:'700',color:t.colors.deepWood},memoryRow:{paddingVertical:13,borderBottomWidth:1,borderBottomColor:t.colors.divider},memory:{fontSize:16,lineHeight:24,color:t.colors.ink},empty:{paddingVertical:20,gap:16},emptyTitle:{fontSize:22,lineHeight:31,fontWeight:'600',color:t.colors.ink},practice:{minHeight:50,alignSelf:'flex-start',paddingHorizontal:22,borderRadius:13,backgroundColor:t.colors.deepWood,alignItems:'center',justifyContent:'center'},practiceText:{color:t.colors.paper,fontWeight:'600'}});
