import { router, Stack, useLocalSearchParams } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { PedagogicalBlockPreview } from '../../../components/blocks/PedagogicalBlockPreview';
import { blockRegistryV4 } from '../../../src/application/v4/blockRegistryV4';

const stages=[
  {role:'TEACH',id:'grammar-role-map',why:'The missing WHO is allowed role requires a construction representation first.'},
  {role:'PRACTICE',id:'sentence-builder',why:'Visible pieces support role ordering; success remains assisted before fade.'},
  {role:'ASSESS',id:'independent-sentence-production',why:'A fresh prompt without leaked wording can afford independent evidence.'},
  {role:'RETURN',id:'return-original-writing',why:'Return to the learner source and preserve source success separately.'},
] as const;
const studentStages={
  teach:{id:'grammar-role-map',label:'\u5148\u770b\u61c2\u53e5\u5b50\u88e1\u7684\u89d2\u8272'},
  practice:{id:'sentence-builder',label:'\u6709\u63d0\u793a\u5730\u7df4\u4e00\u6b21'},
  fade:{id:'sentence-builder',label:'\u63d0\u793a\u5c11\u4e00\u9ede\uff0c\u518d\u81ea\u5df1\u6392\u4e00\u6b21'},
  assess:{id:'independent-sentence-production',label:'\u73fe\u5728\u81ea\u5df1\u5beb\u4e00\u6b21'},
  return:{id:'return-original-writing',label:'\u56de\u5230\u4f60\u7684\u539f\u53e5'},
  alternate:{id:'worked-transformation',label:'\u63db\u4e00\u7a2e\u65b9\u5f0f\uff1a\u770b\u53e5\u5b50\u600e\u9ebc\u4e00\u6b65\u6b65\u6539\u8b8a'},
} as const;

export default function AllowFlow(){
  const{student}=useLocalSearchParams<{student?:keyof typeof studentStages}>();
  if(student){const selected=studentStages[student]??studentStages.teach;return <SafeAreaView style={styles.studentOnly}><Stack.Screen options={{headerShown:false}}/><Text style={styles.learnerStep}>{selected.label}</Text>{student==='practice'?<Text style={styles.supportNote}>{'\u63d0\u793a\uff1aallow \u5f8c\u9762\u5148\u653e\u300c\u8ab0\u300d\uff0c\u518d\u653e to + \u52d5\u4f5c\u3002\u9019\u6b21\u6210\u529f\u4ecd\u7136\u662f\u6709\u5354\u52a9\u5b8c\u6210\u3002'}</Text>:null}{student==='fade'?<Text style={styles.fadeNote}>{'\u63d0\u793a\u5df2\u6e1b\u5c11\uff1a\u9019\u6b21\u4e0d\u986f\u793a\u89d2\u8272\u8aaa\u660e\uff0c\u53ea\u7559\u4e0b\u53e5\u5b50\u90e8\u4ef6\u3002'}</Text>:null}<PedagogicalBlockPreview block={blockRegistryV4.get(selected.id)!}/></SafeAreaView>}
  return <SafeAreaView style={styles.safe}><Stack.Screen options={{headerShown:false}}/><ScrollView contentContainerStyle={styles.page}><Pressable onPress={()=>router.back()}><Text style={styles.back}>Back to Block Library</Text></Pressable><Text style={styles.kicker}>FULL LEARNING FLOW</Text><Text style={styles.title}>allow + O + to V</Text><View style={styles.source}><Text style={styles.sourceLabel}>LEARNER ORIGINAL WRITING</Text><Text style={styles.sourceText}>Schools should allow to use phones for learning.</Text></View>{stages.map((stage,index)=><View key={stage.role} style={styles.stage}><View style={styles.stageHead}><Text style={styles.number}>{index+1}</Text><View><Text style={styles.role}>{stage.role}</Text><Text style={styles.why}>{stage.why}</Text></View></View><PedagogicalBlockPreview block={blockRegistryV4.get(stage.id)!}/></View>)}<View style={styles.branch}><Text style={styles.branchKicker}>AFTER ANOTHER PRACTICE FAILURE</Text><Text style={styles.branchTitle}>Do not repeat the identical teaching mechanism</Text><Text style={styles.branchBody}>The deterministic fixture records representation mismatch and selects a different registered TEACH block.</Text><View style={styles.arrow}><Text style={styles.failed}>Grammar Role Map did not help</Text><Text style={styles.arrowText}>CHANGE STRATEGY</Text><Text style={styles.alternate}>Worked Transformation</Text></View><PedagogicalBlockPreview block={blockRegistryV4.get('worked-transformation')!}/></View></ScrollView></SafeAreaView>;
}

const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#EEECE5'},studentOnly:{flex:1,backgroundColor:'#E9ECE7',alignItems:'center',padding:18},learnerStep:{fontSize:18,fontWeight:'900',color:'#214F45',marginBottom:10},supportNote:{width:'100%',maxWidth:390,padding:12,borderRadius:12,backgroundColor:'#FFF3D5',color:'#6A5428',marginBottom:8,textAlign:'center'},fadeNote:{width:'100%',maxWidth:390,padding:12,borderRadius:12,backgroundColor:'#EEF1F6',color:'#4F5B71',marginBottom:8,textAlign:'center'},page:{padding:26,paddingBottom:100,maxWidth:1000,width:'100%',alignSelf:'center'},back:{fontWeight:'900',color:'#27685A'},kicker:{fontSize:11,fontWeight:'900',letterSpacing:1.2,color:'#397565',marginTop:24},title:{fontSize:40,fontWeight:'900',color:'#183730',marginTop:6},source:{padding:20,borderRadius:18,backgroundColor:'#fff',borderLeftWidth:5,borderLeftColor:'#C45F4E',marginVertical:22},sourceLabel:{fontSize:10,fontWeight:'900',letterSpacing:1,color:'#9B584B'},sourceText:{fontSize:20,lineHeight:28,color:'#283C37',marginTop:7},stage:{marginBottom:36,gap:14},stageHead:{flexDirection:'row',gap:13,alignItems:'center'},number:{width:34,height:34,borderRadius:17,backgroundColor:'#245F53',color:'#fff',fontWeight:'900',textAlign:'center',paddingTop:7},role:{fontSize:14,fontWeight:'900',letterSpacing:1,color:'#245F53'},why:{color:'#64736E',marginTop:3,maxWidth:720},branch:{paddingTop:28,borderTopWidth:2,borderColor:'#CFCBC0',gap:14},branchKicker:{fontSize:11,fontWeight:'900',color:'#A24F44'},branchTitle:{fontSize:28,fontWeight:'900',color:'#3C302D'},branchBody:{color:'#685D58'},arrow:{flexDirection:'row',flexWrap:'wrap',gap:10,alignItems:'center'},failed:{padding:12,borderRadius:12,backgroundColor:'#F4DCD7',color:'#7D3930',fontWeight:'800'},arrowText:{fontWeight:'900',color:'#8A5D30'},alternate:{padding:12,borderRadius:12,backgroundColor:'#DCEDE6',color:'#245F53',fontWeight:'900'}});
