import { router, Stack } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { blockRegistryV4, originalBlockAuditV4 } from '../../../src/application/v4/blockRegistryV4';
import { PedagogicalRoleV4 } from '../../../src/domain/v4/LearningBlockV4';

const roles:PedagogicalRoleV4[]=['TEACH','PRACTICE','ASSESS','TRANSFER','SYSTEM'];
const descriptions:Record<PedagogicalRoleV4,string>={TEACH:'改變理解與 mental representation',PRACTICE:'在支援下建立 retrieval / construction control',ASSESS:'用最少答案洩漏取得可辯護證據',TRANSFER:'回到原作或在新／延遲情境中部署',SYSTEM:'控制與導覽，不是學習活動'};
export default function BlockLibrary(){const all=blockRegistryV4.all();return <SafeAreaView style={s.safe}><Stack.Screen options={{headerShown:false}}/><ScrollView contentContainerStyle={s.page}><Text style={s.kicker}>FOUNDER / DEVELOPMENT</Text><Text style={s.title}>Pedagogical Block Library</Text><Text style={s.sub}>Teaching、Practice、Assessment、Transfer 與 System 是不同權責，不可互換。此 route 不在 learner navigation。</Text><View style={s.actions}><Pressable accessibilityRole="button" onPress={()=>router.push('/__dev__/blocks/allow-flow')} style={s.flowButton}><Text style={s.flowText}>查看 allow O → to V 完整流程</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>router.push('/__dev__/blocks/audit')} style={s.auditButton}><Text style={s.auditText}>原始 41 blocks 審計表</Text></Pressable></View><View style={s.stats}><Text style={s.stat}>{all.length} total registered</Text><Text style={s.stat}>{originalBlockAuditV4.length} original audited</Text></View>{roles.map(role=><View key={role} style={s.section}><View style={s.heading}><View><Text style={s.role}>{role}</Text><Text style={s.description}>{descriptions[role]}</Text></View><Text style={s.count}>{blockRegistryV4.byRole(role).length}</Text></View><View style={s.grid}>{blockRegistryV4.byRole(role).map(block=><Pressable accessibilityRole="button" key={block.id} onPress={()=>router.push({pathname:'/__dev__/blocks/[blockId]',params:{blockId:block.id}})} style={[s.card,role==='TEACH'&&s.teachCard,role==='ASSESS'&&s.assessCard]}><Text style={s.family}>{block.family.replaceAll('_',' ')}</Text><Text style={s.cardTitle}>{block.label}</Text><Text style={s.mechanism}>{block.mechanism}</Text><View style={s.row}><Text style={s.ceiling}>Evidence: {block.evidenceCeiling}</Text><Text style={s.open}>Open →</Text></View></Pressable>)}</View></View>)}<View style={[s.card,s.new]}><Text style={s.cardTitle}>＋ New Learning Block</Text><Text style={s.mechanism}>Founder design → pedagogy review → implementation → Registry approval</Text><Text style={s.ceiling}>Future workflow</Text></View></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#F4F2EC'},page:{padding:28,paddingBottom:80,maxWidth:1180,width:'100%',alignSelf:'center'},kicker:{fontSize:12,fontWeight:'900',letterSpacing:1.2,color:'#286759'},title:{fontSize:38,fontWeight:'900',color:'#182F2A',marginTop:8},sub:{fontSize:16,lineHeight:25,color:'#68756F',maxWidth:760,marginTop:10},actions:{flexDirection:'row',flexWrap:'wrap',gap:10,marginTop:22},flowButton:{backgroundColor:'#215F53',paddingVertical:13,paddingHorizontal:18,borderRadius:14},flowText:{color:'#fff',fontWeight:'900'},auditButton:{borderWidth:1,borderColor:'#6D8E84',paddingVertical:13,paddingHorizontal:18,borderRadius:14},auditText:{color:'#285C51',fontWeight:'900'},stats:{flexDirection:'row',gap:10,marginVertical:24},stat:{paddingHorizontal:13,paddingVertical:8,borderRadius:99,backgroundColor:'#DFEAE6',color:'#285C51',fontWeight:'800'},section:{marginBottom:34,gap:14},heading:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderBottomWidth:1,borderColor:'#D8D6CF',paddingBottom:12},role:{fontSize:22,fontWeight:'900',color:'#193A33'},description:{color:'#6B7873',marginTop:4},count:{fontSize:25,fontWeight:'900',color:'#4C776C'},grid:{flexDirection:'row',flexWrap:'wrap',gap:12},card:{width:350,minHeight:160,padding:19,borderRadius:19,backgroundColor:'#FFFEFA',borderWidth:1,borderColor:'#DEDCD5',justifyContent:'space-between'},teachCard:{borderLeftWidth:5,borderLeftColor:'#2D7565',backgroundColor:'#F7FBF8'},assessCard:{borderLeftWidth:5,borderLeftColor:'#52668C',backgroundColor:'#F7F8FC'},family:{fontSize:10,fontWeight:'900',letterSpacing:.8,color:'#718078'},cardTitle:{fontSize:20,fontWeight:'900',color:'#1C3630',marginTop:6},mechanism:{lineHeight:20,color:'#68756F'},row:{flexDirection:'row',justifyContent:'space-between'},ceiling:{fontSize:11,fontWeight:'800',color:'#667770'},open:{fontWeight:'900',color:'#286759'},new:{borderStyle:'dashed',backgroundColor:'#ECEAE4'}});
