import v35Receipts from './examV35ValidationReceipts.json';

export type ExamValidationGateV1='FORMAT_AUTHENTICITY'|'ANSWER_RUBRIC_VALIDITY'|'ANSWER_UNIQUENESS'|'DISTRACTOR_CAUSALITY'|'SEMANTIC_RUBRIC_SAFETY'|'FRESHNESS_LINEAGE'|'CANONICAL_BINDING'|'PROVENANCE_LICENSE'|'PRE_USE_VALIDATION';
export interface ExamValidationReceiptV1{schemaVersion:1;taskId:string;contentHash:string;bindingVersion:'exam-binding-v1';reviewedAt:string;reviewer:'EOT_EDITORIAL';gates:Readonly<Record<ExamValidationGateV1,'PASS'|'FAIL'|'NOT_APPLICABLE'>>;immutable:true}
const pass=(semantic=true):Readonly<Record<ExamValidationGateV1,'PASS'|'NOT_APPLICABLE'>>=>Object.freeze({FORMAT_AUTHENTICITY:'PASS',ANSWER_RUBRIC_VALIDITY:'PASS',ANSWER_UNIQUENESS:'PASS',DISTRACTOR_CAUSALITY:'PASS',SEMANTIC_RUBRIC_SAFETY:semantic?'PASS':'NOT_APPLICABLE',FRESHNESS_LINEAGE:'PASS',CANONICAL_BINDING:'PASS',PROVENANCE_LICENSE:'PASS',PRE_USE_VALIDATION:'PASS'});
const hashes:Readonly<Record<string,string>>=Object.freeze({'VOC-G-001':'fnv1a32-90a6b11b','VOC-G-002':'fnv1a32-624bb073','VOC-G-003':'fnv1a32-42fd4b50','COMP-G-004':'fnv1a32-1f780f50','COMP-G-007':'fnv1a32-2fb3e3e0','COMP-G-008':'fnv1a32-0ba3a9f4','CF-G-001':'fnv1a32-5fb3e2aa','CF-G-002':'fnv1a32-2df8bc8e','CF-G-004':'fnv1a32-fbe9d0fc','DISC-G-001':'fnv1a32-a341a4eb','DISC-G-003':'fnv1a32-19d4be2e','DISC-G-004':'fnv1a32-a32f1a75','READ-G-001':'fnv1a32-c58ccc6a','READ-G-004':'fnv1a32-27d16197','READ-G-007':'fnv1a32-bb71a9c5','MIX-G-001':'fnv1a32-f333be81','MIX-G-002':'fnv1a32-c6c7057f','MIX-G-004':'fnv1a32-305f470e','TRANS-G-F02':'fnv1a32-1bd7fd21','TRANS-T-001':'fnv1a32-f008434d','TRANS-G-T02':'fnv1a32-6add01b7','TRANS-G-T05':'fnv1a32-1cfc4afb','WRITE-M-001':'fnv1a32-17d1daa5','WRITE-G-M06':'fnv1a32-0f95e34b','WRITE-G-M09':'fnv1a32-60283821','WRITE-P-001':'fnv1a32-51a6115b','WRITE-G-P01':'fnv1a32-6cb5cf71','WRITE-F-001':'fnv1a32-cc4ece1f'});
const currentHashes=Object.freeze({...hashes,'WRITE-M-001':'fnv1a32-c52c0946','WRITE-P-001':'fnv1a32-9393bc1e','WRITE-F-001':'fnv1a32-00005246'});const receipts=new Map<string,ExamValidationReceiptV1>([
 ...Object.entries(currentHashes).map(([taskId,contentHash])=>[taskId,Object.freeze({schemaVersion:1 as const,taskId,contentHash,bindingVersion:'exam-binding-v1' as const,reviewedAt:'2026-09-06',reviewer:'EOT_EDITORIAL' as const,gates:pass(!/^(VOC|COMP|CF|DISC|READ)-/.test(taskId)),immutable:true as const})] as const),
 ...(v35Receipts.receipts as unknown as ExamValidationReceiptV1[]).map(row=>[row.taskId,Object.freeze(row)] as const),
]);
type HashableTask={task_id:string;family:string;subtype:string;payload:unknown;answer_or_rubric?:unknown;freshness_group_id?:string;content_lineage_id?:string;provenance?:unknown;canonicalBinding?:unknown;semanticRubricRef?:string};
const exactBytes=(task:HashableTask)=>JSON.stringify({task_id:task.task_id,family:task.family,subtype:task.subtype,payload:task.payload,answer_or_rubric:task.answer_or_rubric,freshness_group_id:task.freshness_group_id,content_lineage_id:task.content_lineage_id,provenance:task.provenance,canonicalBinding:task.canonicalBinding,semanticRubricRef:task.semanticRubricRef});
export function examContentHashV1(task:HashableTask){const value=exactBytes(task);let hash=2166136261;for(let i=0;i<value.length;i++){hash^=value.charCodeAt(i);hash=Math.imul(hash,16777619)}return`fnv1a32-${(hash>>>0).toString(16).padStart(8,'0')}`}
export function examValidationReceiptV1(taskId:string){return receipts.get(taskId)}
export function validateExamReceiptV1(task:HashableTask,receipt=examValidationReceiptV1(task.task_id)){if(!receipt)return{valid:false as const,reasons:['VALIDATION_RECEIPT_ABSENT'] as const};const failed=Object.entries(receipt.gates).filter(([,value])=>value==='FAIL').map(([gate])=>`${gate}_FAIL`),actual=examContentHashV1(task);return failed.length||actual!==receipt.contentHash?{valid:false as const,reasons:Object.freeze([...failed,...(actual!==receipt.contentHash?['CONTENT_HASH_MISMATCH']:[])])}:{valid:true as const,reasons:Object.freeze([] as string[])}}
export const OLD_AMBIGUOUS_COMP_G_004_HASH='fnv1a32-pre-expense-cost-failed-uniqueness';
