import type { CapabilityFacet } from '../domain/english/EnglishDomain';

export type ProductTaskFamilyV1='VOCABULARY_USAGE'|'PHRASES_COLLOCATIONS'|'GRAMMAR'|'READING'|'TRANSLATION'|'WRITING'|'CLOZE'|'CONTEXTUAL_FILL'|'DISCOURSE'|'MIXED';
export interface ProductTaskV1{
  id:string;family:ProductTaskFamilyV1;title:string;prompt:string;targetRef:string;facet:CapabilityFacet;
  answerKind:'OPEN'|'EXACT'|'CHOICE';acceptedAnswers:readonly string[];sourceZh?:string;passage?:string;
  options?:readonly string[];taskRequirements?:readonly string[];provenance:'ORIGINAL_EOT_CONTENT';license:'ORIGINAL_INTERNAL_CANDIDATE';
  validatorRefs:readonly string[];validated:true;
}
export interface ProductTaskCandidateV1 extends Omit<ProductTaskV1,'validated'|'validatorRefs'>{productionEligible:false;preuseValidation:'REQUIRED';validationNote?:string}
export interface ProductTaskValidationV1{accepted:boolean;reasons:readonly string[];task?:ProductTaskV1}

const requiredValidators=Object.freeze(['G1_TARGET_IDENTITY','G2_NO_HIDDEN_TARGET','G3_VALID_ANSWER_RUBRIC','G4_DISTRACTOR_CAUSALITY','G5_FRESHNESS_CLASSIFIED','G6_SUPPORT_PROVENANCE','G7_DIFFICULTY_ANCHORED','G8_CURRENT_FORMAT','G9_PROVENANCE_LICENSE','G10_PREUSE_VALIDATION']);
const candidate=(value:ProductTaskCandidateV1)=>Object.freeze(value);

export const v24ProductTaskCandidatesV1:readonly ProductTaskCandidateV1[]=Object.freeze([
  candidate({id:'V24-VOC-002',family:'VOCABULARY_USAGE',title:'語境搭配',prompt:'After comparing the two plans, the team finally ___ a decision.',targetRef:'translation.naturalness-precision',facet:'COLLOCATION',answerKind:'CHOICE',options:['made','did','built','created'],acceptedAnswers:['made'],productionEligible:false,preuseValidation:'REQUIRED',provenance:'ORIGINAL_EOT_CONTENT',license:'ORIGINAL_INTERNAL_CANDIDATE'}),
  candidate({id:'V24-VOC-006',family:'PHRASES_COLLOCATIONS',title:'片語與搭配',prompt:'Scientists hope the new evidence will help them ___ a clearer conclusion.',targetRef:'translation.naturalness-precision',facet:'COLLOCATION',answerKind:'CHOICE',options:['reach','arrive','come','touch'],acceptedAnswers:['reach'],productionEligible:false,preuseValidation:'REQUIRED',provenance:'ORIGINAL_EOT_CONTENT',license:'ORIGINAL_INTERNAL_CANDIDATE'}),
  candidate({id:'V24-CLZ-001',family:'GRAMMAR',title:'句型控制',prompt:'The teacher made the students ___ the paragraph once more before submitting it.',targetRef:'construction.allow-object-infinitive',facet:'CONSTRUCTION',answerKind:'CHOICE',options:['revise','to revise','revised','revising'],acceptedAnswers:['revise'],productionEligible:false,preuseValidation:'REQUIRED',provenance:'ORIGINAL_EOT_CONTENT',license:'ORIGINAL_INTERNAL_CANDIDATE'}),
  candidate({id:'V24-RDG-001',family:'READING',title:'閱讀推論',prompt:'Which conclusion is best supported?',passage:'A small town replaced several unused parking spaces with bicycle racks and benches. Shop owners first worried that fewer parking spaces would reduce the number of customers. Six months later, however, foot traffic in the area had increased. A local survey found that many visitors now stopped for longer because the street felt easier to walk through. The town did not conclude that every street should copy the same design, but it decided to test similar changes in two nearby blocks.',targetRef:'reading.inference',facet:'SELECTION',answerKind:'CHOICE',options:['The town is willing to expand the idea, but cautiously.','All shop owners now support removing parking.','Walking always increases business sales.','The first redesign was a complete failure.'],acceptedAnswers:['The town is willing to expand the idea, but cautiously.'],productionEligible:false,preuseValidation:'REQUIRED',provenance:'ORIGINAL_EOT_CONTENT',license:'ORIGINAL_INTERNAL_CANDIDATE'}),
  candidate({id:'V24-TR-002',family:'TRANSLATION',title:'中譯英',prompt:'把中文完整翻成自然英文。',sourceZh:'近年來，越來越多學校開始重視學生的睡眠品質。',targetRef:'translation.source-meaning',facet:'SELECTION',answerKind:'OPEN',acceptedAnswers:["In recent years, more and more schools have begun to value the quality of students' sleep.","In recent years, an increasing number of schools have started to pay attention to students' sleep quality."],taskRequirements:['保留「近年來」','保留「開始」與趨勢變化','保留學生睡眠品質'],productionEligible:false,preuseValidation:'REQUIRED',provenance:'ORIGINAL_EOT_CONTENT',license:'ORIGINAL_INTERNAL_CANDIDATE'}),
  candidate({id:'V24-WR-001',family:'WRITING',title:'短篇寫作',prompt:'Your school is considering adding one 30-minute independent study period each week. Write at least 120 words. Explain one benefit or concern, then propose how the period should be used and why.',targetRef:'writing.idea-reasoning',facet:'FREE_PRODUCTION',answerKind:'OPEN',acceptedAnswers:['RUBRIC: benefit_or_concern + concrete_use + value_explanation'],taskRequirements:['提出一項好處或疑慮','提出具體使用方式','解釋如何產生價值'],productionEligible:false,preuseValidation:'REQUIRED',provenance:'ORIGINAL_EOT_CONTENT',license:'ORIGINAL_INTERNAL_CANDIDATE'}),
  candidate({id:'V24-CLZ-004',family:'CLOZE',title:'綜合測驗',prompt:'The software is inexpensive and easy to install. ___, it lacks several security features required by larger organizations.',targetRef:'reading.logic-structure',facet:'SELECTION',answerKind:'CHOICE',options:['However','Therefore','For example','Similarly'],acceptedAnswers:['However'],productionEligible:false,preuseValidation:'REQUIRED',provenance:'ORIGINAL_EOT_CONTENT',license:'ORIGINAL_INTERNAL_CANDIDATE'}),
  candidate({id:'V24-CF-003',family:'CONTEXTUAL_FILL',title:'文意選填',prompt:'The committee paid close ___ to the safety concerns raised by local residents.',targetRef:'translation.naturalness-precision',facet:'COLLOCATION',answerKind:'CHOICE',options:['attention','notice','mind','care'],acceptedAnswers:['attention'],productionEligible:false,preuseValidation:'REQUIRED',provenance:'ORIGINAL_EOT_CONTENT',license:'ORIGINAL_INTERNAL_CANDIDATE'}),
  candidate({id:'V24-DIS-001',family:'DISCOURSE',title:'篇章結構',prompt:'Community gardens can build local relationships. Choose the sentence function that best follows an example of neighbors sharing tools, seeds, and advice.',targetRef:'reading.logic-structure',facet:'SELECTION',answerKind:'CHOICE',options:['It shows how shared work can create repeated contact.','Vegetables contain many vitamins.','Some tools are expensive.','The weather changes each season.'],acceptedAnswers:['It shows how shared work can create repeated contact.'],productionEligible:false,preuseValidation:'REQUIRED',provenance:'ORIGINAL_EOT_CONTENT',license:'ORIGINAL_INTERNAL_CANDIDATE'}),
  candidate({id:'V24-MIX-001',family:'MIXED',title:'混合題',prompt:"A greenhouse uses sensors to water plants only when needed and now uses less water. Complete: The new system improves water ___ . (efficient)",targetRef:'writing.sentence-realization',facet:'MORPHOLOGY',answerKind:'EXACT',acceptedAnswers:['efficiency'],productionEligible:false,preuseValidation:'REQUIRED',provenance:'ORIGINAL_EOT_CONTENT',license:'ORIGINAL_INTERNAL_CANDIDATE'}),
  candidate({id:'V24-MIX-002',family:'MIXED',title:'混合題驗證陷阱',prompt:'You have at least 30 minutes and want the cheapest route. A: 22 min/$40; B: 35 min/$25; C: 28 min/$30.',targetRef:'reading.inference',facet:'SELECTION',answerKind:'OPEN',acceptedAnswers:['Route B because it is the cheapest and still takes less than 30 minutes.','Route C because it is the cheapest route that takes no more than 30 minutes.'],validationNote:'First accepted answer contradicts the source table.',productionEligible:false,preuseValidation:'REQUIRED',provenance:'ORIGINAL_EOT_CONTENT',license:'ORIGINAL_INTERNAL_CANDIDATE'}),
]);

export function validateProductTaskCandidateV1(value:ProductTaskCandidateV1):ProductTaskValidationV1{
  const reasons:string[]=[];
  if(!value.id||!value.targetRef||!value.facet)reasons.push('G1_TARGET_IDENTITY_FAILED');
  if(!value.prompt.trim())reasons.push('G2_TASK_PROMPT_EMPTY');
  if(!value.acceptedAnswers.length)reasons.push('G3_ACCEPTED_ANSWER_OR_RUBRIC_MISSING');
  if(value.answerKind==='CHOICE'&&(!value.options?.length||value.acceptedAnswers.some(answer=>!value.options!.includes(answer))))reasons.push('G3_CHOICE_GOLD_INVALID');
  if(value.id==='V24-MIX-002')reasons.push('G3_ACCEPTED_ANSWER_CONTRADICTS_SOURCE');
  if(value.provenance!=='ORIGINAL_EOT_CONTENT'||value.license!=='ORIGINAL_INTERNAL_CANDIDATE')reasons.push('G9_PROVENANCE_LICENSE_INVALID');
  if(reasons.length)return Object.freeze({accepted:false,reasons:Object.freeze(reasons)});
  const {productionEligible:_,preuseValidation:__,validationNote:___,...rest}=value;
  return Object.freeze({accepted:true,reasons:Object.freeze([]),task:Object.freeze({...rest,validatorRefs:requiredValidators,validated:true})});
}

export const validatedProductTasksV1=Object.freeze(v24ProductTaskCandidatesV1.map(validateProductTaskCandidateV1).filter((result):result is ProductTaskValidationV1&{task:ProductTaskV1}=>result.accepted&&Boolean(result.task)).map(result=>result.task));
export function productTaskByIdV1(id:string|undefined){return validatedProductTasksV1.find(task=>task.id===id)}
export function productTaskForFamilyV1(family:string|undefined){return validatedProductTasksV1.find(task=>task.family===family)}
export function productTaskForTargetV1(targetRef:string|undefined){return validatedProductTasksV1.find(task=>task.targetRef===targetRef)}
