export interface ContentWaveGCapabilityStatusV1{capabilityId:string;implementationStatus:'CONTRACT_ONLY'|'FIRST_PASS'|'BLOCKED_EXTERNAL';practicalEffect:string;whyNot100:string}
export const contentWaveGCapabilityStatusV1:readonly ContentWaveGCapabilityStatusV1[]=Object.freeze([
 {capabilityId:'G.prompt-generation',implementationStatus:'FIRST_PASS',practicalEffect:'Curated/template prompt generation exists for the current Writing Beta targets without revealing a reference answer.',whyNot100:'Broader target coverage and AI proposal generation remain.'},
 {capabilityId:'G.examples',implementationStatus:'CONTRACT_ONLY',practicalEffect:'Examples remain teaching content and are not required for the fresh-task slice.',whyNot100:'Needs a validated example generator/catalog.'},
 {capabilityId:'G.counterexamples',implementationStatus:'CONTRACT_ONLY',practicalEffect:'Counterexample ownership is established but not production-fed.',whyNot100:'Needs target-specific semantic validation.'},
 {capabilityId:'G.distractors',implementationStatus:'CONTRACT_ONLY',practicalEffect:'Distractors are not used to fake open production.',whyNot100:'Needs a dedicated generation/validation path for selection tasks.'},
 {capabilityId:'G.fresh-task',implementationStatus:'FIRST_PASS',practicalEffect:'A separately identified new task can be generated and validated before H enters fresh assessment.',whyNot100:'Coverage is limited to current curated Writing Beta targets.'},
 {capabilityId:'G.changed-context',implementationStatus:'FIRST_PASS',practicalEffect:'Transfer tasks require a different prompt and bounded lexical/context distance before delivery.',whyNot100:'Semantic context-distance validation is still heuristic outside curated packs.'},
 {capabilityId:'G.difficulty',implementationStatus:'CONTRACT_ONLY',practicalEffect:'Difficulty metadata is explicit rather than inferred from target identity.',whyNot100:'No learner-calibrated difficulty controller yet.'},
 {capabilityId:'G.load',implementationStatus:'CONTRACT_ONLY',practicalEffect:'Task load records length, reasoning, idea-generation, content support and clause count, but does not yet choose tasks from a requested learner-specific load band.',whyNot100:'Needs an explicit desired-load contract, selection policy and empirical calibration before this is load control.'},
 {capabilityId:'G.semantic-validity',implementationStatus:'FIRST_PASS',practicalEffect:'Curated tasks require semantic requirements and canonical target/facet alignment.',whyNot100:'Open AI-generated semantic validation needs independent critic/data support.'},
 {capabilityId:'G.valid-alternatives',implementationStatus:'FIRST_PASS',practicalEffect:'Generated production tasks explicitly accept semantically valid alternatives and do not carry a single answer string.',whyNot100:'K/evaluators need broader target-specific alternative handling.'},
 {capabilityId:'G.content-safety',implementationStatus:'CONTRACT_ONLY',practicalEffect:'Current shipped tasks come only from reviewed curated packs.',whyNot100:'AI-generated/open-corpus content needs dedicated safety validation.'},
 {capabilityId:'G.context-relevance',implementationStatus:'FIRST_PASS',practicalEffect:'Task selection prefers contexts lexically distinct from the authentic source while preserving the D-authorized target.',whyNot100:'Needs semantic/contextual embeddings or critic support for broader content.'},
 {capabilityId:'G.generated-validation',implementationStatus:'FIRST_PASS',practicalEffect:'No candidate is delivered unless canonical target/facet, freshness, context, leakage, reuse and validator provenance gates pass.',whyNot100:'AI proposals still require stronger independent semantic/safety critics.'},
 {capabilityId:'G.content-packs',implementationStatus:'FIRST_PASS',practicalEffect:'A versioned curated Writing Beta task pack supplies known-safe fresh contexts.',whyNot100:'Needs corpus-backed packs and broader learner populations.'},
]);
export const WAVE_G_STATUS='READY_FOR_AUDIT' as const;
