export type LexicalFacetV1='FORM_RECOGNITION'|'SPELLING'|'SENSE_RECOGNITION'|'CONTEXTUAL_SENSE_DISCRIMINATION'|'MORPHOLOGY_FORM_CONTROL'|'COLLOCATION_CONTROL'|'PHRASE_CHUNK_CONTROL'|'CUED_RETRIEVAL'|'FREE_RETRIEVAL'|'PRODUCTIVE_CONTEXTUAL_USE'|'TRANSFER'|'RETENTION_READINESS';
export type LexicalControlV1='UNKNOWN'|'NEEDS_WORK'|'EMERGING'|'CONTROLLED';
export interface GlobalLexicalIdentityV1{lemmaId:string;lemma:string;senseId?:string;form?:string;collocationId?:string;chunkId?:string}
export interface LearnerLexicalObservationV1{id:string;learnerId:string;identity:GlobalLexicalIdentityV1;facet:LexicalFacetV1;control:Exclude<LexicalControlV1,'UNKNOWN'>;occurredAt:string;productContext:'GENERAL'|'EXAM';evidenceEligible:boolean;support:'NONE'|'LOOKUP_ASSISTED'|'OTHER_ASSISTED'}
export interface LearnerLexicalStateV1{learnerId:string;identity:GlobalLexicalIdentityV1;facets:Readonly<Partial<Record<LexicalFacetV1,LexicalControlV1>>>;observationIds:readonly string[]}
const identityKey=(x:GlobalLexicalIdentityV1)=>[x.lemmaId,x.senseId??'',x.form??'',x.collocationId??'',x.chunkId??''].join('|');
export function projectLearnerLexicalStateV1(learnerId:string,observations:readonly LearnerLexicalObservationV1[]):readonly LearnerLexicalStateV1[]{const map=new Map<string,LearnerLexicalObservationV1[]>();for(const o of observations.filter(o=>o.learnerId===learnerId&&o.evidenceEligible&&o.support==='NONE'))map.set(identityKey(o.identity),[...(map.get(identityKey(o.identity))??[]),o]);return Object.freeze([...map.values()].map(items=>{const sorted=[...items].sort((a,b)=>a.occurredAt.localeCompare(b.occurredAt)),facets:Partial<Record<LexicalFacetV1,LexicalControlV1>>={};for(const o of sorted)facets[o.facet]=o.control;return Object.freeze({learnerId,identity:sorted[0].identity,facets:Object.freeze(facets),observationIds:Object.freeze(sorted.map(o=>o.id))})}))}
export function lexicalPracticeNeedsV1(state:LearnerLexicalStateV1):readonly {facet:LexicalFacetV1;mechanismIds:readonly string[]}[]{const needs:{facet:LexicalFacetV1;mechanismIds:readonly string[]}[]=[];const add=(facet:LexicalFacetV1,ids:readonly string[])=>{if((state.facets[facet]??'UNKNOWN')!=='CONTROLLED')needs.push({facet,mechanismIds:Object.freeze(ids)})};add('CONTEXTUAL_SENSE_DISCRIMINATION',['meaning-representation','sense-contrast']);add('COLLOCATION_CONTROL',['collocation-network','chunk-as-unit']);add('FREE_RETRIEVAL',['meaning-word-retrieval']);add('MORPHOLOGY_FORM_CONTROL',['morphology-decomposition']);add('PRODUCTIVE_CONTEXTUAL_USE',['contextual-production','collocation-network']);return Object.freeze(needs)}
export function sameGlobalLexicalTruthV1(a:GlobalLexicalIdentityV1,b:GlobalLexicalIdentityV1){return identityKey(a)===identityKey(b)}
