export interface EnglishDomainWaveBCapabilityStatusV1{
  capabilityId:string;
  beforePercent:number;
  afterPercent:number;
  problem:string;
  rootCause:string;
  upgrade:string;
  dependency:string;
  acceptance:string;
  auditAdjusted?:boolean;
}

const rows = [
  ['B.word',55,88,'Word nodes existed but were not part of a queryable canonical graph.','Legacy EnglishDomainObject was a flat record.','Canonical LEXEME nodes with stable identity, aliases and typed relations.','C/G/J later consume the port.','A word can resolve canonically and link to senses/forms without learner-state fields.'],
  ['B.sense',45,88,'Sense was a type but had no explicit word-to-sense graph semantics.','Flat objects had no typed HAS_SENSE relation.','Canonical SENSE nodes plus HAS_SENSE and meaning-realization edges.','Content population later.','Sense identity is distinct from spelling/form and queryable from its lexeme.'],
  ['B.form',30,86,'Word form was not representable as its own canonical node.','Legacy type union lacked WORD_FORM.','WORD_FORM nodes and HAS_FORM relations preserve form-level claims.','J/K later.','Base/3sg/past forms can be targeted separately from the lexeme.'],
  ['B.spelling',50,86,'Spelling was only a facet on arbitrary objects.','Target identity and form identity were conflated.','Orthographic production is tied to explicit form-capable nodes.','Assessment later.','A spelling claim must resolve to a domain node that affords ORTHOGRAPHIC_PRODUCTION.'],
  ['B.morphology',45,86,'Morphology existed as a facet without a graph object for patterns.','No morphological-pattern node or relation.','MORPHOLOGICAL_PATTERN nodes plus USES_MORPHOLOGY edges.','Language-teacher runtime later.','Inflected forms can point to a reusable morphology pattern.'],
  ['B.chunk',55,86,'Chunk types existed but formulaic language categories were inconsistent.','Several old object types carried overlapping meaning.','Canonical CHUNK/FORMULAIC area normalizes formulaic targets while compatibility remains.','G/J later.','Formulaic targets have stable target identity and production facets.'],
  ['B.collocation',55,86,'Collocation was both an object type and facet but relations were underspecified.','No canonical relation semantics.','COLLOCATION nodes plus typed combination/part/reuse relation vocabulary.','G/J later.','Collocation targets can be distinguished from lexical senses and constructions.'],
  ['B.phrase-frame',40,88,'Reusable frames were folded into broad expression types.','No dedicated phrase-frame target kind.','PHRASE_FRAME nodes support reusable slot/frame targets.','F/G/J later.','A phrase frame can realize meaning without being treated as a full sentence answer key.'],
  ['B.register',45,82,'Register constraints were a string array with unclear evidence meaning.','Domain constraints and learner capability conditions were mixed.','Register/genre constraints stay target metadata while observation conditions are separate.','K/N later.','Register is queryable context metadata and never creates mastery by itself.'],
  ['B.grammar-construction',70,92,'Grammar construction targets worked but were fixture-shaped and detached from broader domain relations.','Stage-oriented target refs lacked canonical graph integration.','GRAMMAR_CONSTRUCTION nodes integrate with meaning, prerequisites and cross-skill enablement.','E/F/J later.','allow-object-infinitive resolves as canonical construction and retains its existing targetRef.'],
  ['B.meaning-encoding',35,90,'Meaning-to-English was a facet but had no first-class semantic anchor.','Graph modeled forms more readily than intended meaning.','MEANING_INTENT nodes plus REALIZES_MEANING edges permit multiple English realizations.','Translation/Writing later.','One meaning can map to more than one realization without declaring a single reference sentence as truth.'],
  ['B.writing-graph',20,84,'Writing capability was one broad object type.','No compositional writing capability graph.','Purpose/audience, idea/reasoning, organization/cohesion, sentence realization and revision nodes with dependencies.','H later deepens pedagogy.','Writing targets are graph-addressable without being learner mastery scores.'],
  ['B.translation-graph',25,86,'Translation dimensions existed in outcome types but not in the English graph.','Translation construct lived outside canonical domain ownership.','Source meaning, segmentation, meaning-to-English and naturalness/precision nodes with prerequisite edges.','I/S later.','Translation can target meaning fidelity separately from English realization quality.'],
  ['B.reading-graph',20,84,'Reading had no canonical capability graph.','Reading was represented mainly as task/runtime concepts.','Meaning decomposition, reference tracking, logic/structure and inference nodes.','J later.','Reading targets can support output/translation without becoming a separate learner truth store.'],
  ['B.retrieval',70,90,'Retrieval facet existed but target affordance was not validated.','Any string targetRef could be paired with a facet.','Capability claims are qualified against canonical target + afforded facet.','C/K later.','Unknown targets or impossible target/facet combinations are rejected.'],
  ['B.production',72,90,'Production facets existed but were not domain-qualified.','Task/evidence layers could carry arbitrary target strings.','Canonical claim qualification distinguishes controlled/free production affordance per target.','C/K later.','Production claim key uses canonical target identity and supported facet.'],
  ['B.transfer',60,84,'Transfer was represented as a facet/state dimension despite being a condition on evidence.','Domain capability and evidence condition were conceptually conflated.','Transfer/context novelty is modeled as observation condition, not a domain target.','C/K/L later.','Same capability can be observed under SOURCE vs CHANGED_CONTEXT without duplicating the target.'],
  ['B.stability',55,84,'Retention was mixed into facet/state vocabulary.','Longitudinal condition was treated like language content.','Delayed context remains a capability observation condition while language target stays stable.','C/K/L later.','Delayed evidence varies condition, not target identity.'],
  ['B.support-dependence',60,88,'Support dependence lived only in learner projection.','No shared domain-level condition contract described what support qualifies an observation.','Typed support condition axis is exported by English Domain.','C/E/K later.','NONE/LIGHT/MEDIUM/EXPLICIT/MODEL can annotate the same canonical claim without changing its target.'],
  ['B.load-recurrence',25,84,'Task load and recurrence were free-text/indirect runtime concepts.','No canonical condition vocabulary.','Task-load and recurrence axes are explicit observation conditions.','D/E/K later.','Load/recurrence are conditions and cannot masquerade as language nodes.'],
  ['B.prerequisite-edges',45,92,'Prerequisite direction was ambiguous and old helper semantics were easy to misuse.','Legacy DomainRelationV4 did not document/query incoming prerequisite edges clearly.','PREREQUISITE_FOR is directional source-prerequisite -> dependent; graph validates cycles.','D/E later.','prerequisites(target) returns incoming prerequisite nodes and prerequisite cycles are rejected.'],
  ['B.target-identity',15,92,'TargetRef was effectively an arbitrary string.','No stable alias/canonical resolution layer.','Canonical IDs plus unique alias resolution preserve legacy refs while enabling stable domain identity.','C/G later.','Aliases resolve deterministically; collisions are rejected.'],
  ['B.semantic-intent',0,90,'Intended meaning was not a graph object.','Reference wording risked becoming the semantic anchor.','MEANING_INTENT nodes are separate from English realizations.','G/H/I later.','realizationsForMeaning returns linguistic realizations while meaning remains independent.'],
  ['B.relation-semantics',20,88,'Graph relations were scattered and incomplete.','ContentGovernanceV4 carried an isolated relation union.','Typed relation vocabulary covers senses/forms/morphology/prerequisites/realizations/alternatives/contrast/register/enablement/reuse.','G later.','Relation endpoints are canonical and duplicate/self relations are rejected.'],
  ['B.condition-schema',15,90,'Support/context/load/recurrence had no shared domain contract.','These dimensions appeared independently across runtime/evidence types.','EnglishCapabilityConditionV2 centralizes observation-condition semantics without owning learner state.','C/E/K/L later.','Condition changes do not change capability claim identity.'],
  ['B.graph-governance',30,88,'Content governance existed separately from the canonical English owner.','Graph nodes did not require provenance/version/validation.','Canonical nodes/edges require source, version and validated provenance.','G/T/U later.','Unvalidated nodes/edges cannot enter a canonical graph.'],
  ['B.graph-query',20,92,'EnglishDomainPortV1 only exposed get/prerequisites on flat objects.','No graph traversal/query authority.','EnglishDomainPortV2 adds resolve, prerequisites/dependents, relations, alternatives, contrasts, meanings, areas and facet checks.','All downstream domain consumers.','Queries operate over one validated immutable graph.'],
] as const;

const independentAuditScoresV1:Readonly<Record<string,number>>=Object.freeze({"B.word":75,"B.sense":75,"B.form":75,"B.spelling":75,"B.morphology":75,"B.chunk":25,"B.collocation":25,"B.phrase-frame":75,"B.register":50,"B.grammar-construction":90,"B.meaning-encoding":75,"B.writing-graph":50,"B.translation-graph":50,"B.reading-graph":50,"B.retrieval":75,"B.production":75,"B.transfer":50,"B.stability":50,"B.support-dependence":50,"B.load-recurrence":50,"B.prerequisite-edges":75,"B.target-identity":90,"B.semantic-intent":75,"B.relation-semantics":75,"B.condition-schema":75,"B.graph-governance":75,"B.graph-query":75});

export const englishDomainWaveBCapabilityStatusV1:readonly EnglishDomainWaveBCapabilityStatusV1[]=Object.freeze(
  rows.map(([capabilityId,beforePercent,_afterPercent,problem,rootCause,upgrade,dependency,acceptance])=>{
    const afterPercent=independentAuditScoresV1[capabilityId]??Number(_afterPercent);
    const auditAdjusted=afterPercent!==Number(_afterPercent);
    return{capabilityId:String(capabilityId),beforePercent:Number(beforePercent),afterPercent,problem:String(problem),rootCause:String(rootCause),upgrade:String(upgrade),dependency:String(dependency),acceptance:auditAdjusted?`${String(acceptance)} Independent audit calibration applied.`:String(acceptance),auditAdjusted};
  })
);
