export type ActivityFamily = 'RECOGNITION' | 'RETRIEVAL' | 'CORRECTION' | 'CONTROLLED_PRODUCTION' | 'TRANSFER' | 'MINI_OUTPUT';
export type AssistanceLevel = 'NONE' | 'SEMANTIC_CUE' | 'RULE_CUE' | 'STRUCTURE_CUE' | 'PARTIAL_REVEAL' | 'FULL_REVEAL';

export const PRODUCTION_ACTIVITY_FAMILIES: ReadonlySet<ActivityFamily> = new Set(['CORRECTION', 'CONTROLLED_PRODUCTION', 'TRANSFER', 'MINI_OUTPUT']);
