import { Stack, router } from 'expo-router';
import { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { founderTeacherScenariosV1, type FounderTeacherScenarioIdV1 } from '../../src/evaluation';
import { advanceTeacherCompositionV1, composeTeacherPlanV1, recomposeTeacherPlanV1 } from '../../src/teaching';

const copy=(kind:string,changed:boolean)=>changed?'剛才的方法沒有幫你看清楚；我們換一個角度，直接做下一小步。':kind==='REPRESENT'?'我看見你卡住的地方了。先只處理這一小步。':kind==='FADE_SUPPORT'?'這一步有進展。現在把提示拿掉，再由你完成一次。':kind==='RETURN_TO_OUTPUT'?'把剛才學到的放回你的原作，由你親自改寫。':'現在換你動手；我只保留目前需要的協助。';
export default function TeacherCoreExperience(){
  const [scenarioId,setScenarioId]=useState<FounderTeacherScenarioIdV1>('RECOMPOSE'),[changed,setChanged]=useState(false),[debug,setDebug]=useState(false);
  const scenario=founderTeacherScenariosV1.find(value=>value.id===scenarioId)??founderTeacherScenariosV1[0];
  const initial=useMemo(()=>composeTeacherPlanV1({request:scenario.request,occurredAt:'2026-08-31T00:00:00Z',sessionId:`founder:${scenario.id}`,mode:scenario.mode}),[scenario]);
  const [plan,setPlan]=useState(initial),piece=plan.pieces[plan.cursor];
  const select=(id:FounderTeacherScenarioIdV1)=>{const next=founderTeacherScenariosV1.find(value=>value.id===id)!;setScenarioId(id);setPlan(composeTeacherPlanV1({request:next.request,occurredAt:'2026-08-31T00:00:00Z',sessionId:`founder:${next.id}`,mode:next.mode}));setChanged(false)};
  const respond=(success:boolean)=>{const advanced=advanceTeacherCompositionV1(plan,success?'ASSISTED_SUCCESS':'CONFUSED',new Date().toISOString());if(advanced.status==='RECOMPOSED'){setPlan(recomposeTeacherPlanV1({prior:advanced,request:{...scenario.request,recentTreatment:[...scenario.request.recentTreatment,{mechanismId:piece.mechanismId??piece.blockId,support:piece.support,outcome:'FAILURE',responseSignal:'CONFUSED'}]},occurredAt:new Date().toISOString(),sessionId:`founder:${scenario.id}`,mode:scenario.mode}));setChanged(true)}else{setPlan(advanced);setChanged(false)}};
  return <SafeAreaView style={s.safe}><Stack.Screen options={{headerShown:false}}/><ScrollView contentContainerStyle={s.page}><Pressable onPress={()=>router.back()}><Text style={s.back}>返回</Text></Pressable><Text style={s.kicker}>FOUNDER TEACHER ACCEPTANCE</Text><Text style={s.title}>真實 Teacher composition 體驗</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} style={s.scenarios}>{founderTeacherScenariosV1.map(value=><Pressable key={value.id} style={[s.chip,value.id===scenarioId&&s.chipOn]} onPress={()=>select(value.id)}><Text style={value.id===scenarioId?s.chipOnText:s.chipText}>{value.label}</Text></Pressable>)}</ScrollView><View style={s.original}><Text style={s.label}>原始學習工作</Text><Text style={s.sentence}>{scenario.purpose}</Text></View><View style={s.teacher}><Text style={s.teacherName}>EOT Teacher</Text><Text style={s.teacherText}>{copy(piece.kind,changed)}</Text></View><View style={s.action}><Text style={s.step}>{piece.kind.replaceAll('_',' ')}</Text><Text style={s.prompt}>{piece.learnerAction}</Text></View>{piece.kind!=='RETURN_TO_OUTPUT'?<View style={s.buttons}><Pressable style={s.primary} onPress={()=>respond(true)}><Text style={s.primaryText}>我完成了這一步</Text></Pressable><Pressable style={s.secondary} onPress={()=>respond(false)}><Text style={s.secondaryText}>我還是不懂</Text></Pressable></View>:<Pressable style={s.primary} onPress={()=>select(scenario.id)}><Text style={s.primaryText}>回到原始工作</Text></Pressable>}<Pressable onPress={()=>setDebug(value=>!value)}><Text style={s.debugToggle}>{debug?'隱藏 Founder Debug View':'顯示 Founder Debug View'}</Text></Pressable>{debug?<View style={s.debug}><Text style={s.debugText}>scenario: {scenario.id}</Text><Text style={s.debugText}>learner state: {scenario.request.learnerState??'UNKNOWN'}</Text><Text style={s.debugText}>target/facet: {scenario.request.targetRef} / {scenario.request.facet}</Text><Text style={s.debugText}>composition: {plan.planId}</Text><Text style={s.debugText}>active piece: {piece.id} ({piece.kind})</Text><Text style={s.debugText}>mechanism/block: {piece.mechanismId??piece.blockId}</Text><Text style={s.debugText}>support: {piece.support}</Text><Text style={s.debugText}>recompose/fade: {changed?'MECHANISM_FAILED_RECOMPOSE':'CURRENT_PLAN_TRANSITION'}</Text><Text style={s.debugText}>Treatment Response used: {scenario.request.recentTreatment.length}</Text><Text style={s.debugText}>PCK assets/provenance: eligible runtime lineage only</Text><Text style={s.debugText}>model route: {scenario.expectedRoute}</Text><Text style={s.debugText}>token/cost telemetry: provider-owned / no synthetic cost</Text><Text style={s.debugText}>evidence ceiling: {piece.evidenceCeiling}</Text><Text style={s.debugText}>return result: {plan.status}</Text><Text style={s.debugText}>mastery mutation allowed: {String(plan.masteryMutationAllowed)}</Text></View>:null}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#F5F0E9'},page:{width:'100%',maxWidth:760,alignSelf:'center',padding:24,paddingBottom:80},back:{color:'#72543F',fontWeight:'800'},kicker:{marginTop:30,fontSize:11,fontWeight:'900',letterSpacing:1.2,color:'#976846'},title:{fontSize:30,lineHeight:39,fontWeight:'900',color:'#332B25',marginTop:7},scenarios:{marginTop:18},chip:{paddingHorizontal:12,paddingVertical:9,borderRadius:999,borderWidth:1,borderColor:'#B9A896',marginRight:8},chipOn:{backgroundColor:'#684B38'},chipText:{color:'#684B38',fontWeight:'700'},chipOnText:{color:'#fff',fontWeight:'800'},original:{marginTop:24,padding:18,borderRadius:16,backgroundColor:'#fff',borderLeftWidth:4,borderLeftColor:'#B7835C'},label:{fontSize:11,fontWeight:'800',color:'#98765D'},sentence:{fontSize:17,lineHeight:26,color:'#302A26',marginTop:7},teacher:{marginTop:18,padding:17,borderRadius:16,backgroundColor:'#EDE3D7'},teacherName:{fontSize:11,fontWeight:'900',color:'#805B40'},teacherText:{fontSize:16,lineHeight:25,color:'#3C322B',marginTop:5},action:{marginTop:15,padding:18,borderRadius:16,backgroundColor:'#FFFEFC',borderWidth:1,borderColor:'#DED4C9'},step:{fontSize:18,fontWeight:'900',color:'#4C3B30'},prompt:{fontSize:14,lineHeight:22,color:'#74685F',marginTop:8},buttons:{gap:9,marginTop:16},primary:{minHeight:50,borderRadius:13,backgroundColor:'#684B38',alignItems:'center',justifyContent:'center',marginTop:16},primaryText:{color:'#fff',fontWeight:'900'},secondary:{minHeight:46,borderRadius:13,borderWidth:1,borderColor:'#A38B78',alignItems:'center',justifyContent:'center'},secondaryText:{color:'#684B38',fontWeight:'800'},debugToggle:{marginTop:24,textAlign:'center',color:'#7A6A5E',fontWeight:'700'},debug:{marginTop:10,padding:14,borderRadius:12,backgroundColor:'#292725'},debugText:{fontFamily:'monospace',fontSize:11,lineHeight:18,color:'#E8E1D9'}});
