import {Stack,useLocalSearchParams} from'expo-router';
import React from'react';
import{Pressable,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import{SafeAreaView}from'react-native-safe-area-context';
import{LearnerPage,SparseCard}from'../../components/experience/LearnerPage';
import{ContextualLookup}from'../../components/learning/ContextualLookup';
import{OutputWorkspace}from'../../components/learning/OutputWorkspace';
import{lessonHarnessFixtureV1}from'../../src/ui/qa/lessonHarness';
import{MemoryTruthSurface}from'../../components/experience/MemoryTruthSurface';
import{LessonErrorState,LessonLoadingState}from'../../components/learning/LessonAsyncState';

export default function UiuxHarness(){const p=useLocalSearchParams<{state?:string;viewport?:string}>(),f=lessonHarnessFixtureV1(p.state),meta=null;
if(['OPENING','TIME','DATE','MOCK','ROUTE','PRACTICE'].includes(p.state??''))return <Setup state={p.state!} meta={meta}/>;
if(p.state==='LOADING')return <Page kicker="" title="" meta={meta}><LessonLoadingState context="The clinic reserves two appointments for urgent cases every morning."/></Page>;
if(p.state==='NETWORK_ERROR')return <Page kicker="" title="" meta={meta}><LessonErrorState context="我非常同意這個想法。" draft="I am very agree with this idea."/></Page>;
if(f.productionEntry==='RESULT')return <Page kicker="" title="今天先到這裡" meta={meta}><Text>18 分鐘</Text><Primary label="完成"/></Page>;
if(f.productionEntry==='MY_ENGLISH')return <Page kicker="MY ENGLISH" title="我的英文" meta={meta}><MemoryTruthSurface groups={[{title:'最近有變化',items:[{when:'今天',target:'qualify / quantify',truth:'換到新的句子後，已經自己判斷對一次。'},{when:'昨天',target:'be responsible for',truth:'看得懂了，自己寫還不穩。'}]}]}/></Page>;
if(f.productionEntry==='PROGRESS_HISTORY')return <Page kicker="PROGRESS / HISTORY" title="進展與歷程" meta={meta}><SparseCard title="回到原作完成修改" body="你把剛才學到的做法帶回原本的作品；這是有意義的里程碑，而不是一次點擊紀錄。"/><SparseCard title="第一次獨立產出" body="在沒有提示與答案曝光的情況下完成。"/></Page>;
return <SafeAreaView style={s.safe}><Stack.Screen options={{headerShown:false}}/><ScrollView contentContainerStyle={s.page}>{meta}{f.productionEntry==='TODAY'?<Today/>:f.productionEntry==='CONTEXTUAL_LOOKUP'?<Lookup/>:f.productionEntry==='READING_PRACTICE'||f.productionEntry==='FORMAL_LOCKED_ATTEMPT'?<Reading formal={f.productionEntry==='FORMAL_LOCKED_ATTEMPT'}/>:f.vm?<OutputWorkspace vm={f.vm} value={f.vm.output.text} onChangeText={()=>{}} onPrimary={()=>{}} onPlaceLanguageObject={()=>{}} onStuck={()=>{}} onCorrectIntent={()=>{}}/>:<Text>{f.transport}</Text>}</ScrollView></SafeAreaView>}
function Page({kicker,title,meta,children}:{kicker:string;title:string;meta:React.ReactNode;children:React.ReactNode}){return <><Stack.Screen options={{headerShown:false}}/><LearnerPage kicker={kicker} title={title}>{meta}{children}</LearnerPage></>}
function Today(){return <><Text style={s.title}>今天</Text><View style={s.todayMission}><Text style={s.label}>詞彙與句子</Text><Text style={s.focusTitle}>先把容易混在一起的意思分清楚</Text><Text style={s.body}>你上次需要提示才能判斷，今天換個句子再確認一次。</Text><Text style={s.note}>約 18 分鐘</Text></View><Primary label="開始"/></>}
function Lookup(){return <><Text style={s.kicker}>原文</Text><Text style={s.passage}>The policy may lead to a significant change in how students learn.</Text><ContextualLookup initialOpenId="e1" entries={[{id:'e1',label:'significant change',meaning:'顯著的改變',note:'這裡表示學習方式會有明顯改變。'},{id:'e2',label:'lead to',meaning:'導致；帶來'}]}/></>}
function Reading({formal}:{formal:boolean}){return <><View style={s.row}><Text style={s.kicker}>{formal?'FORMAL':'PRACTICE'} · 閱讀作答</Text>{formal?<Text style={s.clock}>18 分鐘</Text>:null}</View><View style={s.card}><Text style={s.passage}>The library stayed open because students needed a quiet place to finish their projects.</Text></View><Text style={s.question}>Why did the library stay open?</Text><TextInput multiline value="Students needed a quiet place." editable={false} style={s.input}/><Text style={s.note}>{formal?'正式作答中：Teacher、提示、揭答與查字已鎖定。':'練習模式可在提交前使用一般支援。'}</Text><Primary label="提交整份作答"/></>}
function Primary({label}:{label:string}){return <Pressable style={s.primary}><Text style={s.primaryText}>{label}</Text></Pressable>}
function Setup({state,meta}:{state:string;meta:React.ReactNode}){const rows:Record<string,string[]>={TIME:['10 分','15 分','20 分','30 分','45 分'],DATE:['學測日期　　2027 / 01 / xx　›','下一次模考　　還不確定　›'],MOCK:['詞彙　— / 10','綜合測驗　— / 10','文意選填　— / 10','篇章結構　— / 8','閱讀測驗　— / 24','混合題　— / 10','中譯英　— / 8','英文作文　— / 20'],ROUTE:['先追回最容易拿回來的分數','先把篇章與閱讀接起來','先穩住中譯英和作文'],PRACTICE:['字詞與句子','Vocabulary / Phrase　›','Comprehensive　›','Contextual Fill　›','篇章與閱讀','Discourse　›','Reading　›','Mixed　›','輸出','Translation　›','Writing　›']};const title=state==='OPENING'?'先把你的英文起點抓準。':state==='TIME'?'每天想留多少時間給英文？':state==='DATE'?'接下來的時間點':state==='MOCK'?'最近一次模考':state==='ROUTE'?'接下來怎麼練':'Practice';return <SafeAreaView style={s.safe}><Stack.Screen options={{headerShown:false}}/><ScrollView contentContainerStyle={s.setup}>{meta}{state==='OPENING'?<Text style={s.wordmark}>EOT</Text>:null}<View style={state==='OPENING'?s.setupCenter:undefined}><Text style={s.title}>{title}</Text><Text style={s.body}>{state==='OPENING'?'用最近一次模考，加上你每天能留的時間。':state==='MOCK'?'有寫的就填，沒有可以留白。':state==='PRACTICE'?'想練哪一種？':''}</Text></View><View style={s.setupRows}>{(rows[state]??[]).map((x,i)=><View key={`${x}-${i}`} style={[s.setupRow,state==='ROUTE'&&i===0&&s.routeOn]}><Text style={state==='PRACTICE'&&[0,4,8].includes(i)?s.focusTitle:s.body}>{x}</Text>{state==='ROUTE'?<Text style={s.note}>文意選填和篇章結構掉分最集中，先補這兩區。</Text>:null}</View>)}</View>{state!=='PRACTICE'?<Primary label={state==='OPENING'?'開始設定':state==='ROUTE'?'用這條路開始':'繼續'}/>:null}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({
safe:{flex:1,backgroundColor:'#F7F1E7'},
page:{width:'100%',minWidth:0,alignSelf:'center',maxWidth:390,padding:20,paddingBottom:70,gap:16},
meta:{paddingBottom:8,borderBottomWidth:1,borderBottomColor:'#D9CBB8'},dev:{fontSize:10,fontWeight:'900',color:'#806D59'},metaText:{fontSize:10,color:'#806D59'},
kicker:{fontSize:12,fontWeight:'900',color:'#654D3B'},title:{fontSize:29,lineHeight:39,fontWeight:'900',color:'#2F261F',flexShrink:1},body:{fontSize:15,lineHeight:24,color:'#6F6256',flexShrink:1},note:{fontSize:13,lineHeight:20,color:'#6F6256',flexShrink:1},
focus:{paddingVertical:20,borderTopWidth:1,borderBottomWidth:1,borderColor:'#D9CBB8',gap:8},todayMission:{flex:1,justifyContent:'center',gap:14},label:{fontSize:12,fontWeight:'700',color:'#A87446'},focusTitle:{fontSize:21,lineHeight:30,fontWeight:'700',color:'#2F261F'},
primary:{minHeight:54,borderRadius:14,backgroundColor:'#654D3B',alignItems:'center',justifyContent:'center'},primaryText:{color:'#fff',fontWeight:'900'},row:{flexDirection:'row',justifyContent:'space-between'},clock:{fontSize:12,fontWeight:'900',color:'#A75E2D'},
card:{padding:16,borderRadius:14,backgroundColor:'#FFFCF7',borderWidth:1,borderColor:'#D9CBB8'},passage:{fontSize:16,lineHeight:26,color:'#2F261F',flexShrink:1},question:{fontSize:18,lineHeight:27,fontWeight:'800',color:'#2F261F',flexShrink:1},input:{minHeight:80,borderWidth:1,borderColor:'#D9CBB8',borderRadius:14,padding:14,fontSize:16,backgroundColor:'#FFFCF7'},setup:{flexGrow:1,width:'100%',minWidth:0,alignSelf:'center',maxWidth:390,padding:20,paddingBottom:32,gap:24},wordmark:{fontSize:14,fontWeight:'700',letterSpacing:1.4,color:'#49372D'},setupCenter:{flex:1,justifyContent:'center',gap:16},setupRows:{gap:8,minWidth:0},setupRow:{minHeight:52,width:'100%',minWidth:0,padding:12,borderBottomWidth:1,borderBottomColor:'#DDD4C8',justifyContent:'center',gap:6},routeOn:{borderLeftWidth:3,borderLeftColor:'#C78A45',backgroundColor:'#F8EEE0'}
});
