import type{LessonPlanV1,ProductContextV1}from'../../architecture/contracts';
import type{LearnerModelSnapshotV3}from'../../domain/learner/LearnerModelV3';
import type{BlockSupportV4}from'../../domain/v4/LearningBlockV4';
import{defaultTeachingOpportunityConditionsV1}from'../../teaching';
import{decideInnerTutorV1,type LearnerOutcomeV1,type QualifiedInnerTutorDecisionV1}from'../../teacher-runtime';
import type{SemanticAssessmentDecisionV1}from'../../assessment/semanticAssessment';
import type { InnerTutorDecisionInputV1 } from '../../teacher-runtime';
import { triageExamUnitsV1, type ExamTriageReceiptV1 } from './examTriage';
import { readingAdaptiveTeachingEligibilityV1 } from './readingContinuationCoverage';
import { diagnoseExamFamilyUnitV1, type ExamFamilyDiagnosisV1 } from './examFamilyDiagnosis';
interface BoundUnitV1{unitId:string;responseKey:string;canonicalTargetRef:string;canonicalFacet:string;senseId?:string;evaluatorKind:'EXACT_KEY'|'SEMANTIC_RUBRIC';status:'BOUND'}
interface CanonicalExamTaskV1{task_id:string;family:string;subtype:string;payload:Record<string,unknown>;answer_or_rubric?:unknown;validation?:{canonical?:string};canonicalBinding?:{units:readonly BoundUnitV1[]}}

export interface CanonicalExamSubmissionV1{learnerId:string;sessionId:string;task:CanonicalExamTaskV1;lessonPlan:LessonPlanV1;productContext:ProductContextV1;learnerTruth:LearnerModelSnapshotV3;response:Readonly<Record<string,string>>;semanticOutcomes?:Readonly<Record<string,'CORRECT'|'PARTIALLY_CORRECT'|'INCORRECT'|'AMBIGUOUS'|'ABSTAIN'>>;semanticOutcomesByUnitId?:Readonly<Record<string,'CORRECT'|'PARTIALLY_CORRECT'|'INCORRECT'|'AMBIGUOUS'|'ABSTAIN'>>;semanticAssessmentsByUnitId?:Readonly<Record<string,SemanticAssessmentDecisionV1>>;lookupExposure:readonly string[];support:BlockSupportV4;freshnessIdentity:string;priorDecisions?:readonly QualifiedInnerTutorDecisionV1[]}
export interface CanonicalExamSubmissionResultV1{assessment:'SUCCESS'|'PARTIAL'|'FAILURE'|'NOT_EVALUATED';reasonCodes:readonly string[];unitResults:readonly{unitId:string;targetRef:string;facet:string;senseId?:string;outcome:LearnerOutcomeV1;semanticAssessment?:SemanticAssessmentDecisionV1;familyDiagnosis?:ExamFamilyDiagnosisV1}[];triage:readonly ExamTriageReceiptV1[];teacherDecision?:QualifiedInnerTutorDecisionV1;evidenceCommitAllowed:boolean}
const answers=(value:unknown):Record<string,unknown>=>{if(!value||typeof value!=='object'||Array.isArray(value))return{};const record=value as Record<string,unknown>;return(record.answers&&typeof record.answers==='object'?record.answers:record)as Record<string,unknown>};
const normalized=(value:unknown)=>String(value??'').trim().toLowerCase();
function selectedOptionText(task:CanonicalExamTaskV1,responseKey:string,selectedId:string|undefined){
 if(!selectedId)return undefined;const p=task.payload,collections=[p.blanks,p.questions,p.parts];
 for(const raw of collections){if(!Array.isArray(raw))continue;const item=(raw as {id?:unknown;options?:unknown}[]).find(row=>String(row?.id??'')===responseKey);if(item&&Array.isArray(item.options)){const option=(item.options as {id?:unknown;text?:unknown}[]).find(row=>String(row?.id??'')===selectedId);if(option?.text!==undefined)return String(option.text)}}
 const shared=Array.isArray(p.options)?p.options:Array.isArray(p.sentenceOptions)?p.sentenceOptions:undefined;if(shared){const option=(shared as {id?:unknown;text?:unknown}[]).find(row=>String(row?.id??'')===selectedId);if(option?.text!==undefined)return String(option.text)}
 return undefined;
}
function exactOutcome(task:CanonicalExamTaskV1,responseKey:string,expected:unknown,actual:string|undefined):LearnerOutcomeV1{
 if(actual===undefined||!actual.trim())return'FAILURE';
 if(typeof expected==='string'){const selectedText=selectedOptionText(task,responseKey,actual);return normalized(actual)===normalized(expected)||normalized(selectedText)===normalized(expected)?'SUCCESS':'FAILURE'}
 if(expected&&typeof expected==='object'){
  const rule=expected as{correctOptionId?:unknown;acceptable?:unknown};
  if(typeof rule.correctOptionId==='string')return actual===rule.correctOptionId?'SUCCESS':'FAILURE';
  if(Array.isArray(rule.acceptable)){const accepted=rule.acceptable.map(normalized);return accepted.includes(normalized(actual))?'SUCCESS':'FAILURE'}
 }
 return'NOT_EVALUATED';
}
function evaluate(input:CanonicalExamSubmissionV1):{outcome:LearnerOutcomeV1;reasons:string[];units:{unitId:string;targetRef:string;facet:string;senseId?:string;outcome:LearnerOutcomeV1;semanticAssessment?:SemanticAssessmentDecisionV1}[]}{
 const t=input.task;
 if(t.validation?.canonical!=='PASS'||!t.canonicalBinding?.units.length)return{outcome:'NOT_EVALUATED',reasons:['EXAM_TASK_NOT_CANONICALLY_VALIDATED','NO_NEGATIVE_EVIDENCE'],units:[]};
 const gold=answers(t.answer_or_rubric),semanticCounts=new Map<string,number>();
 for(const unit of t.canonicalBinding.units)if(unit.evaluatorKind==='SEMANTIC_RUBRIC')semanticCounts.set(unit.responseKey,(semanticCounts.get(unit.responseKey)??0)+1);
 const units=t.canonicalBinding.units.map(unit=>{let outcome:LearnerOutcomeV1='NOT_EVALUATED';const semanticAssessment=input.semanticAssessmentsByUnitId?.[unit.unitId],unitScoped=semanticAssessment?.outcome??input.semanticOutcomesByUnitId?.[unit.unitId],responseScoped=semanticCounts.get(unit.responseKey)===1?input.semanticOutcomes?.[unit.responseKey]:undefined,semantic=unitScoped??responseScoped;if(unit.evaluatorKind==='SEMANTIC_RUBRIC')outcome=semantic==='CORRECT'?'SUCCESS':semantic==='PARTIALLY_CORRECT'?'PARTIAL':semantic==='INCORRECT'?'FAILURE':'NOT_EVALUATED';else outcome=exactOutcome(t,unit.responseKey,gold[unit.responseKey],input.response[unit.responseKey]);return{unitId:unit.unitId,targetRef:unit.canonicalTargetRef,facet:unit.canonicalFacet,senseId:unit.senseId,outcome,semanticAssessment}});
 const scored=units.filter(unit=>unit.outcome!=='NOT_EVALUATED');if(!scored.length)return{outcome:'NOT_EVALUATED',reasons:[semanticCounts.size&&[...semanticCounts.values()].some(n=>n>1)?'UNIT_SCOPED_SEMANTIC_ASSESSMENT_REQUIRED':'SEMANTIC_OR_RUBRIC_EVALUATOR_REQUIRED','NO_NEGATIVE_EVIDENCE'],units};
 const outcome=scored.every(unit=>unit.outcome==='SUCCESS')?'SUCCESS':scored.some(unit=>unit.outcome==='SUCCESS'||unit.outcome==='PARTIAL')?'PARTIAL':'FAILURE';return{outcome,reasons:[outcome==='SUCCESS'?'UNIT_SCOPED_SUCCESS':outcome==='PARTIAL'?'UNIT_SCOPED_PARTIAL':'UNIT_SCOPED_FAILURE'],units};
}
export async function submitExamToCanonicalTeacherV1(input:CanonicalExamSubmissionV1 & {provider?:InnerTutorDecisionInputV1['provider']}):Promise<CanonicalExamSubmissionResultV1>{
 const evaluation=evaluate(input),diagnosedUnits=evaluation.units.map(item=>{const binding=input.task.canonicalBinding?.units.find(unit=>unit.unitId===item.unitId);return{...item,familyDiagnosis:diagnoseExamFamilyUnitV1({family:input.task.family,subtype:input.task.subtype,taskId:input.task.task_id,unitId:item.unitId,responseKey:binding?.responseKey??'',targetRef:item.targetRef,facet:item.facet,outcome:item.outcome,payload:input.task.payload,learnerResponse:binding?input.response[binding.responseKey]:undefined,truth:input.learnerTruth})}}),eligible=(unit:typeof evaluation.units[number])=>input.task.family!=='READING'||readingAdaptiveTeachingEligibilityV1(unit.targetRef,unit.facet),baseTriage=triageExamUnitsV1(diagnosedUnits,input.lessonPlan.timeBudgetMinutes),triage=baseTriage.map(item=>{const unit=diagnosedUnits.find(value=>value.unitId===item.unitId),depth=unit?.familyDiagnosis?.recommendedDepth,next=depth==='FIX_ONLY'?{...item,priority:'LOW' as const,action:'FIX_ONLY' as const,reasonCodes:[...item.reasonCodes,'FAMILY_DIAGNOSIS_FIX_ONLY']}:depth==='MICRO_TEACH'&&item.action==='DEEP_TEACH'?{...item,priority:'HIGH' as const,action:'MICRO_TEACH' as const,reasonCodes:[...item.reasonCodes,'FAMILY_DIAGNOSIS_BOUNDED_DEPTH']}:item;return eligible(item)?next:{...next,priority:'LOW' as const,action:'SAVE_FOR_LATER' as const,reasonCodes:[...next.reasonCodes,'READING_FRESH_CONTINUATION_UNAVAILABLE']}});if(evaluation.outcome==='NOT_EVALUATED')return{assessment:'NOT_EVALUATED',reasonCodes:evaluation.reasons,unitResults:diagnosedUnits,triage,evidenceCommitAllowed:false};
 const focus=diagnosedUnits.find(unit=>(unit.outcome==='FAILURE'||unit.outcome==='PARTIAL')&&eligible(unit))??diagnosedUnits.find(unit=>unit.outcome==='SUCCESS'&&eligible(unit));if(!focus)return{assessment:evaluation.outcome as CanonicalExamSubmissionResultV1['assessment'],reasonCodes:[...evaluation.reasons,'READING_ADAPTIVE_TEACHING_HELD_FOR_FRESH_COVERAGE'],unitResults:diagnosedUnits,triage,evidenceCommitAllowed:evaluation.outcome==='SUCCESS'&&input.support==='NONE'};
 const binding=input.task.canonicalBinding?.units.find(unit=>unit.unitId===focus.unitId),canonicalPlan:LessonPlanV1={...input.lessonPlan,targetRef:focus.targetRef,facet:focus.facet,senseId:focus.senseId},now=new Date().toISOString(),prior=input.priorDecisions?.at(-1),familyDiagnosis=diagnoseExamFamilyUnitV1({family:input.task.family,subtype:input.task.subtype,taskId:input.task.task_id,unitId:focus.unitId,responseKey:binding?.responseKey??'',targetRef:focus.targetRef,facet:focus.facet,outcome:focus.outcome,payload:input.task.payload,learnerResponse:binding?input.response[binding.responseKey]:undefined,truth:input.learnerTruth}),focusTriage=triage.find(item=>item.unitId===focus.unitId),rawDecision=await decideInnerTutorV1({lessonPlan:canonicalPlan,productContext:input.productContext,learnerTruth:input.learnerTruth,event:{id:`exam-response:${input.sessionId}:${input.freshnessIdentity}:${focus.unitId}`,kind:'LEARNER_RESPONSE',occurredAt:now,outcome:focus.outcome,support:input.support,observationIds:[],attemptId:input.freshnessIdentity,productionConditions:defaultTeachingOpportunityConditionsV1({support:input.support})},recentAttempts:[],recentTreatmentResponses:[],timeRemainingMinutes:canonicalPlan.timeBudgetMinutes,currentDecision:prior?.blockDecision,currentProvenance:prior?.provenance,sourceTaskContext:{kind:'EXAM_TASK',family:input.task.family,subtype:input.task.subtype,taskId:input.task.task_id,unitId:focus.unitId,responseKey:binding?.responseKey,senseId:focus.senseId,taskPayload:input.task.payload,learnerAttempt:input.response,previousLearnerResponse:binding?input.response[binding.responseKey]:undefined,lookupExposure:input.lookupExposure,familyDiagnosis,examTriage:focusTriage,semanticObservation:focus.semanticAssessment?{outcome:focus.semanticAssessment.outcome,authority:focus.semanticAssessment.authority,dimensions:focus.semanticAssessment.dimensions,reasonCodes:focus.semanticAssessment.reasonCodes}:undefined},provider:input.provider??(async()=>{throw new Error('exam_teacher_provider_unavailable')})}),decision=Object.freeze({...rawDecision,blockDecision:{...rawDecision.blockDecision,configuration:{...rawDecision.blockDecision.configuration,examTriageAction:focusTriage?.action??'MICRO_TEACH'}},experience:focusTriage?.action==='SAVE_FOR_LATER'?{...rawDecision.experience,narrator:{state:'ACKNOWLEDGE' as const,message:'這一點先保留，今天不在這裡卡住。'}}:rawDecision.experience});
 return{assessment:evaluation.outcome as CanonicalExamSubmissionResultV1['assessment'],reasonCodes:evaluation.reasons,unitResults:diagnosedUnits,triage,teacherDecision:decision,evidenceCommitAllowed:evaluation.outcome==='SUCCESS'&&input.support==='NONE'};
}
