import { EnglishDomainObject,EnglishDomainObjectType,EnglishFacet } from '../english/EnglishDomain';
export type ContentValidationStatus='VERIFIED_CURATED'|'TRUSTED_IMPORTED'|'LEARNER_SOURCE_RAW'|'TEACHER_SOURCE_RAW'|'GENERATED_PENDING'|'GENERATED_VALIDATED'|'REJECTED';
export type ContentSourceType='CURATED_SYSTEM'|'LEARNER_ARTIFACT'|'TEACHER_MATERIAL'|'SCHOOL_MATERIAL'|'GENERATED'|'IMPORTED';
export interface DomainRelationV4{id:string;fromId:string;toId:string;relation:'PREREQUISITE_FOR'|'REALIZATION_OF'|'COMMON_COLLOCATE_WITH'|'LEXICALIZES'|'CONSTRUCTION_REQUIRES'|'CONFUSABLE_WITH'|'ALTERNATIVE_REALIZATION_OF'|'REGISTER_VARIANT_OF'|'USABLE_IN_RHETORICAL_FUNCTION'|'EVIDENCE_OVERLAP_WITH';provenanceIds:string[];confidence:'LOW'|'MEDIUM'|'HIGH'}
export interface ContentGovernanceV4{sourceType:ContentSourceType;sourceId:string;owner:string;visibility:'PRIVATE'|'SYSTEM'|'SHARED';license?:string;validationStatus:ContentValidationStatus;register?:string;genres:string[];lastReviewedAt?:string}
export interface ReusableExpressionMetadataV4{function:string;meaning:string;grammaticalSlots:Array<{name:string;constraint:string}>;register:string;genreSuitability:string[];naturalAlternatives:string[];overuseRisk:'LOW'|'MEDIUM'|'HIGH';rubricRelevance?:string[];examples:string[];counterexamples:string[]}
export interface DomainNodeV4 extends EnglishDomainObject{governance:ContentGovernanceV4;reusableExpression?:ReusableExpressionMetadataV4;teachingMechanismIds:string[];teachable:'TEACHABLE'|'NOT_YET_TEACHABLE'}
export interface DomainGraphV4{nodes:readonly DomainNodeV4[];relations:readonly DomainRelationV4[]}
export function validateDomainNodeV4(node:DomainNodeV4):string[]{const errors:string[]=[];if(node.governance.sourceType==='GENERATED'&&!['GENERATED_PENDING','GENERATED_VALIDATED','REJECTED'].includes(node.governance.validationStatus))errors.push('generated content has invalid validation state');if(node.governance.validationStatus==='GENERATED_PENDING'&&node.teachable==='TEACHABLE')errors.push('generated content cannot be teachable before validation');if(node.teachable==='TEACHABLE'&&!node.teachingMechanismIds.length)errors.push('teachable content needs a pedagogical mechanism');if(['IDIOM_PROVERB','FORMULAIC_SEQUENCE','REUSABLE_EXPRESSION'].includes(node.type)&&!node.reusableExpression)errors.push('formulaic content requires deployment metadata');return errors}
export function canBecomeCanonicalContent(node:DomainNodeV4):boolean{return['VERIFIED_CURATED','TRUSTED_IMPORTED','GENERATED_VALIDATED'].includes(node.governance.validationStatus)&&validateDomainNodeV4(node).length===0}
export function prerequisiteHypothesis(graph:DomainGraphV4,targetId:string,facet:EnglishFacet):{relatedIds:string[];mayInformHypothesis:true;mayCreateEvidence:false}{return{relatedIds:graph.relations.filter(r=>r.fromId===targetId&&r.relation==='PREREQUISITE_FOR').map(r=>r.toId),mayInformHypothesis:true,mayCreateEvidence:false}}
