import { EnglishFacet } from '../english/EnglishDomain';
import { CanonicalEvidenceEventV3,EvidenceCandidateV3 } from '../evidence/EvidenceCandidateV3';
import { TaskContract } from '../task/TaskContract';
export type ModelCallTier='ZERO_AI'|'LIGHT_SEMANTIC'|'TEACHER_REASONING'|'VISION'|'CRITIC_SECOND_PASS';
export type InteractionIntent='LANGUAGE_PERFORMANCE'|'HELP_REQUEST'|'CLARIFICATION_REQUEST'|'META_STATE'|'CORRECT_TEACHER'|'ARTIFACT_RESULT_REQUEST'|'EVALUATION_REQUEST'|'NAVIGATION_CONTROL'|'PAUSE_DEFER'|'GOAL_SWITCH'|'PREFERENCE_UPDATE'|'LOOKUP_REQUEST'|'PRODUCT_FEEDBACK';
export interface GroundedInteractionEventV4{id:string;learnerId:string;rawEventId:string;intents:Array<{intent:InteractionIntent;confidence:'LOW'|'MEDIUM'|'HIGH';referent?:string}>;grounding:'GROUNDED'|'PARTIAL'|'UNRESOLVED';activeTaskId?:string;activeObjectiveId?:string;supportStateId?:string;unresolvedReferents:string[];capabilityEligibleByIntent:boolean}
export type ObjectiveState='CANDIDATE'|'SELECTED'|'ACTIVE'|'TEACHING'|'LOCAL_VERIFY'|'RETURN_TO_SOURCE'|'TRANSFER_PENDING'|'DELAYED_PENDING'|'PARKED'|'COMPLETE_FOR_NOW';
export interface LearningObjectiveV4{id:string;learnerId:string;targetRef:string;facet:EnglishFacet;whyNow:string;sourceEvidenceIds:string[];hypotheses:string[];desiredChange:string;evidenceNeededNext:string[];eligibleMechanismIds:string[];forbiddenClaims:string[];stopConditions:string[];returnToSourceCondition?:string;transferPlan?:string;delayedVerificationPlan?:string;timeBudgetMinutes:number;state:ObjectiveState}
export interface SupportStateV4{id:string;visibleBeforeResponse:Array<'CUE'|'HINT'|'EXPLICIT_RULE'|'GUIDED_FRAME'|'MODEL'|'REVEAL'|'LOOKUP'>;updatedAt:string}
export interface SessionV4{id:string;learnerId:string;artifactId?:string;sessionGoal:string;activeObjectiveIds:string[];currentInteractionGoal:string;temporaryGoalStack:string[];supportStates:Record<string,SupportStateV4>;committedEvidenceIds:string[];status:'ACTIVE'|'SUSPENDED'|'COMPLETE_FOR_NOW';activeElapsedMs:number;lastResumedAt?:string;version:number}
export interface EvaluationResultV4{evaluator:'DETERMINISTIC'|'SEMANTIC'|'RUBRIC'|'CAPABILITY'|'INTERACTION';promptScope:string;answerScope:string;evaluatorScope:string;revealScope:string;observations:Array<{scope:string;polarity:'POSITIVE'|'NEGATIVE'|'MIXED'|'UNKNOWN'|'NOT_APPLICABLE';span?:string;confidence:'LOW'|'MEDIUM'|'HIGH'}>;validAlternative:boolean;abstained:boolean;uncertainty:string[];evidenceCandidates:EvidenceCandidateV3[]}
export interface TaskBlueprintV4{task:TaskContract;objectiveId:string;responseMode:string;promptScope:string;answerScope:string;evaluatorScope:string;revealScope:string;validAnswerPolicy:'EXACT'|'SET'|'SEMANTIC_OPEN';expectedAlternatives:string[];contaminationRisks:string[];load:{length:'LOW'|'MEDIUM'|'HIGH';ideaGeneration:'LOW'|'MEDIUM'|'HIGH';clauses:number;timePressure:boolean};generationProvenance:'CURATED'|'TEMPLATE'|'AI_GENERATED'}
export interface ReencounterPlanV4{id:string;learnerId:string;targetRef:string;facet:EnglishFacet;type:'IMMEDIATE_REPAIR'|'SAME_SESSION_FADE'|'CHANGED_CONTEXT_TRANSFER'|'DELAYED_RETRIEVAL'|'DELAYED_PRODUCTION'|'NATURAL_REENCOUNTER';dueAfter?:string;priority:'LOW'|'MEDIUM'|'HIGH';reason:string;sourceEvidenceIds:string[];createsNegativeEvidence:false}
export interface RelevantLearnerContextV4{packetId:string;learnerId:string;decisionScope:string;currentWork:{text:string;artifactId?:string;original:boolean};capabilityEvidenceIds:string[];contradictoryEvidenceIds:string[];interactionEvidenceIds:string[];goalConstraintIds:string[];uncertainties:string[];policyRefs:string[];excludedHistoryCount:number;estimatedTokens:number;generatedAt:string}
export interface ModelCallDecisionV4{tier:ModelCallTier;allowed:boolean;reason:string;includeImage:boolean;criticTrigger?:string;cacheRefs:string[];callsAvoided:number}
export interface ModelRequestTelemetryV4{id:string;model:string;requestType:ModelCallTier;inputTokens?:number;cachedInputTokens?:number;outputTokens?:number;reasoningTokens?:number;latencyMs:number;retries:number;status:'SUCCESS'|'HTTP_FAILURE'|'SCHEMA_REJECTION'|'TIMEOUT';usedImage:boolean;pricingVersion?:string;estimatedCost?:number}
export interface ArchitectureResolutionV4{eventClass:string;governingAuthority:string;evidenceEligibility:'MAYBE'|'INELIGIBLE'|'TASK_GUARDED';nextDecisionOwner:string;modelCall:ModelCallDecisionV4;invariants:string[];evidenceCandidates:EvidenceCandidateV3[];canonicalEvents:CanonicalEvidenceEventV3[];task?:TaskContract;trace:string[]}
