import { CapabilityFacet, EnglishFacet } from '../english/EnglishDomain';
import { EvidenceClaimRef, ProductionConditionsV1, TaskFamily, V3ContextNovelty } from '../task/TaskContract';
export type BlockFamilyV4='MEANING_LEXICAL'|'CHUNK_COLLOCATION'|'GRAMMAR_CONSTRUCTION'|'SPELLING_MORPHOLOGY'|'WRITING_COMPOSITION'|'TRANSLATION'|'RETRIEVAL_TRANSFER'|'SYSTEM_ACTION';
export type BlockInteractionV4='SELECT'|'MATCH'|'ORDER'|'MOVE'|'RECONSTRUCT'|'TYPE'|'REWRITE'|'COMPARE'|'SOURCE_RETURN'|'SYSTEM';
export type BlockSupportV4='MODELED'|'EXPLICIT'|'GUIDED'|'CUED'|'LIGHT'|'NONE';
export type PedagogicalRoleV4='TEACH'|'PRACTICE'|'ASSESS'|'TRANSFER'|'SYSTEM';
export type PedagogicalIntentV4=PedagogicalRoleV4|'RETURN';
export type EvidenceCeilingV4='NONE'|'EXPOSURE_ONLY'|'ASSISTED'|'CONTROLLED'|'INDEPENDENT'|'TRANSFER';
export type BlockLearnerEventTypeV4='BLOCK_SHOWN'|'OPTION_SELECTED'|'ITEM_MOVED'|'ITEM_REORDERED'|'TEXT_ENTERED'|'ANSWER_SUBMITTED'|'HINT_REQUESTED'|'IMPASSE_REPLAN_REQUESTED'|'SUPPORT_REVEALED'|'SUPPORT_FADE_REQUESTED'|'SELF_REPAIR'|'RETRY'|'BLOCK_COMPLETED'|'BLOCK_ABANDONED'|'RETURNED_TO_SOURCE';
export interface LearningBlockDefinitionV4{id:string;version:number;status:'REVIEW'|'APPROVED'|'RETIRED';label:string;family:BlockFamilyV4;role:PedagogicalRoleV4;learnerAction:string;genuineTeaching:boolean;exposesTargetAnswer:boolean;mechanism:string;selectionBelief:string;learnerGain:string;suitableFacets:EnglishFacet[];capabilityAffordance:'FIXED'|'OBJECTIVE_BOUND'|'NONE';contextAffordance:V3ContextNovelty|'NOT_APPLICABLE';inappropriateWhen:string[];interaction:BlockInteractionV4;contentBindings:string[];supportLevels:BlockSupportV4[];forbiddenSupport:BlockSupportV4[];revealRules:string[];fadeRules:string[];successStates:string[];failureStates:string[];retryBehavior:string;exitConditions:string[];nextBlockIds:string[];eligibleClaims:EvidenceClaimRef[];forbiddenClaims:EvidenceClaimRef[];evidenceCeiling:EvidenceCeilingV4;taskConditions:string[];successDoesNotProve:string[];sourceImplication:string;transferImplication:string;accessibility:string[];auditDisposition:'REMAIN'|'CHANGE'|'MERGE'|'SPLIT'|'RENAME'}
export interface BlockContentBindingV4{blockId:string;taskId:string;targetReference:string;prompt:string;sourceText?:string;options?:string[];items?:string[];answer?:string;meaning?:string;validated:true;taskFamily:TaskFamily}
export interface TeacherBlockDecisionV4{objectiveId:string;focus:string;pedagogicalIntent:PedagogicalIntentV4;selectedBlockId:string;targetReference:string;supportLevel:BlockSupportV4;contextProvenance:V3ContextNovelty|'NOT_APPLICABLE';configuration:Record<string,string|number|boolean>;reasonForSelection:string;evidenceToObserve:EvidenceClaimRef[];successTransition:string;failureTransition:string;requestedSystemAction:'NONE'|'CONTINUE_SOURCE'|'CLARIFY_CONTEXT'|'RETURN_TO_SOURCE'}
export interface BlockRuntimeStateV4{instanceId:string;blockId:string;supportLevel:BlockSupportV4;visibleBeforeResponse:string[];attempt:number;status:'INITIAL'|'INTERACTING'|'WRONG'|'SUPPORTED'|'RETRY'|'SUCCESS'|'RETURNED'|'ABANDONED'}
export interface BlockLearnerEventV4{id:string;instanceId:string;type:BlockLearnerEventTypeV4;payload:Record<string,string|number|boolean>;supportLevel:BlockSupportV4;visibleBeforeResponse:string[];occurredAt:string;productionConditions?:ProductionConditionsV1}
