import { useState } from 'react';
import { useLocalSearchParams } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import { LearningBlockDefinitionV4 } from '../../src/domain/v4/LearningBlockV4';
import { LearningBlockPreview } from './LearningBlockPreview';

type TeachingScene={title:string;question:string;steps:{label:string;value:string;color:string}[];insight:string;next:string};
const scenes:Record<string,TeachingScene>={
  'meaning-representation':{title:'significant 的核心意思',question:'不是「很大」，而是「大到值得注意或會造成影響」。',steps:[{label:'影響',value:'a significant impact',color:'#DDEFE8'},{label:'差異',value:'a significant difference',color:'#E5E4FA'},{label:'改變',value:'a significant change',color:'#F5E5D7'}],insight:'共同關係：程度足以影響判斷、結果或注意力。',next:'接著用新情境確認你能自己選用。'},
  'form-contrast':{title:'形式如何改變意思',question:'形式不是裝飾；它告訴讀者事件如何發生。',steps:[{label:'誰允許',value:'Schools',color:'#DDEFE8'},{label:'允許',value:'allow',color:'#F8E8B8'},{label:'誰被允許',value:'students',color:'#E5E4FA'},{label:'做什麼',value:'to use phones',color:'#F5E5D7'}],insight:'allow 後不能直接跳到動作；讀者需要知道「誰被允許」。',next:'下一步：用可移動部件練習角色順序。'},
  'morphology-decomposition':{title:'把字看成有意義的部件',question:'字形不是一串隨機字母。',steps:[{label:'sign',value:'mark / signal',color:'#DDEFE8'},{label:'-ific-',value:'make / carry',color:'#E5E4FA'},{label:'-ant',value:'having the quality',color:'#F5E5D7'}],insight:'用部件與聲音建立可重建的拼字路徑，而不是死背整串。',next:'下一步：有支援地重建，再逐步移除提示。'},
  'meaning-segmentation':{title:'先切意思，再翻譯',question:'不要從第一個中文字逐字往後換。',steps:[{label:'主體',value:'遠距工作',color:'#DDEFE8'},{label:'變化',value:'可能改變',color:'#F8E8B8'},{label:'受影響關係',value:'員工與公司的關係',color:'#E5E4FA'}],insight:'每一段先保留意思，再決定英文 clause 如何組織。',next:'下一步：用 chunks 建立完整翻譯。'},
  'alternative-translation-compare':{title:'同一意思，不同 framing',question:'兩個譯法可以都對，但焦點不同。',steps:[{label:'狀態',value:'The policy is important.',color:'#DDEFE8'},{label:'功能',value:'The policy plays an important role.',color:'#E5E4FA'},{label:'影響',value:'The policy has a significant impact.',color:'#F5E5D7'}],insight:'選擇取決於你要談重要性、功能，還是造成的影響。',next:'下一步：回到原意選擇合適 framing。'},
  'grammar-role-map':{title:'allow + O + to V 角色圖',question:'先理解角色，再記順序。',steps:[{label:'WHO allows',value:'Schools',color:'#DDEFE8'},{label:'ACTION',value:'allow',color:'#F8E8B8'},{label:'WHO is allowed',value:'students',color:'#E5E4FA'},{label:'DO WHAT',value:'to use phones',color:'#F5E5D7'}],insight:'你的原句少了 WHO is allowed，所以 allow 直接接 to use 時角色斷掉。',next:'下一步：Guided Sentence Builder。'},
  'l1-collision':{title:'中文和英文不使用同一骨架',question:'「我很喜歡」不能逐格換字。',steps:[{label:'中文概念',value:'我｜很｜喜歡｜它',color:'#F5E5D7'},{label:'碰撞',value:'I very like it. ✕',color:'#F8DAD2'},{label:'英文強度',value:'I really like it. ✓',color:'#DDEFE8'}],insight:'English 用副詞 really 修飾 like；very 通常修飾形容詞或副詞。',next:'下一步：在新句型中辨認強度位置。'},
  'chunk-as-unit':{title:'把整個 chunk 當成一個產出單位',question:'先不要拆成四個孤立單字。',steps:[{label:'UNIT',value:'play an important role in',color:'#DDEFE8'},{label:'框架 1',value:'Technology plays an important role in education.',color:'#E5E4FA'},{label:'框架 2',value:'Sleep plays an important role in memory.',color:'#F5E5D7'}],insight:'保留 chunk 骨架，只替換主體與領域，更容易直接產出。',next:'下一步：在有提示的句子裡完成 chunk。'},
  'collocation-network':{title:'impact 的自然搭配網絡',question:'搭配不是任意同義字拼接。',steps:[{label:'動詞',value:'have / make an impact on',color:'#DDEFE8'},{label:'形容詞',value:'significant / negative impact',color:'#E5E4FA'},{label:'不相容',value:'do an impact ✕',color:'#F8DAD2'}],insight:'英文使用者把這些組合儲存成可預期的網絡。',next:'下一步：Collocation Match。'},
  'sentence-anatomy':{title:'看見句子的骨架',question:'先找意思角色，不先找「更高級」的字。',steps:[{label:'WHO',value:'Technology',color:'#DDEFE8'},{label:'DOES WHAT',value:'changes',color:'#F8E8B8'},{label:'WHAT',value:'the way we learn',color:'#E5E4FA'},{label:'RESULT',value:'so access becomes easier',color:'#F5E5D7'}],insight:'每個 clause 有自己的工作；關係清楚後才選連接語言。',next:'下一步：Guided Clause Builder。'},
  'reformulation-map':{title:'相關意思，不等於完全互換',question:'選擇表達時看 framing。',steps:[{label:'重要性',value:'is important',color:'#DDEFE8'},{label:'功能',value:'plays an important role in',color:'#E5E4FA'},{label:'因果影響',value:'has a significant impact on',color:'#F5E5D7'}],insight:'不要把較長的片語當成自動「升級版」；它們回答不同問題。',next:'下一步：在原句意圖中選擇 framing。'},
  'cohesion-relation-map':{title:'先決定想法關係',question:'connector 是關係的標記，不是裝飾。',steps:[{label:'CAUSE',value:'because / since',color:'#F8E8B8'},{label:'RESULT',value:'therefore / so',color:'#DDEFE8'},{label:'CONTRAST',value:'however / while',color:'#E5E4FA'},{label:'ADDITION',value:'also / moreover',color:'#F5E5D7'}],insight:'同兩句內容，關係不同就需要不同語言。',next:'下一步：Clause Relation Practice。'},
  'worked-transformation':{title:'看一個句子如何被修好',question:'每一步只改一個有理由的地方。',steps:[{label:'原句',value:'Schools should allow to use phones.',color:'#F8DAD2'},{label:'問題',value:'allow 後缺少「誰被允許」',color:'#F8E8B8'},{label:'套入角色',value:'allow + students + to use',color:'#E5E4FA'},{label:'修訂',value:'Schools should allow students to use phones.',color:'#DDEFE8'}],insight:'改變不是背答案，而是補回 construction 必需的角色。',next:'下一步：換一個句子做 guided reconstruction。'},
};

export function PedagogicalBlockPreview({block}:{block:LearningBlockDefinitionV4}){
  if(block.role==='TEACH')return <TeachingPreview block={block}/>;
  return <View style={[styles.roleFrame,block.role==='ASSESS'&&styles.assessFrame,block.role==='TRANSFER'&&styles.transferFrame]}><View style={styles.roleHeader}><Text style={styles.role}>{block.role}</Text><Text style={styles.rolePromise}>{block.role==='ASSESS'?'不提供答案，看看你現在能不能自己做到':block.role==='TRANSFER'?'把學到的帶回真正作品或新情境':'在支援下建立控制'}</Text></View><LearningBlockPreview block={block}/></View>;
}

function TeachingPreview({block}:{block:LearningBlockDefinitionV4}){
  const scene=scenes[block.id]??scenes['worked-transformation'];
  const{state:reviewState}=useLocalSearchParams<{state?:string}>();
  const[step,setStep]=useState(reviewState==='complete'?scene.steps.length:reviewState==='progress'?Math.min(1,scene.steps.length):0);const complete=step>=scene.steps.length;
  return <View style={styles.teachingPhone}><View style={styles.teachTop}><Text style={styles.teachRole}>理解模式</Text><Text style={styles.counter}>{Math.min(step+1,scene.steps.length)}/{scene.steps.length}</Text></View><View style={styles.teachBody}><Text style={styles.teachTitle}>{scene.title}</Text><Text style={styles.question}>{scene.question}</Text><View style={styles.map}>{scene.steps.slice(0,Math.max(1,step+1)).map((item,index)=><View key={`${item.label}-${index}`} style={[styles.mapCard,{backgroundColor:item.color}]}><Text style={styles.mapLabel}>{item.label}</Text><Text style={styles.mapValue}>{item.value}</Text></View>)}</View>{complete?<View style={styles.insight}><Text style={styles.insightLabel}>你現在看見的規律</Text><Text style={styles.insightText}>{scene.insight}</Text></View>:null}</View><View style={styles.teachFooter}><Pressable accessibilityRole="button" accessibilityLabel={complete?'進入下一步':'揭開下一層'} onPress={()=>setStep(value=>Math.min(value+1,scene.steps.length))} style={styles.teachCta}><Text style={styles.teachCtaText}>{complete?'進入下一步':'揭開下一層'}</Text></Pressable>{complete?<Text style={styles.next}>{scene.next}</Text>:<Text style={styles.noScore}>這裡是在建立理解，不是評分。</Text>}</View></View>;
}

const styles=StyleSheet.create({roleFrame:{gap:10},roleHeader:{padding:14,borderRadius:14,backgroundColor:'#E7F1ED'},role:{fontSize:11,fontWeight:'900',letterSpacing:1.2,color:'#286759'},rolePromise:{marginTop:4,color:'#4D635D'},assessFrame:{backgroundColor:'#EEF1F6',padding:10,borderRadius:26},transferFrame:{backgroundColor:'#F4EDE3',padding:10,borderRadius:26},teachingPhone:{width:'100%',maxWidth:390,minHeight:690,backgroundColor:'#F2F5F0',borderRadius:30,overflow:'hidden',borderWidth:1,borderColor:'#CCD9D2'},teachTop:{padding:22,flexDirection:'row',justifyContent:'space-between',backgroundColor:'#1F574C'},teachRole:{fontSize:13,fontWeight:'900',letterSpacing:1,color:'#E8F5EF'},counter:{color:'#C9E1D8'},teachBody:{flex:1,padding:24,gap:16},teachTitle:{fontSize:27,lineHeight:35,fontWeight:'900',color:'#173C34'},question:{fontSize:16,lineHeight:24,color:'#566B65'},map:{gap:10},mapCard:{padding:16,borderRadius:16,borderWidth:1,borderColor:'rgba(26,55,48,.08)'},mapLabel:{fontSize:11,fontWeight:'900',letterSpacing:.8,color:'#52665F'},mapValue:{fontSize:18,lineHeight:25,fontWeight:'800',color:'#173C34',marginTop:5},insight:{padding:17,borderRadius:16,backgroundColor:'#FFFDF6',borderLeftWidth:4,borderLeftColor:'#D99D47'},insightLabel:{fontSize:11,fontWeight:'900',color:'#8A5B20'},insightText:{fontSize:16,lineHeight:23,color:'#493D2D',marginTop:6},teachFooter:{padding:20,gap:10,borderTopWidth:1,borderColor:'#D8E1DC'},teachCta:{height:54,borderRadius:16,backgroundColor:'#235F53',alignItems:'center',justifyContent:'center'},teachCtaText:{color:'#fff',fontWeight:'900',fontSize:16},noScore:{textAlign:'center',color:'#788A84',fontSize:12},next:{textAlign:'center',color:'#356D60',fontWeight:'800',lineHeight:19}});
