import React,{useMemo,useState}from'react';
import{Pressable,StyleSheet,Text,View}from'react-native';
import type{LearnerActionEvent,LearnerActionSurface,LearnerItem}from'../../../src/ui/learnerActionSurface';
import{eotLearnerTokensV1 as t}from'../../../src/ui/tokens';
import{AnchoredClaim,ContextualMicroPrompt,EvidenceSpan,FocusedRange,InlineSlot,InsertionBoundary,LanguageObject,LearningCanvas}from'./LearningFoundation';

type Props={surface:LearnerActionSurface;initialState?:Readonly<Record<string,unknown>>;onStateChange?:(state:Readonly<Record<string,unknown>>)=>void;onEvent:(event:LearnerActionEvent)=>void};
const emit=(p:Props,kind:LearnerActionEvent['kind'],value:unknown)=>p.onEvent({surfaceId:p.surface.id,kind,value});
export const isFoundationPuzzle=(surface:LearnerActionSurface)=>['READING_EVIDENCE','READING_COMPARE','MEANING_CONTRAST','SLOT','INSERTION','SPAN_REPAIR','TRANSLATION_EDITOR','WRITING_EDITOR','WRITING_DEVELOPMENT'].includes(surface.kind);

export function FoundationPuzzleRenderer(p:Props){switch(p.surface.kind){case'READING_EVIDENCE':return <EvidenceConnect p={p}/>;case'READING_COMPARE':return <EvidenceCompare p={p}/>;case'MEANING_CONTRAST':return <ContrastReplace p={p}/>;case'SLOT':return <InlineCloze p={p}/>;case'INSERTION':return <ParagraphInsert p={p}/>;case'SPAN_REPAIR':case'TRANSLATION_EDITOR':case'WRITING_EDITOR':case'WRITING_DEVELOPMENT':return <AuthoredRepair p={p}/>;default:return null}}

function EvidenceConnect({p}:{p:Props}){const x=p.surface as Extract<LearnerActionSurface,{kind:'READING_EVIDENCE'}>,[chosen,setChosen]=useState(()=>String((p.initialState?.chosen as string[]|undefined)?.[0]??''));return <LearningCanvas><AnchoredClaim>{x.selectedOption}</AnchoredClaim><View style={s.relationship}>{x.spans.map(span=><EvidenceSpan key={span.id} selected={chosen===span.id} onPress={()=>{setChosen(span.id);p.onStateChange?.({chosen:[span.id]})}}>{span.text}</EvidenceSpan>)}</View>{chosen?<Pressable onPress={()=>emit(p,'EVIDENCE',chosen)} style={s.localAction}><Text style={s.localActionText}>比較這段證據</Text></Pressable>:<Text style={s.cue}>碰一下真正支持答案的原文</Text>}</LearningCanvas>}
function EvidenceCompare({p}:{p:Props}){if(p.surface.kind!=='READING_COMPARE')return null;return <LearningCanvas><EvidenceSpan selected onPress={()=>emit(p,'EVIDENCE','comparison-seen')}>{p.surface.sourceSpan}</EvidenceSpan><View style={s.connector}/><AnchoredClaim>{p.surface.selectedOption}</AnchoredClaim><ContextualMicroPrompt text="原文真的說到這麼多嗎？"/></LearningCanvas>}

function splitTarget(sentence:string,words:string[]){const found=words.find(word=>word&&sentence.includes(word));if(!found)return{before:sentence,focus:'',after:''};const i=sentence.indexOf(found);return{before:sentence.slice(0,i),focus:found,after:sentence.slice(i+found.length)}}
function ContrastReplace({p}:{p:Props}){const x=p.surface as Extract<LearnerActionSurface,{kind:'MEANING_CONTRAST'}>,initial=x.contrasts.find(v=>v.id===x.selectedAnswer)?.word??x.contrasts[0]?.word??'',[value,setValue]=useState(initial),parts=splitTarget(x.sentence,[initial,...x.contrasts.map(v=>v.word)]);return <LearningCanvas><Text style={s.sentence}>{parts.before}<LanguageObject state={value===initial?'focused':'corrected'}>{value||parts.focus}</LanguageObject>{parts.after}</Text><View style={s.alternatives}>{x.contrasts.map(item=><Pressable key={item.id} onPress={()=>{setValue(item.word);emit(p,'CHOICE',item.id)}} style={[s.alternative,value===item.word&&s.alternativeOn]}><Text style={s.altWord}>{item.word}</Text><Text style={s.altCue}>{item.meaning}</Text></Pressable>)}</View></LearningCanvas>}

const blankPattern=(id:string)=>new RegExp(`___${id}___|_{2,}|\\[blank\\]`,'i');
function InlineCloze({p}:{p:Props}){const x=p.surface as Extract<LearnerActionSurface,{kind:'SLOT'}>,[placed,setPlaced]=useState(()=>x.candidates.find(v=>v.id===x.placed)),match=blankPattern(x.blankId).exec(x.sentence),before=match?x.sentence.slice(0,match.index):x.sentence+' ',after=match?x.sentence.slice(match.index+match[0].length):'';const place=(item:LearnerItem)=>{setPlaced(item);const state={placed:item.label,itemId:item.id,blankId:x.blankId};p.onStateChange?.(state);emit(p,'PLACEMENT',state)};return <LearningCanvas><Text style={s.sentence}>{before}<InlineSlot value={placed?.label} active={Boolean(placed)} onPress={()=>setPlaced(undefined)}/>{after}</Text><Text style={s.cue}>{placed?'詞已經在句子裡；可以再換':'把語意放回句子裡'}</Text><View style={s.tokens}>{x.candidates.map(item=><Pressable key={item.id} onPress={()=>place(item)} style={[s.token,placed?.id===item.id&&s.tokenOn]}><Text style={s.tokenText}>{item.label}</Text></Pressable>)}</View></LearningCanvas>}

function passageParts(passage:string,points:readonly LearnerItem[]){let rest=passage;const out:{text:string;point?:LearnerItem}[]=[];for(const point of points){const patterns=[`___${point.id}___`,point.label];const marker=patterns.find(v=>rest.includes(v));if(!marker)continue;const i=rest.indexOf(marker);out.push({text:rest.slice(0,i)});out.push({text:'',point});rest=rest.slice(i+marker.length)}out.push({text:rest});return out}
function ParagraphInsert({p}:{p:Props}){const x=p.surface as Extract<LearnerActionSurface,{kind:'INSERTION'}>,[active,setActive]=useState(false),[placed,setPlaced]=useState(()=>x.placed),parts=useMemo(()=>passageParts(x.passage,x.points),[x.passage,x.points]);const choose=(id:string)=>{setPlaced(id);setActive(false);p.onStateChange?.({point:id});emit(p,'PLACEMENT',id)};return <LearningCanvas><Pressable onPress={()=>setActive(v=>!v)} style={[s.candidate,active&&s.candidateLift]}><Text style={s.candidateLabel}>移動這句</Text><Text style={s.candidateText}>{x.candidate}</Text></Pressable><View>{parts.map((part,i)=>part.point?<Pressable key={`${part.point.id}-${i}`} onPress={()=>choose(part.point!.id)}><InsertionBoundary active={active||placed===part.point.id} preview={placed===part.point.id?x.candidate:undefined}/></Pressable>:<Text key={i} style={s.paragraph}>{part.text.trim()}</Text>)}</View>{!active&&!placed?<Text style={s.cue}>碰一下句子，再選文章中的位置</Text>:null}</LearningCanvas>}

function authoredValues(surface:LearnerActionSurface){switch(surface.kind){case'SPAN_REPAIR':return{text:surface.authoredText,target:surface.targetSpan,prompt:surface.goal,event:'REPAIR' as const};case'TRANSLATION_EDITOR':return{text:surface.authoredText,target:surface.targetSpan,prompt:'主詞和動詞要互相配合',event:'REPAIR' as const};case'WRITING_EDITOR':return{text:surface.authoredText,target:surface.targetSpan,prompt:'讓這裡更精確',event:'REPAIR' as const};case'WRITING_DEVELOPMENT':return{text:surface.authoredText,target:surface.targetSpan,prompt:'具體一點',event:'DEVELOP' as const};default:return{text:'',target:'',prompt:'',event:'REPAIR' as const}}}
function AuthoredRepair({p}:{p:Props}){const data=authoredValues(p.surface),[value,setValue]=useState(()=>String(p.initialState?.text??data.text));return <LearningCanvas><FocusedRange value={value} target={data.target} prompt={data.prompt} multiline={p.surface.kind==='WRITING_EDITOR'||p.surface.kind==='WRITING_DEVELOPMENT'} onChange={text=>{setValue(text);p.onStateChange?.({text})}}/><Pressable onPress={()=>emit(p,data.event,value)} style={s.done}><Text style={s.doneText}>改好了</Text></Pressable></LearningCanvas>}

const s=StyleSheet.create({sentence:{fontSize:20,lineHeight:36,color:t.colors.ink},cue:{fontSize:12,lineHeight:18,color:t.colors.subtle},relationship:{gap:2},localAction:{minHeight:44,alignSelf:'flex-start',justifyContent:'center',paddingHorizontal:12},localActionText:{fontSize:14,fontWeight:'700',color:t.colors.deepWood},connector:{width:2,height:22,alignSelf:'center',backgroundColor:t.colors.focus},alternatives:{marginLeft:52,borderLeftWidth:2,borderLeftColor:t.colors.focus},alternative:{minHeight:55,paddingHorizontal:14,paddingVertical:8,borderBottomWidth:1,borderBottomColor:t.colors.divider},alternativeOn:{backgroundColor:t.colors.focusWash},altWord:{fontSize:17,fontWeight:'800',color:t.colors.deepWood},altCue:{fontSize:12,color:t.colors.muted,marginTop:2},tokens:{flexDirection:'row',flexWrap:'wrap',gap:8},token:{minHeight:43,justifyContent:'center',paddingHorizontal:13,borderWidth:1,borderColor:t.colors.dividerStrong,borderRadius:12,backgroundColor:t.colors.paper},tokenOn:{transform:[{translateY:-3}],borderColor:t.colors.focus,backgroundColor:t.colors.focusWash},tokenText:{fontSize:15,color:t.colors.ink},candidate:{paddingVertical:11,paddingHorizontal:12,borderLeftWidth:3,borderLeftColor:t.colors.focus,backgroundColor:t.colors.paper},candidateLift:{transform:[{translateY:-4}],shadowColor:t.colors.shadow,shadowOpacity:.18,shadowRadius:7,elevation:5},candidateLabel:{fontSize:11,color:t.colors.muted,marginBottom:4},candidateText:{fontSize:16,lineHeight:25,color:t.colors.ink},paragraph:{fontSize:18,lineHeight:31,color:t.colors.ink,paddingVertical:5},done:{minHeight:46,alignSelf:'flex-end',justifyContent:'center',paddingHorizontal:16},doneText:{fontSize:15,fontWeight:'700',color:t.colors.deepWood}});
