import type { LessonPlanV1 } from '../../architecture/contracts';
import type { Stage4RuntimeV4 } from '../../domain/stage4/LearnerRuntimeV4';
import type { PedagogicalIntentV4 } from '../../domain/v4/LearningBlockV4';
import type { TranslationDeliveredTaskV1 } from './types';
import { hydrateTranslationWorkV1, type Stage4TranslationRuntimeV1 } from './workRuntime';
const norm=(x:string)=>x.trim().replace(/\s+/g,' ').toLowerCase();
export function validateTranslationDeliveredTaskV1(runtime:Stage4RuntimeV4,lessonPlan:LessonPlanV1,task:TranslationDeliveredTaskV1):readonly string[]{const work=hydrateTranslationWorkV1(runtime),errors:string[]=[];if(!work)return Object.freeze(['TRANSLATION_WORK_MISSING']);if(!task.validated)errors.push('FRESH_TASK_NOT_VALIDATED');if(task.consumedAt)errors.push('FRESH_TASK_ALREADY_CONSUMED');if(task.targetRef!==lessonPlan.targetRef)errors.push('FRESH_TASK_TARGET_MISMATCH');if(task.facet!==lessonPlan.facet)errors.push('FRESH_TASK_FACET_MISMATCH');if(!task.sourceText.trim()||norm(task.sourceText)===norm(work.sourceContext.sourceText))errors.push('FRESH_TRANSLATION_SOURCE_NOT_NEW');if((work.freshTaskHistory??[]).some(item=>item.taskId!==task.taskId&&norm(item.sourceText)===norm(task.sourceText)))errors.push('FRESH_TRANSLATION_SOURCE_REUSED');if(task.purpose==='CHANGED_CONTEXT_TRANSFER'&&task.contextNovelty!=='CHANGED_CONTEXT')errors.push('TRANSFER_TASK_CONTEXT_NOT_CHANGED');if(!task.validatorRefs.length)errors.push('FRESH_TASK_VALIDATOR_MISSING');if(!task.semanticRequirements.length)errors.push('FRESH_TASK_SEMANTIC_REQUIREMENTS_MISSING');return Object.freeze(errors)}
export function registerTranslationDeliveredTaskV1(runtime:Stage4RuntimeV4,lessonPlan:LessonPlanV1,task:TranslationDeliveredTaskV1):Stage4TranslationRuntimeV1{const typed=runtime as Stage4TranslationRuntimeV1,work=hydrateTranslationWorkV1(runtime);if(!work)throw new Error('translation work missing');if(work.freshTaskHistory.some(item=>item.taskId===task.taskId)||work.freshTask?.taskId===task.taskId)throw new Error('translation fresh task id already used');const errors=validateTranslationDeliveredTaskV1(runtime,lessonPlan,task);if(errors.length)throw new Error(`invalid_translation_fresh_task:${errors.join('|')}`);return{...typed,translationWork:{...work,freshTask:Object.freeze({...task}),freshTaskHistory:Object.freeze([...work.freshTaskHistory,Object.freeze({...task})]),phase:'FRESH_TRANSLATION',updatedAt:task.deliveredAt}}}
export function consumeTranslationFreshTaskV1(runtime:Stage4RuntimeV4,occurredAt:string):Stage4TranslationRuntimeV1{const typed=runtime as Stage4TranslationRuntimeV1,work=hydrateTranslationWorkV1(runtime);if(!work?.freshTask)throw new Error('translation fresh task missing');if(work.freshTask.consumedAt)return typed;const consumed=Object.freeze({...work.freshTask,consumedAt:occurredAt});return{...typed,translationWork:{...work,freshTask:consumed,freshTaskHistory:Object.freeze(work.freshTaskHistory.map(item=>item.taskId===consumed.taskId?consumed:item)),updatedAt:occurredAt}}}
export function translationFreshOpportunityGateV1(runtime:Stage4RuntimeV4,lessonPlan:LessonPlanV1,intent:PedagogicalIntentV4){if(intent!=='ASSESS'&&intent!=='TRANSFER')return{allowed:true,reasons:Object.freeze([] as string[])};const work=hydrateTranslationWorkV1(runtime);if(!work)return{allowed:false,reasons:Object.freeze(['TRANSLATION_WORK_MISSING'])};const task=work.freshTask;if(!task)return{allowed:false,reasons:Object.freeze(['VALIDATED_TRANSLATION_FRESH_TASK_NOT_DELIVERED'])};const reasons=[...validateTranslationDeliveredTaskV1(runtime,lessonPlan,task)];if(intent==='TRANSFER'&&task.purpose!=='CHANGED_CONTEXT_TRANSFER')reasons.push('TRANSFER_REQUIRES_CHANGED_CONTEXT_TRANSLATION_TASK');if(intent==='ASSESS'&&task.purpose!=='FRESH_CHECK')reasons.push('ASSESS_REQUIRES_FRESH_TRANSLATION_TASK');return{allowed:reasons.length===0,reasons:Object.freeze(reasons),task}}
