import type { ProductionConditionsV1 } from '../../domain/task/TaskContract';
import { productionConditionsAllowIndependentV1 } from '../../domain/task/productionConditions';
import type { TranslationRevisionActorV1, TranslationRevisionOperationV1, TranslationRevisionVersionV1 } from './types';
const clean=(value:string)=>value??'';
export function translationRevisionActorFromProductionConditionsV1(c:ProductionConditionsV1|undefined):TranslationRevisionActorV1{return productionConditionsAllowIndependentV1(c).allowed?'LEARNER':'LEARNER_ASSISTED'}
export function diffTranslationRevisionV1(before:string,after:string){let start=0;while(start<before.length&&start<after.length&&before[start]===after[start])start++;let beforeEnd=before.length,afterEnd=after.length;while(beforeEnd>start&&afterEnd>start&&before[beforeEnd-1]===after[afterEnd-1]){beforeEnd--;afterEnd--}return Object.freeze({sourceSpan:Object.freeze({start,end:beforeEnd}),before:before.slice(start,beforeEnd),after:after.slice(start,afterEnd)})}
export function createOriginalTranslationRevisionV1(input:{revisionId:string;originalArtifactId:string;text:string;createdAt:string}):TranslationRevisionVersionV1{return Object.freeze({revisionId:input.revisionId,originalArtifactId:input.originalArtifactId,text:clean(input.text),operations:Object.freeze([]),createdAt:input.createdAt,immutable:true as const})}
export function createTranslationRevisionV1(input:{revisionId:string;originalArtifactId:string;parent:TranslationRevisionVersionV1;text:string;operation:TranslationRevisionOperationV1;createdAt:string}):TranslationRevisionVersionV1{if(input.parent.originalArtifactId!==input.originalArtifactId)throw new Error('translation revision must remain bound to original artifact');return Object.freeze({revisionId:input.revisionId,originalArtifactId:input.originalArtifactId,parentRevisionId:input.parent.revisionId,text:clean(input.text),operations:Object.freeze([input.operation]),createdAt:input.createdAt,immutable:true as const})}
export function translationRevisionCanProveLearnerProductionV1(revision:TranslationRevisionVersionV1){const reasons:string[]=[];if(!revision.operations.length)reasons.push('ORIGINAL_NOT_NEW_PRODUCTION');for(const op of revision.operations){if(op.actor!=='LEARNER')reasons.push('TRANSLATION_REVISION_ASSISTED');const independent=productionConditionsAllowIndependentV1(op.productionConditions);if(!independent.allowed)reasons.push(...independent.reasons.map(reason=>`TRANSLATION_REVISION_CONDITION:${reason}`))}return Object.freeze({eligible:reasons.length===0,reasons:Object.freeze([...new Set(reasons)])})}
