import type { LessonPlanV1 } from '../../architecture/contracts';
import type { Stage4RuntimeV4 } from '../../domain/stage4/LearnerRuntimeV4';
import type { CapabilityFacet } from '../../domain/english/EnglishDomain';
import type { ProductionConditionsV1 } from '../../domain/task/TaskContract';
import { createOriginalTranslationRevisionV1, createTranslationRevisionV1, diffTranslationRevisionV1, translationRevisionActorFromProductionConditionsV1 } from './revision';
import type { TranslationArtifactContextV1, TranslationDeliveredTaskV1, TranslationOpportunityCandidateV1, TranslationRevisionOperationV1, TranslationRevisionVersionV1, TranslationSourceContextV1 } from './types';
import { diagnoseTranslationV1, type TranslationDiagnosisV1, type TranslationDiagnosticEvidenceV1 } from './diagnosis';

export interface TranslationWorkStateV1{schemaVersion:1;sourceContext:TranslationSourceContextV1;artifact:TranslationArtifactContextV1;diagnosisStatus:TranslationDiagnosisV1['status'];diagnosisReasonCodes:readonly string[];focusCandidates:readonly TranslationOpportunityCandidateV1[];freshTask?:TranslationDeliveredTaskV1;freshTaskHistory:readonly TranslationDeliveredTaskV1[];phase:'ORIGINAL_TRANSLATION'|'LOCAL_REPAIR'|'RETURN_TO_ORIGINAL'|'FRESH_TRANSLATION'|'COMPLETE_FOR_NOW';createdAt:string;updatedAt:string}
export type Stage4TranslationRuntimeV1=Stage4RuntimeV4&{translationWork?:TranslationWorkStateV1};
export function translationCandidatesForAuthorizedPlanV1(input:{lessonPlan:LessonPlanV1;sourceText:string;learnerText:string;evidence?:readonly TranslationDiagnosticEvidenceV1[];analysisComplete?:boolean}):readonly TranslationOpportunityCandidateV1[]{
  return diagnoseTranslationV1({sourceText:input.sourceText,learnerText:input.learnerText,authorizedTargetRef:input.lessonPlan.targetRef,evidence:input.evidence??[],analysisComplete:input.analysisComplete??false}).candidates;
}
export function startTranslationWorkV1(input:{runtime:Stage4RuntimeV4;lessonPlan:LessonPlanV1;sourceContext:TranslationSourceContextV1;createdAt?:string}):Stage4TranslationRuntimeV1{
  if(input.runtime.artifact.mode!=='TRANSLATION')throw new Error('translation work requires TRANSLATION artifact');
  const now=input.createdAt??input.runtime.artifact.submittedAt,original=createOriginalTranslationRevisionV1({revisionId:`translation-original:${input.runtime.artifact.id}`,originalArtifactId:input.runtime.artifact.id,text:input.runtime.usableSourceText,createdAt:now});
  const diagnosis=diagnoseTranslationV1({sourceText:input.sourceContext.sourceText,learnerText:original.text,authorizedTargetRef:input.lessonPlan.targetRef,evidence:[],analysisComplete:false});
  return {...input.runtime,translationWork:{schemaVersion:1,sourceContext:input.sourceContext,artifact:{originalArtifactId:input.runtime.artifact.id,originalRevisionId:original.revisionId,workingRevisionId:original.revisionId,revisions:Object.freeze([original])},diagnosisStatus:diagnosis.status,diagnosisReasonCodes:diagnosis.reasonCodes,focusCandidates:diagnosis.candidates,freshTaskHistory:Object.freeze([]),phase:'ORIGINAL_TRANSLATION',createdAt:now,updatedAt:now}};
}
export function hydrateTranslationWorkV1(runtime:Stage4RuntimeV4){return (runtime as Stage4TranslationRuntimeV1).translationWork}
export function currentTranslationRevisionV1(work:TranslationWorkStateV1):TranslationRevisionVersionV1{const revision=work.artifact.revisions.find(item=>item.revisionId===work.artifact.workingRevisionId);if(!revision)throw new Error('translation working revision missing');return revision}
export function recordLearnerTranslationRevisionV1(input:{runtime:Stage4RuntimeV4;text:string;occurredAt:string;productionConditions:ProductionConditionsV1;visibleBeforeResponse?:readonly string[];reasonRef?:string}):Stage4TranslationRuntimeV1{
  const runtime=input.runtime as Stage4TranslationRuntimeV1,work=runtime.translationWork;if(!work)throw new Error('translation work missing');const prior=currentTranslationRevisionV1(work);if(prior.text===input.text)return runtime;
  const revisionId=`translation-revision:${runtime.id}:${work.artifact.revisions.length}`,diff=diffTranslationRevisionV1(prior.text,input.text),operation:TranslationRevisionOperationV1={operationId:`translation-op:${runtime.id}:${work.artifact.revisions.length}`,revisionId,actor:translationRevisionActorFromProductionConditionsV1(input.productionConditions),sourceSpan:diff.sourceSpan,before:diff.before,after:diff.after,occurredAt:input.occurredAt,productionConditions:input.productionConditions,visibleBeforeResponse:Object.freeze([...(input.visibleBeforeResponse??[])]),reasonRef:input.reasonRef},next=createTranslationRevisionV1({revisionId,originalArtifactId:work.artifact.originalArtifactId,parent:prior,text:input.text,operation,createdAt:input.occurredAt});
  return {...runtime,translationWork:{...work,artifact:{...work.artifact,workingRevisionId:next.revisionId,revisions:Object.freeze([...work.artifact.revisions,next])},phase:work.phase==='FRESH_TRANSLATION'?'FRESH_TRANSLATION':'LOCAL_REPAIR',updatedAt:input.occurredAt}};
}
export function markTranslationReturnToOriginalV1(runtime:Stage4RuntimeV4,occurredAt:string):Stage4TranslationRuntimeV1{const typed=runtime as Stage4TranslationRuntimeV1,work=typed.translationWork;if(!work)throw new Error('translation work missing');return{...typed,translationWork:{...work,phase:'RETURN_TO_ORIGINAL',updatedAt:occurredAt}}}
export function translationProviderContextV1(runtime:Stage4RuntimeV4,lessonPlan:LessonPlanV1){const work=hydrateTranslationWorkV1(runtime);if(!work)return undefined;const revision=currentTranslationRevisionV1(work),focus=work.focusCandidates.find(c=>c.targetRefs.includes(lessonPlan.targetRef)&&c.facets.includes(lessonPlan.facet as CapabilityFacet));return Object.freeze({sourceContext:{...work.sourceContext,referenceAnswers:Object.freeze([])},diagnosisStatus:work.diagnosisStatus,diagnosisReasonCodes:work.diagnosisReasonCodes,activeFreshTask:work.phase==='FRESH_TRANSLATION'&&work.freshTask?Object.freeze({taskId:work.freshTask.taskId,sourceText:work.freshTask.sourceText,purpose:work.freshTask.purpose,contextNovelty:work.freshTask.contextNovelty,semanticRequirements:work.freshTask.semanticRequirements,validatorRefs:work.freshTask.validatorRefs}):undefined,originalArtifactId:work.artifact.originalArtifactId,originalRevisionId:work.artifact.originalRevisionId,workingRevisionId:work.artifact.workingRevisionId,currentLearnerTranslation:revision.text,focusCandidate:focus,validAlternativePolicy:'MEANING_PRESERVING_ALTERNATIVES_ACCEPTED' as const,referenceAnswersAreAuthority:false as const,phase:work.phase,authority:{targetOwner:'D' as const,teacherActionOwner:'E' as const,mechanismOwner:'F' as const,translationSemanticsOwner:'I' as const,evidenceOwner:'C/K' as const}})}
