const LIMIT_MAX=50;
const normalize=value=>String(value??'').normalize('NFKC').trim().toLocaleLowerCase('en');
const sourcePolicy=(alias,context)=>context==='INTERNAL_RESEARCH'?`${alias}.internal_use_allowed=1`:`${alias}.display_allowed=1 AND ${alias}.generation_allowed=1 AND ${alias}.license_status IN ('VERIFIED_PRODUCTION_ALLOWED','ATTRIBUTION_REQUIRED') AND ${alias}.usage_scope NOT IN ('RESEARCH_ONLY','DISCOVERY_ONLY','UNKNOWN','QUARANTINED','REJECTED')`;
const prov='s.source_id sourceId,s.version sourceVersion,s.license_name licenseName,s.license_status licenseStatus,s.usage_scope usageScope,s.attribution_text attributionText,s.attribution_required attributionRequired';
const unique=(rows,key)=>[...new Map(rows.map(x=>[key(x),x])).values()];
export function queryCorpus(db,input={}){
  const context=input.usagePolicy==='INTERNAL_RESEARCH'||input.context==='INTERNAL_RESEARCH'?'INTERNAL_RESEARCH':'LEARNER_PRODUCTION',query=normalize(input.lemma??input.surfaceForm??input.query??input.targetRefs?.[0]),limit=Math.max(1,Math.min(LIMIT_MAX,Number(input.limit)||20)),resource=input.requestedResourceType??'ALL',where=sourcePolicy('s',context);
  if(!query)return {context,query,limit,records:[],provenance:[],sourceVersions:[],licenseStatus:'NO_USABLE_RESULTS',qualitySignals:['EMPTY_QUERY'],retrievalReason:'empty bounded target'};
  const senses=resource==='ALL'||resource==='LEMMA_SENSES'?db.prepare(`SELECT l.lemma,l.pos,se.sense_id senseId,se.synset_id synsetId,se.glosses_json glosses,se.source_record_id sourceRecordId,${prov} FROM lexemes l JOIN senses se ON se.lexeme_id=l.lexeme_id JOIN source_registry s ON s.source_id=l.source_id WHERE l.normalized_lemma=? AND (? IS NULL OR l.pos=?) AND ${where} LIMIT ?`).all(query,input.pos??null,input.pos??null,limit).map(x=>({...x,glosses:JSON.parse(x.glosses),relations:db.prepare('SELECT relation_type type,to_record_id targetId FROM lexical_relations WHERE from_record_id=? AND source_id=? LIMIT 30').all(x.synsetId,x.sourceId)})):[];
  const morphology=resource==='ALL'||resource==='MORPHOLOGY'?db.prepare(`SELECT m.lemma,m.form,m.features,m.source_record_id sourceRecordId,${prov} FROM morphology m JOIN source_registry s ON s.source_id=m.source_id WHERE (m.normalized_form=? OR m.normalized_lemma=?) AND ${where} LIMIT ?`).all(query,query,limit).map(x=>({...x,features:x.features.split(';')})):[];
  const examples=resource==='ALL'||resource==='EXAMPLES'?db.prepare(`SELECT e.example_id exampleId,e.text,e.normalized_text normalizedText,e.source_record_id sourceRecordId,se.synset_id synsetId,l.lemma,l.pos,${prov} FROM examples e JOIN senses se ON se.synset_id=e.synset_id AND se.source_id=e.source_id JOIN lexemes l ON l.lexeme_id=se.lexeme_id JOIN source_registry s ON s.source_id=e.source_id WHERE l.normalized_lemma=? AND ${where} GROUP BY e.example_id LIMIT ?`).all(query,limit).map(x=>({...x,language:'eng',targetOccurrence:{start:x.normalizedText.indexOf(query),length:query.length},learnerDisplayEligible:true})):[];
  const pairWhere=context==='INTERNAL_RESEARCH'?"ep.usage_eligibility<>'REJECTED' AND zp.usage_eligibility<>'REJECTED'":"ep.usage_eligibility IN ('PRODUCTION_ALLOWED','ATTRIBUTION_REQUIRED') AND zp.usage_eligibility IN ('PRODUCTION_ALLOWED','ATTRIBUTION_REQUIRED') AND ep.provenance_complete=1 AND zp.provenance_complete=1 AND ep.source_integrity_valid=1 AND zp.source_integrity_valid=1 AND ep.record_quality_valid=1 AND zp.record_quality_valid=1";
  const ftsTarget=`"${query.replaceAll('"','""')}"`,sentencePairs=resource==='ALL'||resource==='SENTENCE_PAIRS'?db.prepare(`SELECT e.sentence_id englishId,e.text english,e.normalized_text englishNormalized,z.sentence_id chineseId,z.text chinese,z.normalized_text chineseNormalized,tp.source_record_id sourceRecordId,${prov},ep.contributor englishContributor,ep.record_license englishLicense,ep.license_status englishLicenseStatus,ep.attribution_text englishAttribution,ep.usage_eligibility englishEligibility,zp.contributor chineseContributor,zp.record_license chineseLicense,zp.license_status chineseLicenseStatus,zp.attribution_text chineseAttribution,zp.usage_eligibility chineseEligibility FROM translation_pairs tp JOIN sentences e ON e.sentence_id=tp.from_sentence_id JOIN sentences z ON z.sentence_id=tp.to_sentence_id JOIN sentence_provenance ep ON ep.sentence_id=e.sentence_id JOIN sentence_provenance zp ON zp.sentence_id=z.sentence_id JOIN source_registry s ON s.source_id=tp.source_id WHERE e.language='eng' AND z.language='cmn' AND (e.sentence_id IN (SELECT sentence_id FROM sentences_fts WHERE normalized_text MATCH ?) OR z.sentence_id IN (SELECT sentence_id FROM sentences_fts WHERE normalized_text MATCH ?)) AND ${where} AND ${pairWhere} GROUP BY e.normalized_text,z.normalized_text LIMIT ?`).all(ftsTarget,ftsTarget,limit):[];
  const records=resource==='ALL'?{senses,morphology,examples,sentencePairs}:resource==='LEMMA_SENSES'?senses:resource==='MORPHOLOGY'?morphology:resource==='EXAMPLES'?examples:sentencePairs,flat=Array.isArray(records)?records:Object.values(records).flat(),provenance=unique(flat.map(x=>({sourceId:x.sourceId,sourceVersion:x.sourceVersion,sourceRecordId:x.sourceRecordId,licenseName:x.licenseName,licenseStatus:x.licenseStatus,usageScope:x.usageScope,attributionText:x.attributionText,attributionRequired:Boolean(x.attributionRequired)})),x=>`${x.sourceId}|${x.sourceVersion}|${x.sourceRecordId}`),sourceVersions=unique(provenance.map(x=>({sourceId:x.sourceId,version:x.sourceVersion})),x=>`${x.sourceId}|${x.version}`);
  return {context,query,limit,records,provenance,sourceVersions,licenseStatus:flat.length?(provenance.some(x=>x.attributionRequired)?'ATTRIBUTION_REQUIRED':'ALL_ALLOWED'):'NO_USABLE_RESULTS',qualitySignals:[],retrievalReason:`bounded ${resource} retrieval; eligibility filtered before delivery; policy=${context}`};
}
export {LIMIT_MAX};
