import React,{useState}from'react';import{Pressable,StyleSheet,Text,TextInput,View}from'react-native';
import{LearningBlockDefinitionV4}from'../../src/domain/v4/LearningBlockV4';
type Props={block:LearningBlockDefinitionV4;sourceText:string;support:string;onEvent:(type:'SUPPORT_REVEALED'|'ANSWER_SUBMITTED'|'BLOCK_COMPLETED'|'RETURNED_TO_SOURCE',payload:Record<string,string|number|boolean>,success:boolean)=>void;onPause:()=>void;onCorrectInterpretation:()=>void};
const copy:Record<string,{title:string;prompt:string;model?:string;placeholder?:string}>={
 'grammar-role-map':{title:'先看清楚句子裡的角色',prompt:'allow 後面需要先說「允許誰」，再說那個人做什麼。',model:'Schools allow students to use phones.\n誰允許？Schools　允許誰？students　做什麼？to use phones'},
 'sentence-builder':{title:'把角色放回句子',prompt:'請重組：學校應該允許學生使用手機。',model:'Schools / should / allow / students / to use / phones',placeholder:'寫下完整句子'},
 'independent-sentence-production':{title:'現在自己說一次',prompt:'不看前面的句子，請表達：公司允許員工在家工作。',placeholder:'Write your sentence'},
 'return-original-writing':{title:'回到你的原作',prompt:'只修改剛才處理的地方；原作不會被覆寫。',placeholder:'在這裡寫下你的修訂'},
 'meaning-segmentation':{title:'先切清楚中文意思',prompt:'找出「誰／允許誰／做什麼」，再回到你的翻譯。',model:'學校｜應該允許｜學生｜使用手機'},
 'translation-chunk-builder':{title:'依照意思重組',prompt:'用自己的英文保留原意。',placeholder:'Write your translation'},
 'independent-translation':{title:'自己重新翻譯',prompt:'不看範例，寫出一個意思完整的英文版本。',placeholder:'Write a valid English translation'},
 'return-original-translation':{title:'回到原翻譯',prompt:'保留你的意思，修訂原本的英文。',placeholder:'在這裡寫下修訂'},
 'changed-context-production':{title:'換一個情境試試看',prompt:'寫一句「圖書館允許訪客使用電腦」。',placeholder:'Write a new-context sentence'},
 'return-source-navigation':{title:'回到原作',prompt:'這只是返回原作，不會記錄學習證據。'}
};
export function RegisteredBlockSurface({block,sourceText,support,onEvent,onPause,onCorrectInterpretation}:Props){const[text,setText]=useState(''),[help,setHelp]=useState(false),c=copy[block.id]??{title:block.label,prompt:block.learnerAction,placeholder:'寫下你的英文'};const teaching=block.role==='TEACH',navigation=block.id==='return-source-navigation';return <View style={s.card}><Text style={s.eyebrow}>{block.role==='TEACH'?'學習':block.role==='PRACTICE'?'練習':block.role==='ASSESS'?'自己試一次':block.role==='TRANSFER'?'回到真實作品':'原作'}</Text><Text style={s.title}>{c.title}</Text><View style={s.source}><Text style={s.sourceLabel}>你的原作</Text><Text style={s.sourceText}>{sourceText}</Text></View><Text style={s.prompt}>{c.prompt}</Text>{c.model&&(teaching||help)?<View style={s.model}><Text style={s.modelText}>{c.model}</Text></View>:null}{!teaching&&!navigation?<TextInput multiline value={text} onChangeText={setText} placeholder={c.placeholder} placeholderTextColor="#8A9691" style={s.input}/>:null}<Pressable style={s.cta} onPress={()=>{if(teaching)onEvent('BLOCK_COMPLETED',{taskId:block.id},true);else if(navigation)onEvent('RETURNED_TO_SOURCE',{taskId:block.id},false);else onEvent('ANSWER_SUBMITTED',{taskId:block.id,response:text},Boolean(text.trim()))}}><Text style={s.ctaText}>{teaching?'我看懂角色了':navigation?'回到原作':'確認'}</Text></Pressable>{!teaching&&!navigation&&block.role!=='ASSESS'?<Pressable onPress={()=>{setHelp(true);onEvent('SUPPORT_REVEALED',{visible:'SYSTEM_SUPPORT'},false)}}><Text style={s.secondary}>我還不會</Text></Pressable>:null}<View style={s.actions}><Pressable onPress={onPause}><Text style={s.action}>先暫停</Text></Pressable><Pressable onPress={onCorrectInterpretation}><Text style={s.action}>這不是我的意思</Text></Pressable></View><Text style={s.runtime}>目前支援：{support==='NONE'?'無':support}</Text></View>}
const s=StyleSheet.create({card:{gap:16},eyebrow:{color:'#236B5D',fontSize:12,fontWeight:'900'},title:{fontSize:27,lineHeight:36,fontWeight:'900',color:'#18312C'},source:{padding:15,borderRadius:14,backgroundColor:'#FFFEFA',borderLeftWidth:3,borderLeftColor:'#71988D'},sourceLabel:{fontSize:11,fontWeight:'900',color:'#66746F',marginBottom:6},sourceText:{fontSize:15,lineHeight:23,color:'#29413B'},prompt:{fontSize:18,lineHeight:28,color:'#18312C'},model:{padding:16,borderRadius:15,backgroundColor:'#E4F0EA'},modelText:{fontSize:16,lineHeight:27,color:'#18312C'},input:{minHeight:130,borderWidth:1,borderColor:'#D7DDD7',borderRadius:16,backgroundColor:'#FFFEFA',padding:16,fontSize:17,lineHeight:26,textAlignVertical:'top',color:'#18312C'},cta:{minHeight:55,borderRadius:16,backgroundColor:'#236B5D',alignItems:'center',justifyContent:'center'},ctaText:{fontWeight:'900',fontSize:16,color:'#fff'},secondary:{textAlign:'center',fontWeight:'800',color:'#4E6C64'},actions:{flexDirection:'row',justifyContent:'space-between'},action:{color:'#66746F',fontWeight:'700'},runtime:{fontSize:11,color:'#87918D',textAlign:'center'}});
